### ISSUE TITLE
Inlay hints wrong order for records

### ISSUE THREAD

**Issue by gruvw** [redhat-developer/vscode-java#2414] opened 2022-04-15 07:21 UTC
Hello, when using the new inlay hints I just discovered that sometimes the order of the arguments was not correct. 

Example:
![inlay_order_issue](https://user-images.githubusercontent.com/63407038/163538203-765d25b2-e168-4a24-821a-e3d0b06f35d3.png)

For the moment it only happened to me when using java records syntax.

##### Environment
- Operating System: Ubuntu
- JDK version: 17
- Visual Studio Code version: 1.66.2
- Java extension version: v1.5.0

**Comment by FieteO** [comment] 2022-04-15 12:17
I think this is caused by the `getDeclaredFields()` method not returning the fields in a particular order (called in the [InlayHintVisitor](https://github.com/eclipse/eclipse.jdt.ls/blob/346d6fa63d00f3a30091ac1984e1cd835b13e83f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java#L206)).
[From the javadoc](https://git.eclipse.org/r/plugins/gitiles/jdt/eclipse.jdt.core/+/refs/heads/master/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ITypeBinding.java#144):
``` java
	/**
	 * Returns a list of bindings representing all the fields declared
	 * as members of this class, interface, or enum type.
	 *
	 * <p>These include public, protected, default (package-private) access,
	 * and private fields declared by the class, but excludes inherited fields.
	 * Synthetic fields may or may not be included. Fields from binary types that
	 * reference unresolved types may not be included.</p>
	 *
	 * <p>Returns an empty list if the class, interface, or enum declares no fields,
	 * and for other kinds of type bindings that do not directly have members.</p>
	 *
	 * <p>The resulting bindings are in no particular order.</p>
	 *
	 * @return the list of bindings for the field members of this type,
	 *   or the empty list if this type does not have field members
	 */
	public IVariableBinding[] getDeclaredFields();
```

**Comment by jdneo** [comment] 2022-04-18 01:55
Hi @angelozerr,

Do you have any idea how we can support inlay hints for `Record` class? The current problem is that `getDeclaredFields()` does not return fields with declared order.

**Comment by angelozerr** [comment] 2022-04-18 10:28
No sorry I cannot help you for this topic.

**Comment by jdneo** [comment] 2022-04-19 06:53
The correct parameter names are stored in the internal `MethodBinding`. But I didn't find a way to access it

**Comment by jdneo** [comment] 2022-04-20 01:56
> This seems tricky because the record invocation(s) and declaration can be different files.

Yes, that means we need first find the record type in the Java project, and then get its type root, which would be too expensive for displaying inlay hints.

How about we try to add the API at upstream? Before the new API is available, we disable the inlay hint for record method invocations temporarily.

**Comment by jdneo** [comment] 2022-05-24 04:51
@rgrunber Will you add that required API at upstream?

**Comment by rgrunber** [comment] 2022-06-16 21:24
JDT Core : https://github.com/eclipse-jdt/eclipse.jdt.core/compare/master...rgrunber:param-names-api
JDT UI : https://github.com/eclipse-jdt/eclipse.jdt.ui/compare/master...rgrunber:param-names-records

The JDT Core change is all that's needed to expose the necessary API. We can probably write the same code as in JDT UI.

![param-names-hints-records-fix](https://user-images.githubusercontent.com/1417342/174167406-f0aad370-c608-49e4-902f-06f1cfd17f6d.png)

I'll go ahead and propose these changes.

**Comment by rgrunber** [comment] 2022-07-21 14:01
The API to do this on JDT Core has been available since https://download.eclipse.org/eclipse/updates/4.25-I-builds/I20220719-1800/ . I've also merged a change to fix the issue on Eclipse, so we should be able to go ahead and fix it in vscode-java now.

See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/149/files for an example.

**Comment by jdneo** [comment] 2022-07-28 02:07
Thank you @rgrunber, I'll follow up the fix at the JDT.LS side.

**Closed** 2022-08-02 01:47 UTC
Labels: bug
