### ISSUE TITLE
Syntax highlighting is not working with comment

### ISSUE THREAD

**Issue by Munodi** [redhat-developer/vscode-java#338] opened 2017-10-21 03:59 UTC
Normally a comment would be grey-greened out but I've discovered an instance where it is not.

##### Environment
- Operating System: Windows 10 64 bit
- JDK version: 9
- Visual Studio Code version: 1.17.1
- Java extension version: 0.12.0

##### Steps To Reproduce
1. Create a class and add the code below to it.
2. See that the comment is not highlighted correctly like it is in GitHub.

~~~~Java
private JPanel plottingSurface = new JPanel() /* {
        @Override
        public Dimension getPreferredSize() {
            return new Dimension(400, 300);
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
        }
    }*/;
~~~~

##### Current Result
not syntax-highlighted
##### Expected Result
Comment between first and last line coloured correctly
##### Additional Informations
Interestingly adding a semicolon before the comment colours the comment as expected

**Comment by fbricon** [comment] 2017-10-22 01:12
Syntax highlighting is provided by the [Textmate bundle embedded in vscode](https://github.com/Microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json). Usually that kind of syntax highlighting problem is caused by a bug in the [upstream Textmate bundle](https://github.com/textmate/java.tmbundle), but here, the issue can not be reproduced in Textmate, so this looks like a bug in vscode itself. Can you please open a report in https://github.com/Microsoft/vscode/issues?

cc @aeschli

**Comment by snjeza** [comment] 2017-10-22 18:11
I have converted the latest Textmate - https://github.com/textmate/java.tmbundle and it works fine.

[java.tmLanguage.json ](https://gist.github.com/snjeza/42960be25e6c2671f11de8822015f2b0)

**Comment by snjeza** [comment] 2017-10-22 18:12
![syntax](https://user-images.githubusercontent.com/388609/31864856-45bb17be-b765-11e7-9dbc-4590df7907d2.png)

**Comment by fbricon** [comment] 2017-10-22 18:38
@snjeza Please open a PR to vscode-java and link it here

**Comment by snjeza** [comment] 2017-10-22 19:39
![syntax1](https://user-images.githubusercontent.com/388609/31865592-763e06e2-b771-11e7-982a-08536813f02d.png)

**Comment by fbricon** [comment] 2018-02-01 17:36
With the vscode 1.19.3 (probably earlier versions too), highlighting is better, but there are still some issues with comments in the middle of a variable declaration:
<img width="508" alt="screen shot 2018-02-01 at 12 33 41 pm" src="https://user-images.githubusercontent.com/148698/35693436-3564a024-074c-11e8-9db9-feb8e65ba2c2.png">

**Comment by Eskibear** [comment] 2019-11-21 07:24
<img width="396" alt="Screen Shot 2019-11-21 at 3 23 28 PM" src="https://user-images.githubusercontent.com/2351748/69316038-e53ce600-0c72-11ea-8e07-4c880c16291a.png">

```
Version: 1.41.0-insider
Commit: fe03510f9e9fb269ca35da0ea600dd95279fa2b7
Date: 2019-11-18T05:25:58.947Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by Vigilans** [comment] 2019-11-25 14:28
There are still some issues with comment. 

<img width="396" alt="Screen Shot 2019-11-21 at 3 23 28 PM" src="https://user-images.githubusercontent.com/20227484/69548456-557c9c00-0fd2-11ea-8f31-8d5547156c12.png">

It is owing to the massive usage of look around assertions in java's textmate grammar.

**Comment by fbricon** [comment] 2020-04-27 17:48
This is partially fixed with the new semantic highlighting support in vscode-java 0.61.0. Requires `"java.semanticHighlighting.enabled": true` in settings.json. Without semantic highlighting, the Textmate grammar is still broken.

**Closed by fbricon** 2020-04-27 17:48 UTC
Labels: bug, highlighting, upstream
