### ISSUE TITLE
Automatic sorting members

### ISSUE THREAD

**Issue by Osolemio44** [redhat-developer/vscode-java#2274] opened 2022-01-05 16:54 UTC
Hello. In Eclipse there is an option that sorts the code automatically (source> sort members> all members). 
![image](https://user-images.githubusercontent.com/55595063/148256658-0216f910-a25f-4aca-96b6-b56e01a63d74.png)

Be careful not to be confused with refactoring. I am not looking to indent the code but to reorder the methods. Does anyone know how I can do the same in VSCode?

**Comment by fbricon** [comment] 2022-01-05 17:28
This feature is not supported at the moment

**Comment by rgrunber** [comment] 2022-01-10 19:42
Marking as duplicate of https://github.com/redhat-developer/vscode-java/issues/2139 (would be good to upvote there) . I think this is definitely possible because the API to achieve it is open to us from the JDT-LS side. I discuss a bit of what might need to happen to achieve this, but If I get some time and more people indicate their interest, maybe we can prioritize.

**Closed by rgrunber** 2022-01-10 19:42 UTC
Labels: enhancement, code action
