### ISSUE TITLE
not suppor a package name with dot 

### ISSUE THREAD

**Issue by henuhaigang** [redhat-developer/vscode-java#3571] opened 2024-04-11 14:12 UTC
[provide a description of the issue]

##### Environment
- Operating System:OS version: Darwin arm64 23.0.0
- JDK version: jdk8
- Visual Studio Code version: Code 1.88.0 (https://github.com/microsoft/vscode/commit/5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:09.495Z)
- Java extension version:

java project not support package name with dot，if package name has dot ,it will report error with red line ,for example

The declared package "com.aa.bb.service" does not match the expected package

aa.bb is a directory name in mac

more info can see this :https://github.com/microsoft/vscode/issues/209816#issue-2230777889

hope fix it !

**Comment by rgrunber** [comment] 2024-04-11 16:21
I'm going to mark this as a duplicate of https://github.com/redhat-developer/vscode-java/issues/1406 . The issue is known. The ECJ compiler is a bit more strict with package name requirements. However, I'm pretty sure we'll be addressing this in the future.

**Closed by rgrunber** 2024-04-11 16:21 UTC
Labels: duplicate

**Comment by henuhaigang** [comment] 2024-04-13 14:13
oh, It's realy a long time!

**Comment by rgrunber** [comment] 2024-04-15 16:35
It's definitely an old (and known) issue, but recently has been given priority, so there should be a solution in the near future.
