### ISSUE TITLE
Can't import java.xml module with fop jar,error code is Java(8390063)

### ISSUE THREAD

**Issue by iorimoe** [redhat-developer/vscode-java#1000] opened 2019-07-24 04:26 UTC
##### Environment
- Operating System:Window 10
- JDK version:11
- Visual Studio Code version:1.36.1
- Java extension version:0.47.0

##### Steps To Reproduce
1. use org.apache.xmlgraphics.fop-2.3.jar
2. write test file to import org.xml.sax.SAXException or javax.xml.transform.*

the error message is:
The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml Java(8390063)

Update：
exclude xml-apis.jar has fix that problem

**Comment by fbricon** [comment] 2019-07-24 06:36
Can you zip and attach your project so we can reproduce the issue?

**Comment by iorimoe** [comment] 2019-07-24 06:47
> Can you zip and attach your project so we can reproduce the issue?
[test.zip](https://github.com/redhat-developer/vscode-java/files/3425346/test.zip)
demo for this issue.

**Comment by fbricon** [comment] 2019-07-24 08:36
So here's the thing: in this case, it turns out the JDT compiler (and by extension vscode-java) is right, and the fact your project compiles with javac (and by extension Gradle and IntelliJ IDEA) is actually a bug. You can find the explanation in https://bugs.eclipse.org/bugs/show_bug.cgi?id=536928#c53.     
Once https://bugs.openjdk.java.net/browse/JDK-8215739 is fixed, your project won't be able to compile either from CLI/other IDEs.
The *correct* solution is to exclude xml-apis from your classpath.
I'm closing this issue as there's nothing we can do from our side, sorry.

**Closed by fbricon** 2019-07-24 08:36 UTC
Labels: not-a-bug, upstream
