### ISSUE TITLE
Escape text when pasting into a string literal

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1429] opened 2020-05-01 16:37 UTC
Similar to Eclipse IDE
<img width="477" alt="Screen Shot 2020-05-01 at 6 32 36 PM" src="https://user-images.githubusercontent.com/148698/80822052-2bab4f00-8bda-11ea-8088-c1fca968465e.png">

when pasting say `<a href="https://github.com/">GitHub</a>` into double quotes, it should be escaped to : `<a href=\"https://github.com/\">GitHub</a>`

![May-01-2020 18-35-25](https://user-images.githubusercontent.com/148698/80822257-9a88a800-8bda-11ea-9fd9-61382f1ad790.gif)

This requires vscode to provide some hooks into pasting events. Not sure what's the status is on that front.

**Comment by rgrunber** [comment] 2022-10-12 02:29
Duplicate of https://github.com/redhat-developer/vscode-java/issues/1249 .

**Closed by rgrunber** 2022-10-12 02:29 UTC
Labels: duplicate, enhancement
