### ISSUE TITLE
VSCode reloads Java projects on each startup which takes a very long time

### ISSUE THREAD

**Issue by xxc-zsz** [redhat-developer/vscode-java#2643] opened 2022-08-23 08:33 UTC
I am in the process of switching from Eclipse to VSCode for Java Development - so far, I have been able to setup a workspace folder with all my Java projects in it and all works fine.

However, every time I restart VSCode, all projects are rebuilding (showing me "Opening Java Projects: check details") which takes a very long time (about 5 minutes) - in comparision, when I am re-opening my Eclipse workspace with the same amount of projects, it only takes ~30 seconds for everything to be ready. Is there something I am doing wrong or can't VSCode "remember" Java projects as good as Eclipse?

**Comment by snjeza** [comment] 2022-08-23 20:00
@xxc-zsz What OS are you using? Do you use maven, gradle?

**Comment by THWU** [comment] 2022-08-24 03:28
Hi @snjeza 
I had a similar problem, but my situation was that the build stalled.
This issue affects other features of VSCode (such as Source Control)
If I disable "Language Support for Java(TM)" extension, source control works fine.
This problem had begun in the last few days

Maven project
VSCode: v1.70.2
Language Support for Java(TM): v1.9.0

**Comment by THWU** [comment] 2022-08-24 04:56
> Hi @snjeza I had a similar problem, but my situation was that the build stalled. This issue affects other features of VSCode (such as Source Control) If I disable "Language Support for Java(TM)" extension, source control works fine. This problem had begun in the last few days
> 
> Maven project VSCode: v1.70.2 Language Support for Java(TM): v1.9.0

I found https://github.com/redhat-developer/vscode-java/issues/2577#issuecomment-1208922149 can solve my problem.
Sorry, i miss this issue.

**Comment by jdneo** [comment] 2022-10-25 08:04
@xxc-zsz Did you still observe the problem with the latest pre-release? There are several fixes regarding perf done recently.

You can click this button to turn on the pre-release channel
![image](https://user-images.githubusercontent.com/6193897/197718224-e987ad4a-41f9-4c97-a5e8-642dd0d4eaba.png)

**Comment by youngky-h** [comment] 2023-01-02 04:06
I have same problem here... I run vscode server in docker container. It took more than 5 minutes for loading java project...

System used:
Host: ubuntu 22.04
Docker Image: ubuntu 20.04
VSCode: 1.74.1
Language Support For Java: 1.13.0
Java on Docker: OpenJDK 11.0.17

**Comment by benjaminbauer** [comment] 2023-01-03 08:22
I am experiencing the same problem running in a devcontainer. The project does not even contain much Java, it is mostly used to build things with maven.

Host: MacOs (aarch64)
Docker image (devcontainer): bullseye
VS Code: 1.74.2
Language Support For Java: 1.13.0
openjdk version "17.0.5" 2022-10-18 LTS

My initial thought was, that file I/O on docker on macOs is not the fastest. This can be improved by making the used folder a volume. Can someone tell me, what folder this extension puts its index in (assuming the indexing of the project is the slow part)?

**Comment by tarekahf** [comment] 2023-04-02 09:52
I'm facing the same problem and switched back to eclipse. Any update on this issue?

**Comment by GourabIX** [comment] 2023-04-27 12:41
Is 6 months not enough time to verify and reproduce this issue? @jdneo

**Comment by tarekahf** [comment] 2023-04-27 14:02
In eclipse, it take less than a minute to load several huge java projects and you are ready to run the tests. But, in vscode, you have to wait until you see the thumbs up icon in the status bar, which can take between 2 to 5 minutes for one maven project with 5 relatively large modules. During the loading process, nothing works like intelisens, running tests... etc.. You have to sit and wait...

**Comment by snjeza** [comment] 2023-04-27 17:05
@GourabIX @tarekahf Could you, please, provide a project example?

**Comment by jcgaming-official** [comment] 2023-05-07 13:38
I am facing the same problem, any update regarding this issue?

**Comment by snjeza** [comment] 2023-05-07 17:01
@jcgaming-official You can try to set
```
"java.jdt.ls.vmargs": "-Daether.dependencyCollector.impl1=df <your VM args",
```
to your settings.json. 
See https://github.com/redhat-developer/vscode-java/issues/2643#issuecomment-1526044671

**Comment by tarekahf** [comment] 2023-05-07 19:06
Try this project to reproduce the issue 👍

https://github.com/javalite/jar-explorer

Everytime you open the project, open a Java source file and watch how the code is being compiled. This is a small project so compilation might finish quickly. But, it will always compile and you can click on view details to see the progress in the terminal window.

Let me if you need more information...

**Comment by rajmetti** [comment] 2023-05-23 06:19
facing the same issue, at first vs code opened projects very fast like 1 or 2 mins, don't know what happened after updating in oct/ nov in 2023, every time i open java project in vscode, it is taking like 20 mins to load all the projects.

**Comment by rajmetti** [comment] 2023-05-24 04:35
my bad, yes that is 2022

**Comment by overtomanu** [comment] 2023-11-01 15:34
I am still facing this issue on Oct / Nov 2023

**Comment by tarekahf** [comment] 2023-11-01 18:55
I'm always facing the same problem. It takes about 7 minutes to load and run the unit test in VS code. In eclipse it takes 40 seconds.

**Comment by snjeza** [comment] 2023-11-01 19:44
@overtomanu @tarekahf Could you, please, provide a project example?

**Comment by tarekahf** [comment] 2023-11-01 20:12
> @overtomanu @tarekahf Could you, please, provide a project example?

I already provided one above. I'll try to make a screen recording for both.

**Comment by overtomanu** [comment] 2023-11-02 03:26
@snjeza I have opened around 8 to 10 work related projects. These projects are spring boot projects with some of them having proto files, nothing out of the ordinary.

**Comment by Alirez14** [comment] 2024-04-11 07:42
i also have problems here please improve this

**Comment by jcgaming-official** [comment] 2024-04-11 07:48
> I also have problems here please improve this it takes 35 min each time to load the project, and I need to use lightweight mode but then I cannot debug it's so annoying @jdneo I use the pre-release version

I found a solution and it us the best. To fix this issue, just switch your OS into Linux. Yes I am using that now and it's open smoothly

**Comment by cervantesandres** [comment] 2024-05-20 19:38
I'm facing the same problem. I have about 70 java projects and it's taking more than 35 minutes. Not sure why it has to reload everything. It should just be reloading the deltas.

**Comment by snjeza** [comment] 2024-05-20 20:15
@cervantesandres Could you try VS Code Pre-Release? It includes the fix for https://github.com/redhat-developer/vscode-java/issues/3637

**Comment by cervantesandres** [comment] 2024-05-20 23:29
@snjeza Could you clarify what you're referring to by "VS Code Pre-Release"?

**Comment by fbricon** [comment] 2024-05-20 23:45
Select the pre-release vscode-java version

<img width="732" alt="Screenshot 2024-05-21 at 01 44 18" src="https://github.com/redhat-developer/vscode-java/assets/148698/ecf6b1d5-ec72-471c-aa6c-cebdb62f114d">

**Comment by cervantesandres** [comment] 2024-05-21 17:16
@fbricon @snjeza Switching to Pre-Release didn't resolve the issue; Java building still takes around 35 minutes.

**Comment by snjeza** [comment] 2024-05-21 17:43
@cervantesandres Could you try the steps from https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3150#issue-2279821730? Step 6 is the same, but step 7 has improved significantly.

**Comment by cervantesandres** [comment] 2024-05-21 17:56
@snjeza to clarify, you want me to try these 7 steps?
<img width="419" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/50704403/cbe713da-93f3-4fc1-8334-c98eed0dc4a0">

**Comment by snjeza** [comment] 2024-05-21 18:10
>  to clarify, you want me to try these 7 steps?

Yes. You should use your project instead of [quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j)

**Comment by cervantesandres** [comment] 2024-05-21 20:07
@snjeza I followed the steps you recommended, yet I'm still experiencing no improvement in time efficiency. My workspace comprises 70 repositories, each of which is a Java project.

**Comment by cervantesandres** [comment] 2024-05-21 20:48
@snjeza I'd appreciate the opportunity to discuss what I'm seeing over a call. Could you please let me know your availability so we can arrange a suitable time?

**Comment by snjeza** [comment] 2024-05-21 22:02
@cervantesandres You have to wait for the build to finish in step 6.

**Comment by cervantesandres** [comment] 2024-05-22 01:01
@snjeza I've revised the steps, and now the process takes between 8 to 12 minutes. While it's an improvement, waiting for the Java reload to complete still feels too long.

**Comment by snjeza** [comment] 2024-05-23 15:32
@cervantesandres Could you provide your project? You can send it to my email snjezana.peco@redhat.com

**Comment by cervantesandres** [comment] 2024-05-23 17:20
@snjeza Regrettably, I'm unable to share it as it's proprietary code. Let me provide some context: I manage a workspace in Visual Studio Code comprising over 70 Git Java web repositories. These projects are unrelated to each other. However, in VSCode, they all share the same reference libraries. In Eclipse, each web project has its own reference libraries. This setup might be causing VSCode to perceive them as a single project, necessitating a refresh for every change.

<img width="264" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/50704403/743ad311-79f4-42e1-8d04-24d37752e301">
<img width="173" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/50704403/d59abf53-a36e-4279-8d2b-9f18275b52bd">

**Comment by snjeza** [comment] 2024-05-23 17:59
@cervantesandres What projects are you using: Eclipse, Maven, Gradle?

**Comment by cervantesandres** [comment] 2024-05-23 18:57
@snjeza Initially, all projects were developed in Eclipse without using build automation tools like Maven or Gradle. We are now transitioning to VSCODE.

**Comment by snjeza** [comment] 2024-05-23 23:06
Eclipse projects should work fine.
Could you show your settings.json file and your .project  .classpath files?

**Comment by cervantesandres** [comment] 2024-05-24 14:51
@snjeza I identified the problem: when I imported the folder containing all my Java programs into VSCode, it treated it as a single project. To resolve this, I created a new workspace and added each folder individually. Now, they are treated as separate projects within a single workspace.

In Eclipse, you can refer to other project within the workspace. Is there an option like that in VSCode? I have a common project that is reference in every other project.  
<img width="433" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/50704403/609723f9-e541-42ff-a0ec-45cf6a1b5620">

**Comment by libnoon** [comment] 2024-06-03 14:24
I was hit by the slowness issue too, it could take 10 minutes each time.
But then I switched to the Pre-Release version of the plugin (currently v1.32.2024053108), and had no issues since then.

**Comment by tarekahf** [comment] 2024-06-03 16:53
> I was hit by the slowness issue too, it could take 10 minutes each time. But then I switched to the Pre-Release version of the plugin (currently v1.32.2024053108), and had no issues since then.

No kidding! I must give it a shot!

**Comment by GourabIX** [comment] 2024-06-11 15:06
The release version of the extension pack for Java (v0.27.0) resolves this issue. Projects don't get re-compiled every time, and it takes around 25s for 4 complex Java Spring Boot projects to become ready. First time compilation has also become noticeably faster.

**Comment by rgrunber** [comment] 2024-06-26 15:07
I'm going to close this issue, given that the past few commenters have indicated that recent versions of the extension seem to have fixed this. The following issues, which resulted in fixes, may have also fixed this one :

- https://github.com/redhat-developer/vscode-java/issues/3637 (user reported something like a ~30min import time goes down to under a minute for quarkus-langchain4j)
- https://github.com/redhat-developer/vscode-java/issues/3387 (this was basically an endless build loop that consumed CPU if the project misconfigured null analysis)

Feel free to request re-opening if not the case, but it might be better to file a new issue.

**Closed by rgrunber** 2024-06-26 15:07 UTC
Labels: performance, need verify
