### ISSUE TITLE
Modifying files in resources/templates doesn't reload in Spring Boot

### ISSUE THREAD

**Issue by sant123** [redhat-developer/vscode-java#425] opened 2018-01-31 15:59 UTC
When modifying resources in templates or static, Spring Boot doesn't take the changes. I have tried disabling cache for view engine but it didn't work.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_162
- Visual Studio Code version: 1.19.3
- Java extension version: 0.17.0

##### Steps To Reproduce
Please see https://github.com/Microsoft/vscode-java-debug/issues/226

This is the project I'm working on:
[project.zip](https://github.com/redhat-developer/vscode-java/files/1682294/project.zip)

Tested in Netbeans.

Thank you!

**Comment by fbricon** [comment] 2018-01-31 16:34
Duplicate of #400. Try to force an incremental build (Alt+Shift+B) when after you changed your templates

**Closed by fbricon** 2018-01-31 16:34 UTC
