### ISSUE TITLE
strange additionalTextEdit with 'import' completion item

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#1860] opened 2021-04-01 17:05 UTC
Originally reported in https://github.com/MicrosoftDocs/intellicode/issues/281 , I reproduced it and investigated a little bit. See below:

https://user-images.githubusercontent.com/2351748/113328028-4936ea80-934e-11eb-9343-72a2eb3aeb7c.mp4
##### Environment
- Operating System: Windows
- JDK version: 11
- Visual Studio Code version: both 1.54.3 / 1.55.0
- Java extension version: 0.76.0

##### Steps To Reproduce
It's not stably reproducible. It often occurs at the first time you type "import" statement. If you redo it, it works well. 

#### I assume it has something to do `additionalTextEdit` by comparing server logs:
When 1st time it's not working:
```
[Trace - 12:59:09 AM] Received response 'completionItem/resolve - (88)' in 5ms.
Result: {
    "label": "java.util",
    "kind": 9,
    "detail": "(package) java.util",
    "sortText": "999999215",
    "insertTextFormat": 2,
    "textEdit": {
        "range": {
            "start": {
                "line": 1,
                "character": 7
            },
            "end": {
                "line": 1,
                "character": 12
            }
        },
        "newText": "java.util.${0:*};"
    },
    "additionalTextEdits": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 16
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "newText": "\r\n\r\n"
        }
    ]
}
```

The 2nd time it's working:
```
[Trace - 1:00:57 AM] Received response 'completionItem/resolve - (116)' in 6ms.
Result: {
    "label": "java.util",
    "kind": 9,
    "detail": "(package) java.util",
    "sortText": "999999215",
    "insertTextFormat": 2,
    "textEdit": {
        "range": {
            "start": {
                "line": 1,
                "character": 7
            },
            "end": {
                "line": 1,
                "character": 13
            }
        },
        "newText": "java.util.${0:*};"
    }
}

```

**Comment by snjeza** [comment] 2021-04-06 18:09
@Eskibear @Pascal-Klinkenbergh Could you try to reproduce the issue when starting VS Code with the following property:

```
"java.jdt.ls.vmargs": "... -Djava.lsp.joinOnCompletion=true ...",
```

**Comment by Eskibear** [comment] 2021-04-07 02:09
@snjeza By adding above vmargs I can still repro it. 
https://user-images.githubusercontent.com/2351748/113800132-00859400-9789-11eb-97b4-42f43bdc30e4.mp4

Try creating a new class, I feel that's easier to reproduce it.

**Comment by snjeza** [comment] 2021-04-07 03:17
@Eskibear could you disable the Visual Studio IntelliCode extension?

```
 "vsintellicode.java.completionsEnabled": false,
```

**Comment by Eskibear** [comment] 2021-04-07 04:20
As shown in the first video, I don't have intelliCode extension installed. And from the server log, you can see it was `completionItem/resolve` response (different from those when IntelliCode is activated).

**Comment by snjeza** [comment] 2021-04-07 17:32
> By adding above vmargs I can still repro it.
https://user-images.githubusercontent.com/2351748/113800132-00859400-9789-11eb-97b4-42f43bdc30e4.mp4
Try creating a new class, I feel that's easier to reproduce it.

I can't reproduce it with "-Djava.lsp.joinOnCompletion=true" . Could you attach your server log?

**Comment by jdneo** [comment] 2022-02-08 07:15
It's the same as https://github.com/redhat-developer/vscode-java/issues/1422 and is fixed in https://github.com/eclipse/eclipse.jdt.ls/pull/1944

**Comment by fbricon** [comment] 2022-02-08 08:03
Closing as duplicate of #1422

**Closed by fbricon** 2022-02-08 08:03 UTC
Labels: bug, duplicate
