### ISSUE TITLE
Code completion broken with IntelliCode

### ISSUE THREAD

**Issue by jvalkeal** [redhat-developer/vscode-java#1213] opened 2019-12-23 11:06 UTC
Looks like latest release `0.55.0` broke server side snippets / code completions

##### Environment
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-70-generic
redhat.java: 0.55.0

##### Steps To Reproduce
Create empty MyClass.java file and type `class` to get basic package/class snippet to. This error is then logged in `Language Support for Java` output:

```
[Error - 10:53:29] 23-Dec-2019 10:53:29 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.<init>(Lorg/eclipse/jdt/core/ICompilationUnit;I)V
java.lang.NoSuchMethodError: org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.<init>(Lorg/eclipse/jdt/core/ICompilationUnit;I)V
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.initializeRequestor(CompletionProvider.java:133)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.computeContentAssist(CompletionProvider.java:89)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.provideCompletionItems(CompletionProvider.java:60)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.executeCommand(CommandHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:472)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:963)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[Error - 10:53:29] 23-Dec-2019 10:53:29 Error in calling delegate command handler
org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.<init>(Lorg/eclipse/jdt/core/ICompilationUnit;I)V
java.lang.NoSuchMethodError: org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.<init>(Lorg/eclipse/jdt/core/ICompilationUnit;I)V
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.initializeRequestor(CompletionProvider.java:133)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.computeContentAssist(CompletionProvider.java:89)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.provideCompletionItems(CompletionProvider.java:60)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.executeCommand(CommandHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:472)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:963)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Now I just wonder if this issue is coming from other plugin which hooks to jdt as I'm not that familiar with how that part works.

**Comment by LaughingVzr** [comment] 2019-12-23 11:13
yes,I have got the same problem. wating for response.

**Comment by jvalkeal** [comment] 2019-12-23 11:20
Right, looks to be [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) as when I disabled that extension, problem went away.

**Comment by LaughingVzr** [comment] 2019-12-23 11:44
> Right, looks to be [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) as when I disabled that extension, problem went away.

Right,so if disable it , only use redhut plugin for this work. but it seem like not other influence.

**Comment by arekgofi** [comment] 2019-12-23 13:50
> Right, looks to be [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) as when I disabled that extension, problem went away.

That works for me

**Comment by jrobi001** [comment] 2019-12-23 14:12
> Right, looks to be [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) as when I disabled that extension, problem went away.

Thanks! Works for me, was wondering why the snippets stopped working 10-15s after opening a project today

**Comment by fbricon** [comment] 2019-12-23 14:29
@testforstephen @akaroml I'm surprised QA didn't catch that one

**Comment by Tazaf** [comment] 2019-12-23 14:34
Got the same issue, but decided to install the previous vscode-java version (0.54.2) instead of completly disabling IntelliCode (that is until this behavior is fixed by either one of the extensions)

**Comment by fbricon** [comment] 2019-12-23 15:31
Weird, I can't reproduce the issue. Can you guys try to call the "Clean the Java language server workspace" command? (F1)

**Comment by jrobi001** [comment] 2019-12-23 16:01
Not sure if this helps: my snippets disappear locally, I uninstalled vscode and extensions fully, then only installed the java pack and the issue remained. (before finding this).

not sure all snippets disappear, but class and sysout do for me, attached is a screenshot showing the snippets provided with intellicode disabled and enabled:
![dissaperingsnippets](https://user-images.githubusercontent.com/39461114/71367423-e9736080-259c-11ea-8bd4-f4cb839bbc82.png)

**Comment by jvalkeal** [comment] 2019-12-23 16:12
Well yes `vscjava.vscode-java-pack` contains `VisualStudioExptTeam.vscodeintellicode`, version `1.2.2`  which errors and prevents server side completion. Proper snippets defined in an extension naturally work. I did workspace reload few times before started to look deeper. Also re-enabling intellisense anyway asks you to reload.

**Comment by jvalkeal** [comment] 2019-12-23 16:17
@fbricon  Btw, just tried insiders and it's working just fine there.

**Comment by fbricon** [comment] 2019-12-23 16:24
Fix is on its way (https://github.com/eclipse/eclipse.jdt.ls/pull/1313)

**Comment by fbricon** [comment] 2019-12-23 16:52
Can you guys please try to install https://download.jboss.org/jbosstools/jdt.ls/staging/java-0.55.1-1983.vsix?

**Comment by anothernode** [comment] 2019-12-23 17:07
@fbricon, I had the same problem and after installing the VSIX from your link, IntelliSense completion works fine again for me! 😊

**Comment by arekgofi** [comment] 2019-12-23 17:10
Works fine for me as well

**Comment by fbricon** [comment] 2019-12-23 17:12
Ok thanks for checking. 0.55.1 is being rolled out on the VS Code Marketplace. Should be available in the next few minutes.

**Closed by fbricon** 2019-12-23 17:12 UTC
Labels: bug

**Comment by Tazaf** [comment] 2019-12-23 17:15
Thanks @fbricon ! I can confirm that this fix resolves the issue on my end also.
The reactivity is very much appreciated 👍

**Comment by jvalkeal** [comment] 2019-12-23 17:36
Thanks a bunch for a super quick fix!

**Comment by LaughingVzr** [comment] 2019-12-24 00:11
fix quick,good job!

**Comment by testforstephen** [comment] 2019-12-24 02:27
> @testforstephen @akaroml I'm surprised QA didn't catch that one

Thanks to point it out. Currently the compatibility for the third party extensions are not well covered, i will update the test plan for this part.

**Comment by akaroml** [comment] 2020-01-09 03:13
> @testforstephen @akaroml I'm surprised QA didn't catch that one

I was surprised too and sorry about that. As a follow-up, we'll:
1.  Add integration tests by installing Java Extension Pack instead of just vscode-java
2.  Make the test plan public so all parties can comment

@jdneo will be on this.

**Comment by jdneo** [comment] 2020-01-09 03:22
Tracking issue: https://github.com/microsoft/vscode-java-pack/issues/289
