### ISSUE TITLE
new file snippet generate twice class keyword

### ISSUE THREAD

**Issue by fourcels** [redhat-developer/vscode-java#2462] opened 2022-05-20 06:25 UTC
new file snippet generate twice class keyword

##### Environment
- Operating System: macOS 12
- JDK version: 18
- Visual Studio Code version: 1.67.2
- Java extension version: 1.6.0

##### Steps To Reproduce

https://user-images.githubusercontent.com/1042568/169465345-73705cda-2d5a-4d94-8306-b28021d44b3d.mov

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment] 2022-05-20 08:39
Something's fishy happening around https://github.com/redhat-developer/vscode-java/blob/master/src/fileEventHandler.ts#L111. @jdneo I could be wrong but I don't think this is related to the recent insert/overwrite mode changes.

**Comment by jdneo** [comment] 2022-05-20 09:24
No, it's not related with the insert/overwrite capability. That's released in 1.6.0, but this bug can be reproduced in 1.5.0 on my machine.

It looks like VS Code has some problem when the choice text has space. I can do more experiments and file ticket upstream if necessary.

**Comment by jdneo** [comment] 2022-05-20 10:31
Bug created: https://github.com/microsoft/vscode/issues/150016

**Comment by mdmiles** [comment] 2022-05-20 22:58
I am experiencing the same behavior. If I go to create a class, interface, enum, etc., it ends in the following signatures:
public class class SomeClass {
public class interface SomeInterface {
It apparently is not replacing the default "class" keyword; it is just appending the chosen one to what is already there.

**Comment by jdneo** [comment] 2022-05-21 03:43
Ok it's originally tracked by https://github.com/microsoft/vscode/issues/148976, and already fixed in the latest VS Code Insider.

I think we can close this ticket and just wait for the next stable release of VS Code.

**Closed** 2022-05-27 20:56 UTC
Labels: upstream, snippets
