### ISSUE TITLE
Problems Java(16777540), Java(134217868), and more reported when running HelloWorld

### ISSUE THREAD

**Issue by Sami058706** [redhat-developer/vscode-java#3295] opened 2023-09-14 00:30 UTC
<img width="1512" alt="Screenshot 2023-09-13 at 8 25 47 PM" src="https://github.com/redhat-developer/vscode-java/assets/144498354/7ddeefd5-a217-4650-8a83-130ec19c5010">

[provide a description of the issue]

##### Environment
- Operating System: MacOS Ventura 13.5
- JDK version: JDK 20.0.2
- Visual Studio Code version: 1.82.1 (Universal)
- Java extension version: 0.25.14

##### Steps To Reproduce
1. Open new file (title HelloWorld.java) (First error Java(16777540)
2. Write full HelloWorld Program
3. Run (6 problems reported)

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment] 2023-09-14 06:44
closing as duplicate of #3287

**Closed by fbricon** 2023-09-14 06:44 UTC
