### ISSUE TITLE
Feature request: Provide a way to use annotation processors based on jar file

### ISSUE THREAD

**Issue by cnsgithub** [redhat-developer/vscode-java#376] opened 2017-11-23 12:12 UTC
Hi, would it be possible to add support for Annotation processors based on a local jar file? E.g. eclipse has support for them by using a .factorypath file

```xml
<factorypath>
    <factorypathentry kind="WKSPJAR" id="/libs/hibernate-jpamodelgen-5.2.12.Final.jar" enabled="true" runInBatchMode="false"/>
    <factorypathentry kind="WKSPJAR" id="/libs/querydsl-jpa-4.1.4-apt-one-jar.jar" enabled="true" runInBatchMode="false"/>
</factorypath>
```
This will then auto-generate the APT entities automatically into the source output folder for them

Additional notes, on how to use them in other IDEs. This might give ideas on how to implement this
https://docs.jboss.org/hibernate/stable/jpamodelgen/reference/en-US/html_single/#d0e302

Or is there already a way to do this? (Without using maven or gradle! It is important that it is supported for custom *.jar files)

**Comment by fbricon** [comment] 2017-11-23 14:08
Duplicate of #339. Whether AP is based on Maven or directly from Eclipse APT, this is the same [problem](https://github.com/redhat-developer/vscode-java/issues/339#issuecomment-338442937).

**Closed by fbricon** 2017-11-23 14:08 UTC
