### ISSUE TITLE
[Formatter] Extra two spaces after word wrapping

### ISSUE THREAD

**Issue by mahyarmirrashed** [redhat-developer/vscode-java#2357] opened 2022-03-14 15:18 UTC
Formatter, when set to spaces of size 2 for indentation, formats the wrapping in a weird and unexpected way. It add four spaces rather than 2 on the following line.

##### Environment
- Operating System: Fedora Linux 35 (KDE Plasma) x86_64
- JDK version: openjdk 17.0.2 2022-01-18
- Visual Studio Code version: 1.65.2
- Java extension version: Language support for Java ™ for Visual Studio Code v1.4.0

##### Steps To Reproduce
1. Set formatter to spaces and indent size of 2.
2. Write a line exceeding the wrapping limit.
3. Format the document.

##### Current Result

![image](https://user-images.githubusercontent.com/59240843/158202378-36c748a0-4736-4d21-a8ca-2e5fe66050a4.png)

##### Expected Result

Add option to remove the extra two spaces before of `final Packet packet` in formatter settings.

**Comment by rgrunber** [comment] 2022-03-15 21:27
If a wrapped line was indented the same as some inner block, that might cause a bit of confusion, but it can be done if wanted. The default value for this is, `org.eclipse.jdt.core.formatter.continuation_indentation=2` (when using the default formatter).

One way is to create a file and make sure `java.settings.url` points to it. From there You can provide the above setting in that file.

You can also create a separate formatter (XML) file whose path you'd set in `java.format.settings.url` . See https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings .

Also note that there are many ways to configure the formatter : https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/formatter/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.java .

**Comment by rgrunber** [comment] 2022-03-22 17:41
Closing this out as I think I've addressed the main issues here.

The root of the problem is we need to make the formatting options more discoverable. At the very least, maybe I can print them out somewhere like we did for https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences#java-compiler-options until we get a proper UI around all the options.

**Closed by rgrunber** 2022-03-22 17:41 UTC
Labels: question
