### ISSUE TITLE
Starting Java Language Server never ends

### ISSUE THREAD

**Issue by mgcvnrpj** [redhat-developer/vscode-java#158] opened 2017-02-26 09:08 UTC
"Starting Java Language Server never" message never ends at the status bar after installing the extension Language Support for java by Red Hat

##### Environment
- Operating System: Microsoft Windows 7 Enterprise - 32 bit
- JDK version:1.8.0_121
- Visual Studio Code version:1.9.1

##### Steps To Reproduce
1. Installed extension Language support for java
2. User Settings for "java.home":null
3. JAVA_HOME pointing to C:\Program Files\Java\jdk1.8.0_112

##### Current Result
Couldnot start client language support for java
unexpected end of file

##### Additional Informations
![image](https://cloud.githubusercontent.com/assets/17407202/23338436/4a0760c4-fc13-11e6-9f19-b5b65db87daf.png)

**Comment by gorkem** [comment] 2017-02-27 14:23
Can you remove the `java.home` setting completely? 
Is this a maven based project?

**Comment by mgcvnrpj** [comment] 2017-02-27 14:31
I removed the user settings completely. Deleted all that was there and restarted but the same result.

**Comment by gorkem** [comment] 2017-02-27 14:41
Downloading an ubuntu. I will try to replicate.

**Comment by mgcvnrpj** [comment] 2017-02-27 15:38
It is a Maven project

**Comment by mgcvnrpj** [comment] 2017-02-27 16:45
Is there any wrong settings I am doing from my side. I am attaching java configuration, user settings and the JAVA_HOME env variable. Please let me know if I am missing any settings

![image](https://cloud.githubusercontent.com/assets/17407202/23370281/df5bdae2-fd1c-11e6-9a67-7f9c91807c9d.png)

**Comment by mgcvnrpj** [comment] 2017-02-27 16:48
OS Details and JAVA Version below

OS Name:                   Microsoft Windows 7 Enterprise 
OS Version:                6.1.7601 Service Pack 1 Build 7601
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)

**Comment by mgcvnrpj** [comment] 2017-03-02 04:56
Any update on the issue?

**Comment by gorkem** [comment] 2017-03-02 14:22
I was not able to reproduce so far. I still need to find a win7.

**Comment by korn3l** [comment] 2017-03-02 14:47
I also started experiencing this but on Windows 10 (also a Maven project)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by rubin55** [comment] 2017-03-07 08:33
I am experiencing this on Gentoo with JDK 1.8.0_121 and vscode 1.10.1; It seems the language server never completes startup.

**Comment by korn3l** [comment] 2017-03-07 10:04
Manage to fix this by deleting  %APPDATA%\Code\User\workspaceStorage\

**Comment by gorkem** [comment] 2017-03-07 12:19
I suspect that some of the metadata that server uses gets corrupted and server shuts down itself, this may be rooted from #3. As  @korn3l suggested deleting this metadata can be a workaround. Does it work for others?

**Comment by rubin55** [comment] 2017-03-07 14:53
I can confirm that removing ~/.config/Code/User/workspaceStorage/ (I'm on linux) works! after removing that and starting code, completion works immediately.

**Comment by mgcvnrpj** [comment] 2017-03-07 18:34
I am still facing the same issue even after deleting %APPDATA%\Code
Tried it on vscode 1.10.1, Language Support for Java 0.0.11 on windows 7 for a maven project

**Comment by ffaubert** [comment] 2017-03-09 13:32
I just had this issue start happening to me this morning after working for weeks.  The error getting thrown was:
[Error - 8:27:52 AM] Mar 9, 2017 8:27:50 AM Missing resource filter type: 'org.eclipse.ui.ide.multiFilter'.
null
java.lang.Error
     at org.eclipse.core.internal.resources.Filter.match(Filter.java:64)
     at org.eclipse.core.internal.resources.Filter.filterExcludes(Filter.java:159)
     at org.eclipse.core.internal.resources.Filter.filter(Filter.java:112)
     at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1971)
     at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1933)
     at org.eclipse.core.internal.localstore.UnifiedTree.getLocalList(UnifiedTree.java:352)
     at org.eclipse.core.internal.localstore.UnifiedTree.addChildren(UnifiedTree.java:140)
     at org.eclipse.core.internal.localstore.UnifiedTree.addNodeChildrenToQueue(UnifiedTree.java:246)
     at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:112)
     at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:971)
     at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:954)
     at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1560)
     at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.createProject(EclipseProjectImporter.java:103)
     at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importToWorkspace(EclipseProjectImporter.java:84)
     at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
     at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:89)
     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)


I deleted ~/Library/Application Support/Code/User/workspaceStorage and restarted VSCode and it started working again.

**Comment by gorkem** [comment] 2017-03-09 14:14
@ffaubert thanks for the info.

**Comment by fbricon** [comment] 2017-03-14 16:25
@ffaubert according to https://www.eclipse.org/forums/index.php/t/1078337/, this is begnin. org.eclipse.ui.ide.multiFilter is added from a UI plugin, which jdt.ls is lacking. Did you open the same project in eclipse at some point, fiddling with UI filters?

@gorkem I wonder if it's worth providing a noop extension point for org.eclipse.ui.ide.multiFilter, to prevent that kind of errors

Anyways, that should be handled in a separate ticket.

**Comment by jxsl13** [comment] 2017-03-21 13:09
same problem mac os x 10.12.3 opening a single java file.

**Comment by fbricon** [comment] 2017-03-26 20:28
@jxsl13 single file opening was broken in the last release. It's fixed upstream https://github.com/eclipse/eclipse.jdt.ls/issues/194

We'll release an update before the end of this week

**Comment by fbricon** [comment] 2017-03-31 15:32
Guys, please try 0.1.0 out. If the problem still persists, please attach [log files](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) here.

**Comment by jxsl13** [comment] 2017-03-31 19:28
seems to work (Y)

**Comment by yuchuangu85** [comment] 2017-04-08 08:14
same problem mac os x 10.11.6 opening android-7.1.1-R1.

**Comment by fbricon** [comment] 2017-04-08 14:19
@yuchuangu85 please attach [log files](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) here.

**Comment by yuchuangu85** [comment] 2017-04-08 14:37
[Error - 10:30:40 PM] Apr 8, 2017 10:21:13 PM Problem importing to workspace
Cannot nest 'gdx-backend-gwt/src/com/badlogic/gdx/backends/gwt/emu' inside 'gdx-backend-gwt/src'. To enable the nesting exclude 'com/' from 'gdx-backend-gwt/src'
org.eclipse.core.runtime.CoreException: Cannot nest 'gdx-backend-gwt/src/com/badlogic/gdx/backends/gwt/emu' inside 'gdx-backend-gwt/src'. To enable the nesting exclude 'com/' from 'gdx-backend-gwt/src'
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:322)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.updateProjects(MavenProjectImporter.java:111)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:92)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:106)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by fbricon** [comment] 2017-04-10 16:30
@yuchuangu85 The error that occurs is then caused by a conflict between the .classpath definition and what Maven tried to set instead. I'm a bit confused as to why the server tries to import `gdx-backend-gwt` as a Maven project though, since [it contains a gradle build file](https://github.com/libgdx/libgdx/tree/master/backends/gdx-backends-gwt), it should be imported as a Gradle project. Which is what happens on my machine. Where (in the folder hierarchy) did you open that project from?

**Comment by missedone** [comment] 2017-08-16 03:12
i'm encountering this on Mac 10.12.6.
vscode: 1.15.0
vscode-java: 0.8.0

----
```
[Error - 8:08:10 PM] Aug 15, 2017 8:08:09 PM Missing resource filter type: 'org.eclipse.ui.ide.multiFilter'.
null
java.lang.Error
	at org.eclipse.core.internal.resources.Filter.match(Filter.java:64)
	at org.eclipse.core.internal.resources.Filter.filterExcludes(Filter.java:159)
	at org.eclipse.core.internal.resources.Filter.filter(Filter.java:112)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1971)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1933)
	at org.eclipse.core.internal.localstore.UnifiedTree.getLocalList(UnifiedTree.java:352)
	at org.eclipse.core.internal.localstore.UnifiedTree.addChildren(UnifiedTree.java:140)
	at org.eclipse.core.internal.localstore.UnifiedTree.addNodeChildrenToQueue(UnifiedTree.java:246)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:112)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:971)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:954)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshRoot(FileSystemResourceManager.java:996)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:947)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1560)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:163)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 8:08:10 PM] Aug 15, 2017 8:08:09 PM Missing resource filter type: 'org.eclipse.ui.ide.multiFilter'.
null
java.lang.Error
	at org.eclipse.core.internal.resources.Filter.match(Filter.java:64)
	at org.eclipse.core.internal.resources.Filter.filterExcludes(Filter.java:159)
	at org.eclipse.core.internal.resources.Filter.filter(Filter.java:112)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1971)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1933)
	at org.eclipse.core.internal.localstore.UnifiedTree.getLocalList(UnifiedTree.java:352)
	at org.eclipse.core.internal.localstore.UnifiedTree.addChildren(UnifiedTree.java:140)
	at org.eclipse.core.internal.localstore.UnifiedTree.addNodeChildrenToQueue(UnifiedTree.java:246)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:112)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:971)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:954)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1560)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.updateProjects(MavenProjectImporter.java:136)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:118)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by ycycn** [comment] 2017-08-25 05:44
[Error - 下午1:43:53] 2017-8-25 13:43:47 Missing resource filter type: 'org.eclipse.ui.ide.multiFilter'.
null
java.lang.Error
	at org.eclipse.core.internal.resources.Filter.match(Filter.java:64)
	at org.eclipse.core.internal.resources.Filter.filterExcludes(Filter.java:159)
	at org.eclipse.core.internal.resources.Filter.filter(Filter.java:112)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1971)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1933)
	at org.eclipse.core.internal.localstore.UnifiedTree.getLocalList(UnifiedTree.java:352)
	at org.eclipse.core.internal.localstore.UnifiedTree.addChildren(UnifiedTree.java:140)
	at org.eclipse.core.internal.localstore.UnifiedTree.addNodeChildrenToQueue(UnifiedTree.java:246)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:112)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:971)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:954)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1560)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.updateProjects(MavenProjectImporter.java:136)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:118)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by ycycn** [comment] 2017-08-25 05:46
[Error - 下午1:46:19] 2017-8-25 13:45:26 Missing resource filter type: 'org.eclipse.ui.ide.multiFilter'.
null
java.lang.Error
	at org.eclipse.core.internal.resources.Filter.match(Filter.java:64)
	at org.eclipse.core.internal.resources.Filter.filterExcludes(Filter.java:159)
	at org.eclipse.core.internal.resources.Filter.filter(Filter.java:112)
	at org.eclipse.core.internal.resources.Resource.filterChildren(Resource.java:1971)
	at org.eclipse.core.internal.resources.Resource.isFilteredWithException(Resource.java:1916)
	at org.eclipse.core.internal.resources.Resource.isFiltered(Resource.java:1888)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allResourcesFor(FileSystemResourceManager.java:233)
	at org.eclipse.core.internal.resources.WorkspaceRoot.findFilesForLocationURI(WorkspaceRoot.java:94)
	at org.eclipse.core.internal.resources.WorkspaceRoot.findFilesForLocationURI(WorkspaceRoot.java:87)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findFile(JDTUtils.java:517)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:121)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:105)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.handleOpen(DocumentLifeCycleHandler.java:199)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$3.run(DocumentLifeCycleHandler.java:163)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.didOpen(DocumentLifeCycleHandler.java:160)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didOpen(JDTLanguageServer.java:401)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by psergiojr** [comment] 2018-05-27 02:45
vscode: 1.23.0 and 1.23.1
vscode-java: 0.25.0
JDK: 1.8.0_162
Manjaro Linux 64-bit

Deleting `workspaceStorage/` folder + restarting doesn't work.

It gets stuck in "37% Starting Java Language Server" forever. A process keep running and consuming RAM until there's nothing left.

When trying to "Open Java Language Server log file", nothing happens. In Developer Tools Console tab, nothing appears. Is there any file where I could get useful information to this thread?

**Comment by xianxingg** [comment] 2018-07-19 09:39
one possible reason maybe `gradle installation`. after uninstalling all java-related plugins, problem solved.

**Comment by matihost** [comment] 2018-10-31 21:20
Tried all internet hints:
- disabled gradle setting (aka  "java.import.gradle.enabled": false )
- removed workspace (aka https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory ) 
- left only Language Support for Java plugin v `0.33.0`  (remaining from MS recommended 'Java Extension Pack' disabled)

Java OpenJDK 1.11.0.1
Ubuntu 18.10

And `~/.config/Code/User/workspaceStorage/1051a_longHash_d8d0a3c/redhat.java/jdt_ws/.metadata/.log` contains:

```
!SESSION 2018-10-31 21:33:24.610 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /home/alaMaKota/.config/Code/User/workspaceStorage/1051a_longHash_d8d0a3c/redhat.java/jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.097
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.292
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.326
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.327
!MESSAGE Initializing Java Language Server 0.27.0.201810230509

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.384
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.444
!MESSAGE Creating the default Java project

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-31 21:33:28.613
!MESSAGE Finished creating the default Java project

!ENTRY org.eclipse.core.jobs 4 2 2018-10-31 21:35:14.692
!MESSAGE An internal error occurred during: "Initialize Workspace".
!STACK 0
java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1012)
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:667)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:593)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
(...)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:121)
```

PS. Feature improvement proposal: 
The option ctrl + shift + P  -> 'Java: Open Java Language Sever log files':  should show also `~/.config/Code/User/workspaceStorage/..../redhat.java/jdt_ws/.metadata/.log`   especially when the server has issues with starting.

**Comment by snjeza** [comment] 2018-10-31 23:08
@matihost Do you use symbolic links?

**Comment by matihost** [comment] 2018-11-01 12:54
Yes, I have symbolic links.
After removing them (hints: `find <workspace root dir> -type l` for other people  to locate them) 
the problem vanished.
I would consider this as a bug.

**Comment by snjeza** [comment] 2018-11-01 15:48
I think you had cyclic symbolic links.

**Comment by fbricon** [comment] 2018-11-01 16:20
@snjeza ideally, LocalProjectScanner should guard against infinite recursion.  @matihost can you describe how the links were set up, so we can reproduce the issue and guard against it?

**Comment by snjeza** [comment] 2018-11-01 23:30
Re https://bugs.eclipse.org/bugs/show_bug.cgi?id=540700

**Comment by houmanMP** [comment] 2019-03-11 18:27
I have a `node_modules` directory, which naturally comes with quite a few symlinks, and cannot delete it and have this issue. Might be related, dunno.

**Comment by fbricon** [comment] 2019-03-11 19:41
@houmanMP  node_modules is ignored during project discovery. Increasing the heap might be necessary for large projects (including many modules).

@matihost is this still an issue for you? The fix for circular symlinks has actually been applied weeks ago.

**Comment by matihost** [comment] 2019-03-11 22:07
Confirming that VSC: 1.32.1 +  Java Extension Pack 0.6.0  + some ansible galaxy import with symlinks
+ the option ctrl + shift + P -> 'Java: Open Java Language Sever log files': should show also ~/.config/Code/User/workspaceStorage/..../redhat.java/jdt_ws/.metadata/.log  shows
zero exceptions.

Thanks for fix

**Comment by roger93y** [comment] 2019-04-10 15:40
> Manage to fix this by deleting %APPDATA%\Code\User\workspaceStorage\

It really works! 

Windows 10 / VS Code 1.33.0

**Comment by wtsiamruk** [comment] 2019-04-13 17:19
> > Manage to fix this by deleting %APPDATA%\Code\User\workspaceStorage\
> 
> It really works!
> 
> Windows 10 / VS Code 1.33.0

Not for me :)

Windows 10/ VS Code 1.33.1 
Oracle Jdk 1.8.0_201 
MultiModule maven project

**Comment by yaohaizh** [comment] 2019-04-15 02:50
@wtsiamruk Could you help share your log here? And what is the size of your project?

**Comment by wtsiamruk** [comment] 2019-04-15 14:52
@yaohaizh project size is ~128mb (node_modules are excluded)
Unfortunately I have deleted workspaceStorage, and even done clean reinstall of vscode, still no success...

**Comment by wtsiamruk** [comment] 2019-04-21 13:38
@yaohaizh 

Here are logs from vscode Developer Console


```
[37m||-[2019-04-21 16:29:19.860][INFO][extension.js] Congratulations, your extension "vscode-java-saber" is now active![0m
console.ts:134 [Extension Host] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
t.log @ console.ts:134
console.ts:134 [Extension Host] Starting Java server with: C:\Program Files\Java\jdk1.8.0_201\bin\java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\Users\Admin\.vscode\extensions\redhat.java-0.43.0\server\plugins\org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar -configuration C:\Users\Admin\.vscode\extensions\redhat.java-0.43.0\server\config_win -data c:\Users\Admin\AppData\Roaming\Code\User\workspaceStorage\f0fa056c9a0643c94ffed8efa4cc302b\redhat.java\jdt_ws
console.ts:134 [Extension Host] [redhat.vscode-xml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[xml]', provide the URI of a resource or 'null' for any resource.
t.log @ console.ts:134
console.ts:134 [Extension Host]% false
```

Here is the image of stuck language server.

![image](https://user-images.githubusercontent.com/20062612/56470824-82247000-6453-11e9-91a7-579cf7430be8.png)


I've tried get logs of java language server but Nothing got opened after i've selected that option, it shows that in status bar

![image](https://user-images.githubusercontent.com/20062612/56470865-ec3d1500-6453-11e9-90e7-bac96537525f.png)

And then again back to '35%'

**Comment by snjeza** [comment] 2019-04-21 14:33
@wtsiamruk could you try to set the following property:
```
"java.jdt.ls.vmargs": "-Dlog.level=ALL -noverify -Xmx2G -XX:+UseG1GC -XX:+UseStringDeduplication",
```

**Comment by wtsiamruk** [comment] 2019-04-21 14:49
> @wtsiamruk could you try to set the following property:
> 
> ```
> "java.jdt.ls.vmargs": "-Dlog.level=ALL -noverify -Xmx2G -XX:+UseG1GC -XX:+UseStringDeduplication",
> ```

Sure, how?

**Comment by snjeza** [comment] 2019-04-21 15:23
File>Preferences>Settings

**Comment by wtsiamruk** [comment] 2019-04-21 15:42
> File>Preferences>Settings

after adding that property still can't open Java log server log but on developer console there is a lot of such thing


![image](https://user-images.githubusercontent.com/20062612/56472291-4692a180-6465-11e9-9c38-d2aab68200cb.png)

**Comment by wtsiamruk** [comment] 2019-04-21 15:44
I can invite one people to see source of the project.. because on another simple maven project all runs ok.

**Comment by snjeza** [comment] 2019-04-21 16:23
You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/580#issuecomment-443302372

**Comment by wtsiamruk** [comment] 2019-04-21 16:52
Nope, that doesn't help :(

**Comment by XanderWang** [comment] 2019-12-06 08:44
I had the same problem , when i try changed my project path , it is ok , you can try changed your porject path.

**Comment by jimnz111** [comment] 2020-03-30 00:50
I have been having issue of it never ending. Looked at the .log file and it was due to a git branch that had unmappable characters. I removed the branch locally and it now builds.

**Comment by Clinan** [comment] 2020-11-18 02:45
I remove workspaceStorage dir and uninstall plugin *vsc-mybatis*, it works!

**Comment by navaneeth-spotnana** [comment] 2021-03-10 10:54
I uninstalled the plugin and that also worked. :p

**Comment by JasonWThompson** [comment] 2021-07-22 16:22
This started happening recently for me. It seems to hang with some of my RPM projects. I'm using the rpm-maven-plugin. If I add said projects _after_ the language server is done loading, it works fine. But if I open up a workspace with an RPM project, it freezes at 63%.

**Comment by fbricon** [comment] 2021-07-22 16:26
@JasonWThompson see https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712

**Comment by rgrunber** [comment] 2021-08-19 21:46
I'm guessing this was resolved some time ago, but is a generic enough issue that can likely have many different causes (as described in #2020. To avoid just piling onto this issue, I'm going to close this off, so if the problem is persisting, we can get some more recent information in a new bug.

**Closed by rgrunber** 2021-08-19 21:46 UTC
Labels: bug, upstream
