### ISSUE TITLE
new version not support java8

### ISSUE THREAD

**Issue by daidai21** [redhat-developer/vscode-java#1764] opened 2021-01-14 06:49 UTC
##### Environment
- Operating System: mac
- JDK version: jdk1.8
- Visual Studio Code version: 1.52.1
- Java extension version: 0.73.0

##### Steps To Reproduce
1. [step 1] using jdk1.8, install vscode, intall newest `vscode-java` version
2. [step 2] open vscode, vscode-java start error.

##### Additional Informations

When I use  vscode-java `0.56.0`, this is success start and work.

**Comment by fbricon** [comment] 2021-01-14 07:48
Java 11 is required to run the vscode-java extension. But you can still compile your projects against Java 8 (from Java 1.5 to Java 15 actually). See https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#do-i-need-to-migrate-my-projects-to-java-11

Closing as duplicate of https://github.com/redhat-developer/vscode-java/issues/1543

**Closed by fbricon** 2021-01-14 07:48 UTC
Labels: duplicate
