### ISSUE TITLE
Reference markers misplaced and blinking

### ISSUE THREAD

**Issue by petrux** [redhat-developer/vscode-java#92] opened 2016-11-13 14:22 UTC
The reference markers are misplaced, moreover they continue appearing and disappearing as I edit making the whole editor totally unusable. Moreover, some other absurd error highlighted here and there. Please, see screencast attached.

##### Environment
- Operating System: Ubuntu 16.04
- JDK version: Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
- Visual Studio Code version: Version 1.7.1
- Java extension version: 0.0.6

![output](https://cloud.githubusercontent.com/assets/401919/20246312/a1d679ae-a9b4-11e6-8564-20b49abf6b89.gif)

**Comment by fbricon** [comment] 2016-11-14 13:33
Closing as duplicate of #87

**Closed by fbricon** 2016-11-14 13:33 UTC
Labels: duplicate

**Comment by petrux** [comment] 2016-11-14 16:23
In general, I noticed that some old errors remain highlighted. Is there any way to force a refresh?

**Comment by fbricon** [comment] 2016-11-14 17:42
No, except restarting vscode. We're looking into this issue, but it's not trivial.
