### ISSUE TITLE
Autocompletion with unimported types

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1123] opened 2019-10-29 09:12 UTC
When trying to invoke a static/instance method on an unimported type, VS Code should be more helpful.

##### Environment
- Operating System: Windows_NT x64 10.0.18362
- JDK version: openjdk full version "13.0.1+9"
- Visual Studio Code version: 1.39.2 (user setup)
- Java extension version: 0.52.0

##### Steps To Reproduce
Consider the code snippets below. When invoking code completion after the dot, I'd expect VS Code to help me somehow, e.g. by proposing all possible completions of all applicable types it knows of. Or by proposing to import the unknown types.

````java
class Foo {
    void foo() {
        IntStream.
    }
}
````

````java
class Foo {
    void foo() {
        new ArrayList().
    }
}
````

##### Current Result
For the first example, I need to first type something like `IntStream i;`, then trigger imports, then go back to `IntStream.` to trigger autocompletion.

##### Expected Result
I'd expect VS Code to help me somehow, e.g. by proposing all possible completions of all applicable types it knows of. Or by proposing to import the missing types.

##### Additional Informations
For comparison, when invoking the samples above in Apache NetBeans 11.0, I get the following:

![image](https://user-images.githubusercontent.com/15714253/67752889-1b03fb80-fa34-11e9-8f0a-bb41a7eda15b.png)

![image](https://user-images.githubusercontent.com/15714253/67752970-42f35f00-fa34-11e9-8709-3255734ffb9e.png)

**Comment by fbricon** [comment] 2019-10-29 09:16
That's an interesting feature, but we might be limited by JDT's capabilities. @snjeza can you please investigate whether this needs fixing upstream JDT or if it's doable from jdt.ls?

**Comment by mickaelistria** [comment] 2023-10-21 13:37
> Eclipse works the same way.

Can you please report the issue upstream in JDT then?

**Comment by snjeza** [comment] 2023-10-21 16:47
The following works in VS Code >= 1.23.0
```
void foo() {
    IntStream.|
}
```
![vscode3](https://github.com/redhat-developer/vscode-java/assets/388609/7b804c10-44b3-4b38-85d2-89850da256ee)

**Comment by snjeza** [comment] 2023-10-23 02:12
> Can you please report the issue upstream in JDT then?

@mickaelistria You may want to take a look at https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1502

**Comment by mickaelistria** [comment] 2023-10-23 07:38
thank you

**Comment by snjeza** [comment] 2023-10-23 23:34
The issue can be reproduced in Oracle Java Platform Support

![1123](https://github.com/redhat-developer/vscode-java/assets/388609/3fe817b5-9d59-411e-b729-68baa697eb4a)

**Comment by snjeza** [comment] 2023-10-29 16:47
I have tried Netbeans 19 and IntelliJ IDEA 2022.2.5.  They work like eclipse

Netbeans 19

![netbeans](https://github.com/redhat-developer/vscode-java/assets/388609/9cfd8d73-7c96-4965-ba9d-ff2d5126866e)

 IntelliJ IDEA 2022.2.5

![idea](https://github.com/redhat-developer/vscode-java/assets/388609/d7055a72-4590-42cd-a701-75a0df677883)

cc @fbricon @mickaelistria @anthonyvdotbe

**Comment by anthonyvdotbe** [comment] 2023-10-29 17:22
For NetBeans: yes, ArrayList broke somewhere between 11 and 19; IntStream still works.
For IntelliJ: enable `Add unambiguous imports on the fly`.

**Comment by snjeza** [comment] 2023-10-29 17:56
> IntStream still works.

It works in Eclipse/VS Code, too

**Comment by snjeza** [comment] 2023-10-30 14:55
> For IntelliJ: enable Add unambiguous imports on the fly.

+1

**Comment by rgrunber** [comment] 2024-12-09 16:07
Just tried this out in our pre-releases, since the fix was merged upstream (thanks to @snjeza ), and it seems we've picked it up as well now :

![Image](https://github.com/user-attachments/assets/01d2cc26-b6df-4adf-9d22-d38d646b1321)

Marking as closed for now.

**Closed by rgrunber** 2024-12-09 16:07 UTC
Labels: enhancement, upstream, content-assist
