### ISSUE TITLE
JDK-16 support

### ISSUE THREAD

**Issue by DarkDeveloper-Plant** [redhat-developer/vscode-java#1849] opened 2021-03-25 09:40 UTC
Hi, When language support for jdk-16 on vscode extention will arrive?

##### Environment
- Operating System: Linux Mint cinnamon 20
- JDK version: 16
- Visual Studio Code version: 1.54.3
- Java extension version: 0.76.0

**Comment by fbricon** [comment] 2021-03-25 09:46
Closing as duplicate of #1835

There should be a new release in the next couple of weeks. Until then, you can already try a CI build (see https://github.com/redhat-developer/vscode-java#contributing)

**Closed by fbricon** 2021-03-25 09:46 UTC
