### ISSUE TITLE
Java Annotations seems to be buggy

### ISSUE THREAD

**Issue by mac10046** [redhat-developer/vscode-java#104] opened 2016-11-25 04:31 UTC
I used Log4j annotation for logging ... and its working fine in eclipse IDE. I tested the same Gradle project 
and read the annotations but it gave a red underline in statements where I have used log.info stating that it could not find any imports for it.

##### Environment
- Windows 7:
- JDK 1.8:
- Visual Studio Code 1.7.2:
- Java extension v0.0.7:

##### Steps To Reproduce
1. use @Log4j annotations about the class name
2. use log.info("log info texr"); in functions

**Comment by fbricon** [comment] 2016-11-25 14:10
Gradle support is not available yet.

Your project is partially configured because it was open in Eclipse, therefore it has some eclipse project metadata that were used to configure Java support in vscode. But because the gradle support is missing, all dependencies provided by the Gradle classpath container can't be found.

Closing as duplicate of #10.

**Closed by fbricon** 2016-11-25 14:10 UTC
Labels: duplicate
