### ISSUE TITLE
[Enhancement] Support for local workspace resolution of dependencies

### ISSUE THREAD

**Issue by fcrespo82** [redhat-developer/vscode-java#464] opened 2018-03-13 21:29 UTC
Hi, I'm working with 2 related projects in a vscode workspace.

One is a CORE structure and the other an API for that CORE.

In the pom.xml for the API it has the dependency set as such:

```xml
<dependency>
    <groupId>my.package</groupId>
    <artifactId>CORE</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
```

It would be from great value, if the plugin could handle that situation.

Right now, I must install CORE to my local maven repository to get the updates to CORE.

Would be nice if it supports the same type of local dependency as Eclipse and [IntelliJ IDEA](https://stackoverflow.com/a/35739440/1631382) resolve Workspace artifacts.

**Comment by fbricon** [comment] 2018-03-13 22:13
It already works like that. Do you have sample projects where it doesn't?

**Comment by fcrespo82** [comment] 2018-03-13 22:23
Right now I only have my company's code which I can't share for obvious reasons.

I'll try to replicate in a sample project and them post back here.

**Comment by fcrespo82** [comment] 2018-03-13 22:39
Investigating further I've found that it happened when I changed a yaml configuration file. It does not trigger the rebuild and fails to get the changes to the file. But if I then change some java code, it triggers the build and reload the configuration file correctly.

Is there some way to force the build when a config file (.yml or .properties) change?

**Comment by fbricon** [comment] 2018-03-13 22:40
Is this a runtime or a compilation issue?

**Comment by fcrespo82** [comment] 2018-03-13 22:44
Runtime. I have this yaml that is referenced in a SpringBoot Configuration Class that is instantiated on running the project.

```yaml
store:
   root: '/path-to-file-store'
```

**Comment by fbricon** [comment] 2018-03-13 22:48
ok so this is a duplicate of #400. There's no solution right now, other than performing a manual `mvn process-resources` (add -o to speed it up)

**Closed by fbricon** 2018-03-13 22:48 UTC

**Comment by fcrespo82** [comment] 2018-03-13 22:53
Ohh. Couldn’t find that on my searches. Thanks for the quick reply!
