### ISSUE TITLE
Can not start java language server with jdk 9

### ISSUE THREAD

**Issue by netroby** [redhat-developer/vscode-java#173] opened 2017-03-30 00:57 UTC
[Error - 上午8:55:06] Starting client failed
[object Object]

##### Environment
- Operating System: windows 10 x64
- JDK version: jdk9
- Visual Studio Code version: 1.10.2
- Java extension version: 

##### Steps To Reproduce
1. Install jdk 9 
2. install vscode-java
3. open java project

##### Current Result
show error:

couldn't start client language support for java
##### Expected Result
java language server start success

**Comment by fbricon** [comment] 2017-03-30 02:06
Closing as duplicate of #43

**Closed by fbricon** 2017-03-30 02:06 UTC
