### ISSUE TITLE
Ant Build.xml support

### ISSUE THREAD

**Issue by ericj79** [redhat-developer/vscode-java#635] opened 2018-09-11 17:56 UTC
I would like the extension to support a workspace with a build.xml file instead of a pom.xml or build.gradle. I have a have project that builds using Ant. It is very simple, and I have no reason to change the build system, but I would like the java plugin to be able to support intellisense for my code.
It would also be nice if I could specify where the build file is found. I have a folder in my workspace, but the project uses multiple languages. I have all the build files in a separate folder.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_91
- Visual Studio Code version: 1.26.1
- Java extension version: 0.29.0

**Comment by fbricon** [comment] 2018-09-11 18:56
Closing as duplicate of #477

**Closed by fbricon** 2018-09-11 18:56 UTC
Labels: duplicate
