### ISSUE TITLE
The entire class name is deleted after pressing the backspace key on the keyboard

### ISSUE THREAD

**Issue by loralei28** [redhat-developer/vscode-java#3226] opened 2023-07-27 09:23 UTC
##### Environment
- Operating System: M1
- JDK version:17.0.4
- Visual Studio Code version:1.80.1-universal
- Java extension version:1.21.0

##### Steps To Reproduce
1. Open a java file 
2. Double click on the class name > Rename Symbol
3. Press the backspace key on the keyboard

##### Current Result

https://github.com/redhat-developer/vscode-java/assets/108506566/368d689a-2734-4675-888d-1c30c15c71b8

##### Expected Result

![1](https://github.com/redhat-developer/vscode-java/assets/108506566/b53acb3a-fa7e-454c-b004-a9b15dacb65e)

**Comment by testforstephen** [comment] 2023-07-27 11:17
This is a regression caused by https://github.com/redhat-developer/vscode-java/pull/3159, which intercepts the system `backspace` shortcut and results in rename refactoring broken. We have to revert that PR first.

**Comment by snjeza** [comment] 2023-07-28 21:18
Fixed via https://github.com/redhat-developer/vscode-java/pull/3229

**Closed by snjeza** 2023-07-28 21:18 UTC
Labels: regression
