### ISSUE TITLE
Add support for looking up Classes and Methods on classpath

### ISSUE THREAD

**Issue by rubin55** [redhat-developer/vscode-java#204] opened 2017-05-08 06:30 UTC
Currently vscode-java allows completion and introspection of Classes and Methods on-the-fly while editing your code. Afaik, currently the only way for someone to find the source of a class or method is to have the Class imported.

 It would be amazingly helpful if you could find Classes, Interfaces (and their implementations) and methods that are available to you (i.e. configured on the classpath, either explicitly or via Maven dependencies). 

##### Environment
- Operating System: Windows 10
- JDK version: Oracle JDK 8 Release 121
- Visual Studio Code version: 1.12.1
- Java extension version: 0.3.0

##### Steps To Reproduce
N/A, Feature request.

**Comment by fbricon** [comment] 2017-05-08 13:17
You can already find classes and interfaces available in the classpath:
![autocomplete](https://cloud.githubusercontent.com/assets/148698/25805571/326a8674-33ce-11e7-950c-4b42289b8a09.gif). 

Search for interface implementors is something we'll implement, eventually, see https://github.com/eclipse/eclipse.jdt.ls/issues/99.

Method autocompletion requires the type to be imported in the 1st place. If you have a specific workflow in mind, could you please describe it, or point us to similar workflows in other IDEs?

**Comment by rubin55** [comment] 2017-05-08 16:22
I was thinking more like "pop up dialog by some key combination" type, get class or class.method by matching, press enter, open .java or .class file. To do that in the file you're working on atm directly is a little hackish (ie you introduce errors in the current file, you might not want to use said clase in the current file at all but are looking for general usage details/impl details for the class).

**Comment by fbricon** [comment] 2017-05-08 18:10
So as I understand it, that'd be something similar to the `Ctrl+T` (or `Cmd`+T on Mac) to open workspace symbols (=types),  only it would be extended to all available classes.

I'm not too fond of the idea of introducing additional windows/wizards if we could avoid it.

So ideally, we could perform a workspace wide search for all types with our own custom prefix in the command palette (say `$` instead of `#`), to perform something equivalent to `Ctrl+Shift+T` in eclipse. I don't know if vscode allows extensions to contribute such action prefixes to the command palette. @jrieken @egamma what are our options here?

We could still perform the full classpath search when hitting `#`, but I'd feel like abusing the semantic of `Go to symbol in workspace` action.

**Comment by egamma** [comment] 2017-05-08 18:51
@fbricon 
>We could still perform the full classpath search when hitting  # , but I'd feel like abusing the semantic of  Go to symbol in workspace  action.

In the context of Java I consider this as fair play to implement the LSP protocol `workspace/symbol` to mean all symbols available on the class path. When selecting a symbol that is located outside of the workspace then vscode-java can open a virtual document.

**Comment by fbricon** [comment] 2017-05-08 20:32
@egamma ok so I gave it a try and unfortunately it just doesn't scale. Including JDK and other classpath dependencies to the workspace symbol search, for the [spring-amqp](https://github.com/spring-projects/spring-amqp) project as an example, the search engine returns 67862 hits, that are transformed into SymbolInformations. So everything is super slow until the UI just freezes and we never even see one result on screen.

Obviously we need to limit the results, but then the problem is no new search is triggered if you continue typing in the search bar. `workspace/symbol` is invoked once and for all by VS Code. I think the server protocol should allow some sort of isComplete attribute in the response, similar to what's done for `textDocument/completion`. wdyt?

**Comment by egamma** [comment] 2017-05-09 09:35
@fbricon  I did not expect that this works without some more tuning. I remember all the effort that was put into Eclipse to make this fast.

How many of the hits are types? The Intellisense widget can handle hits of this magnitude, we have tests with about 20k hits. One difference is that the Intellisense widget is using a newer tuned list widget, whereas quick pick is still using the tree. So this is another optimization area.

I've added @aeschli his memory is more fresh than mine on what was all done in Eclipse to make this fast.

**Comment by aeschli** [comment] 2017-05-09 09:53
I thought the Java Language server already implement the workspace symbols request.
See [WorkspaceSymbolHandler].(https://github.com/eclipse/eclipse.jdt.ls/blob/47a4d8b19df53f7da8865b4e643033cf4d76fb7b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java)

This should run pretty performant as it limits itself to types (no fields or methods) which is highly tuned in JDT.

To avoid the huge result set, the API should be used with a filter string.
Also in the LSP, the `workspace/symbol` request has a queryString argument.

In Eclipse we didn't return any results unless you provided a filter string. I suggest changing the implementation in the Java language server to do the same.

**Comment by rubin55** [comment] 2017-05-09 10:29
That sounds great, even if only classes/types and not methods, it would definitely be a major plus with a more experimental development flow (getting to know the framework/library you're using, reading the code representation of a class, etc).

**Comment by fbricon** [comment] 2017-05-09 13:33
@egamma  @aeschli when forcing a non empty query, things get better, but still feel too sluggish. When sending `A` for instance, the server return 4204 types in 5 seconds. From there, the result list is displayed very fast. 
So the server side search is way too slow, compared to Eclipse's same type search. It seems the search itself is fairly fast, but we spend a huuuge amount of time converting the results into SymbolInformations. Anyways, that one's on us, not vscode :-)

**Comment by aeschli** [comment] 2017-05-09 13:44
@fbricon Something must go wrong in [WorkspaceSymbolHandler](https://github.com/eclipse/eclipse.jdt.ls/blob/47a4d8b19df53f7da8865b4e643033cf4d76fb7b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java), causing to resolve the TypeNameMatch's underlying JavaElement.
My wild guess its that it is in `DocumentSymbolHandler.mapKind(match.getType()))` and the test `type.isInterface()`.

Instead use 
```
  int flags= match.getModifiers(); 
   if (Flags.isInterface(flags)) { 
    if ((typeKinds & SimilarElementsRequestor.INTERFACES) != 0) {
      ...

```

**Comment by fbricon** [comment] 2017-05-09 13:57
Thanks for the pointer @aeschli. I'll try that as soon as I can

**Comment by jrieken** [comment] 2017-05-10 07:46
FYI and unsure if you already do that, but resolving workspace symbols can happen in two steps: First (when `provide` is called) you can leave out the location information and feed that in when `resolve` is being called (when a references is actually being selected). We have done that because  providers often have to pay an extra price to compute the the line/column information (instead of offsets) we want. Unsure if that applies for Java tho

**Comment by fbricon** [comment] 2017-05-10 14:24
@jrieken For now location for types is not computed, always set to 0,0. so that's not an issue.

The performance issue is indeed caused by computing the types, as @aeschli hinted, but we also loaded each type's buffer at some point which was unnecessary. I'm down to ~1 sec to load the types starting with letter A now, but I need to figure out why I'm seeing duplicates and some results cause an error. Anyway, making progress here :-)

**Closed** 2017-05-15 20:08 UTC
Labels: enhancement, in progress, need info

**Comment by fbricon** [comment] 2017-05-15 20:10
Ctrl+T now lists all classes from the workspace
Once you found your class and opened it, Ctrl+Shift+o will list all methods and attributes from said class (if source is available)

**Comment by rubin55** [comment] 2017-05-16 08:45
Just updated to 0.4.0 and tested this, works great!

Much appreciated. I'm still awed by how quick you implemented this. Thanks again!

**Comment by dmarrazzo** [comment] 2019-05-24 15:29
Hi,
Is it possible to extend this feature to match even partial string?
I mean if I type "vismec", I'd like to match "VisitOrMechanic" class.

**Comment by fbricon** [comment] 2019-05-24 18:48
@dmarrazzo CamelCase search is supported:
![camel-case-search](https://cloud.githubusercontent.com/assets/148698/26115970/90abf940-3a2f-11e7-8da1-bef437123965.gif)

so, in your case, you should try searching for `VisMec`

**Comment by b-liberman** [comment] 2019-08-03 09:54
I have version 0.47.0 and it is not working well. 
For some classes - it works as expected, e.g.
![image](https://user-images.githubusercontent.com/22765155/62410373-f4752680-b5e4-11e9-80ef-75864818067b.png)

However, many times I have to type "*" in front and then type the complete name before it appears in the list, e.g.:
![image](https://user-images.githubusercontent.com/22765155/62410401-2b4b3c80-b5e5-11e9-936e-88c2ea982e33.png)
![image](https://user-images.githubusercontent.com/22765155/62410409-3bfbb280-b5e5-11e9-827b-e6ac9f1bd083.png)
![image](https://user-images.githubusercontent.com/22765155/62410416-5766bd80-b5e5-11e9-8ee2-6f93701a4a0d.png)
![image](https://user-images.githubusercontent.com/22765155/62410420-62215280-b5e5-11e9-9e99-3d8982071a09.png)

Boris

**Comment by fbricon** [comment] 2019-08-03 12:23
Can you please attach a sample projects reproducing the issue?

**Comment by b-liberman** [comment] 2019-08-03 15:10
here is my gradle and vs code files
[vscode_204.zip](https://github.com/redhat-developer/vscode-java/files/3463974/vscode_204.zip)

**Comment by banatara** [comment] 2019-09-29 03:27
Hi Team, I am able to search types based on the java class name or Interface name, but could not list the  types that are with the package. Say example, when I type `ctrl+t` `#sun.rmi.server` it should probably list all the class /Interface or anything with that package. This has been the feature in eclipse already as mentioned by peoples earlier in this thread.

**Comment by liudonghua123** [comment] 2021-05-25 02:29
I also looking for search java classes which the classes are in some jars.
