### ISSUE TITLE
leaves zombie processes

### ISSUE THREAD

**Issue by aviv-amdocs** [redhat-developer/vscode-java#1980] opened 2021-06-14 06:55 UTC
Issue Type: <b>Bug</b>

Using the extension and exiting/reloading vscode leaves zombie (defunct) `java` processes on the host.
I'm using "Remote: SSH" to work (remote is Linux, local is Windows).

Extension version: 0.79.2
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit
Remote OS version: Linux x64 5.10.25-linuxkit
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary> pgrep | ps </summary>

```
$ pgrep java | xargs ps -f 
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
user     323     1  0 Jun11 pts/4    Z      0:53 [java] <defunct>
user     845     1  0 Jun10 ?        Z      3:13 [java] <defunct>
user     877     1  0 Jun10 ?        Z      3:21 [java] <defunct>
user     975     1  0 Jun10 ?        Z      3:15 [java] <defunct>
user    3858     1  0 Jun10 ?        Z     25:55 [java] <defunct>
user   13540     1  0 Jun13 ?        Z      6:16 [java] <defunct>
user   16407     1  0 Jun12 pts/4    Z      0:51 [java] <defunct>
user   20677     1  0 09:12 ?        Z      0:11 [java] <defunct>
user   22122     1  0 Jun12 pts/4    Z      0:51 [java] <defunct>
user   25333     1  0 Jun11 ?        Z      2:02 [java] <defunct>
user   25822     1  0 Jun10 pts/4    Z      0:53 [java] <defunct>
user   30418     1  7 09:23 ?        Z      2:05 [java] <defunct>
user   31579     1  0 Jun10 pts/4    Z      1:28 [java] <defunct>
user   36139     1  0 09:28 ?        Z      0:06 [java] <defunct>
user   37038     1  0 09:29 ?        Z      0:08 [java] <defunct>
user   37646     1  0 09:29 ?        Z      0:07 [java] <defunct>
user   38144     1  0 Jun13 ?        Z      0:33 [java] <defunct>
user   39655     1  0 09:31 ?        Z      0:06 [java] <defunct>
user   40020     1  0 Jun13 ?        Z      0:57 [java] <defunct>
user   40079     1  5 09:31 ?        Z      1:05 [java] <defunct>
user   42914     1  0 Jun13 pts/4    Z      0:14 [java] <defunct>
user   43065     1  0 Jun13 pts/4    Z      0:47 [java] <defunct>
user   54953     1  0 Jun13 ?        Z      0:27 [java] <defunct>
user   55101     1  0 Jun13 ?        Z      8:54 [java] <defunct>
user   55573     1  0 Jun12 pts/4    Z      0:21 [java] <defunct>
user   55769     1  0 Jun12 pts/4    Z      0:33 [java] <defunct>
user   56866 52065  0 09:44 ?        Sl     0:04 /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/user/.vscode-server/extensions/redhat.java-0.79.2/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /home/user/.vscode-server/data/User/globalStorage/redhat.java/0.79.2/config_ss_linux -data /home/user/.vscode-server/data/User/workspaceStorage/73e7468acc665bdca57d62194cba9be9/redhat.java/ss_ws
user   57034     1  8 Jun12 ?        Sl   212:10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/user/.vscode-server/extensions/redhat.java-0.79.2/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /home/user/.vscode-server/data/User/globalStorage/redhat.java/0.79.2/config_linux -data /home/user/.vscode-server/data/User/workspaceStorage/ecbff0b173cd02be928095d5a6e765cb/redhat.java/jdt_ws
user   57093 52052  1 09:44 ?        Sl     0:08 /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/user/.vscode-server/extensions/redhat.java-0.79.2/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /home/user/.vscode-server/data/User/globalStorage/redhat.java/0.79.2/config_ss_linux -data /home/user/.vscode-server/data/User/workspaceStorage/158468538c785d689c62e773b324708c/redhat.java/ss_ws
user   57126     1  0 Jun13 ?        Z      1:07 [java] <defunct>
user   57176 52053  1 09:44 ?        Sl     0:06 /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/user/.vscode-server/extensions/redhat.java-0.79.2/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /home/user/.vscode-server/data/User/globalStorage/redhat.java/0.79.2/config_ss_linux -data /home/user/.vscode-server/data/User/workspaceStorage/ecbff0b173cd02be928095d5a6e765cb/redhat.java/ss_ws
user   71016     1  0 Jun12 ?        Z      1:04 [java] <defunct>
user   77966     1  0 Jun11 ?        Z      6:00 [java] <defunct>
user   81535     1  0 Jun12 ?        Z      0:18 [java] <defunct>
user   81747     1  0 Jun12 ?        Z      0:44 [java] <defunct>
user   81943     1  0 Jun12 ?        Z      1:06 [java] <defunct>
user   84281     1  0 Jun12 ?        Z      0:18 [java] <defunct>
user   84471     1  0 Jun12 ?        Z      0:44 [java] <defunct>
user   84716     1  0 Jun13 ?        Z      1:34 [java] <defunct>
user   85093     1  0 Jun13 ?        Z      1:21 [java] <defunct>
user   86370     1  0 Jun13 ?        Z      1:11 [java] <defunct>
user   86616     1  0 Jun13 ?        Z      8:25 [java] <defunct>
user   87113     1  0 Jun12 ?        Z      0:54 [java] <defunct>
user   88254     1  0 Jun12 ?        Z      0:57 [java] <defunct>
user   89366     1  0 Jun12 ?        Z      1:26 [java] <defunct>
user   93919     1  0 Jun11 ?        Z      0:02 [java] <defunct>
```

</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (3 x 1992)|
|Memory (System)|18.57GB (8.03GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (3 x 1992)|
|Memory (System)|18.57GB (8.03GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (3 x 1992)|
|Memory (System)|18.57GB (8.03GB free)|
|VM|0%|
</details>

**Comment by aviv-amdocs** [comment] 2021-06-14 09:15
A bit more info: I have a `watch` over `pgrep java | grep defunct | wc -l` running, and here's some stuff I've noticed:
- activating "clean java language server workspace" task increases zombie count by 1.
- Switching from "lightweight" mode to "standard" increases zombie count by 1.
- closing a vscode window (in standard mode): plus 2 zombies.

**Comment by rgrunber** [comment] 2021-06-14 16:43
Part of this is a known issue which should be fixed by https://github.com/redhat-developer/vscode-java/issues/1928. When we adopted languageclient v7, shutdown requests sent to the syntax server were not being handled correctly, so in our next release, we have a workaround.

The zombie process behaviour could be an issue with remote connections given that  it seems to happen for any language server (syntax, standard) that's started up.

**Comment by snjeza** [comment] 2021-06-15 12:56
I can't reproduce the issue on Windows (local) and Fedora (remote).
What Linux are you using?

**Comment by aviv-amdocs** [comment] 2021-06-15 13:02
It's Ubuntu: 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

but it's running as a Docker container under Windows (Docker-Desktop-with-Hyper-V)
```
$ uname -a
Linux b 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

(Connecting over SSH).

**Comment by snjeza** [comment] 2021-06-15 13:37
Could you attach your Dockerfile?

**Comment by aviv-amdocs** [comment] 2021-06-15 13:45
Sure (slightly redacted):
```dockerfile
ARG USER_ID=1000
ARG USER_NAME=user

FROM ubuntu:20.04

RUN apt-get update
RUN yes | unminimize
RUN apt-get upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

RUN apt-get update && apt-get install -y \
    bash-completion \
    busybox \
    dnsutils \
    iproute2 \
    less \
    lsof \
    man \
    nano \
    netcat \
    psmisc \
    sudo \
    ;
RUN apt-get install -y \
    openssh-server \
    ;
RUN apt-get install -y  \
    inotify-tools \
    language-pack-en
RUN apt-get install -y  \
    automake \
    curl \
    git-man \
    pkg-config
RUN apt-get install -y  \
    graphviz
RUN apt-get install -y \
    python3-pip \
    virtualenv \
    ;
RUN apt-get update && apt-get install -y  \
    build-essential \
    colordiff \
    jq \
    libncurses-dev \
    moreutils \
    p7zip-full \
    tmux \
    tree \
    unzip \
    zlib1g-dev \
    ;
RUN apt-get install -y  \
    maven \
    openjdk-11-jdk \
    ;

RUN pip3 install \
    click \
    mypy \
    pyyaml \
    requests \
    ;


COPY --from=docker:dind /usr/local/bin/docker /usr/bin/
ADD https://github.com/docker/cli/raw/master/contrib/completion/bash/docker /usr/share/bash-completion/completions/docker
RUN chmod 644 /usr/share/bash-completion/completions/docker

ADD https://github.com/openshift/oc/raw/master/contrib/completions/bash/oc /usr/share/bash-completion/completions/oc
RUN chmod 644 /usr/share/bash-completion/completions/oc

RUN update-locale LANG=en_US.utf8

EXPOSE 22
RUN mkdir /var/run/sshd
CMD ["sudo", "/usr/sbin/sshd", "-D"]

COPY environment /etc/environment
COPY certs/*crt /usr/local/share/ca-certificates/
RUN chmod 644 /usr/local/share/ca-certificates/*crt
RUN update-ca-certificates

ARG USER_ID
ARG USER_NAME
RUN adduser --uid ${USER_ID} --gecos '' \
  --disabled-password --home /home/user \
  ${USER_NAME}
RUN echo "${USER_NAME} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers.d/user

WORKDIR /home/user
USER ${USER_ID}:${USER_ID}
```


`/etc/environment` and `/ca-certs/` are just some local-site related proxies and self-signed certs.

**Comment by snjeza** [comment] 2021-06-16 17:11
@aviv-amdocs  I can reproduce the issue using your docker image.
It isn't a VS Code issue.
You have to start sshd properly.
You can try to start sshd using the following:

1. add entrypoint.sh:
```
#!/usr/bin/env bash
sudo /usr/bin/ssh-keygen -A
sudo /usr/sbin/sshd -D &
tail -f /dev/null
```
2. remove the line:
```
CMD ["sudo", "/usr/sbin/sshd", "-D"]
```
3. add
```
COPY ["entrypoint.sh","/home/user/entrypoint.sh"]
ENTRYPOINT ["/home/user/entrypoint.sh"]
```
after 
```
USER ${USER_ID}:${USER_ID}
```

**Comment by aviv-amdocs** [comment] 2021-06-17 05:46
Thanks @snjeza, I'll explore this avenue.

**Comment by aviv-amdocs** [comment] 2021-06-21 06:03
Yeah, looks like adding a `sh` parent to `sudo ssh` does reap zombies.

Still, the plugin should do a better job at cleaning up its children.

**Comment by snjeza** [comment] 2021-06-21 18:28
> Still, the plugin should do a better job at cleaning up its children.

You can reproduce the issue using a simple ssh connect/disconnect and your docker image. VS Code also use a such client. sshd creates these children and it should clean them. VS Code can do nothing.

**Comment by rgrunber** [comment] 2021-08-06 14:12
Closing this out as it seems there's a valid workaround. If this continues to be an issue in other situations, then maybe we can look at some kind of strategy to prevent this.

**Closed by rgrunber** 2021-08-06 14:12 UTC
Labels: upstream
