### ISSUE TITLE
Zsh updated macs fail to link java with newest update

### ISSUE THREAD

**Issue by andrewtheiss** [redhat-developer/vscode-java#3294] opened 2023-09-13 21:12 UTC
WHY IS THE ABOVE ALL CAPS?  I FEEL LIKE YOU'RE YELLING

- My class is using this plugin and a recent update to zsh properly links to JAVA_HOME via the new shell.  Once updating to the recent version of the plugin, java (and all sub classes i.e. java.lang, java.lang.Object... etc) cannot be properly linked. 

- Solution: revert to the previous version of this code

- More permanent solution:
   Manually define JAVA HOME links in a resource file such as:

file contents of ~/.zshrc
export JAVA_HOME=$(/src/libexec/java_home)
export PATH=$JAVA_HOME/bin:$PATH

Please check if this was compiled on a computer/mac which changes linking to JAVA_HOME or still using the now deprecated shell (not zsh) on mac.

Hope it's reproducible! 

[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment] 2023-09-13 21:35
see if this helps: https://github.com/redhat-developer/vscode-java/issues/3287#issuecomment-1718107346, might be the same issue

**Comment by fbricon** [comment] 2023-09-14 09:52
Closing as duplicate of #3287. [Please update to 1.22.1](https://github.com/redhat-developer/vscode-java/issues/3287#issuecomment-1719130432)

**Closed by fbricon** 2023-09-14 09:52 UTC
