### ISSUE TITLE
The declared package "x" does not match the expect package ""

### ISSUE THREAD

**Issue by safield** [redhat-developer/vscode-java#778] opened 2019-01-27 01:17 UTC
OS: Linux Mint 19.1
OpenJDK 1.8
VSCode v1.30.2
Java language support extension v0.37

I have a Java project using gradle to build. The Gradle build is configured to build as a lib. When I build with gradle everything is great. From the Java compilers perspective there is nothing wrong with my code.

But the VsCode java plugin is complaining about my package statement...

It says .... 

> The declared package "dawcore" does not match the expected package "".

My folder structure matched the correct folder structure for the package, eg the src files are in the folder src/dawcore.

I have also run update project configuration.

I have attached a very minimal project example of my situation. If you open the file src\dawcore\AudioMaster.java, you should be able to observe the error I am seeing.

[DawCoreTest.zip](https://github.com/redhat-developer/vscode-java/files/2799671/DawCoreTest.zip)

**Comment by snjeza** [comment] 2019-01-28 18:35
@safield You haven't defined project source directory properly .
Try the following build.gradle:
```
apply plugin: 'java-library'
repositories {
    jcenter()
}

sourceSets {
    main {
        java {
            srcDirs = ['src'] // changed line
        }
    }
}
```

**Comment by fbricon** [comment] 2019-02-07 17:05
Even though javac compiles the class on CLI, you can't run it. The Eclipse compiler is more strict, so this is expected. 
You need to fix the srcDirs value, as shown by @snjeza.

Closing as not a bug

**Closed by fbricon** 2019-02-07 17:05 UTC
Labels: Gradle, not-a-bug

**Comment by MattMcL1221** [comment] 2021-05-03 19:50
What is build.gradle? I'm having the same issue and can't find a way to fix the bug as my package definitely is declared despite it saying otherwise

**Comment by snjeza** [comment] 2021-05-03 20:05
@MattMcL1221 Could you attach a project example?

**Comment by MattMcL1221** [comment] 2021-05-03 20:10
@snjeza Sorry to bother! I managed to fix it by editing whatever was in the settings.json file and then closing and reopening the VS Code app 4 times. Not sure why this happens though I feel like the program should still run fine even when trying to declare a package
