### ISSUE TITLE
Syntax highlighting degrades over time

### ISSUE THREAD

**Issue by DerDunkel** [redhat-developer/vscode-java#3147] opened 2023-06-09 12:25 UTC
while writing code over time the syntax highlighting creates more and more artefacts. 
After a while there is code highlighted that is commented out
Existing code starts to get highlighted wrong starting in the middle of a word.

After a restart it is correct again for a little while.

##### Environment
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
- JDK version: java 17.0.6 2023-01-17 LTS
- Java extension version:1.19.0

##### Steps To Reproduce
The problem seems to appear after a time after writing any code. Added a picture that shows the results.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by jdneo** [comment] 2023-06-12 01:54
Looks like there is no screenshot attached.

While I guess the problem is the same as https://github.com/redhat-developer/vscode-java/issues/2176. Because the textmate based highlighting won't get `wrong starting in the middle of a word.`

**Comment by fbricon** [comment] 2023-06-19 07:39
closing as duplicate of #2176

**Closed by fbricon** 2023-06-19 07:39 UTC
Labels: duplicate, highlighting
