### ISSUE TITLE
Bug: Quick fix does not suggest basic imports as a solution

### ISSUE THREAD

**Issue by Biyakuga** [redhat-developer/vscode-java#3715] opened 2024-07-19 20:12 UTC
[provide a description of the issue]

##### Environment
Operating System: Windows11
JDK version: 17
Visual Studio Code version: 1.88
Java extension version: 1.29

##### Steps To Reproduce
1. Create a java file and try to create List/Set/Map
2. Error no import available from quick fix

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

![image](https://github.com/user-attachments/assets/7170d117-650c-4962-9123-28da799cd496)

##### Current Result
Like in the image above I have to manually add the import to fix the problem

##### Expected Result
Quick fix should give me imports as a suggestion

**Comment by snjeza** [comment] 2024-07-19 21:25
I can't reproduce the issue. 
@Biyakuga Could you show your extensions and settings.json?

**Comment by anthonyvdotbe** [comment] 2024-07-23 09:05
I'm having the same issue (also with classes outside `java.util`, like e.g. `java.time.format.DateTimeFormatter`).
This is with the pre-release version (v1.33.2024072008) and the following settings:

```json
"java.autobuild.enabled": false,
"java.codeGeneration.hashCodeEquals.useJava7Objects": true,
"java.codeGeneration.toString.codeStyle": "STRING_FORMAT",
"java.codeGeneration.useBlocks": true,
"java.completion.favoriteStaticMembers": [
    "java.lang.System.Logger.Level.*",
    "java.nio.charset.StandardCharsets.*",
    "java.util.Spliterator.*",
    "java.util.function.Predicate.*",
    "java.util.stream.Collectors.*"
],
"java.completion.guessMethodArguments": true,
"java.configuration.updateBuildConfiguration": "automatic",
"java.format.comments.enabled": false,
"java.inlayHints.parameterNames.enabled": "none",
"java.signatureHelp.enabled": true,
```

**Comment by fbricon** [comment] 2024-07-23 09:20
I've had this issue yesterday. `Java: Clean Java Language Server Workspace` fixed it for me. There's definitely something fishy here we need to fix.

**Comment by magicalmuggle** [comment] 2024-08-26 06:14
I encountered the same problem. One not very stable reproduction method is to delete the import statement of the `List` class, then close the window, reopen the window, and press `Ctrl +.` after the project is loaded. Repeat the operation. Sometimes quick fixes do not recommend basic imports as a solution.

**Comment by rgrunber** [comment] 2024-10-16 19:10
I would try the vscode-java pre-release build tomorrow. There's a good chance this has been fixed now.

**Comment by MartinBernstorff** [comment] 2024-10-24 07:44
This was fixed for me by using the pre-release build 👍

**Closed** 2024-10-29 15:05 UTC
Labels: bug, code action
