### ISSUE TITLE
How to search in java dependencies ?

### ISSUE THREAD

**Issue by l0ca1** [redhat-developer/vscode-java#1283] opened 2020-02-18 08:38 UTC
Like this feature of idea：
![image](https://user-images.githubusercontent.com/23295562/74718163-a0721c80-526c-11ea-974e-c1919363a1c6.png)

##### Environment
- Operating System: mac
- Visual Studio Code version: 1.42.1
- Java extension version:Java Dependency Viewer 0.8.0

**Comment by fbricon** [comment] 2020-02-18 08:50
Dependency sources search is currently not supported. It's an interesting feature though, but would require indexing all sources of all dependencies, that might be tricky, slow, and memory hungry ;-)

Right now, you can do a type search though: `Cmd+T` (`Ctrl+T` on Win/Linux), type the class name you're looking for, it'll search for all matching types in the workspace. Camel case typing works, like NPE for NullPointerException.

**Comment by rgrunber** [comment] 2023-03-03 20:43
Closing as a duplicate of https://github.com/redhat-developer/vscode-java/issues/1712 . Basically we can search for all types, and even methods from source files. To be able to search for any member(field,method,type,etc.), there would be performance concerns, but there are ways to address this, as I mention in https://github.com/redhat-developer/vscode-java/issues/1712#issuecomment-1059524516 .

**Closed by rgrunber** 2023-03-03 20:43 UTC
Labels: enhancement
