### ISSUE TITLE
Signature Help sometimes doesn't work on constructors and qualified method declarations

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2097] opened 2021-09-05 02:07 UTC
Issue Type: <b>Bug</b>

In the process of editing Java code, the method parameter prompt is abnormal, and the method parameter information cannot be correctly prompted.
In some cases, the method parameter information cannot be prompted, which is very frustrating. . .
For a demo, please see the attached...

Extension version: 0.81.0
VS Code version: Code - Insiders 1.60.0-insider (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:40:58.134Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (3.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by zhouxinghong** [comment] 2021-09-05 03:04
https://user-images.githubusercontent.com/54253524/132113483-7910e7db-260e-44a7-9d76-b5777f2925c9.mp4

**Comment by testforstephen** [comment] 2021-09-06 01:34
Your video is broken, i just saw a blank screen there.

**Comment by zhouxinghong** [comment] 2021-09-06 03:54
Please download and watch again. . .

**Comment by zhouxinghong** [comment] 2021-09-10 00:09
https://user-images.githubusercontent.com/54253524/132778284-ad5f5738-931d-49d8-93bc-f09ed5362c34.mp4

**Comment by testforstephen** [comment] 2021-09-10 01:31
i couldn't open this video in macOS, but i finally saw your video on a Windows machine.

Your issue is about signatureHelp feature. I reproduced it using [eclipse.jdt.ls source code](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java#L50) itself.

Move the cursor over the sendStatus method and then trigger the parameter hint (aka. signature help), and it will show some other unrelated method parameters like `equals`.
![image](https://user-images.githubusercontent.com/14052197/132783685-3ad90827-ddf3-4868-960d-d70a78f06031.png)

**Comment by zhouxinghong** [comment] 2021-09-11 06:04
https://user-images.githubusercontent.com/54253524/132938043-a211f3c4-2455-444e-aad3-0e044390b634.mp4
Thank you!

**Comment by zhouxinghong** [comment] 2021-09-11 06:09
After triggering the method parameter prompt shortcut key on some methods, the method has no response. . .

**Comment by zhouxinghong** [comment] 2021-10-02 03:58
> i couldn't open this video in macOS, but i finally saw your video on a Windows machine.
> 
> Your issue is about signatureHelp feature. I reproduced it using [eclipse.jdt.ls source code](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java#L50) itself.
> 
> Move the cursor over the sendStatus method and then trigger the parameter hint (aka. signature help), and it will show some other unrelated method parameters like `equals`. ![image](https://user-images.githubusercontent.com/14052197/132783685-3ad90827-ddf3-4868-960d-d70a78f06031.png)

Hello! In which version will this problem be fixed?

**Comment by zhouxinghong** [comment] 2021-11-15 15:09
> Your video is broken, i just saw a blank screen there.

Hello, teacher! 
      excuse me! Could this problem be fixed by the next milestone? Looking forward to your fix in the next milestone, thank you very much!

**Comment by zhouxinghong** [comment] 2021-11-15 15:10
Hello, teacher! 
      excuse me! Could this problem be fixed by the next milestone? Looking forward to your fix in the next milestone, thank you very much!

**Comment by snjeza** [comment] 2022-02-21 04:14
Related issue - https://github.com/eclipse/eclipse.jdt.ls/issues/1980
@zhouxinghong Could you reproduce the issue in VS Code 1.3.0?

**Comment by zhouxinghong** [comment] 2022-02-22 10:11
> 

@snjeza When using the shortcut key to trigger the view method parameter overload in 1.30, nothing happens in the vscode editor. But the method itself has multiple overloaded parameters. See example:

https://user-images.githubusercontent.com/54253524/155110090-ac1826f4-315a-4515-acbd-56e57d302ed7.mp4

![2022-02-22_175738_无法显示方法参数重载](https://user-images.githubusercontent.com/54253524/155110205-369ba23c-86a8-498c-83cd-fb46c2f0a617.png)

**Comment by zhouxinghong** [comment] 2022-02-23 03:55
> @zhouxinghong Could you, please, attach a sample project?

very sorry! This is a commercial item inconvenient to offer. . .

**Comment by zhouxinghong** [comment] 2022-02-23 04:02
This issue has been confirmed by the testers above. . . You can consult them for specific reasons. . .

**Comment by snjeza** [comment] 2022-02-23 19:39
> This issue has been confirmed by the testers above. . . You can consult them for specific reasons. . . @testforstephen

> i couldn't open this video in macOS, but i finally saw your video on a Windows machine.

> Your issue is about signatureHelp feature. I reproduced it using [eclipse.jdt.ls source code](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java#L50) itself.

> Move the cursor over the sendStatus method and then trigger the parameter hint (aka. signature help), and it will show some other unrelated method parameters like equals.

@zhouxinghong I can't reproduce this issue in VS Code 1.30. It has been fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/1981

> Unable to view method/parameters overloads

Does CA (Ctrl-Space) work properly?

**Comment by zhouxinghong** [comment] 2022-02-24 06:59
> 
Now the parameter prompt is triggered by the shortcut key as shown in the above video and screenshot annotations I uploaded

**Comment by nimatrueway** [comment] 2022-02-24 07:27
Not an irrelevant parameter hint case; but I have a very sample project with 2 classes that if you try to invoke parameter hint on `new AuthenticationService(...)` nothing shows up.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/2261274/155477634-28c70f7f-4959-441a-b2fd-f5e186e8a27b.png">

[sample.zip](https://github.com/redhat-developer/vscode-java/files/8130446/sample.zip)

**Comment by snjeza** [comment] 2022-02-24 22:46
> The following is the performance of 1.3.0. . .
> Unable to view method/parameters overloads

@zhouxinghong Does CA (Ctrl-Space) work properly here?

> Not an irrelevant parameter hint case; but I have a very sample project with 2 classes that if you try to invoke parameter hint on new AuthenticationService(...) nothing shows up.

@nimatrueway I can reproduce the issue. I will try to fix it.

**Comment by zhouxinghong** [comment] 2022-02-25 13:50
@nimatrueway Very true, I agree with him!

**Comment by zhouxinghong** [comment] 2022-02-25 13:51
> @nimatrueway Very true, I agree with him!



> > The following is the performance of 1.3.0. . .
> > Unable to view method/parameters overloads
> 
> @zhouxinghong Does CA (Ctrl-Space) work properly here?
> 
> > Not an irrelevant parameter hint case; but I have a very sample project with 2 classes that if you try to invoke parameter hint on new AuthenticationService(...) nothing shows up.
> 
> @nimatrueway I can reproduce the issue. I will try to fix it.

@nimatrueway Very true, I agree with him!

**Comment by snjeza** [comment] 2022-02-28 17:09
@zhouxinghong @nimatrueway Could you, please, check https://github.com/snjeza/vscode-test/raw/master/java-1.4.0.vsix ?

**Closed** 2022-03-02 17:54 UTC
Labels: bug, content-assist
