### ISSUE TITLE
Cannot find JDK

### ISSUE THREAD

**Issue by TTanner21** [redhat-developer/vscode-java#63] opened 2016-10-13 17:35 UTC
ok so I have my JAVA_HOME set to the home path for the redhat jdk-8 but still get the error that its not installed and cannot be started.

what else do I have to do to get this to work?
I have looked through the other posts but have yet to find a solution. 
this is on windows 10 btw.

**Comment by fbricon** [comment] 2016-10-14 03:00
Can you paste the path you used here? 
Also can you check if you still have the issue with the new release (0.0.5)?
BTW, you can now set up the java.home variable in VS Code preferences, starting in 0.0.5.

**Comment by navneetkarnani** [comment] 2016-10-14 11:21
Can you add support for variable JDK_HOME and JAVA_HOME instead of having to compulsorily use java.home ? 

In the 20 years I have been programming with Java, my understanding is that the way the environment variables being used is to have the JRE be pointed by the JAVA_HOME and the JDK be pointed by JDK_HOME. In case developers want, they can point both to the JDK.

Look at documentation here for some reference:
https://docs.oracle.com/cd/E35865_01/doc.1120/e29687/preinstall.htm#CIHCIHDE
https://docs.oracle.com/cd/E13222_01/wls/docs/techstart/environment.html

**Comment by gorkem** [comment] 2016-10-14 13:42
@navneetkarnani _java.home_ configuration is NOT mandatory. We have added it as a way to override the _JAVA_HOME_ for situations such as developer needs JAVA_HOME to point to JDK which is not sufficient for running our tools. See #28 for full discussion. 

In @TTanner21's case we are still trying to determine why _JAVA_HOME_ is not automatically discovered, using _java.home_ with the same value as _JAVA_HOME_ would hint us that the path is actually good.

**Comment by TTanner21** [comment] 2016-10-17 17:57
> Can you paste the path you used here? 
Also can you check if you still have the issue with the new release (0.0.5)?
BTW, you can now set up the java.home variable in VS Code preferences, starting in 0.0.5.

the path is C:\java-1.8.0-openjdk-1.8.0.102-1
I don't know why its not working, but using the java.home variable does work with the same path.

**Comment by schmic** [comment] 2016-10-18 08:32
@TTanner21 You need to escape the backslashes in the configuration.

From my user settings:
`"java.home": "D:\\Dev\\jdk\\jdk1.8.0_25_x86"`

**Comment by gorkem** [comment] 2016-10-28 21:32
fixed with https://github.com/redhat-developer/vscode-java/commit/9de94901e7cb2f829e74f748ae96a6c211e219da

**Closed by gorkem** 2016-10-28 21:32 UTC
Labels: bug, need info

**Comment by carlin-q-scott** [comment] 2016-12-17 03:21
I have this same issue and had to paste my JDK_Home environment variable value into the VSC java.home setting, escaping the backslashes. Is it possible that you guys need to escape the backslashes when using JDK_Home for some reason?

**Comment by gorkem** [comment] 2016-12-17 04:19
@carlin-q-scott What is your OS?

**Comment by carlin-q-scott** [comment] 2017-01-09 18:32
@gorkem Windows 10 Home.

**Comment by kmccmk9** [comment] 2018-02-09 03:19
I also seem to be having issues with this. I have correctly set my java.home workspace setting to:

`"java.home": "C:\\Program Files\\Java\\jdk1.8.0_162"`

When running a maven build task I get the error in console: 

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.068 s
[INFO] Finished at: 2018-02-08T22:18:53-05:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project HelpMeAdvanced-Sponge: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
```

**Comment by fbricon** [comment] 2018-02-09 14:13
@kmccmk9 Running the Java editor is one thing, running Maven from CLI is another. Those are 2 pieces of software each requiring their settings. 
The `java.home` preference is only used by vscode-java (actually the underlying jdt.ls backend). Maven is not aware of vscode preferences.
If you set JAVA_HOME globally on your system, then vscode-java should be able to pick it up, Maven too.

**Comment by jgabrielgv** [comment] 2018-10-15 02:47
It was happening the same to me in Ubuntu 18.04, where the $JAVA_HOME variable was pointing to:
`"/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`
So I just changed the User Settings to the following value and it worked:
`"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"`

**Comment by pskrunner14** [comment] 2018-11-23 21:55
> It was happening the same to me in Ubuntu 18.04, where the $JAVA_HOME variable was pointing to:
> `"/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`
> So I just changed the User Settings to the following value and it worked (removed the /bin/java):
> `"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"`

Fixed it for me.

**Comment by PhazonicRidley** [comment] 2019-11-09 20:06
I am on fedora, and I have it set to
`"java.home": "/usr/lib/jvm/java-11-openjdk-11.0.5.10-0.fc30.x86_64",` and it doesnt want to work for me. Any thoughts?

**Comment by snjeza** [comment] 2019-11-09 20:49
@PhazonicRidley you can try the following:

```
sudo dnf install java-11-openjdk java-11-openjdk-devel
code ...
```

**Comment by meSajied** [comment] 2019-11-22 19:37
> It was happening the same to me in Ubuntu 18.04, where the $JAVA_HOME variable was pointing to:
> `"/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`
> So I just changed the User Settings to the following value and it worked (removed the /bin/java):
> `"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"`

This is not working for me... What can I do..
![aaaaa](https://user-images.githubusercontent.com/40203390/69455080-c719d780-0d91-11ea-9dad-d0c462de57dd.png)

**Comment by jdneo** [comment] 2019-11-23 08:42
@meSajied if the path is correct. I think what you need to do is adding `,` after the `}` at line 15

**Comment by miteshgoplani** [comment] 2020-05-12 15:38
Duplicate of #

**Comment by miteshgoplani** [comment] 2020-05-12 15:45
> It was happening the same to me in Ubuntu 18.04, where the $JAVA_HOME variable was pointing to:
> `"/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`
> So I just changed the User Settings to the following value and it worked (removed the /bin/java):
> `"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"`

Doesn't work for Kali Linux v2019.4
Any Suggestions?

```
{
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
    "editor.suggestSelection": "first",
}
```

![image](https://user-images.githubusercontent.com/29533998/81715240-fc040e80-9445-11ea-8720-2bff0c7b286e.png)

**Comment by mgautam98** [comment] 2020-05-14 10:49
> It was happening the same to me in Ubuntu 18.04, where the $JAVA_HOME variable was pointing to:
> `"/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`
> So I just changed the User Settings to the following value and it worked (removed the /bin/java):
> `"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"`

I have tried all sorts of combination and I am still getting thins error 
- /usr/lib/jvm/java-11-openjdk-amd64/bin/java
- /usr/lib/jvm/java-11-openjdk-amd64/bin
- /usr/lib/jvm/java-11-openjdk-amd64

![image](https://user-images.githubusercontent.com/29784549/81925643-68c20900-95fe-11ea-9e9a-8bd484e6dab9.png)

**Comment by mgautam98** [comment] 2020-05-14 11:29
> > It was happening the same to me in Ubuntu 18.04, where the $JAVA_HOME variable was pointing to:
> > `"/usr/lib/jvm/java-11-openjdk-amd64/bin/java"`
> > So I just changed the User Settings to the following value and it worked (removed the /bin/java):
> > `"java.home": "/usr/lib/jvm/java-11-openjdk-amd64"`
> 
> Doesn't work for Kali Linux v2019.4
> Any Suggestions?
> 
> ```
> {
>     "workbench.editor.enablePreview": false,
>     "workbench.editor.enablePreviewFromQuickOpen": false,
>     "java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
>     "editor.suggestSelection": "first",
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/29533998/81715240-fc040e80-9445-11ea-8720-2bff0c7b286e.png)

@miteshgoplani See if you installed both jdk and jre I had the same problem I only installed jre. After installing jdk add this to settings.json
```
"java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
```

**Comment by fbricon** [comment] 2020-05-14 12:02
Yes make sure you use a JDK, not a JRE, and don't set the path to bin/ or bin/java.

**Comment by victormaricato** [comment] 2021-08-01 14:58
About @fbricon and @mgautam98, I had only jre in `/usr/lib/jvm/java-11-openjdk-amd64`. Installing JDK worked.

To verify if this is your case, you can check that `javac --version` will return an error.

To install JDK on top of what I had, I just did:

`sudo apt install default-jdk`
