### ISSUE TITLE
org.eclipse.core.runtime.CoreException: No file system is defined for scheme: inmemory

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/vscode-java#116] opened 2016-12-08 21:48 UTC
I see a lot of the following stacktrace in the Output console:
````
[Error - 7:39:40 PM] Dec 8, 2016 7:37:36 PM Internal Error
No file system is defined for scheme: inmemory
org.eclipse.core.runtime.CoreException: No file system is defined for scheme: inmemory
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:49)
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:44)
	at org.eclipse.core.internal.filesystem.InternalFileSystemCore.getFileSystem(InternalFileSystemCore.java:65)
	at org.eclipse.core.internal.filesystem.InternalFileSystemCore.getStore(InternalFileSystemCore.java:107)
	at org.eclipse.core.filesystem.EFS.getStore(EFS.java:478)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.findLinkedResourcesPaths(FileSystemResourceManager.java:147)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allPathsForLocationNonCanonical(FileSystemResourceManager.java:129)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allPathsForLocation(FileSystemResourceManager.java:65)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.allResourcesFor(FileSystemResourceManager.java:221)
	at org.eclipse.core.internal.resources.WorkspaceRoot.findFilesForLocationURI(WorkspaceRoot.java:94)
	at org.eclipse.core.internal.resources.WorkspaceRoot.findFilesForLocationURI(WorkspaceRoot.java:87)
	at org.jboss.tools.vscode.java.internal.JDTUtils.findFile(JDTUtils.java:410)
	at org.jboss.tools.vscode.java.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:85)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler.handleOpen(DocumentLifeCycleHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler.access$1(DocumentLifeCycleHandler.java:135)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler$OpenHandler$1.run(DocumentLifeCycleHandler.java:84)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:81)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:205)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

##### Environment
- Operating System: Fedora 25
- JDK version: JDK 1.8.0_122
- Visual Studio Code version: 
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
- Java extension version:

##### Steps To Reproduce
1. git clone https://github.com/obsidian-toaster/generator-backend
2. Open ForgeInitializer.java and type `Project` then press Ctrl+ Space

##### Current Result
The org.eclipse.core.runtime.CoreException: No file system is defined for scheme: inmemory error message is displayed in the output. Autocompletion works fine though

##### Expected Result
No errors in the output window

**Comment by fbricon** [comment] 2016-12-08 21:50
Duplicate of #109

**Closed by fbricon** 2016-12-08 21:50 UTC
