### ISSUE TITLE
Variable arguments in record constructor not working

### ISSUE THREAD

**Issue by sjaaksm** [redhat-developer/vscode-java#2844] opened 2022-12-25 15:47 UTC
Records constructors with variable arguments do not work.

public record Bla(int ... foo) {
}

The following declaration will not be accepted. 
Bla bl = new Bla(1,2);
I get the error: The constructor Bla(int, int) is undefinedJava(134217858)

##### Environment
- Operating System:Windows 10
- JDK version:jdk-17.0.2
- Visual Studio Code version:1.74.2
- Java extension version:v1.13.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by snjeza** [comment] 2022-12-25 18:18
A duplicate of #2640

**Closed by snjeza** 2022-12-25 18:18 UTC
