### ISSUE TITLE
Rename class won't save the file

### ISSUE THREAD

**Issue by samba2** [redhat-developer/vscode-java#871] opened 2019-04-09 07:46 UTC
When renaming a class (F2) the class symbol and the file itself are renamed properly. However, when I try to save the file the following error is displayed:

_Failed to save 'NewName.java': The content on disk is newer. Please compare your version with the one on disk._

When I now click on the compare button (part of the error popup) and accept the change then the renamed class is eventually saved.

##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_181
- Visual Studio Code version: 1.33
- Java extension version: 0.42.1

##### Steps To Reproduce
1. create new file _MyClass.java_
2. inside _MyClass.java_ expand the template"class" which gives you a skeleton for _MyClass_
3. position the cursor inside the symbol _MyClass_
4. press F2 (rename)
5. enter _NewName_
6. the mentioned error popup is displayed
7. press _Compare_
8. accept new version
9. _NewName.java_ is saved

##### Current Result
Extra step to save/ accept the renamed class.

##### Expected Result
After changing the name of the class via F2, the class symbol as well as the file name are changed and saved.

##### Additional Informations
When autosave is turned on the error occurs instantly, with autosave turned off the error popup is displayed when saving manually.

![vs-code-rename-error](https://user-images.githubusercontent.com/1508184/55782290-3addcd00-5aac-11e9-8b11-1fa9d185917b.png)

**Comment by yaohaizh** [comment] 2019-04-09 08:19
Reproed this issue on the latest version.

**Comment by VanessaLange** [comment] 2019-04-15 12:31
I can reproduce this issue.
Operating System: Windows_NT x64 10.0.17134
JDK version: openjdk version "11.0.2" 2019-01-15
Visual Studio Code version: 1.33.1
Java extension version: 0.42.1

**Comment by fbricon** [comment] 2019-04-15 13:15
Indeed, this is new. Looks like a bug in vscode, since jdt.ls hasn't changed anything in that area in a long time.

**Comment by fbricon** [comment] 2019-04-15 14:00
I've opened https://github.com/Microsoft/vscode/issues/72343 upstream

**Comment by fbricon** [comment] 2019-04-25 18:59
The problem is fixed in VSCode. You can use the [Insiders]( https://code.visualstudio.com/insiders/) build until the next official release (1st week of May, probably)

**Closed by fbricon** 2019-04-25 18:59 UTC
Labels: bug, regression, upstream

**Comment by GabrielBB** [comment] 2019-04-26 20:14
Great. I'll wait for the next official release then
