### ISSUE TITLE
Add a flat packages view

### ISSUE THREAD

**Issue by dschaefer** [redhat-developer/vscode-java#411] opened 2018-01-12 18:47 UTC
Us old timers in Eclipse have gotten used to seeing the packages presented in a flat list. I'm not sure whether that's a good thing or bad thing, but it would help with the transition. And it is good for users looking at a project for the first time and doesn't know what the class names are.

**Comment by rgcv** [comment] 2018-04-06 22:57
This is a duplicate of #315, could be closed.

**Closed** 2018-04-06 23:29 UTC
Labels: duplicate, enhancement
