### ISSUE TITLE
Some error for foldingrange

### ISSUE THREAD

**Issue by bsaby** [redhat-developer/vscode-java#969] opened 2019-07-01 10:57 UTC
##### Environment
- Operating System: Windows
- JDK version: 12.0.1
- Visual Studio Code version: 1.35.1
- Java extension version: 0.46.0

##### Steps To Reproduce
1.  Open project 21.single-file.
2. Change String s = "1"; to String s = 1;

[attach a sample project reproducing the error]
https://github.com/microsoft/vscode-java-debug/tree/master/testprojects/21.single-file

##### Current Result
Error about foldingrange in output
```
[Error - 6:18:18 AM] Jul 1, 2019, 6:18:18 AM Problem with folding range for /21.single-file_ef5e71/_/Main.java
Invalid_Character_Constant
org.eclipse.jdt.core.compiler.InvalidInputException: Invalid_Character_Constant
    at org.eclipse.jdt.internal.core.util.PublicScanner.getNextToken(PublicScanner.java:1442)
    at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.computeFoldingRanges(FoldingRangeHandler.java:110)
    at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.foldingRange(FoldingRangeHandler.java:61)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$25(JDTLanguageServer.java:762)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$40(JDTLanguageServer.java:881)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by rgrunber** [comment] 2023-08-15 15:15
I'm no longer able to reproduce this with https://github.com/microsoft/vscode-java-debug/tree/0.35.0/testprojects/21.single-file . @hopehadfield , can you ?

**Comment by hopehadfield** [comment] 2023-08-15 17:42
@rgrunber Nope, I can't reproduce this either.

**Comment by rgrunber** [comment] 2023-08-15 17:50
Closing for now as given the date of reporting, I suspect it has been fixed. If anyone can still reproduce with the code snippet (or another), feel free to re-open.

**Closed by rgrunber** 2023-08-15 17:50 UTC
Labels: need info, editor-folding
