### ISSUE TITLE
Limit Extension storage usage

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/vscode-java#185] opened 2017-04-13 10:15 UTC
_From @Geeprox on April 13, 2017 9:39_

- VSCode Version: 1.11.1
- OS Version: Windows 7

There are so many index.db files that takes a lot of storage space
(for example: \AppData\Roaming\Code\User\workspaceStorage\13d502476c69532f0fce4f9ab9ea9f18\redhat.java\jdt_ws\.metadata\.plugins\org.eclipse.jdt.core\index.db)

I know they are useful caches, but can we give it a limit space or give it a survival time or something else?

_Copied from original issue: Microsoft/vscode#24666_

**Comment by fbricon** [comment] 2017-04-13 14:27
Wow, indeed, the workspaceStorage grows freakingly fast. My 13 workspaces eat up to 3.5GB :-/

This is caused by Eclipse JDT [new Java index ](https://www.eclipse.org/eclipse/news/4.7/M3/#new-java-index). There's nothing much we can do at that point about limiting its size, other than disabling it completely, which is not something I'm too keen on doing (i.e. exposing another eclipse internal). I'll ask the JDT team about it

**Comment by gorkem** [comment] 2017-04-13 14:46
Larger index files vs speedier searches was a design decision. I do not think this is a performance problem though.

**Comment by fbricon** [comment] 2017-04-13 14:51
So I commented on [Eclipse Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481796#c179).

Turns out even disabling the index [will not prevent the index.db creation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481796#c177).

**Comment by fbricon** [comment] 2019-11-14 09:30
@rgrunber brings us hope with his work on JDT shared indexes:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=515268
- https://rgrunber.fedorapeople.org/jdt-shared-index.mp4

**Comment by fbricon** [comment] 2021-09-14 17:11
@rgrunber https://twitter.com/artursignell/status/1437817323574943748 reminded me of this issue. We should prioritize this work in the coming sprints

**Comment by rgrunber** [comment] 2021-09-17 17:05
I'm going to close this issue as it was originally filed against the `index.db` files generated by the new index. Lately they should not be generated as the new index was disabled (for not providing the kind of performance boost that was expected), so we're back to the old ${checksum}.index files, which we can address in the recently filed #210.

**Closed by rgrunber** 2021-09-17 17:05 UTC
Labels: enhancement, upstream
