### ISSUE TITLE
Signature help doesn't work properly during code completion in some cases

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2441] opened 2022-05-05 09:15 UTC
##### Environment
- Operating System: Win
- JDK version: 11
- Visual Studio Code version: 1.66.2
- Java extension version: 1.6.0

##### Steps To Reproduce and Current Result
Enable "java.signatureHelp.enabled" > Type `System.out.print` > Select `print(Object obj)`  and press Enter > Show help info of `print(char[] s)`
![image](https://user-images.githubusercontent.com/31497677/166893688-8d9e287d-23f4-44f7-889c-d20f76072e92.png)

##### Expected Result
 If select `print(Object obj)` , it should show help info of `print(Object obj)`

**Comment by testforstephen** [comment] 2022-05-05 09:19
@jdneo for a look.

**Comment by jdneo** [comment] 2022-05-05 09:31
This was discussed in https://github.com/redhat-developer/vscode-java/pull/2426

Currently since we do not record the selected completion item, so the server side is lack of the information to provide a correct signature help when it comes to overload methods.

BTW, this problem can also be observed in 1.5.0, it's not a regression

**Comment by rgrunber** [comment] 2022-05-05 15:15
Noticed this as well when reviewing the above issue. At least we now have this issue to track progress.

**Comment by rgrunber** [comment] 2023-11-08 19:19
![signature-help-respects-completion-item](https://github.com/redhat-developer/vscode-java/assets/1417342/bdf232af-25bd-44b0-a89c-10463958db3c)

I think this was addressed in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2686 . @jdneo , is this still an issue or can it be closed ?

**Comment by jdneo** [comment] 2023-11-09 01:48
@rgrunber Thank you for reminding, it can be closed.

**Closed by jdneo** 2023-11-09 01:48 UTC
Labels: bug, content-assist, signature help
