### ISSUE TITLE
Consumes 744MB on Ubuntu 18.04

### ISSUE THREAD

**Issue by tivrfoa** [redhat-developer/vscode-java#1090] opened 2019-10-08 23:04 UTC
[provide a description of the issue]
It consumes a lot of memory

##### Environment
- Operating System: Ubuntu 18.04.3
- JDK version: 11.0.4
- Visual Studio Code version: 1.38.1
- Java extension version: 0.50.0 (October 1st, 2019)

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by rgrunber** [comment] 2021-07-07 15:00
Looks like this was more of a question/call for performance improvement that had an acceptable workaround for then.

In https://github.com/redhat-developer/vscode-java/pull/1262 we did improve performance by encouraging the language server to perform garbage collection more frequently. This would have especially improved cases where initial project import consumed a lot of memory, and freed it very relucantly, leading to the OOM issues.

Also, we're looking at catching, reporting, and handling OOM issues more gracefully on #1959 .

Marking this as a duplicate of that for now.

**Closed by rgrunber** 2021-07-07 15:00 UTC
Labels: duplicate, performance
