### ISSUE TITLE
when can support jdk 11 lts?

### ISSUE THREAD

**Issue by IMJacky** [redhat-developer/vscode-java#651] opened 2018-09-27 03:58 UTC
##### Environment
- Operating System:windows 7
- JDK version:jdk 11 lts
- Visual Studio Code version:1.27.2

##### Exception
java.lang.NoClassDefFoundError: ApplicationContext

when i only install jdk 11 lts，the gs-spring-boot project can't run?

**Comment by IMJacky** [comment] 2018-09-27 07:13
this is the spring-guide project : [https://github.com/spring-guides/gs-spring-boot](https://github.com/spring-guides/gs-spring-boot)

you can only install jdk11(uninstall jdk 10 or other) and run this project in vs code,
the exception just java.lang.NoClassDefFoundError: ApplicationContext

**Comment by fbricon** [comment] 2018-09-27 21:34
Ok so I can reproduce the issue with a gradle project without the gradle wrapper. 

It works when the project is imported as a Maven project. You need to:

1- Disable gradle import in your settings.json
 >   "java.import.gradle.enabled": false
2 - Close vscode
3 - Clean the [vscode workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)
4 - Reopen vscode

**Comment by fbricon** [comment] 2018-09-27 21:35
Closing as duplicate of #653

**Closed by fbricon** 2018-09-27 21:36 UTC
Labels: Java 11, duplicate, need info

**Comment by IMJacky** [comment] 2018-09-28 02:01
ths @fbricon ,that work wo me!!!
