### ISSUE TITLE
Project keeps building (loop) when groupId is dynamic in pom.xml

### ISSUE THREAD

**Issue by gian1200** [redhat-developer/vscode-java#2360] opened 2022-03-15 06:21 UTC
The plugin keeps building the project (looping).

I have a project built with Quarkus 1.13.7. When updating it to version 2 (2.0.3), the plugin started looping the build process.

I think I've pinpoint the issue to the groupId of the plugin. Due to the update, it changed from static to dynamic value. When I rollback this line, the loop stops (sometimes it needs a VSCode restart).

Before (no loop):
```xml
<build>
    <plugins>
        <plugin>
	    <groupId>io.quarkus</groupId>
	    <artifactId>quarkus-maven-plugin</artifactId>
	    <version>${quarkus.platform.version}</version>
...
```
After (loop):
```xml
<build>
    <plugins>
        <plugin>
	    <groupId>${quarkus.platform.group-id}</groupId>
	     <artifactId>quarkus-maven-plugin</artifactId>
	    <version>${quarkus.platform.version}</version>
...
```

##### Environment
- Operating System: Win10
- JDK version: 11.0.11, AdoptOpenJDK
- Visual Studio Code version: 1.65.2 (user setup)
- Java extension version: v1.4.0

##### Steps To Reproduce
1. Have a pom.xml with a plugin with a dynamic groupId

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/405347/158317018-8ae1287b-84c8-45c4-9368-ea5ca8ce90ff.png)

##### Expected Result
Project builds once

**Comment by fbricon** [comment] 2022-03-15 09:17
please attach a sample project reproducing this issue

**Comment by snjeza** [comment] 2022-03-17 16:55
@gian1200 Could you try https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.5.0-559/java-1.5.0-559.vsix

**Comment by rgrunber** [comment] 2022-03-21 14:06
Could this be related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=579153 ? A change as introduced in https://bugs.eclipse.org/bugs/show_bug.cgi?id=578640 that would have made it into our 1.4.0 release (since we used a TP from `I20220216-0600`) .

Easy way to test is to try a recent build, which is what I think @snjeza is implying here.

**Comment by gian1200** [comment] 2022-03-21 21:46
Sorry for the delay.  Yes, the vsix you provided with 1.5.0 version fixes (so far) the infinite loop.

Note: Since it's an internal project I was unable to provide it, but I was also not able to reproduce the issue in a small project.

![image](https://user-images.githubusercontent.com/405347/159368552-3e6532cd-799c-4315-b238-76feb63340fa.png)

**Comment by rgrunber** [comment] 2022-03-21 23:26
Closing issue, as the fix will be included in the next release. If the issue does come up, feel free to re-open.

**Closed by rgrunber** 2022-03-21 23:26 UTC
Labels: bug
