### ISSUE TITLE
Continuously asks to install dependency analzyer plugin even after hitting "never"

### ISSUE THREAD

**Issue by hayden-mumm** [redhat-developer/vscode-java#2948] opened 2023-02-16 16:48 UTC
Every time a pom.xml file is opened it asks to install a dependency analyzer

##### Environment
- Operating System: Windows 10
- JDK version: 8
- Visual Studio Code version: 1.75.1
- Java extension version: 1.14.0

##### Steps To Reproduce
1. open a pom.xml file
2. It will ask if you want to use a dependency analyzer. Click Never.
3. Close pom and reopen it
4. It will ask again anyway.

[my-app.zip](https://github.com/redhat-developer/vscode-java/files/10758332/my-app.zip)
[server.log](https://github.com/redhat-developer/vscode-java/files/10758367/server.log)

Didn't see anything in the console output

##### Current Result

Keeps asking me

##### Expected Result

Don't ask me ever again if I hit never.

**Comment by fbricon** [comment] 2023-02-16 17:05
Closing as duplicate of https://github.com/redhat-developer/vscode-java/issues/2892

**Closed by fbricon** 2023-02-16 17:05 UTC
Labels: duplicate
