### ISSUE TITLE
JavaFX application produce warning

### ISSUE THREAD

**Issue by kant2002** [redhat-developer/vscode-java#120] opened 2016-12-17 20:31 UTC
A lot of warnings about restricted API

##### Environment
- Operating System: Windows 10 64-bit
- JDK version: jdk1.8.0_111
- Visual Studio Code version: 1.8
- Java extension version: 0.0.7

##### Steps To Reproduce
1. Create JavaFX hello world
2. Open project in VS Code
3. Open HelloWorld.java

##### Current Result
All code has following hints:
```
[Java] Access restriction: The type 'Application' is not API (restriction on required library 'C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jfxrt.jar')
```

##### Expected Result
No hints provided, or some configuration option needed to override restricted libraries.

**Comment by alexandrio** [comment] 2017-01-09 20:03
same here add an image of warning.
![virtualbox_xubu_09_01_2017_14_02_12](https://cloud.githubusercontent.com/assets/547785/21781286/66c6c1ce-d674-11e6-9452-cb9363d8f68a.png)

**Comment by gorkem** [comment] 2017-01-09 20:15
Technically the libraries from extension classpath are not guaranteed to exist on JVMs so they are restricted. I think we need to introduce a setting to suppress these warnings.

**Comment by kant2002** [comment] 2017-02-03 06:05
@gorkem is there any specific location in code where I could look to implement this ? I treat any warning as errors and having that warnings don't allow me keep track of other warnings

**Comment by gorkem** [comment] 2017-02-07 06:59
You can have a workaround by adding access rules to the .classpath files. [This](http://stackoverflow.com/questions/31817620/how-to-disable-css-warning-unknown-property-in-eclipse-mars) has an example of how to add JavaFX entries and maintaining them.

**Comment by fbricon** [comment] 2017-02-07 16:30
@gorkem we should probably provide a quick fix that performs that change in the access rules automagically

**Comment by Taximan** [comment] 2017-03-04 09:26
any update on this ?

`javafx.scene.layout.VBox vb = new javafx.scene.layout.VBox();`
produces a red underline with the following error message

> [Java] Access restriction: The type 'VBox' is not API (restriction on required library 'C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar')

autocomplete does seem to still work tho. i just would really need to simply ignore this error.

**Comment by tomsontom** [comment] 2017-03-06 09:46
As the author of e(fx)clipse I had to fix the same problems you see for the Eclipse IDE. There are in fact 2 things to consider for JavaFX
* it's a library from the ext-folder
* it's source is not part of rt-src.zip

What we do in e(fx)clipse is that we use a JDT-Extension-Point to configure the VMInstall to:
* contain the correct accessibility rules
* add the source-path for javafx-rt.zip

You can see our code at 
* AccessRule
  * https://github.com/eclipse/efxclipse-eclipse/blob/master/bundles/tooling/org.eclipse.fx.ide.jdt.core/plugin.xml#L15
  * https://github.com/eclipse/efxclipse-eclipse/blob/master/bundles/tooling/org.eclipse.fx.ide.jdt.core/src/org/eclipse/fx/ide/jdt/core/internal/FXAccessRuleParticipant.java

* Source-Resolver
  * https://github.com/eclipse/efxclipse-eclipse/blob/master/bundles/tooling/org.eclipse.fx.ide.jdt.core/plugin.xml#L22
  * https://github.com/eclipse/efxclipse-eclipse/blob/master/bundles/tooling/org.eclipse.fx.ide.jdt.core/src/org/eclipse/fx/ide/jdt/core/internal/FXLibraryLocationResolver.java

**Comment by rogeriomq** [comment] 2017-03-24 00:36
**# Access restriction: The type 'Platform' is not API (restriction on required library '/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar')**
...
_Solution?_

**Comment by FutureProg** [comment] 2017-05-06 14:51
Bumping this again to see if a solution has been found. Sure it compiles fine but the errors in the IDE are a little annoying.

**Comment by joewood** [comment] 2017-06-13 15:08
Seeing this too for jdk.nashorn. No idea why it's restricted. Really need a setting on the plugin to suppress these errors.

**Comment by fbricon** [comment] 2017-06-13 16:19
As a workaround, to get rid of theses warnings, you can add `org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore` to your `<project>/.settings/org.eclipse.jdt.core.prefs`. You'll need to install the [latest CI build](http://download.jboss.org/jbosstools/jdt.ls/staging/) for this modification to reach the java language server (#239).

@joewood see @gorkem's [explanation](https://github.com/redhat-developer/vscode-java/issues/120#issuecomment-271395007) about the restriction.

**Comment by pichardoJ** [comment] 2018-03-21 23:16
Any updates on this thread?

**Comment by StephenOTT** [comment] 2018-03-21 23:45
+1

**Comment by markoczy** [comment] 2018-08-19 13:39
#276 gets closed because of this, this gets closed because of #276.. doesn't seem like a solution will come up.. +1

**Comment by primesoftware** [comment] 2018-09-02 22:32
Any updates the status of this? I am running the latest Oracle Java 8, latest VS Code, and downloaded the CI build of the plugin yet still have this problem. I tried the 'workaround' (org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore) but that didn't work for me either. Here is what I have as far as build is concerned.

<project>/.settings/org.eclipse.buildship.core.prefs
```
auto.sync=false
build.scans.enabled=false
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=
eclipse.preferences.version=1
gradle.user.home=
offline.mode=false
override.workspace.settings=true
org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore
```

<project>/.classpath
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```
<project>/.project
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>ChemCreator</name>
	<comment>Project ChemCreator created by Buildship.</comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.buildship.core.gradleprojectbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.buildship.core.gradleprojectnature</nature>
	</natures>
</projectDescription>
```

<project>/build.gradle
```
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.10/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    id 'java'

    // Apply the application plugin to add support for building an application
    id 'application'
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

// Define the main class for the application
mainClassName = 'MyClass'

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    compile 'com.google.guava:guava:23.0'

    // Use JUnit test framework
    testCompile 'junit:junit:4.12'
}

// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

sourceSets {
    main {
        java {
            srcDir 'src'
        }
        resources {
            srcDir 'resources'
        }
    }
}
```

<project>/.vscode/settings.json
```
{
    "java.configuration.updateBuildConfiguration": "automatic"
}
```

I'm building a basic JavaFX example from Oracle's samples.

**Comment by snjeza** [comment] 2018-09-02 23:49
>  I tried the 'workaround' (org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore) but that didn't work for me either. Here is what I have as far as build is concerned.

> /.settings/org.eclipse.buildship.core.prefs

.settings/org.eclipse.jdt.core.prefs

**Comment by primesoftware** [comment] 2018-09-03 00:14
@snjeza Oh wow, I totally missed the paths in between. I didn't see that file in .settings, so I created it but I am still seeing the error. Is that file automatically read or do I have to point a var to it?

**Comment by primesoftware** [comment] 2018-09-03 01:39
@snjeza Still doing the same thing after restart. This is really puzzling. Are there any cache files that may be prioritized over the files in .settings?

**Comment by snjeza** [comment] 2018-09-03 02:04
> Are there any cache files that may be prioritized over the files in .settings?

@primesoftware No, there aren't any files. you can try to clean your workspace - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory

**Comment by primesoftware** [comment] 2018-09-03 02:32
@snjeza That did it!!! No more nasty red underlines! Any thoughts as to why the workspace needed to be cleared?

**Comment by primesoftware** [comment] 2018-09-08 04:37
@ESLHemantSangle I had it working, but I'm having .classpath issues now since I switched to using Gradle's new .kts build scripts.

**Comment by tomsontom** [comment] 2018-10-07 15:55
Starting with Java-11 - It is an ordinary library you add simply as a maven dependency so the problem solves itself

**Comment by shrey150** [comment] 2020-08-09 19:14
Any update on this issue? I'm still running into @fwcd 's problem: it's very annoying to manually add access rules to the `pom.xml` of Java 8 projects. Is there any plan to allow some form of configuration so that JavaFX in Oracle's JDK 8 plays nicely with this extension?

**Comment by fbricon** [comment] 2020-09-02 13:00
So I tried @tomsontom's solution of automatically relaxing the access rules when javafx is detected in the JDK, by copying a bunch of e(fx)clipse classes to JDT.LS. 
It works for Oracle JDK 1.8  and Liberica 8.0.265.FX. Other JDK 8 distros that don't ship Java FX obviously can't compile the project.

So, what next? Anything else I'd need to do to ensure JavaFX support is acceptable? (I have zero interest in Java FX myself so please enlighten me).

**Comment by tomsontom** [comment] 2020-09-02 13:28
Well the question is could efxclipse restructure its codebase and deliver an extension one can optionally install into jdt.ls

**Comment by fbricon** [comment] 2020-09-02 15:34
Anyone willing to test my changes can [manually install this vsix file in vscode](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix): https://dl.bintray.com/fbricon/vscode-extensions/vscode-java/:redhat.java-0.66.999.vsix

@tomsontom if you can provide an eclipse plugin containing just those files: https://github.com/eclipse/eclipse.jdt.ls/pull/1536, then I can remove them from jdt.ls and use it directly. I don't think it's worth having another 3rd party vscode extension just this basic JavaFX support.

**Comment by shrey150** [comment] 2020-09-02 23:51
@fbricon your custom `vscode-java` plugin fixed the issue for me, thanks! (I'm running on Oracle JDK 8u191).

**Comment by tomsontom** [comment] 2020-09-08 08:12
@fbricon I guess the problem is that efxclipse dropped from the release train hence adopting would not be so simple for you and given the JDK-8 will be used less and less I guess it is not worth the effort

**Comment by shrey150** [comment] 2020-09-23 23:18
Since RedHat is pushing out new updates without adding JavaFX support, I made a quick extension for Java 8 users that automatically adds the `<accessrule>` necessary to suppress API warnings whenever `.classpath` is updated in the project configuration. It's available here if anyone would like to use it:

https://marketplace.visualstudio.com/items?itemName=shrey150.javafx-support

**Comment by fbricon** [comment] 2020-09-29 17:07
Fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/1536. Will be released tomorrow.

**Closed by fbricon** 2020-09-29 17:07 UTC
Labels: enhancement

**Comment by shrey150** [comment] 2020-09-29 18:19
Thank you for fixing this!

**Comment by BenHunt-io** [comment] 2022-07-15 19:37
I also had this issue for the `com.sun.management` package.

The gradle fix described by @fwcd worked. I made an example here: 
https://github.com/BenHunt-io/access-restriction-vscode
