### ISSUE TITLE
What exactly do I have to install to make this work?

### ISSUE THREAD

**Issue by richardk2016** [redhat-developer/vscode-java#60] opened 2016-10-13 09:38 UTC
What does this mean? "Recognizes only projects with maven build files on the directory hierarchy, or to a lesser extent, simple Eclipse projects, i.e. containing .project and .classpath files." I am new to Java. What do I have to install on a freshly installed Windows 10 machine? What I already have is Visual Studio Code (latest version), a Java 8 SDK with JAVA_HOME set and the Redhat Java plugin. And a java file to look into it.

Label = question

**Comment by fbricon** [comment] 2016-10-13 13:36
Currently the vs code extension only supports opening folders containing a Maven project descriptor (pom.xml) or the Eclipse settings files (.project and .classpath files). 

Opening a single Java file still causes some errors (a fix will be released later today), but doesn't provide you with content assist or error reporting. This is due to the compiler/linter not being able to access a Java classpath. We're working on providing limited support (content assist) for classes from the JDK, but that will come at a later date.

**Comment by gorkem** [comment] 2016-10-13 13:40
Hmm I guess we need getting started documentation. I wonder if @burrsutter has something we can use?

**Comment by austo** [comment] 2016-10-14 03:54
I apologize if this is slightly off-topic, but I think the base case of a _single_ `.java` file not having any dependencies or being part of a package ought to work, but it _silently_ fails on my machine as of `0.0.5`. Even a vscode-level setting where one could configure the classpath for the working directory would be sufficient. One of the likely reasons for using this plugin would be for local experiments where a user doesn't want the pomp and circumstance of a fullblown IDE, so in the absence of classpath info, _always load the jdk and the current directory_ seems sensible. I'd actually be interested in fixing this, so any guidance would be appreciated. Thanks.

**Comment by fbricon** [comment] 2016-10-14 04:01
@austo I have a local work-in-progress that kinda work and does load the classes from the JDK but we decided to delay its release as there are a too many gotchas that would likely confuse users even more. It's proven way more complicated than expected. Hopefully we should fix that for the next release (end of October)

**Comment by austo** [comment] 2016-10-14 17:02
@fbricon, I'm interested to learn what your solution entails, though I'm sure I'll need to study up on [java-language-server](https://github.com/gorkem/java-language-server) to get a better understanding of the "gotchas". Any quick suggestions about where to start? Thanks.

**Comment by gorkem** [comment] 2016-10-15 15:31
@fbricon would it be possible to share that work on a PR for others to play with?

**Comment by fbricon** [comment] 2016-10-15 15:43
Yeah once I get back to my computer

**Comment by gorkem** [comment] 2016-10-15 15:55
Whaaat, no computer! I guess blondes do get all the fun :)

**Comment by fbricon** [comment] 2016-10-15 17:15
see https://github.com/gorkem/java-language-server/pull/88

**Comment by davidbruce** [comment] 2016-11-23 22:37
This plugin does not seem to be working at all?  I saw that it downloaded the server and that I am getting a thumbs up, but I cannot go to any references, there is no code completion, etc.  

I'm on OS X El Capitan 10.11.6

**Comment by gorkem** [comment] 2016-11-23 22:40
@davidbruce rumor is it works most of the time.  Do you have any logs when you click on the thumbs up?

**Comment by davidbruce** [comment] 2016-11-23 22:40
Nope, no logs at all. :/

**Comment by gorkem** [comment] 2016-11-23 22:43
@davidbruce I guess you have already tried restarting it.

**Comment by gorkem** [comment] 2016-11-23 22:49
@davidbruce just released 0.0.7 can you also try with it and let me know if it is any different.

**Comment by davidbruce** [comment] 2016-11-23 23:47
@gorkem Hey bud, I updated to 0.0.7 now I get the following Warning, but I still do not have any features working.

[Warn  - 6:44:49 PM] Nov 23, 2016 6:44:49 PM The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by gorkem** [comment] 2016-11-24 01:54
@davidbruce This is very strange. Server seems to be up and able to send information to VS Code. Is this always with the same workspace? Do you have a project that you can share?

**Comment by davidbruce** [comment] 2016-11-24 02:44
Unfortunately the project I'm working on I cannot share.  I can tell you though it has a pom.xml.

**Comment by gorkem** [comment] 2016-11-24 03:44
That is not enough to reproduce.  Sometime cleaning the ~/Library/Application Support/Code/User/workspaceStorage helps as it cleans up some cached data but I am just fishing.

**Closed** 2017-03-07 12:37 UTC
Labels: question
