### ISSUE TITLE
False positives problems (when using Lombok)

### ISSUE THREAD

**Issue by herrmanno** [redhat-developer/vscode-java#458] opened 2018-03-06 08:53 UTC
When using this plugin with a lombok-project the plugin determines many problems (e. g. for missing getters and setters) that disappear when the corresponding file is opened.

##### Environment
- Operating System: macOS
- JDK version: 1.8.0_102
- Visual Studio Code version: 1.20.1
- Java extension version: 0.20.0

##### Steps To Reproduce
1. Configure lombok support for this plugin, as described [here][1]
2. Open a project that uses lombok annotations like @Getter or @Data

##### Sample Project

Unfortunately, I cannot submit the affected project.
The important bits are:
```xml
<!-- pom.xml -->
<dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <scope>provided</scope>
</dependency>
```

```java
// License.java
@Data
public class License {
    private String serial;
}
```

##### Java Language Server log
```text
!SESSION 2018-03-06 07:59:11.945 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Command-line arguments:  -data /Users/oliverherrmann/Library/Application Support/Code/User/workspaceStorage/d8ec444f7205bbe5fb9c8b70109bb494/redhat.java/jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-03-06 07:59:14.658
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-03-06 07:59:14.992
!MESSAGE Main thread is waiting


{ ... }


!ENTRY org.eclipse.jdt.ls.core 4 0 2018-03-06 08:00:20.767
!MESSAGE Error occured while building workspace. Details: 
message: The method getSerial() is undefined for the type License;code: 67108964
message: The method getExportChannels() is undefined for the type Project;code: 67108964
message: The method getEditions() is undefined for the type Project;code: 67108964
```

##### Current Result
A Problem “The method getSerial() is undefined for the type License“ is listed in the problems view. When opening the corresponding file by clicking on the entry the problem disappears after a few seconds.  
This behavior is reproducable when restarting vs code.

##### Expected Result
No problem “The method getSerial() is undefined for the type License“ is listed in the problems view. 

[1]: https://github.com/redhat-developer/vscode-java/wiki/Lombok-support

**Comment by snjeza** [comment] 2018-04-16 19:41
I can't reproduce the issue.
I have used the attached project and the following settings:

```
"java.jdt.ls.vmargs": "-javaagent:/home/snjeza/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar -Xbootclasspath/a:/home/snjeza/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication",
```

[mytest.zip](https://github.com/redhat-developer/vscode-java/files/1916956/mytest.zip)

**Comment by GabrielBB** [comment] 2018-12-12 00:39
This issue bug is still happening, please see: [Problems list still show errors of undefined for getters or setters](https://github.com/GabrielBB/vscode-lombok/issues/13)

**Comment by snjeza** [comment] 2018-12-12 23:17
@GabrielBB could you attach a sample project?

**Comment by YongJieYongJie** [comment] 2020-10-09 16:27
Here's how I managed to solve the problem:
1. Make sure everything else works:
    - I.e., even though the errors show up in the PROBLEMS list, once you navigate to the specific file, the errors for that file disappears.
    - You will likely need to install the **Lombok Annotations Support for VSCode** extension for this.
1. Run **Java: Clean the Java language server workspace** from Command Palette.
1. Run **Java: Import Java projects in workspace** from Command Palette.
1. The problem is fixed (at least for me).
    - Do note however that you might still see a huge number of warnings / info messages.

**Comment by EuniceB** [comment] 2020-10-14 12:50
I tried @YongJieYongJie 's solution but the problems appeared again as soon as I compiled the project using maven.

**Comment by Koishilll** [comment] 2021-07-21 20:02
Maybe the extension [Lombok Annotations Support for VS Code](https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok) can help.

**Comment by EuniceB** [comment] 2021-07-21 22:52
@Koishilll unfortunately that project seems to be inactive for a while, [see here](https://github.com/GabrielBB/vscode-lombok/issues/58)

**Comment by gandhiprachi** [comment] 2021-07-28 02:38
I saw this issue too, but this goes away if i downgrade vscode-java plugin to 0.79.2

**Comment by monaka** [comment] 2021-12-25 06:43
Just in my case, the issue was fixed by adding `<java.version>11</java.version>` to pom.xml.
No vmargs setting required.

```xml
<properties>
  <java.version>11</java.version>
</properties>
```

It looks vscode-java generates configs for Java8 and recent versions of jars expect newer Javas.
I'm not familiar with Java build tools except Maven. But I guess there is a way to set the version of Java.

My env is [java-0.82.0-369.vsix on Theia in Eclipse/Che](https://github.com/eclipse-che/che-plugin-registry/blob/39631dab9450be9570f8312fd44d77de0d9442d5/che-theia-plugins.yaml#L418-L441).

**Comment by jdneo** [comment] 2023-02-10 07:59
Lombok is supported now. Check https://github.com/redhat-developer/vscode-java/wiki/Lombok-support

**Closed by jdneo** 2023-02-10 07:59 UTC
Labels: bug, diagnostics, Lombok

**Comment by jkone27** [comment] 2023-02-15 14:25
i opened it in nov 2022, lombok support was from july 2022 so i suspect it was already there at the time of this, i will try reload the app to see if the problem persist after updating all...
