### ISSUE TITLE
Incorrect JDK used when running with Gradle

### ISSUE THREAD

**Issue by aaronshenhao** [redhat-developer/vscode-java#3633] opened 2024-04-27 16:34 UTC
Edit: Solved. Not a bug but configuration error (solution below).

Upon clicking run, I notice that my project is being run with the JDK located under `~/.gradle/jdks` instead of the JDK I specified in `settings.json`.

##### Environment
- Operating System: Windows 11 Home
- JDK version: OpenJDK-18
- Visual Studio Code version: 1.88.1
- Java extension version: 1.30.0

##### Steps To Reproduce
1. Load a gradle project and set up the settings as below.
2. Click run.

Unable to attach sample files as it is for coursework.

##### Current Result
This is what it runs the project with:
```
cd /home/username/projectfile ; /usr/bin/env /home/username/.gradle/jdks/eclipse_adoptium-18-amd64-linux/jdk-18.0.2.1+1/bin/java @/tmp/cp_argfile.argfile ore.Driver 
```

##### Expected Result
This is what it should run the project with:
```
cd /home/username/projectfile ; /usr/bin/env /home/username/.jdks/openjdk-19 @/tmp/cp_argfile.argfile ore.Driver 
```

##### Additional Informations
`settings.json` file:
```json
{
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-19",
            "path": "/home/username/.jdks/openjdk-19",
        },
        {
            "name": "JavaSE-19",
            "path": "/home/username/.jdks/openjdk-20",
        },
        {
            "name": "JavaSE-19",
            "path": "/home/username/.jdks/openjdk-22",
            "default": true
        },
    ],

    "java.jdt.ls.java.home": "/home/username/.jdks/openjdk-19"
}
```

`java.jdt.ls.java.home` is being used by the "Gradle for Java" extension by Microsoft to specify the JDK.

**Comment by mklinkj** [comment] 2024-04-28 09:54
hello.

I created an example test project and checked its operation...

If you want to use the coursework project with JDK 18, you can do it as follows.

```json
{
    "java.configuration.runtimes": [
			  { 
            "name": "JavaSE-18",  // 💡Install Java 18 on the system and add the path
            "path": "/home/username/.jdks/openjdk-18",
        },
        {
            "name": "JavaSE-19",
            "path": "/home/username/.jdks/openjdk-19",
        },
        {
            "name": "JavaSE-20", // 💡Renamed to JavaSE-20.
            "path": "/home/username/.jdks/openjdk-20",
        },
        {
            "name": "JavaSE-22", // 💡Renamed to JavaSE-22.
            "path": "/home/username/.jdks/openjdk-22",
            "default": true
        },
    ],

    // 💡 Path to Java Home to run Gradle for Java
    "java.jdt.ls.java.home": "/home/username/.jdks/openjdk-19"

}
```



### TODO:

1. Add JavaSE 18 installation path to `java.configuration.runtimes`.
2. Correctly corrected duplicate `JavaSE-??` name.

`"java.jdt.ls.java.home"` is simply the path to run the Gradle for Java extension, and if JAVA_HOME is set globally on the system, it does not seem to need to be specifically specified.



# Example Test

### Example Project

* https://github.com/mklinkj/QnA/tree/master/vscode-java/gradle-java-home-test

This is a simple example program that prints the currently running Java Home.



### System environment

In my case, to prevent gradle from automatically downloading a JDK that cannot be used, I disabled automatic downloading and manually specified the JDK path.

#### **%USERPROFILE%/.gradle/gradle.properties**

```properties
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C:/JDK/8,C:/JDK/11,C:/JDK/17,C:/JDK/18,C:/JDK/21
```



#### VSCode - User Settings.json

```json
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-17",
        "path": "C:\\JDK\\17\\",
        "default": true
      },
      {
        "name": "JavaSE-21",
        "path": "C:\\JDK\\21\\"
      },
      {
        "name": "JavaSE-11",
        "path": "C:\\JDK\\11\\"
      },
		  {
        "name": "JavaSE-18",
        "path": "C:\\JDK\\18\\"
      },
      {
        "name": "JavaSE-1.8",
        "path": "C:\\JDK\\8\\"
      }
    ],
    // Java runtime path to run Gradle for Java
    // Required after installing "Gradle for Java". If the JAVA_HOME environment variable is set globally on the system, it does not need to be set.
    "java.import.gradle.java.home": "C:\\JDK\\21",
```



#### Java Version settings for example project - build.gradle

```groovy
// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(18)
  }
}
```



#### Run it by clicking the Run link that appears above the main() method.

If you run the test project with the settings as above...

```
C:\git-mklinkj\QnA\vscode-java\gradle-java-home-test> cmd /C "C:\JDK\18\bin\java.exe @%LOCALAPPDATA%\Temp\cp_bcmlni503byv5p5eyxxi4hqsu.argfile org.example.App "
Java Home: C:\JDK\18
```

* I confirmed that it works well with JDK 18.

  ![image-20240428182053968](https://github.com/redhat-developer/vscode-java/assets/96992046/0a93aa26-6954-47a3-9f75-fcb3fe634c9f)



#### Run it by clicking application > run Task in “Gradle for Java”

* I confirmed that it works well with JDK 18.

  ![image-20240428181800400](https://github.com/redhat-developer/vscode-java/assets/96992046/4cc72ec9-694c-40c7-b900-6cc413252a1b)



## ⚠️ Caution

* When changing the JDK version of a project, it is better to use Clean Java Language Server Workspace.

  

💡 If you have a development environment that uses multiple versions of the JDK environment, I personally think it would be better to disable Gralde's automatic JDK detection function and automatic download function... 😅



Then, please take note of this. Have a great day.

**Comment by aaronshenhao** [comment] 2024-04-28 16:15
> hello.
> 
> I created an example test project and checked its operation...
> 
> If you want to use the coursework project with JDK 18, you can do it as follows.
> 
> ```json
> {
>     "java.configuration.runtimes": [
>         { 
>             "name": "JavaSE-18",  // 💡Install Java 18 on the system and add the path
>             "path": "/home/username/.jdks/openjdk-18",
>         },
>         {
>             "name": "JavaSE-19",
>             "path": "/home/username/.jdks/openjdk-19",
>         },
>         {
>             "name": "JavaSE-20", // 💡Renamed to JavaSE-20.
>             "path": "/home/username/.jdks/openjdk-20",
>         },
>         {
>             "name": "JavaSE-22", // 💡Renamed to JavaSE-22.
>             "path": "/home/username/.jdks/openjdk-22",
>             "default": true
>         },
>     ],
> 
>     // 💡 Path to Java Home to run Gradle for Java
>     "java.jdt.ls.java.home": "/home/username/.jdks/openjdk-19"
> 
> }
> ```
> 
> ### TODO:
> 
>     1. Add JavaSE 18 installation path to `java.configuration.runtimes`.
> 
>     2. Correctly corrected duplicate `JavaSE-??` name.
> 
> 
> `"java.jdt.ls.java.home"` is simply the path to run the Gradle for Java extension, and if JAVA_HOME is set globally on the system, it does not seem to need to be specifically specified.
> # Example Test
> ### Example Project
> 
>     * https://github.com/mklinkj/QnA/tree/master/vscode-java/gradle-java-home-test
> 
> 
> This is a simple example program that prints the currently running Java Home.
> ### System environment
> 
> In my case, to prevent gradle from automatically downloading a JDK that cannot be used, I disabled automatic downloading and manually specified the JDK path.
> #### **%USERPROFILE%/.gradle/gradle.properties**
> 
> ```ini
> org.gradle.java.installations.auto-detect=false
> org.gradle.java.installations.auto-download=false
> org.gradle.java.installations.paths=C:/JDK/8,C:/JDK/11,C:/JDK/17,C:/JDK/18,C:/JDK/21
> ```
> 
> #### VSCode - User Settings.json
> 
> ```json
>     "java.configuration.runtimes": [
>       {
>         "name": "JavaSE-17",
>         "path": "C:\\JDK\\17\\",
>         "default": true
>       },
>       {
>         "name": "JavaSE-21",
>         "path": "C:\\JDK\\21\\"
>       },
>       {
>         "name": "JavaSE-11",
>         "path": "C:\\JDK\\11\\"
>       },
> 		  {
>         "name": "JavaSE-18",
>         "path": "C:\\JDK\\18\\"
>       },
>       {
>         "name": "JavaSE-1.8",
>         "path": "C:\\JDK\\8\\"
>       }
>     ],
>     // Java runtime path to run Gradle for Java
>     // Required after installing "Gradle for Java". If the JAVA_HOME environment variable is set globally on the system, it does not need to be set.
>     "java.import.gradle.java.home": "C:\\JDK\\21",
> ```
> 
> #### Java Version settings for example project - build.gradle
> 
> ```groovy
> // Apply a specific Java toolchain to ease working on different environments.
> java {
>   toolchain {
>     languageVersion = JavaLanguageVersion.of(18)
>   }
> }
> ```
> 
> #### Run it by clicking the Run link that appears above the main() method.
> 
> If you run the test project with the settings as above...
> 
> ```
> C:\git-mklinkj\QnA\vscode-java\gradle-java-home-test> cmd /C "C:\JDK\18\bin\java.exe @%LOCALAPPDATA%\Temp\cp_bcmlni503byv5p5eyxxi4hqsu.argfile org.example.App "
> Java Home: C:\JDK\18
> ```
> 
>     * I confirmed that it works well with JDK 18.
>       ![image-20240428182053968](https://private-user-images.githubusercontent.com/96992046/326248182-0a93aa26-6954-47a3-9f75-fcb3fe634c9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTc2ODQsIm5iZiI6MTcxNDMxNzM4NCwicGF0aCI6Ii85Njk5MjA0Ni8zMjYyNDgxODItMGE5M2FhMjYtNjk1NC00N2EzLTlmNzUtZmNiM2ZlNjM0YzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE1MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjhkMTNiZTk4MDA4MTQ2OTU4YWFmOWYxM2I2NDEyZjhjNjU1ZjE5NzlkOTA4OWZlZjQyMzlmNjFlNzAyYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9sKj9raLRn__HwGsaz8WpYVDpdCSqLKxQupW5YekaU)
> 
> 
> #### Run it by clicking application > run Task in “Gradle for Java”
> 
>     * I confirmed that it works well with JDK 18.
>       ![image-20240428181800400](https://private-user-images.githubusercontent.com/96992046/326248194-4cc72ec9-694c-40c7-b900-6cc413252a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTc2ODQsIm5iZiI6MTcxNDMxNzM4NCwicGF0aCI6Ii85Njk5MjA0Ni8zMjYyNDgxOTQtNGNjNzJlYzktNjk0Yy00MGM3LWI5MDAtNmNjNDEzMjUyYTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE1MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MWQxNDllMTVlZmUzMTM5ZjE4OTcxNmMyNjlhNDQyZDY0MDI1Njk1M2UyMDlmN2M2ZmY2Y2FjZDIwZjI2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-c4vzHUb-zj9TrFhJtV5Ew2jbvuzW1yCj8mXGLQlKP8)
> 
> 
> ## ⚠️ Caution
> 
>     * When changing the JDK version of a project, it is better to use Clean Java Language Server Workspace.
> 
> 
> 💡 If you have a development environment that uses multiple versions of the JDK environment, I personally think it would be better to disable Gralde's automatic JDK detection function and automatic download function... 😅
> 
> Then, please take note of this. Have a great day.

Wow, I really appreciate the detailed solution. And apologies for the typo.

Thanks to your example, I've managed to find the source of the problem. There appeared to be two separate problems, which affected the "Language Support for Java" and "Gradle for Java" extensions separately.

I do have the following setting in my `build.gradle` file. I should have probably mentioned it, but you've picked up on it as well.

```java
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(18)
    }
}
```

1. JavaSE-18 was required in `build.gradle`, but it was unavailable due to it not being listed in `java.configuration.runtimes` in `settings.json`.
    - Effect: Language Support for Java imports the wrong JVM (automatically downloaded by Gradle).
    - Fix: List it in `java.configuration.runtimes` or remove the requirement in `build.gradle`
    - Gradle for Java is not affected.
2. `java.jdt.ls.java.home` does not point to the correct JDK (JavaSE-18).
    - Effects: Gradle for Java imports the wrong JVM (automatically downloaded by Gradle).
    - Fix: Make `java.jdt.ls.java.home` point to the correct JDK or remove the requirement in `build.gradle`
    - Language Support for Java is not affected (still manages to find the correct version).

I found that `java.import.gradle.java.home` or modifying the `gradle.properties` file had no effect on my machine. I thought setting the `gradle.properties` file would help in case 2, but it didn't.

Gradle properties additions I used:
> org.gradle.java.installations.auto-detect=false
> org.gradle.java.installations.auto-download=false
> org.gradle.java.installations.paths=C:/JDK/8,C:/JDK/11,C:/JDK/17,C:/JDK/18,C:/JDK/21

Other notes:
I got link errors, but that was because I clicked the wrong button on the Gradle for Java sidebar (build instead of application/run).

**Comment by mklinkj** [comment] 2024-04-29 03:57
I did this because I didn't want Gradle to automatically download and use JDKs that weren't on my system and preferred to use JDKs that I had manually installed on my system.

Glad it worked out for you and thanks for the answer. Have a nice day 👍

**Comment by rgrunber** [comment] 2024-05-14 17:08
Glad you were able to resolve this. Closing for now but feel free to re-open if there's some other problems.

Note, as of [1.23.0](https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#1230-september-28th-2023) (we're about to release 1.31.0 soon), JDK detection is done automatically which should lessen the strain of users needing to populate `java.configuration.runtimes` manually. See https://www.npmjs.com/package/jdk-utils#usage for some of the supported locations. Also as was pointed out the `java.jdt.ls.java.home` & `java.import.gradle.java.home` are meant for the JRE used for the JDT-LS/Gradle runtimes. For configuring which JDK is used by an open project, there is `java.configuration.runtimes`.

**Closed by rgrunber** 2024-05-14 17:08 UTC
