### ISSUE TITLE
Can't resolve references to maven groups/artifacts in pom.xml

### ISSUE THREAD

**Issue by dlee005c** [redhat-developer/vscode-java#712] opened 2018-11-13 03:11 UTC
Java Language server fails to update/run when editing a maven project that references a maven artifact that is not in the public maven repo.  Specifically for a pom that contains

```
<parent>
    <artifactId>parent-artifact</artifactId>
    <groupId>com.mycompany.other.group</groupId>
    <version>1.0.82</version>
    <relativePath/>
</parent>
```

##### Environment
- Operating System: Mac OSX 10.13.6
- JDK version: openjdk64-1.8.0.181
- Visual Studio Code version: 1.29.0
- Java extension version: 0.33.0

##### Steps To Reproduce
1. Create a maven project that references a pom that is not in public repository
2. Open project in VSCode with Language Support for Java extension installed

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
The following error occurs in my pom.xml (redacted)
{
	"resource": "/.../Projects/.../pom.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "0",
	"severity": 8,
	"message": "Project build error: Non-resolvable parent POM for com.mycompany.my.group:artifact-name:2.7.0-SNAPSHOT: Failure to find com.mycompany.other.group:parent-artifact:pom:1.0.82 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 2,
	"endLineNumber": 1,
	"endColumn": 2
}
preventing the Java Language server from doing its job

And the following error in Java Language Server logs

!ENTRY org.eclipse.core.jobs 4 2 2018-11-12 19:02:45.321
!MESSAGE An internal error occurred during: "Update project artifact-name".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.managers.MavenBuildSupport.collectProjects(MavenBuildSupport.java:88)
	at org.eclipse.jdt.ls.core.internal.managers.MavenBuildSupport.update(MavenBuildSupport.java:71)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$4.runInWorkspace(ProjectsManager.java:416)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

##### Expected Result

Java Language Server runs and extension behaves as normal.

##### Additional Informations

I've checked that my local maven repo contains the artifact, and it does.
I am able to successfully execute maven commands on my project from the command line.
I've configured the Java extention to use my settings.xml file ("java.configuration.maven.userSettings": "~/.m2/settings.xml")

**Comment by fbricon** [comment] 2018-11-13 14:29
Closing as duplicate of #702. 

Please try the latest CI build from [http://download.jboss.org/jbosstools/jdt.ls/staging/](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D). Download the most recent `java-<version>.vsix` file and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Closed by fbricon** 2018-11-13 14:29 UTC
Labels: duplicate
