### ISSUE TITLE
Language Server fails to start with multiple --add-exports in java.jdt.ls.vmargs

### ISSUE THREAD

**Issue by paulmedynski-microsoft** [redhat-developer/vscode-java#3577] opened 2024-04-16 14:26 UTC
The Language Server fails to start when multiple ```---add-exports``` are specified in the ```java.jdt.ls.vmargs``` setting.

For example these VSCode settings (in ```.vscode/settings.json```) start the Language Server correctly:

```
{
  "java.jdt.ls.vmargs": "--add-exports java.xml/com.sun.org.apache.xerces.internal.impl.dtd=ALL-UNNAMED",
  "java.trace.server": "verbose"
}
```

These settings do not:

```
{
  "java.jdt.ls.vmargs": "--add-exports java.xml/com.sun.org.apache.xerces.internal.impl.dtd=ALL-UNNAMED --add-exports java.xml/com.sun.org.apache.xerces.internal.xni.parser=ALL-UNNAMED --add-exports java.xml/com.sun.org.apache.xerces.internal.xni.grammars=ALL-UNNAMED --add-exports java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED --add-exports java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED --add-exports java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED"
  "java.trace.server": "verbose"
}
````

I see this error in the Language Support for Java output pane:

```
Error: Could not find or load main class java.xml.com.sun.org.apache.xerces.internal.xni.parser=ALL-UNNAMED
Caused by: java.lang.ClassNotFoundException: java.xml.com.sun.org.apache.xerces.internal.xni.parser=ALL-UNNAMED
```

I don't see any errors reported in the Chrome dev tools console, or in the Language Server workspace logs.

##### Environment
- Operating System:  Windows 11 and WSL2 Debian 12
- JDK version:  21.0.1
- Visual Studio Code version:  1.88.1
- Java extension version:  v1.30.2024041608 (pre-release)

##### Steps To Reproduce
1. Add multiple ```--add-exports``` arguments to the ```java.jdt.ls.vmargs``` value in VSCode ```settings.json```.
2. Open a Java project workspace.

##### Current Result

The Language Server fails to start, and reports the above error to the Output pane.

##### Expected Result

The Language Server starts with all ```--add-exports``` supplied to the JVM.

**Comment by rgrunber** [comment] 2024-04-16 20:02
I'm able to reproduce this as well. It's due to :

https://github.com/redhat-developer/vscode-java/blob/34f54ac178b544d9def4409bff080282e8dacaa2/src/javaServerStarter.ts#L310-L318 . After the first `--add-exports` is pushed, the subsequent ones are skipped causing it to appear as if one of the arguments is being run as the main class.

**Comment by snjeza** [comment] 2024-04-17 01:13
> can you think of any JVM arguments that when duplicated would produce an issue starting up ? https://github.com/redhat-developer/vscode-java/pull/50 so maybe we should relax the restriction.

I agree, we should relax the restriction.

**Comment by paulmedynski-microsoft** [comment] 2024-04-17 10:15
Thanks for the quick turnaround!  Is there anything I can do with my local extension installation to make a similar change while I wait for the next release?

**Comment by rgrunber** [comment] 2024-04-17 14:08
Once the change is merged, the pre-release stream should contain the fix the next day so you could definitely try that. I checked if there was some workaround to bypass the incorrect behaviour in a current released version, but there doesn't seem to be any.

**Closed** 2024-04-17 14:26 UTC
Labels: bug
