### ISSUE TITLE
Is my configuration of java.import.exclusions correct?

### ISSUE THREAD

**Issue by hanct** [redhat-developer/vscode-java#1698] opened 2020-11-13 16:28 UTC
vscode-java:0.68
OS: windows 10

Hi all,

I have a workspace folder which contains 2 subfolders called Frontend and Backend.
I have set the "java.import.exclusions":["workspace/Frontend"], but everytime i reload my vscode IDE, it keep importing the project inside the Frontend folder, why is that so?

I even try "java.import.exclusions":["\*\*workspace/Frontend/\*\*"],  but still no avail.  Am i setting correctly?

**Comment by snjeza** [comment] 2020-11-13 17:00
@hanct could you try
```
"java.import.exclusions": [
     "**/node_modules/**",
    "**/.metadata/**",
    "**/archetype-resources/**",
    "**/META-INF/maven/**",
    "**/Frontend/**",
],
```

**Comment by hanct** [comment] 2020-11-13 17:08
> @hanct could you try
> 
> ```
> "java.import.exclusions": [
>      "**/node_modules/**",
>     "**/.metadata/**",
>     "**/archetype-resources/**",
>     "**/META-INF/maven/**",
>     "**/Frontend/**",
> ],
> ```

Thanks for the suggestion. I try it, but still no avail, it stilll try to import the stuff inside the Frontend folder.


2a73934a Importing Gradle project(s): 47% D:\Projects\Source_Codes\SmartKlik_CSV_Aggregator\workspace\Frontend\CSV_Aggregator\node_modules\@angular-devkit\build-angular [465/1000]

My target is to avoid importing anything except for the projects inside the Backend folder.

**Comment by snjeza** [comment] 2020-11-13 17:17
@hanct could you try to call **Java: Clean the Java language server workspace** and click **Restart and delete**?

**Comment by hanct** [comment] 2020-11-14 02:16
> @hanct could you try to call **Java: Clean the Java language server workspace** and click **Restart and delete**?

Hi, I try it now, and saw that it is currently in the midst of initializing workspace, and i saw that it is also intializing the folder in Frontend too. Is this initializing of workspace, anything to do with java.import.exclusions?
![image](https://user-images.githubusercontent.com/4410920/99136738-b2e57f00-2661-11eb-9a7c-7792c86092c4.png)


After initializing ended, my Java dependencies look like this:  CSV_Aggregator is a project in the frontend folder, but clicking on it shows nothing underneath it.  csv_bundler is a project in the backend folder
![image](https://user-images.githubusercontent.com/4410920/99136770-f9d37480-2661-11eb-8ad1-5bd32fb29eca.png)

By using the java.import.exclusions:
1) Am i expecting the Java dependencies should only display  the csv_bundler?
2) Am i expecting that it should only initialize workspace for the projects in backend folder?

**Comment by snjeza** [comment] 2020-11-14 03:03
@hanct you can try the following settings:

```
"java.import.exclusions": [
     "**/node_modules/**",
    "**/.metadata/**",
    "**/archetype-resources/**",
    "**/META-INF/maven/**",
    "**/Frontend/**",
    "**/CSV_Aggregator/**",
],
```
and call **Java: Clean the Java language server workspace**, click **Restart and delete**

**Comment by hanct** [comment] 2020-11-14 05:55
Hi,
Tried, still no avail after cleaning the workspace, restart and delete.
![image](https://user-images.githubusercontent.com/4410920/99140821-12eb1e00-2680-11eb-8f71-2158e0472e38.png)

The initializing of the workspace still include the CSV_Aggregator in the frontend folder. Finally I still got this
![image](https://user-images.githubusercontent.com/4410920/99140830-239b9400-2680-11eb-8a1e-d9b576c71d82.png)

I even set to exclude everything, clean workspace, restart and delete
"java.import.exclusions": ["**"]

Yet, the initializing of the workspace still include the CSV_Aggregator in the frontend folder. 
And the Java dependencies still see the CSV_Aggregator.. Strange..

**Comment by snjeza** [comment] 2020-11-14 16:27
@hanct check your workspace settings.json

![workspace](https://user-images.githubusercontent.com/388609/99151906-9f0c3e00-269e-11eb-9b34-af4a540b0743.png)

**Comment by hanct** [comment] 2020-11-14 16:34
Hi, i look at my workspace setting file, which is inside the .vscode folder.  What am i suppose to check?  It just contain a bunch of settings, among which is the java.import.exclusion.

**Comment by snjeza** [comment] 2020-11-14 16:50
@hanct check the java.import.exclusions property in workspace settings.json (not  java.import.exclusion)
Could you show your workspace file structure?

**Comment by hanct** [comment] 2020-11-15 02:24
Hi, 

Below is my workspace folders (the red circled one is my workspace setting
![image](https://user-images.githubusercontent.com/4410920/99160923-8d22ad80-2727-11eb-9e0c-b66f6aa984a5.png)


Below is the content of my workspace setting
```
{
	"folders": [
		{
			"path": "Frontend\\CSV_Aggregator"
		},
		{
			"path": "Backend\\csv_bundler"
		},
		{
			"path": "."
		}
	],
	"settings": {
		"workbench.tree.indent": 16,
		"explorer.compactFolders": false,
		"culp.fullPath.removeDiscColons": true,
		"git.ignoreLimitWarning": true,
		"terminal.integrated.env.windows": {
			"PATH":"${env:PATH};${workspaceFolder:workspace}/node.js;D:/Software/java/jdk-15/bin;${workspaceFolder:CSV_Aggregator}/node_modules/.bin",
			"GRADLE_USER_HOME":"${workspaceFolder:csv_bundler}/.gradle"
		},
		"eslint.options": {
			"extensions": [".ts", ".html"]
		},
	
		"eslint.validate": [
			"javascript",
			"javascriptreact",
			"typescript",
			"typescriptreact",
			"html"
		],
		"gradle.nestedProjects":true,
		"gradle.debug":false,
		"gradle.javaDebug": {
			"tasks": [
				"main-service:bootRun"
			]
		},
		"java.home": "D:/Software/java/jdk-15", 
		"java.import.gradle.enabled":true,  
		"java.import.gradle.wrapper.enabled": true,
		"java.import.gradle.offline.enabled": true,
		"java.import.gradle.user.home": "D:/Projects/Source_Codes/SmartKlik_CSV_Aggregator/workspace/Backend/csv_bundler/.gradle",
		"java.debug.settings.hotCodeReplace": "auto",
		"java.import.exclusions": [
			"**"
		]
	
	}
}
```

Today, i repeat the clean workspace, restart and delete, but still with the above setting, I still got the below, although i expect it to be empty , as my exclusions is everything.
![image](https://user-images.githubusercontent.com/4410920/99161371-9e21ed80-272c-11eb-9f4c-fb9cac1f6ca5.png)

**Comment by hanct** [comment] 2020-11-15 02:25
> Hi, i look at my workspace setting file, which is inside the .vscode folder. What am i suppose to check? It just contain a bunch of settings, among which is the java.import.exclusion.

I think i see wrongly. My workspace setting is not in .vscode folder, but outside it. But i think its location should not matter

**Comment by snjeza** [comment] 2020-11-15 16:12
@hanct Could you enable Java LS tracing and attach the logs from the output view (Java Language server)?
See https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server

**Comment by hanct** [comment] 2020-11-15 18:18
Hi, i set the tracing to "verbose". Attach is the log. Do let me know if i attached the incorrect log, cos this is the first time i enable such tracing and viewing such log.
[LS_log.txt](https://github.com/redhat-developer/vscode-java/files/5542876/LS_log.txt)

**Comment by snjeza** [comment] 2020-11-15 19:24
This settings is incorrect:
```
"java.import.exclusions": [
	"**"
]
```
Could you try the following:
- close VS Code
- remove .project, .classpath, .settings in the CSV_Aggregator directory
- disable or remove the "Lombok Annotations Support for VS Code" extension
- remove the c:\Users\hanzh\AppData\Roaming\Code\User\workspaceStorage
- set the following settings.json
```
...
"java.import.exclusions": [
    "**/node_modules/**",
    "**/.metadata/**",
    "**/archetype-resources/**",
    "**/META-INF/maven/**",
    "**/Frontend/**",
    "**/CSV_Aggregator/**",
],
"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m",
"java.trace.server": "verbose",
... 

```
- start VS Code
- zip and attach the c:\Users\hanzh\AppData\Roaming\Code\User\workspaceStorage\*\redhat.java directory

> Do let me know if i attached the incorrect log, cos this is the first time i enable such tracing and viewing such log.

You can use the **Java: Open all log files** command

**Comment by hanct** [comment] 2020-11-16 01:28
> This settings is incorrect:
> ```
> "java.import.exclusions": [
> 	"**"
> ]
> ```
> Could you try the following:
> - start VS Code
> - disable or remove the "Lombok Annotations Support for VS Code" extension
> - close VS Code
> - remove .project, .classpath, .settings in the CSV_Aggregator directory
> - remove the c:\Users\hanzh\AppData\Roaming\Code\User\workspaceStorage
> - set the following settings.json
> ```
> ...
> "java.import.exclusions": [
>     "**/node_modules/**",
>     "**/.metadata/**",
>     "**/archetype-resources/**",
>     "**/META-INF/maven/**",
>     "**/Frontend/**",
>     "**/CSV_Aggregator/**",
> ],
> "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m",
> "java.trace.server": "verbose",
> ... 
> 
> ```
> - start VS Code
> - zip and attach the c:\Users\hanzh\AppData\Roaming\Code\User\workspaceStorage\*\redhat.java directory
> 
> > Do let me know if i attached the incorrect log, cos this is the first time i enable such tracing and viewing such log.
> 
> You can use the **Java: Open all log files** command

Hi, thanks for the steps. Will try it out tonight when I get back home. Meanwhile, may I know why is the exclusion setting incorrect? Cos I wanted to try exclude everything, to verify if the exclusion works. Or did I use the wrong syntax to exclude everything

**Comment by snjeza** [comment] 2020-11-16 01:44
>  may I know why is the exclusion setting incorrect? Cos I wanted to try exclude everything, to verify if the exclusion works. Or did I use the wrong syntax to exclude everything

It will exclude all projects. The syntax is correct.

**Comment by hanct** [comment] 2020-11-16 12:50
> This settings is incorrect:
> 
> ```
> "java.import.exclusions": [
> 	"**"
> ]
> ```
> 
> Could you try the following:
> 
> * start VS Code
> * disable or remove the "Lombok Annotations Support for VS Code" extension
> * close VS Code
> * remove .project, .classpath, .settings in the CSV_Aggregator directory
> * remove the c:\Users\hanzh\AppData\Roaming\Code\User\workspaceStorage
> * set the following settings.json
> 
> ```
> ...
> "java.import.exclusions": [
>     "**/node_modules/**",
>     "**/.metadata/**",
>     "**/archetype-resources/**",
>     "**/META-INF/maven/**",
>     "**/Frontend/**",
>     "**/CSV_Aggregator/**",
> ],
> "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m",
> "java.trace.server": "verbose",
> ... 
> ```
> 
> * start VS Code
> * zip and attach the c:\Users\hanzh\AppData\Roaming\Code\User\workspaceStorage*\redhat.java directory
> 
> > Do let me know if i attached the incorrect log, cos this is the first time i enable such tracing and viewing such log.
> 
> You can use the **Java: Open all log files** command

Hi,
Done as u requested. I have uninstall lombok support extension,  There is no  .project and .classpath, .settings in the Frontend/CSV_Aggregator directory for me to delete
Below is the attached

[redhat.java.zip](https://github.com/redhat-developer/vscode-java/files/5546274/redhat.java.zip)

**Comment by snjeza** [comment] 2020-11-17 03:13
@hanct Could you try the following:

- right click CSV_Aggregator and select **Remove Folder from Workspace**
- run **Java: Clean the Java language server workspace**, click **Restart and delete**

Your CSV_Aggregator is already included in '/Projects/Source_Codes/SmartKlik_CSV_Aggregator/workspace'.

**Comment by hanct** [comment] 2020-11-17 07:29
Hi, once i remove the CSV_Aggregator folder from workspace, and yes the Java_dependencies no longer listed it out., after i clean the workspace, restart and delete.   

Then when i add it back into the workspace again, the Java dependencies list it out again.
![image](https://user-images.githubusercontent.com/4410920/99345692-d1e84900-28cd-11eb-94af-f1aaa64badc4.png)

I am still using the java.import.exclusions as u suggested above.

**Comment by hanct** [comment] 2020-11-17 07:30
In other word, if i have 3 workspace folders, the java dependencies will have these 3 folders, regardless of  the java.import.exclusions. Is this the way suppose to work?

**Comment by snjeza** [comment] 2020-11-17 16:52
> Then when i add it back into the workspace again, the Java dependencies list it out again.
> In other word, if i have 3 workspace folders, the java dependencies will have these 3 folders, regardless of the java.import.exclusions. Is this the way suppose to work?

Why you add CSV_Aggregator? It is already under the workspace directory. 
You can add all folders under CSV_Aggregator to java.import.exclusions.

**Comment by hanct** [comment] 2020-11-17 17:29
My intention is just to include CSV_aggregator and csv_bundler folder in the workspace folder (ultimately , i will not include the folder called workspace, so we can ignore that).  Reason is because in real life, developer would be coding the frontend (e.g angular)  and backend (e.g spring boot) in vscode.  That is why I need to include both folders.

But nevertheless, I really appreciate your help on this. As long as anyone who use this vscode-java has verified that the java.import.exclusions are indeed working, I suspect could be something i have done wrong here, Maybe when i have time, i try to create another simple workspace, and see if the java.import.exclusions work.

For now, I am just hoping that there could be a documentation or tutorial out there that could use a demo to show how java.import.exclusions work, and what to expect.

**Comment by snjeza** [comment] 2020-11-17 18:17
>  My intention is just to include CSV_aggregator and csv_bundler folder in the workspace folder (ultimately , i will not include the folder called workspace, so we can ignore that). Reason is because in real life, developer would be coding the frontend (e.g angular) and backend (e.g spring boot) in vscode. That is why I need to include both folders.

You can create a new directory (your_workspace), add both your folders to it and open only your_workspace.

> For now, I am just hoping that there could be a documentation or tutorial out there that could use a demo to show how java.import.exclusions work, and what to expect.

You can't exclude a root folder. I suppose that your CSV_Aggregator includes pom.xml, build.gradle or .project.

**Comment by hanct** [comment] 2020-11-17 18:28
> > My intention is just to include CSV_aggregator and csv_bundler folder in the workspace folder (ultimately , i will not include the folder called workspace, so we can ignore that). Reason is because in real life, developer would be coding the frontend (e.g angular) and backend (e.g spring boot) in vscode. That is why I need to include both folders.
> 
> You can create a new directory (your_workspace), add both your folders to it and open only your_workspace.


> 
> > For now, I am just hoping that there could be a documentation or tutorial out there that could use a demo to show how java.import.exclusions work, and what to expect.
> 
> You can't exclude a root folder. I suppose that your CSV_Aggregator includes pom.xml, build.gradle or .project.

I already have a directory called workspace. This directory contains the CSV_Aggregator (it is an angular project, so it don't have pom.xml or build.gradle. I also could not find any .project file within it. ) and csv_bundler.  U might be wondering why i don't  just add the workspace directory as the workspace folder,. Reason is because there is a plugin that i use, which require one of the workspace folder to contain the build.gradle at the root, then it can work. That is y, i have to add "csv_bundler" folder as a workspace folder, since it directly contains the build.gradle.

**Comment by snjeza** [comment] 2020-11-17 19:21
>  That is y, i have to add "csv_bundler" folder as a workspace folder, since it directly contains the build.gradle.

You can add csv_bundler and remove CSV_Aggregator.
You can also try to upgrade your VS Code Java Extension Pack. The Java Dependencies view is old. See https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency

**Comment by hanct** [comment] 2020-11-18 13:03
The only problem is , if i want to work with frontend, i need the CSV_Aggregator. If i want to work with backend, i need csv_bundler. Hence i can't exclude either of them.  Unless I create two workspaces, and run 2 different instance of visual studio code on them, which is something i want to avoid

**Comment by snjeza** [comment] 2020-11-18 16:58
> The problem is , if i want to work with frontend, i need the CSV_Aggregator.

It is under your workspace directory. You shouldn't add it.

>  So now i am wondering does the java.import.exclusions really works? If it works, then it does not really matter whether i add the CSV_Aggregator folder.

It works, but you can't exclude a root path.
Could you show the contents of your CSV_Aggregator directory including hidden files from the Windows Explorer or command line?

**Comment by snjeza** [comment] 2020-11-18 17:11
> Today, i repeat the clean workspace, restart and delete, but still with the above setting, I still got the below, although i expect it to be empty , as my exclusions is everything.

https://user-images.githubusercontent.com/4410920/99161371-9e21ed80-272c-11eb-9f4c-fb9cac1f6ca5.png

Could you expand the CSV_Aggregator entry in order to see if there is a java project?

**Comment by hanct** [comment] 2020-11-18 17:22
> > The problem is , if i want to work with frontend, i need the CSV_Aggregator.
> 
> It is under your workspace directory. You shouldn't add it.
> 
> > So now i am wondering does the java.import.exclusions really works? If it works, then it does not really matter whether i add the CSV_Aggregator folder.
> 
> It works, but you can't exclude a root path.
> Could you show the contents of your CSV_Aggregator directory including hidden files from the Windows Explorer or command line?

Hi, here it is, including hidden files

![image](https://user-images.githubusercontent.com/4410920/99563072-dca4fa00-2a03-11eb-86bc-f9fb46be6460.png)

**Comment by hanct** [comment] 2020-11-18 17:29
I think the exclusion is indeed working. here is my experiment:  I import the 2 folders (csv_bundler and CSV_Aggregator).
Then i set the exclusion to this
![image](https://user-images.githubusercontent.com/4410920/99564764-cf890a80-2a05-11eb-9d86-cf03eb38bef1.png)

And finally i got the below:
    Even though the Java dependencies list the 2 folders, but as shown in the screenshot, when i expand the 2 folders, they are EMPTY. which mean the exclusions work.  Correct me if my understanding is wrong
![image](https://user-images.githubusercontent.com/4410920/99564817-dfa0ea00-2a05-11eb-905c-b909b9d79902.png)

The only problem here is, since i exclude everything, why is the vscode-java extension still initialize the workspace for these excluded folders (see screenshot below).  To me, the vscode-java extension should not even bother to initialize the workspace for these folders, since they are excluded, as initializing take quite some time before the Java Dependencies panel appear.
![image](https://user-images.githubusercontent.com/4410920/99565091-39091900-2a06-11eb-8d5a-442bf5be3bd8.png)

**Comment by snjeza** [comment] 2020-11-18 17:46
> ... as initializing take quite some time before the Java Dependencies panel appear.

Java LS scans all your root paths. I suppose that they contain a lot files. You can try
```
"java.import.exclusions": [
    "**",
   "**/node_modules/**",
   "**/dist/**",
    "**/.metadata/**",
    "**/archetype-resources/**",
    "**/META-INF/maven/**",
    "**/Frontend/**",
    "**/CSV_Aggregator/**",
],

**Comment by hanct** [comment] 2020-11-19 08:04
No difference. It still scan my CSV_aggregator.
Can i confirm that the java.import.exclusions  setting is supposed to prevent the java LS from scanning all the root paths? If this setting is not meant for preventing scanning of certain folders, then there is no need for me to pursue on the scanning part.

**Comment by hanct** [comment] 2020-11-21 14:17
In other word, can i conclude that the java.import.exclusions setting is not working as expected (hence considered a bug)? since it initialize the paths that are configured in the java.import.exclusions

**Comment by snjeza** [comment] 2020-11-21 16:33
> In other word, can i conclude that the java.import.exclusions setting is not working as expected (hence considered a bug)? since it initialize the paths that are configured in the java.import.exclusions

Java LS scans all root paths. Your CSV_Aggregator is a root path. You can add all CSV_Aggregatorall sub-directories to java.import.exclusions.

```
"java.import.exclusions": [
    "**",
   "**/node_modules/**",
   "**/dist/**",
   "**/src/**",
   "**/.history/**",
   "**/e2e/**",
   "**/.vscode/**",
    "**/.metadata/**",
    "**/archetype-resources/**",
    "**/META-INF/maven/**",
    "**/Frontend/**",
    "**/CSV_Aggregator/**",
],
```

**Comment by hanct** [comment] 2020-11-21 17:24
When we say "Java LS scans all root paths", that mean it scans the top-level folders that are added to the workspace. I am ok for it to scan.   But i thought we should not expect it to scan within the CSV_Aggregator/node_modules folder, since the node_modules folder is NOT the root path, and is inside my java.import.exclusions

![image](https://user-images.githubusercontent.com/4410920/99883195-c778d700-2c60-11eb-8513-268d8cd07608.png)

That is y i suspect the java.import.exclusions might not be working as expected

**Comment by snjeza** [comment] 2020-11-21 17:43
Could you attach your csv_bundler/build.gradle and csv_bundler/settings.gradle?

**Comment by hanct** [comment] 2020-11-22 01:20
Attached as request. Change the extension to .log in order to be able to upload

[settings.log](https://github.com/redhat-developer/vscode-java/files/5578746/settings.log)
[build.log](https://github.com/redhat-developer/vscode-java/files/5578747/build.log)

**Comment by snjeza** [comment] 2020-11-22 17:32
> When we say "Java LS scans all root paths", i assume u mean it will scan the top-level folders that are added to the workspace. I am ok for it to scan.   But i thought we should not expect it to scan within the CSV_Aggregator/node_modules folder, since the node_modules folder is NOT the root path, and is inside my java.import.exclusions
![image](https://user-images.githubusercontent.com/4410920/99883195-c778d700-2c60-11eb-8513-268d8cd07608.png)

Your gradle build uses the CSV_Aggregator/node_modules folder. You can check */csv_bundler/apps/main-service/build.gradle and */csv_bundler/apps/main-service/settings.gradle

**Comment by hanct** [comment] 2020-11-23 11:17
> > When we say "Java LS scans all root paths", i assume u mean it will scan the top-level folders that are added to the workspace. I am ok for it to scan.   But i thought we should not expect it to scan within the CSV_Aggregator/node_modules folder, since the node_modules folder is NOT the root path, and is inside my java.import.exclusions
> > ![image](https://user-images.githubusercontent.com/4410920/99883195-c778d700-2c60-11eb-8513-268d8cd07608.png)
> 
> Your gradle build uses the CSV_Aggregator/node_modules folder. You can check */csv_bundler/apps/main-service/build.gradle and */csv_bundler/apps/main-service/settings.gradle

Hi, 
I think that could not be possible. Cos my main-service do not have build.gradle and setings.gradle. It inherit from the root's build.gradle and settings.gradle (which is the one I attached earlier).

![image](https://user-images.githubusercontent.com/4410920/99955576-8ba85380-2dbf-11eb-8815-ec71f1255bd0.png)

**Comment by snjeza** [comment] 2020-11-23 13:03
Could you attach your project?

**Comment by hanct** [comment] 2020-11-23 14:00
I can only attach the backend, not the frontend, as my frontend code are confidential, and my backend has barely started yet. However, even backend i can't attach, as github complain the file is very big.

**Comment by hanct** [comment] 2020-11-23 14:04
I saw another issue titled "java.import.exclusions preference is ignored during server startup" at [https://github.com/redhat-developer/vscode-java/issues/444](url).  The reporter mention thatt java.import.exclusions are actually ignored during import, as the import is initialized. That issue is raised in year 2018, so I wonder if that is the cause of what i observed currently?    But i assume should not be the case, since by now the issue should have not resolved.

**Comment by hanct** [comment] 2020-11-23 14:15
> I can only attach the backend, not the frontend, as my frontend code are confidential, and my backend has barely started yet. However, even backend i can't attach, as github complain the zipped copy is very big.

In my opinion, perhaps u can help to verify by setting up 2 workspace folders at your side, and use java.import.exclusions set to "**" to exclude everything? if doing so, still result in the scanning of the any of the subfolders of the 2 workspace folders. Then the import.java.exclusions is definitely not what is expected.

**Comment by snjeza** [comment] 2020-11-23 15:45
> In my opinion, perhaps u can help to verify by setting up 2 workspace folders at your side, and use java.import.exclusions set to "**" to exclude everything? if doing so, still result in the scanning of the any of the subfolders of the 2 workspace folders. Then the import.java.exclusions is definitely not what is expected.

It works fine for me.

**Comment by hanct** [comment] 2020-11-23 16:12
Noted. Anyway, in 2 days time, i still unable to solve the issue, i will close this issue, since most probably the issue lie in my machine. Thanks snjeza for your patient and help.

**Comment by freelancer1845** [comment] 2020-12-18 10:33
Can you confirm that it's not importing demo-frontend/node_modules in this project?

https://github.com/freelancer1845/vscode-maven-exclude-issue

It does for me:

1. Start after Clean LS -> Resolve Plugin dependencies ... (scans node_modules using absolute path)
2. Start -> Importing maven projects (also scans node_modules)

Maybe its related to how maven finds the parent spring pom?

**Comment by hanct** [comment] 2020-12-19 04:27
> Can you confirm that it's not importing demo-frontend/node_modules in this project?
> 
> https://github.com/freelancer1845/vscode-maven-exclude-issue
> 
> It does for me:
> 
> 1. Start after Clean LS -> Resolve Plugin dependencies ... (scans node_modules using absolute path)
> 2. Start -> Importing maven projects (also scans node_modules)
> 
> Maybe its related to how maven finds the parent spring pom?

Hi, thanks for the reply. I am using Gradle, not maven. To me, it is not about how the maven/gradle find the parent config file, the issue is how come the "java.import.exclusions" seem not in effect for my project.  Even if i exclude everything, the vscode-java still scan the project folders..

**Comment by snjeza** [comment] 2020-12-19 21:16
@hanct @freelancer1845 could you check https://github.com/snjeza/vscode-test/raw/master/java-0.73.1.vsix

@hanct you can also try to set
```
"java.import.maven.enabled": false,,
```

**Comment by hanct** [comment] 2020-12-20 03:34
> @hanct @freelancer1845 could you check https://github.com/snjeza/vscode-test/raw/master/java-0.73.1.vsix
> 
> @hanct you can also try to set
> 
> ```
> "java.import.maven.enabled": false,,
> ```

Hi @snjeza , i have installed the java-0.73.1.vsix. I discovered that unlike earlier threads, this time round, it no longer scan my project's frontend (CSV_Aggregator) folder anymore.  And the initializing is fast. 

The strange thing is, even when i omit "java.import.exclusions" (that is, i dont configure it at all),  it will also NOT scan the frontend folder anymore

**Comment by snjeza** [comment] 2020-12-20 04:17
@hanct Thanks. I will create a PR.

**Comment by freelancer1845** [comment] 2020-12-20 07:49
Same for me :) Worked without resetting the LS and also after resetting.
Also renaming "node_modules" to "node_modulesa" did not break it again.
Seems like you found another way of resolving everything! nice :) Thanks a lot

**Comment by hanct** [comment] 2020-12-20 08:27
> Same for me :) Worked without resetting the LS and also after resetting.
> Also renaming "node_modules" to "node_modulesa" did not break it again.
> Seems like you found another way of resolving everything! nice :) Thanks a lot

@freelancer1845 , have u try removing the java.import.exclusions, also? if removed, did u notice that it also does not scan the node_modules?

**Comment by freelancer1845** [comment] 2020-12-20 09:02
@hanct 
Yes, but I think by default these exclusions are passed to the server.
```
[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]
```
But even renaming node_modules didn't trigger the scanning... 

Without seeing the actual changes by snjeza I suspect that he/she changed what is to be considered a "scanworthy" directory

**Comment by hanct** [comment] 2020-12-24 18:17
@snjeza   Will the updates you make, also resolve the issue that @freelancer1845 face?  Cos he mentions that after renaming node_modules to some other name which is not part of the exclusions, the renamed version did not trigger the scanning, which should not be the case

**Comment by snjeza** [comment] 2020-12-24 21:49
>  Will the updates you make, also resolve the issue that @freelancer1845 face?

Yes, it will.

>  Cos he mentions that after renaming node_modules to some other name which is not part of the exclusions, the renamed version did not trigger the scanning, which should not be the case

I can't reproduce it.

**Closed** 2021-01-12 07:02 UTC

**Comment by chrisawad** [comment] 2022-09-28 19:55
I'm having this exact same issue now. Projects are detected as Maven projects, but the Java Language Server does not honor "java.import.exclusions" in the workspace .vscode/settings.json file and complains about an excluded folder due to permission issue and does not continue scanning.

Firstly, the Java Language Server should probably just skip over folders that it can't access instead of just failing all together, and secondly, it should honor "java.import.exclusions"....

Is there any fix for this available in 2022?
