### ISSUE TITLE
language server too slow & inefficient

### ISSUE THREAD

**Issue by YaduAhuja** [redhat-developer/vscode-java#1549] opened 2020-07-28 10:15 UTC
whenever we try to reference a class or we try to create an object of a class the Intellisense stucks for 5-7 seconds.

Intellisense is inefficient as it does not includes mini templates 
for e.g. when we type List and use Intellisense, it only types List and the angular brackets of generics doesn't type
like in eclipse whenever we type list the intellisense autocompletes as 
List<E>
where the cursor is at E.
![scr eclipse](https://user-images.githubusercontent.com/66440500/88653066-34cc8f00-d0e9-11ea-9013-385780c00c72.png)

**Comment by testforstephen** [comment] 2020-07-28 11:36
Could you share a bit more about your scenario? For example, what kind of project are you working on? How big your project is? Java files number in your project? Also your current Java extension version.

We're looking into the performance too, just want to ensure your scenario is covered.

**Comment by YaduAhuja** [comment] 2020-07-28 11:43
It happens even in single file also.
Here is the code of that file: 

public class test{ 
      public static void main(string[] args){
            List<Integer> list = new Arraylist<>();
            list.add(65);
            list.add(89);
            System.out.println(list);
}

}

Jdk version - 11 ( Oracle Open JDK )
Extension is the latest one
 
PC Details: 
Processor : I3 4005u
Ram : 4 GB
SSD is present 
Windows Version : 1909

**Comment by testforstephen** [comment] 2020-07-28 11:59
Interesting. I didn't observe such performance issue in single file. 

Could you enable the user setting "java.trace.server": "verbose", and click command "Java: Open all log files" to find the client.log file and share to us?

**Comment by YaduAhuja** [comment] 2020-07-28 17:36
Here are the log files
[redhat.java.zip](https://github.com/redhat-developer/vscode-java/files/4990103/redhat.java.zip)

**Comment by fbricon** [comment] 2020-07-28 17:42
Try disabling all Java extensions other than vscode-java

**Comment by YaduAhuja** [comment] 2020-07-28 18:09
I tried disabling all extensions.
It made quite fast (now wait time is from 0.5 sec to 1.5 sec ) but it is still much slower than eclipse intellisense.

Is there any option for activation delay or intellisense delay like there is in eclipse in VSCode.

Please also include snippets for basic things like methods, classes etc.

**Comment by testforstephen** [comment] 2020-07-29 03:04
Have a look at the client.log files, i suppose these log files above are tested with all Java extensions enabled. 

**Facts from the logs:**
- most of `completion` requests are responded within 1s, not 5-7s you declared. However it is an obvious laggy.
- when you're editing the Java file, the triggered LSP requests all are from language server itself (such as `completion`, `completion/resolve`, `provideSemanticToken`, `codeLens`, `codeLens/resolve`, `codeAction`, `foldingRange`) and debugger (`workspaceCommand: resolveMainMethod`). And Java test runner and Java dependency viewer didn't trigger request during editing.

**Possible reasons for the performance:**
- Since the PC's hardware is modest, it seems most requests cost more than 100ms to finish.
- The LSP scheduler in vscode-java has potential limitation. 
Currently it uses a common thread pool ForkJoinPool.commonPool to handle these requests in parallel. And the max parallelism depends on your CPU core. `I3 4005u` should be dual core (4 logical cores), that means the LSP scheduler will use the maximum 3 threads to handle these LSP requests in parallel. As you enable more features, more requests will be triggered when you edit the file. And these requests will complete for the limited 3 threads to run. If the previous requests are not finishing quickly, then the subsequent requests will be queuing there. That's why the lagging happens.

**Current workaround:**
- Turn off the codeLens to reduce the LSP frequency during editing:
  - Turn off the reference codeLens via disabling the user setting `java.referencesCodeLens.enabled`.
  - Turn off the debugger codeLens via disabling the user setting `java.debug.settings.enableRunDebugCodeLens`.

**Comment by YaduAhuja** [comment] 2020-07-29 10:31
These Log files were with Dependency extension, Debugger Extension, Maven Extension disabled. That is why Java test runner and Java dependency viewer did not triggered in the logs. 

**Workarounds I did**:

- Turned off the codeLens.
- Turned off other Extensions.


Now it is pretty fast than earlier.

Extensions affected the most in the intellisense. when I disabled them time to generate suggestions reduced to half.
when I turned off codeLens the vscode didn't ran to not responding (earlier the vscode ran into not responding when editing large files.)

Thanks for help.

Please add some snippets and fix some previous snippets like of list or of methods.

**Comment by joshvanderberg** [comment] 2020-07-30 17:36
After support for JDK 8 was dropped, we were forced to update to JDK 11 and take the latest version of the vscode Java support plugins, and we are experiencing very inconsistent typeahead/code completion performance.  Sometimes fast, sometimes a dozen or more second to suggest a complete variable name or to show a list of methods on a variable.  This was not our experience in previous versions, and it makes this not terribly usable.

We thought it might be because we were running in a container, but no, we can reproduce this running with native java extensions and a local JDK.  I think the container version is a bit slower, but not that much.  Both are mostly unusable.

This is in a relatively large Java/Tomcat project.  But again, we didn't have these performance issues previous to moving to JDK 11.

**Comment by snjeza** [comment] 2020-07-30 21:13
@joshvanderberg could you try to set:

```
"java.semanticHighlighting.enabled": false,
```

**Comment by joshvanderberg** [comment] 2020-07-31 21:40
Even disabling semanticHighlighting it's still slow, but inconsistent.  Sometimes fast, sometimes takes ten seconds or more.

**Comment by snjeza** [comment] 2020-07-31 22:00
@joshvanderberg could you try the following:
```
"vsintellicode.java.completionsEnabled": false,
```
or disable the Visual Studio IntelliCode extension.

**Comment by joshvanderberg** [comment] 2020-07-31 22:02
But the code completion is what's slow, disabling it seems, beside the point?  Am I missing something?

**Comment by snjeza** [comment] 2020-07-31 22:52
It will disable the  Visual Studio IntelliCode completion and enable the Java LS completion.

**Comment by gombosg** [comment] 2020-09-16 08:15
Necrobumb, but disabling IntelliCode sped up Java code completion by at least 3x.

**Comment by hanct** [comment] 2020-11-21 15:58
I agree. The initialization of the workspace is slow...i have to wait for it to finish, before intellisense kick in. Even configuring java.import.exclusions to prevent specific folder from being initialized does not work. I am now thinking of switching back to Eclipse or intellij for java development, which is a sad thing, since i quite like vscode. IDE

**Closed** 2021-04-16 14:48 UTC
Labels: performance

**Comment by cyraid** [comment] 2021-07-06 20:31
Yeah, the one thing stopping me from coming fully to vscode for all my projects is, maven support would be nice.. Fast intellisense (maybe branching support of contextual based typing).. Typing in a parameter should maybe expect variable names and sort them based on relevance.

I'm not sure if you guys do this already but as an optimization tip, when you hit 'a' it shouldn't scan through absolutely everything (an entire list), but through a tree.

**Comment by itsmaheshkariya** [comment] 2021-07-10 20:09
![image](https://user-images.githubusercontent.com/16520789/125175246-749c6180-e1e8-11eb-8f86-e24c91b110a1.png)


I am waiting from last 4 hours to finish this thing, Yesterday it took 2 hours (For fresh spring boot project).

**Comment by hanct** [comment] 2021-07-11 09:17
> Yeah, the one thing stopping me from coming fully to vscode for all my projects is, maven support would be nice.. Fast intellisense (maybe branching support of contextual based typing).. Typing in a parameter should maybe expect variable names and sort them based on relevance.
> 
> I'm not sure if you guys do this already but as an optimization tip, when you hit 'a' it shouldn't scan through absolutely everything (an entire list), but through a tree.

But i thought there are a lot of maven related extension for vscode to support maven?

**Comment by hanct** [comment] 2021-07-11 09:21
> ![image](https://user-images.githubusercontent.com/16520789/125175246-749c6180-e1e8-11eb-8f86-e24c91b110a1.png)
> 
> I am waiting from last 4 hours to finish this thing, Yesterday it took 2 hours (For fresh spring boot project).

So during these hours,  r u actually able to coding concurrenty?

**Comment by cyraid** [comment] 2021-07-11 14:18
> ![image](https://user-images.githubusercontent.com/16520789/125175246-749c6180-e1e8-11eb-8f86-e24c91b110a1.png)
> 
> I am waiting from last 4 hours to finish this thing, Yesterday it took 2 hours (For fresh spring boot project).

Just use intellij for java community for now. It's lightning fast and really good. Hoping java extension for vscode gets to that point.
