### ISSUE TITLE
Does the extension support other JDK?

### ISSUE THREAD

**Issue by Yi-yi** [redhat-developer/vscode-java#480] opened 2018-03-27 12:45 UTC
Hello, recently I need to use JavaFX so I download the Oracle JDK and change the "java.home" to the new directory, however, still get errors reported in Vscode. Does the extension "language support for Java" support Oracle JDK as well?

**Comment by gorkem** [comment] 2018-03-27 22:17
Yes, it does support Oracle JDK. What are the errors?

**Comment by Yi-yi** [comment] 2018-03-28 09:22
Errors are: 

"package javafx.scene does not exist"
"cannot find symbol public void start(Stage primaryStage) throws Exception"
"cannot find symbol Group root = new Group();"

I also use IntelliJ with Oracle JDK, it works well.

**Comment by fbricon** [comment] 2018-04-04 21:36
Can you provide a sample project reproducing this issue?

**Comment by fbricon** [comment] 2020-09-29 17:11
Closing as duplicate of #120

**Closed by fbricon** 2020-09-29 17:11 UTC
Labels: duplicate
