### ISSUE TITLE
save all project related files on the top level vscode folder

### ISSUE THREAD

**Issue by pmlopes** [redhat-developer/vscode-java#478] opened 2018-03-23 17:58 UTC
Vscode Java plugin uses eclipse underneath and suffers from the fact that for each maven module it adds 2 files and a directory:

* .classpath
* .project
* .settings

This is quite annoying as it is usual for plugins to store all their data under a single top level .vscode directory.

**Comment by fbricon** [comment] 2018-04-03 17:50
It's going to be tricky. We depend on the eclipse platform for the Java support. We currently have no way to set project metadata to a custom location. Eclipse Che managed to do it by forking key eclipse plugins, but we probably won't do that. Best case scenario, we get Eclipse upstream to open up project metadata configuration, but even then, we'll most likely end up with one .vscode (or whatever) folder per project/module.

One advantage of keeping the eclipse metadata files as-is, is it allows you to open the same folders in Eclipse, Atom, VIM (with ycm), without adding more IDE/Editor specific stuff.

**Comment by fbricon** [comment] 2019-12-10 13:34
Closing as duplicate of #618

**Closed by fbricon** 2019-12-10 13:34 UTC
Labels: duplicate, enhancement
