### ISSUE TITLE
We also met the below issue 

### ISSUE THREAD

**Issue by zhou-1** [redhat-developer/vscode-java#2945] opened 2023-02-16 11:25 UTC
Environment
Operating System: Windows
JDK version: oracle JDK-11.0.9
Visual Studio Code version: v1.75.0
Plugin version：v1.1.4.0

While using the plugin "Language Support for Java by Red Hat", the output echo below error and CPU load upto 100%; Also, whole IDE is down:
![image](https://user-images.githubusercontent.com/27023540/219351635-74eb8e06-0aa4-4ac1-b2b6-a13b777087d4.png)

Similar issue: https://github.com/redhat-developer/vscode-java/issues/1774

**Comment by jdneo** [comment] 2023-02-22 07:37
@zhou-1 Does this occur in all your projects or some specific ones? Could you share some reproduce steps?

**Comment by rgrunber** [comment] 2024-01-23 19:43
I'm going to mark this as a duplicate of https://github.com/redhat-developer/vscode-java/issues/1976 . The error is not harmful, and is the result of a misunderstanding between client/server over whether a cancellation should be marked as an error. See my comment at https://github.com/redhat-developer/vscode-java/issues/1976#issuecomment-858683678 . I think this needs to be fixed in lsp4j. I can probably have a look eventually. I suspect I left this once I realized the error itself isn't harmful.

**Closed by rgrunber** 2024-01-23 19:43 UTC
Labels: duplicate, need info
