### ISSUE TITLE
Java language support requires Java 8 (using C:\ProgramData\Oracle\Java\javapath\java.exe)

### ISSUE THREAD

**Issue by cryptojonnyboy** [redhat-developer/vscode-java#441] opened 2018-02-14 22:03 UTC
[provide a description of the issue]
Dear community im getting this error messages. How can I solve this?

The java.home variable defined in VS Code settings points to a missing folder
Java language support requires Java 8 (using C:\ProgramData\Oracle\Java\javapath\java.exe)
Thank you in advance.
![java](https://user-images.githubusercontent.com/35565338/36230605-3c86e936-11db-11e8-86c7-10a03dcddcce.JPG)

##### Environment
- Operating System: win 10
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment] 2018-02-14 22:07
Seems like a duplicate of https://github.com/redhat-developer/vscode-java/issues/431#issuecomment-362782640. Make sure you uninstall georgewfraser.vscode-javac

**Comment by cryptojonnyboy** [comment] 2018-02-14 22:28
@fbricon Thank you for you help. The first one got solved . The second one is a little harder for me to solve. 

The java.home variable defined in VS Code settings points to a missing folder

**Comment by fbricon** [comment] 2018-02-14 22:30
make sure java.home points to the java home folder, not java.exe

**Comment by cryptojonnyboy** [comment] 2018-02-14 22:47
Copy pasted this. I still cant star writing codes :(
![java 2](https://user-images.githubusercontent.com/35565338/36232262-5f7cb47e-11e1-11e8-9814-c6a2b2a60425.JPG)

C:/Program Files/Java/jdk1.8.0_131

**Comment by fbricon** [comment] 2018-02-14 23:05
can you try with backslashes? 
`C:\Program Files\Java\jdk1.8.0_131`
or 
`C:\Progra~1\Java\jdk1.8.0_131`

**Comment by cryptojonnyboy** [comment] 2018-02-14 23:15
@fbricon I tried both of them it is quite presistent. Anymore things I can try?

**Comment by snjeza** [comment] 2018-02-14 23:55
Could you try 
```
"java.home": "C:\\Program Files\\Java\\jdk1.8.0_131"
```

**Comment by cryptojonnyboy** [comment] 2018-02-15 00:01
@snjeza @fbricon I installed the software on my other pc with windows 7 its working like charm there so lets hope its stays that way. Well I tried your code and its working @snjeza. Thank you @fbricon and @snjeza.

**Comment by cryptojonnyboy** [comment] 2018-02-15 00:17
@snjeza I tried your code with different pathname since my computer has 32-bit OS and 64-bit and the message does not appear anymore. So I guess its working thank you!

"C:\\Program Files\\Java\\jdk1.8.0_131"

**Comment by fbricon** [comment] 2018-02-15 00:37
@cryptojonnyboy so you made it work on your win10 machine with "C:\Program Files\Java\jdk1.8.0_131"? or were you referring to your win7 pc?

**Comment by cryptojonnyboy** [comment] 2018-02-15 01:11
@fbricon Hello, its working on my windows 10 machine with this code "java.home": "C:\\\Program Files\\\Java\\\jdk1.8.0_131"

**Comment by fbricon** [comment] 2018-02-15 02:09
Ok, I've made the description more helpful, hopefully:

<img width="593" alt="screen shot 2018-02-14 at 9 05 33 pm" src="https://user-images.githubusercontent.com/148698/36237666-45267de6-11cb-11e8-9725-a4fc88bc311d.png">

**Closed by fbricon** 2018-02-15 02:09 UTC

**Comment by cryptojonnyboy** [comment] 2018-02-15 03:34
Haha thank you nice!! @fbricon
