### ISSUE TITLE
Variables in settings not being expanded

### ISSUE THREAD

**Issue by ob** [redhat-developer/vscode-java#1337] opened 2020-03-20 20:55 UTC
If you add [configuration variables](https://code.visualstudio.com/docs/editor/variables-reference) to your settings, they don't seem to get expanded. In my case, I was trying to set:

```
"java.import.gradle.arguments": "-I ${env:HOME}/.gradle/gradle.dynamic-init-script.gradle"
```

Briefly mentioned at the end of #868.

**Comment by testforstephen** [comment] 2020-03-23 03:50
This seems to be a common need for many extensions. It’s better to let VS Code platform to expose the resolveVariable API for extensions to adopt. I already pushed comments to the upstream issue microsoft/vscode#2809, and see how it's going.

**Comment by fbricon** [comment] 2020-03-23 14:43
Closing as duplicate of #806

**Closed by fbricon** 2020-03-23 14:43 UTC
Labels: duplicate
