### ISSUE TITLE
support linked editing

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#2620] opened 2022-08-10 08:10 UTC
when enabling linked editing in vscode I would expect that when editing declarations that references would be renamed.

i.e.

```
String test = "a great string";
test.upper();
```

if editing "test" in second line nothing should change, but if linked editing enable editing "test" in first line to i.e. "mystring" the "test.upper()" should change to "mystring.upper()"

**Comment by fbricon** [comment] 2022-08-10 08:38
linked editing is currently not supported, but you can use F2 to rename 'test' and it'll work as you expect

**Comment by rgrunber** [comment] 2022-08-17 15:03
Closing as a duplicate of https://github.com/eclipse/eclipse.jdt.ls/issues/1919 .

**Closed by rgrunber** 2022-08-17 15:03 UTC
Labels: duplicate, enhancement
