### ISSUE TITLE
Import packages show the wrong result

### ISSUE THREAD

**Issue by pl07** [redhat-developer/vscode-java#1422] opened 2020-04-30 08:28 UTC
##### Environment
- Operating System: Win, Mac, Linux
- Visual Studio Code version: 1.44.2
- Java extension version: 0.61.0

##### Steps To Reproduce
1. New a java file and input `class`, from the completion item list, select the one of the type "Snippet"
2. Before the note, input `import java.util.A` 
![image](https://user-images.githubusercontent.com/46642771/80688895-1a414480-8aff-11ea-88fb-780256e72834.png)

3. Choose one from the list below

##### Current Result
![image](https://user-images.githubusercontent.com/46642771/80688818-fbdb4900-8afe-11ea-9b27-d454dfb7fb93.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/46642771/80689070-596f9580-8aff-11ea-8e76-b36b9fbbd0da.png)

**Comment by fbricon** [comment] 2020-04-30 09:03
That's a strange one, but I can reproduce it too.

**Comment by fbricon** [comment] 2020-04-30 09:11
Looks like it only happens when there are no other imports

**Comment by snjeza** [comment] 2020-05-11 23:15
@fbricon @pl07  Can you reproduce the issue when starting the server with the following property:

```
"java.jdt.ls.vmargs": "-Djava.lsp.joinOnCompletion=true -noverify -Xmx1G -XX:+UseG2GC -XX:+UseStringDeduplication",
```

See https://github.com/eclipse/eclipse.jdt.ls/issues/591
See #512 (comment)

**Comment by pl07** [comment] 2020-05-12 03:05
@snjeza Cannot reproduce when starting server with  `-Djava.lsp.joinOnCompletion=true`

**Comment by Eskibear** [comment] 2020-06-29 12:45
I cannot reproduce with IntelliCode either enabled or disabled. 
```
Version: 1.47.0-insider
Commit: 9bf6af04dcb5c2e531cedca83cd188939ca1b0db
Date: 2020-06-26T21:11:02.609Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0
```

**Comment by v-yuyul** [comment] 2021-10-12 02:57
I can still reproduce in latest 0.83 build

**Comment by jdneo** [comment] 2021-11-17 03:13
Observed an additional textedit that removes several lines when resolving the completion item, and it only happens when there are no other imports in the file.

```
"additionalTextEdits": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 52
                },
                "end": {
                    "line": 4,
                    "character": 0
                }
            },
            "newText": "\r\n\r\n"
        }
    ]
```

**Closed** 2021-12-15 03:38 UTC
Labels: bug, content-assist
