### ISSUE TITLE
Gradle 6.4 wrapper incorrectly marked as potentially malicious

### ISSUE THREAD

**Issue by lptr** [redhat-developer/vscode-java#1492] opened 2020-06-12 07:36 UTC
I'm running VSCode on my macOS Catalina, using an SSH remote to open a Java project on a Windows 10 machine. Upon opening the project (see https://github.com/gradle/native-platform/tree/b8f27b864ff82621cb80e127579c1a75b682be91) I got the following warning pop-up:

![image](https://user-images.githubusercontent.com/495366/84476997-3b18c000-ac8f-11ea-8c73-adb6b5d849b3.png)

The repo at this time uses a wrapper JAR from Gradle 6.4. The SHA256 of the JAR is `70239e6ca1f0d5e3b2808ef6d82390cf9ad58d3a3a0d271677a51d1b89475857`, which matches the officially published one (see https://services.gradle.org/versions/all and https://services.gradle.org/distributions/gradle-6.4-wrapper.jar.sha256).

This means that the JAR should not be flagged, yet it is.

##### Environment

- Operating System: macOS Catalina / Windows 10
- JDK version: OpenJDK 11
- Visual Studio Code version: 1.45.1
- Java extension version: 0.62.0

**Comment by snjeza** [comment] 2020-06-12 15:43
I can't reproduce the issue.
Is there the ~/.tooling/gradle/checksums/gradle-6.4-wrapper.jar.sha256 file on your ssh server?

**Comment by lptr** [comment] 2020-06-12 15:52
Yes:

```text
PS C:\Users\vmadmin\.tooling\gradle\checksums> cat gradle-6.4-wrapper.jar.sha256
70239e6ca1f0d5e3b2808ef6d82390cf9ad58d3a3a0d271677a51d1b89475857
```

**Comment by lptr** [comment] 2020-06-12 15:54
Where do these files come from? Is it possible that they were updated after I got the error?

**Comment by snjeza** [comment] 2020-06-12 16:38
> Where do these files come from? Is it possible that they were updated after I got the error?

Yes. You probably face a connection limit. Could you reproduce the error when starting VS Code again?

**Comment by fbricon** [comment] 2020-07-01 14:54
Should be fixed with https://github.com/eclipse/eclipse.jdt.ls/issues/1486

**Closed by fbricon** 2020-07-01 14:54 UTC
Labels: Gradle, bug
