### ISSUE TITLE
OperationCanceledException

### ISSUE THREAD

**Issue by jtsiros** [redhat-developer/vscode-java#241] opened 2017-06-15 22:38 UTC
I've been consistently experiencing an output dialog message that indicates a problem with codeComplete - OperationCanceledException:

##### Environment
- Operating System: MacOS 10.12.5
- JDK version: 1.8.0_131-b11
- Visual Studio Code version: 1.13.1
- Java extension version: 0.5.0

##### Steps To Reproduce
1. Open Maven project with several packages and classes
2. Write code and see output show OperationCanceledException in output dialog.

I've reinstalled both my visual studio code environment and the plugin and I can't seem to get this Exception to stop.

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Additional Informations

stack trace
`[Error - 3:29:24 PM] Jun 14, 2017 3:43:08 PM Problem with codeComplete for file:///Users/xxx/dev/java/.../controllers/SampleController.java
null
org.eclipse.core.runtime.OperationCanceledException
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.checkCancel(CompletionEngine.java:1819)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.acceptType(CompletionEngine.java:1315)
	at org.eclipse.jdt.internal.core.SearchableEnvironment$4.acceptType(SearchableEnvironment.java:422)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine$5.acceptIndexMatch(BasicSearchEngine.java:1808)
	at org.eclipse.jdt.core.search.SearchPattern.acceptMatch(SearchPattern.java:319)
	at org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(SearchPattern.java:2348)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.findIndexMatches(MatchLocator.java:280)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:109)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.execute(PatternSearchJob.java:65)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:262)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllTypeNames(BasicSearchEngine.java:1816)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:432)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findTypesAndPackages(CompletionEngine.java:10832)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnSingleNameReference(CompletionEngine.java:3451)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:1849)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2075)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:131)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:357)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:345)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:79)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.lambda$0(CompletionHandler.java:39)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by fbricon** [comment] 2017-06-16 05:57
Looks like a duplicate of #213  which should be fixed in 0.6.0.  Please update your version of vscode-java

**Comment by fbricon** [comment] 2017-06-19 19:40
Please reopen if you can reproduce with 0.6.0

**Closed by fbricon** 2017-06-19 19:40 UTC
Labels: duplicate
