### ISSUE TITLE
Autocompletion sometimes not working for method reference

### ISSUE THREAD

**Issue by batraz90** [redhat-developer/vscode-java#1034] opened 2019-08-18 15:06 UTC
### Environment
- Operating System: Windows 10 Build 18362
- JDK version: 12
- Visual Studio Code version: 1.37.1
- Java extension version: 0.47.0

##### Steps To Reproduce
1. Pick a suggested method **by hitting enter** 
2. Try to get a list of suggested method references

##### Current Result
![result](https://user-images.githubusercontent.com/27906867/63226442-d230fa80-c1d9-11e9-9484-570900c756b1.gif)

##### Expected Result
If `forEach(` gets written out manually (without hitting enter on the autocomplete suggestion), autocompletion for method references works.
![expected](https://user-images.githubusercontent.com/27906867/63226444-d52beb00-c1d9-11e9-824b-0269741a577c.gif)

**Comment by snjeza** [comment] 2019-08-27 20:10
I can't reproduce the issue.

**Comment by batraz90** [comment] 2019-08-30 11:23
> 
> 
> I can't reproduce the issue.

Are you running VS Code on Windows?

**Comment by snjeza** [comment] 2019-08-30 15:03
> Are you running VS Code on Windows?

I have tested on Windows and Linux.

**Comment by JoseLion** [comment] 2020-08-11 01:53
I'm having the same issue, however it only happens when it needs to infer the type on some generics. I'm attaching an example which should be easy to reproduce. Hope this helps 🙂 

![vscode-issue](https://user-images.githubusercontent.com/3087228/89848156-76c6ed80-db4b-11ea-9c5b-512d8dfb1955.gif)

**Comment by snjeza** [comment] 2020-08-11 19:55
@JoseLion could you attach a project example?

**Comment by fbricon** [comment] 2020-08-12 13:14
Try disabling the intellicode extension, see if it works better.

**Comment by JoseLion** [comment] 2020-08-18 06:08
@fbricon disabling the intellicode extension didn't worked.
@snjeza currently all my projects are private, but I'll try to set up a playground project to attach it 🙂

**Comment by JoseLion** [comment] 2020-10-24 04:32
@snjeza sorry it's been some time. I created a small repo with an example [here](https://github.com/JoseLion/webflux-playground) 🙂 

Specifically, there's a few blocks of code to run some tests in the file bellow:
https://github.com/JoseLion/webflux-playground/blob/main/src/test/java/com/github/joselion/webfluxplayground/modules/account/AccountTest.java

BTW, since Java 15 is officially released, I've been using the new [Text Blocks feature](https://docs.oracle.com/en/java/javase/15/text-blocks/index.html) and I find a couple of issues:
- Syntax highlight might not be ok (I'm not sure about this 😅)
- The auto-complete feature does not work well after text blocks, it suggests the words from the text block instead of the `String` methods

Would you mind taking a look at those too? I added some code to test in the same [example above](https://github.com/JoseLion/webflux-playground/blob/main/src/test/java/com/github/joselion/webfluxplayground/modules/account/AccountTest.java). Although, I'll be glad to open a separate issue for those if preferable 🙂 

Cheers!

**Comment by JoseLion** [comment] 2020-11-21 20:54
@snjeza @fbricon any news around this issue? To be honest, it has become very difficult to use "method reference" in VSCode as autocomplete breaks in the whole chain once a method reference is used:
```java
return request.bodyToMono(type)
  .map(validator::validate) // <---- After this, autocomplete will not work. After the `;` it works again
  .flatMapMany(Flux::fromIterable)
  .map(this::errorToMessageKey)
  .map(I18n.with(request.exchange())::get)
  .collectList()
  .filter(not(List::isEmpty))
  .flatMap(unprocessableEntity()::bodyValue);
```

I hope this can be fixed soon. Also, I'll be happy to help out if you point me in the right direction. 🙂

**Comment by snjeza** [comment] 2020-11-21 21:54
> The auto-complete feature does not work well after text blocks, it suggests the words from the text block instead of the String methods

@JoseLion You can try 
```
"editor.wordBasedSuggestions": false
```

**Comment by snjeza** [comment] 2020-11-21 22:59
>  I added some code to test in the same example above. 

I can reproduce it in Eclipse. You can create a bug at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by markusroessler** [comment] 2020-11-22 13:18
@JoseLion @batraz90 There's already an open JDT bug report for this issue. You can vote for it here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563020

**Comment by JoseLion** [comment] 2020-11-28 01:40
Thank you @markusroessler! I added my vote to that bug report 🙂

**Comment by JoseLion** [comment] 2020-11-28 01:45
> "editor.wordBasedSuggestions": false

@snjeza I tried the suggested configuration, and the autocomplete does not suggest the words from the text block anymore, but it won't suggest the methods from the String class either 😞

**Comment by JoseLion** [comment] 2021-09-10 23:53
@snjeza @fbricon this seems to be solved now! I think this can be closed, at least from my side 🙂

**Comment by testforstephen** [comment] 2023-02-13 07:35
> @snjeza @fbricon this seems to be solved now! I think this can be closed, at least from my side 🙂

Closing it. Feel free to reopen if this issue is still not solved.

**Closed by testforstephen** 2023-02-13 07:35 UTC
Labels: content-assist
