### ISSUE TITLE
Can not save as utf8

### ISSUE THREAD

**Issue by Yensan** [redhat-developer/vscode-java#405] opened 2018-01-08 07:36 UTC
reported in VScode https://github.com/Microsoft/vscode/issues/40743
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 6.1.7601

Extension|Author (truncated)|Version
---|---|---
java|red|0.16.0

Can not save as utf8. **This is a new issue in 1.19.** 

Steps to Reproduce:

- turn off java plugin, new a file `CharacterTest.java`. Paste code below, then save ---- every thing is OK
```java
public class CharacterTest{ // in comment 注释会乱码呀！！！
    Ascii ascii;
    public void test() {
        System.out.println(" in String 字符串也要乱码！！！66666");
    }
}
```
- turn on java plugin, and don't edit, just `ctrl+s`,  ---- every thing is OK
- hit a key in keybord to insert something in file `CharacterTest.java`, then  `ctrl+s` (that means file changed, VScode will really save it.)  ---- oops, mess code. (even insert a space into file will cause mess code)

**Comment by Yensan** [comment] 2018-01-08 07:39
https://github.com/Microsoft/vscode/issues/40743

**Comment by Yensan** [comment] 2018-01-08 07:45
#394

**Comment by snjeza** [comment] 2018-01-08 14:02
A duplicate of #394

**Closed by snjeza** 2018-01-08 14:02 UTC
