### ISSUE TITLE
Library "Attach Source" has to be done everytime

### ISSUE THREAD

**Issue by Deno123** [redhat-developer/vscode-java#1946] opened 2021-05-13 23:02 UTC
Everytime I open a project I have to attach the src.zip of the JavaFX Libraries again. I can't seem to find an option to attach this src.zip to the libraries permanently.

On this topic I would like to know if it is possible to attach a source to more then 1 .jar file at a time.
I always have to attach the src.zip to javafx.base.jar, javafx.graphics.jar, and so on separately. Is there no way to select it just once?

##### Environment
- Operating System: Windows_NT x64 10.0.19042
- JDK version: 15.0.2.7
- Visual Studio Code version: 1.56.2 (user)
- Java extension version: 0.79.1

**Comment by snjeza** [comment] 2021-05-13 23:40
@Deno123 Could you attach a sample project reproducing the issue?

**Comment by Deno123** [comment] 2021-05-14 02:13
@snjeza 
It happens for every JavaFX Project I create.
I attached a zip with one of my JavaFX project folders and the workspaceStorage folder of this project.
I hope this contains everything you need.
[JavaFXProject.zip](https://github.com/redhat-developer/vscode-java/files/6476076/JavaFXProject.zip)

**Comment by rgrunber** [comment] 2021-05-14 14:34
I'm only able to reproduce this behaviour if I trigger a "Java : Clean Language Server Workspace". The sourcepath entry for the corresponding library only gets persisted in the workspace's .classpath, so if that gets cleaned out, then that would produce what you're seeing. Are you cleaning out the workspace on every re-start/re-opening of the project ? If not then this is a bug, but I'm not able to reproduce.

More generally, this seems similar to #1862 , in that it's also a request to persist manual source attachment logic. This is pretty reasonable for invisible projects. We already have `java.project.referencedLibraries` so what we really need is some basic rule-based mapping format from library to its corresponding source jar. Currently, the only supported functionality is if the library has a `-sources` suffix to the name (and before the extension). So if a library folder containing `foo-1.0.0.jar` also has `foo-1.0.0-sources.jar`, that will be used as the source attachment.

**Comment by Deno123** [comment] 2021-05-14 15:27
@rgrunber as far as I know I’m not cleaning out the workspace on every re-start/re-opening.
I have done a complete reinstall of vs code a few days ago (problem was present even before this) so if that is not a default setting I’m not doing it.

Do you have maybe a suggestion what I could try? 
If it is a bug where is the path to the source file normally saved?

**Comment by rgrunber** [comment] 2021-05-17 14:40
You could try monitoring the content of your workspaceStorage folder corresponding to the project (ie. myFirstJavaFXProject_7f257e5a)  . Specifically, the `.classpath` file. When you attach a source to a class (which corresponds to a particular jar) I would confirm that the `<classpathentry>` (in the .classpath) for the corresponding jar has a "sourcepath" attribute created that points to the source you specified. After restarting VS Code or restarting or re-opening the editor, I would see whether that source disappears.

**Comment by snjeza** [comment] 2021-05-17 15:49
@Deno123 Could you try to use the following .vscode/settings.json:

```
{
    "java.project.referencedLibraries": {
        "include": [
            "lib/**/*.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.base.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.controls.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.fxml.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.graphics.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.media.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.swing.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.web.jar",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx-swt.jar"
        ],
        "sources": {
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.base.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip",
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.controls.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.fxml.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.graphics.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.media.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.swing.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.web.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
            "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\javafx.swt.jar": "c:\\Users\\User\\Documents\\javafx-sdk-16\\lib\\src.zip"
        }
    }
}
```

**Comment by snjeza** [comment] 2021-05-17 16:17
>  @snjeza are you able to reproduce on strictly re-opening the editor/workspace after source is attached (without clearing workspace) ?

@rgrunber No, I'm not. It is reproducible after clearing workspace.

**Comment by Deno123** [comment] 2021-05-18 15:30
> You could try monitoring the content of your workspaceStorage folder corresponding to the project (ie. myFirstJavaFXProject_7f257e5a)

@rgrunber I tried this and when I attach the source it actually appends the sourcepath at the corresponding .jar, like this: 
`<classpathentry kind="lib" path="C:/Users/User/Documents/javafx-sdk-16/lib/javafx.base.jar" sourcepath="c:/Users/User/Documents/javafx-sdk-16/lib/src.zip"/>`.
But after closing and reopening the `.classpath` file is completely reset.
Any change I do or VSCode does to the `.classpath` file are obsolete.
How can I stop VSCode from resetting these files on startup/opening a project?

> @Deno123 Could you try to use the following .vscode/settings.json:

@snjeza this works and seems to not reset on reopening. Thank you.
Seems like I have to copy this part into all my JavaFX projects.

**Comment by snjeza** [comment] 2021-05-18 15:43
> Seems like I have to copy this part into all my JavaFX projects.

@Deno123 you can try to set the java.project.referencedLibraries property in the user's setting.json

**Comment by Deno123** [comment] 2021-05-18 15:55
> @Deno123 you can try to set the java.project.referencedLibraries property in user's settings.json

@snjeza Thank you works perfectly!

**Comment by rgrunber** [comment] 2021-06-08 19:05
Closing as this seems to be addressed. The `sources` mapping of `java.project.referencedLibraries` can set the source lookups.

**Closed by rgrunber** 2021-06-08 19:05 UTC
Labels: enhancement, need info
