### ISSUE TITLE
Intellisense not available in Java projects.. Taking forever "Starting Java Language Server"

### ISSUE THREAD

**Issue by majiccode** [redhat-developer/vscode-java#153] opened 2017-02-09 13:17 UTC
When opening a java source file in a large project the java language server never seems to finish loading causing all intelisense tooltips to just show "loading..."

##### Environment
- Windows 10
- 1.8.0.92
- 1.9.0
- 0.0.9

##### Steps To Reproduce

1. Open a folder housing several reasonably large java projects.
      c:\git-repos
                          \repo1
                          \repo2
                          \repo3
                           ....
   Not all repositories are java but the the majority are.

2. Open a java source file from one of the projects (c:\gitrepos\repo1\src\main\java\com...\SomeJavaFile.Java) and look at the intelisense for anything.
"Loading..." will appear in the tooltip and the status bar you will see "Starting Java Language Server..." I've waited over 30 minutes and still see this with no intelisense available. The projects are not insanely huge. This has worked on a tiny test project outside the folder containing lots of java project repositories,

**Comment by fbricon** [comment] 2017-02-09 14:10
The problem with opening a root folder of many java projects is the Java Language Server (JLS) will open all of them at once.
- How many projects exactly? How many java files/jar dependencies per projects? 
- Using build type: Maven? Gradle? pure Eclipse? 
- can you [take a Thread dump of the JLS java process using jstack](https://dzone.com/articles/how-analyze-java-thread-dumps)?

Some actions that might help:
- You can increase the amount of heap given to the JLS (default is -Xmx1G), by adjusting the `java.jdt.ls.vmargs` parameter in VS Code settings
- Disable reference codelenses by setting `java.referencesCodeLens.enabled` to false

**Comment by fbricon** [comment] 2017-02-09 14:15
@gorkem I think we should probably revisit the way projects are imported on startup. I'm thinking, unless a project is found at the root of the folder, don't try to look deeper. On the 1st file opened, if it doesn't belong to an open project, find the closest pom.xml and lazy load the project

**Comment by fbricon** [comment] 2017-03-31 15:41
@majiccode please try 0.1.0 out. If the problem still persists, please attach [log files](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) here.

**Comment by fbricon** [comment] 2017-04-18 15:15
Closing as duplicate of #162, that seems to be fixed anyway.

**Closed by fbricon** 2017-04-18 15:15 UTC
Labels: bug, need info, performance
