### ISSUE TITLE
auto complete error about "import"

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#1162] opened 2019-11-27 02:26 UTC
Originally reported in https://github.com/microsoft/vscode-java-pack/issues/262

I myself can reproduce it on both Mac & Windows, vscode-java@0.53.1, with IntelliCode disabled. Below is my screenshot and LS log:

![image](https://user-images.githubusercontent.com/2351748/69688119-1c424a00-1100-11ea-87ae-5056f3058dbb.png)

[completion-for-import.log](https://github.com/redhat-developer/vscode-java/files/3894819/completion-for-import.log)

**Comment by akaroml** [comment] 2019-11-29 06:06
This looks like a vscode issue. microsoft/vscode#85741 was created to track this.

**Comment by testforstephen** [comment] 2019-12-03 11:09
See the discussion  https://github.com/microsoft/vscode/issues/85741#issuecomment-561093528 with VS Code team, it turns out the Java LS lazy sets `textEdit` property during `completionItem/resolve` request, this is not the right behavior. Because updating textEdit during resolve will change the ranking and sorting, this is not supported by VS Code. Besides, VS Code has no guarantee that resolve is called at all.

And the [LSP](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion) documentation also mentioned "**properties that are needed for the initial sorting and filtering, like sortText, filterText, insertText, and textEdit must be provided in the textDocument/completion response and must not be changed during resolve.**".

The fix for this issue is to set the textEdit in the `textDocument/completion` request.

// cc: @fbricon

**Comment by fbricon** [comment] 2019-12-03 11:13
yes, this is a discussion we had in https://github.com/eclipse/eclipse.jdt.ls/issues/465. https://github.com/fbricon/eclipse.jdt.ls/commit/0e570a068cd659afc180a155a106bd916053b4e9#commitcomment-36238803 was originally an attempt at fixing it

**Comment by jdneo** [comment] 2022-02-08 07:26
Cannot reproduced with 1.3.0, looks like the issue has been fixed.

**Comment by fbricon** [comment] 2022-02-08 08:07
Please reopen if you still see the issue.

**Closed by fbricon** 2022-02-08 08:07 UTC
