### ISSUE TITLE
Class Path Case sensitive problem

### ISSUE THREAD

**Issue by PSC13** [redhat-developer/vscode-java#717] opened 2018-11-16 02:47 UTC
[provide a description of the issue]

##### Environment
- Operating System: macOS
- JDK version: JDK 11
- Visual Studio Code version: 1.29.1
- Java extension version: 0.15.0

##### Steps To Reproduce
1. [step 1] Install it on a case sensitive macOS. (choose the file system as case sensitive)
2. [step 2] then everything will going wrong.

I am not sure if it is because of this extension, there is a bug on macOS, my macOS is case sensitive, and the Java Support extension fixed the path to be upercase.
So while my class is under Users/my_name/Document/test.java  and so on.
It will try to locate it at USERS/my_name/Document/test.java

and it will report cannot find it.

Hope someone can fix it. 

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Expected Result
Automatically generate the correct path of classes.

**Comment by fbricon** [comment] 2018-12-17 13:35
Closing as duplicate of #238

**Closed by fbricon** 2018-12-17 13:35 UTC
Labels: bug, duplicate
