### ISSUE TITLE
addFinalModifier save action cannot be disabled

### ISSUE THREAD

**Issue by knutae** [redhat-developer/vscode-java#3370] opened 2023-10-30 10:32 UTC
After upgrading to the latest version (1.24.0), final modifiers are added to parameters and variables on save, even though the addFinalModifier has been explicitly omitted from the Java save actions settings.

##### Environment
- Operating System: Ubuntu 22.04
- JDK version: 17.0.9
- Visual Studio Code version: 1.83.1
- Java extension version: 1.24.0

##### Steps To Reproduce
1. Configure Java Save Actions to only contain addOverride. E.g.: `"java.cleanup.actionsOnSave": ["addOverride"]`
2. Edit and save any Java file, and observe that final modifiers are added automatically.

##### Current Result
Final modifiers are added during save, and there does not appear to be a way to disable this.

##### Expected Result
Final modifiers should only be added if the "addFinalModifier" save action is configured.

##### Additional Information
The issue exists both in 1.24.0 and the latest prerelease version. Downgrading the plugin to 1.23.0 fixes the issue.

**Comment by snjeza** [comment] 2023-10-30 15:21
I can't reproduce the issue. Could you check your workspace settings (<your_project>/.vscode/settings.json)?

**Comment by stianeikeland** [comment] 2023-10-30 20:14
I'm experiencing the same issue, on macOS 14, vscode 1.83.1, extension 1.24.0.

Workspace settings contain:
```
"java.cleanup.actionsOnSave": ["addOverride"],
```
Personal settings.json doesn't contain any `java.cleanup` settings.

**Comment by snjeza** [comment] 2023-10-30 23:05
@knutae @stianeikeland could you try to remove the `<your_project>/.settings/org.eclipse.jdt.ui.prefs` file if it exists.

**Comment by knutae** [comment] 2023-10-31 10:02
Yes, removing `.settings/org.eclipse.jdt.ui.prefs` fixes the problem. Investigated a bit further and figured out that flipping `sp_cleanup.make_variable_declarations_final` from `true` to `false` also fixes it.

**Comment by rgrunber** [comment] 2023-10-31 15:14
Seems like this is due to https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2870 . The language server detects the preference constants that would have been supported in Eclipse-land under settings, and opts to include them. @knutae , did you also have `editor_save_participant_org.eclipse.jdt.ui.postsavelistener.cleanup` entry within that `.settings/org.eclipse.jdt.ui.prefs` file ?

It's a bit odd that a user could enable cleanups via. the vscode option, `"java.cleanup.actionsOnSave"` and cleanups not mentioned there get activated because they happen to have a `.settings/org.eclipse.jdt.ui.prefs` file with some cleanups set there. On the other hand, we are just respecting (merging) settings in supported settings files.

**Comment by knutae** [comment] 2023-11-01 11:21
Yes `editor_save_participant_org.eclipse.jdt.ui.postsavelistener.cleanup=true` is also present.

**Comment by rgrunber** [comment] 2023-11-06 14:14
Based on the fact that this is causing, I'll disable it when we detect that JDT-LS is running headless (or when there is no jdt.ui bundle detected)

**Comment by rgrunber** [comment] 2023-11-20 17:33
I think I'll close this for now as the main issue is addressed. There remains a much smaller issue, which is that if `java.cleanup.actionsOnSave` is empty, or not defined at all, then any cleanups defined under `.settings/org.eclipse.jdt.ui.prefs` (assuming `editor_save_participant_org.eclipse.jdt.ui.postsavelistener.cleanup=true`) will get picked up.

This is really a case of the client wanting to take ownership over a setting for all scopes, but a particular project type (eg. Eclipse-style projects) has a way to set those settings at the project-level through another mechanism. I don't think it's too annoying to respect those setting if someone has taken the time to place them in the project.

This reminds me a lot of https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2942 .

**Closed by rgrunber** 2023-11-20 17:33 UTC
Labels: bug
