### ISSUE TITLE
Click the bulbs to Organize imports throws the error

### ISSUE THREAD

**Issue by molly-w** [redhat-developer/vscode-java#1840] opened 2021-03-19 08:26 UTC
Click bulb to organize imports, throw the error: Running the contributed command: '_vscode_delegate_...' failed..
##### Environment
- Operating System: Microsoft Windows [Version 10.0.19041.572]
- JDK version: openjdk version "11.0.8" 2020-07-14
- Visual Studio Code version: 1.54.3
- Java extension version: Java Extension Pack(v0.13.0)

##### Steps To Reproduce
1. Add the following code in Settings.json:
```
"java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
"java.format.settings.profile": "GoogleStyle"
```
2. Press Shift+Alt+O to show the yellow bulb,
3. Click the bulb and choose Organize imports

**Sample code:**
```
import java.awt.Frame;
import java.awt.Label;
class awtLabel {
    public static void main(String[] args) {
        Frame f = new Frame("Label Example");
        Label l1, l2;
        l1 = new Label("First Label");
        l1.setBounds(50, 100, 100, 30);
        l2 = new Label("Second Label");
        l2.setBounds(50, 150, 10, 30);
        f.add(l1);
        f.add(l2);
        f.setSize(400, 400);
        f.setLayout(null);
        f.setVisible(true);
    }
}
```

##### Current Result
click the yellow bulb and choose organize imports, the error occured:
![d](https://user-images.githubusercontent.com/63043224/111750744-8e7b0700-88ce-11eb-84a1-e5df4105fc09.gif)

When i check Log(Extension Host), it showed: `actual command NOT FOUND _vscode_delegate_cmd_kmel0ckh`
![image](https://user-images.githubusercontent.com/63043224/111750863-bbc7b500-88ce-11eb-83c7-8394c7a5af71.png)

##### Expected Result
no error shown
##### Additional Informations
original post: https://stackoverflow.com/questions/66676438/google-style-formatting

**Comment by testforstephen** [comment] 2021-09-08 10:54
This duplicates with the upstream issue https://github.com/microsoft/vscode/issues/132637

It happens when you use the shortcut key to trigger "Organize imports", VS Code will run it, but meanwhile display the menu "Organize imports" in the bulb again. When you click on the menu in the bulbs, it throws error. This can also reproduce with other language such as typescript. It's an upstream VS Code issue.

**Comment by testforstephen** [comment] 2021-09-14 04:05
The upstream issue has been fixed, it will be released in next VS Code version. With the latest fix, no more bulbs show up when you click  shortcut to trigger "Organize imports". This makes sense because the shortcut has already organized the imports of current file.

**Closed by testforstephen** 2021-09-14 04:05 UTC
Labels: bug, upstream
