### ISSUE TITLE
package declaration linting message goes wrong

### ISSUE THREAD

**Issue by luyiming** [redhat-developer/vscode-java#324] opened 2017-10-11 12:18 UTC
![image](https://user-images.githubusercontent.com/15070842/31439819-3b435cc2-aec0-11e7-92ea-8c87848d03c3.png)

It seems to only work when the top folder name is `src`?

![image](https://user-images.githubusercontent.com/15070842/31439884-6d371cfa-aec0-11e7-91c5-f286db3fd23e.png)

I'm new to Java so I can't tell if it is a bug or it has something to do with the language?

##### Environment
- Operating System: Windows 10 Pro
- JDK version:  java version "1.8.0_144"
- Visual Studio Code version: 1.17.0
- Java extension version: 0.11.0

**Comment by yaohaizh** [comment] 2017-10-11 12:44
In the first, try declear package

```java
package A.B;
```

**Comment by fbricon** [comment] 2017-10-11 12:51
I believe this is a duplicate of #274. We seem to have a fix (https://github.com/eclipse/eclipse.jdt.ls/pull/356), but it only works on Linux and Windows, for some reason.

**Comment by luyiming** [comment] 2017-10-11 23:54
@yaohaizh I've tried declaring `package A.B;`,  doesn't work.

**Comment by luyiming** [comment] 2017-10-12 00:09
@fbricon Does the latest version contain that fix? Because I can still reproduce the bug.

## Steps to reproduce:
1. create a folder named `A`
![image](https://user-images.githubusercontent.com/15070842/31472818-77201d62-af23-11e7-8356-e29c8d86d78c.png)

2. right click this folder and select `Open with code`.
![image](https://user-images.githubusercontent.com/15070842/31472851-aad02dbe-af23-11e7-8b19-2c2edf696d84.png)

3. In the vs-code sidebar, click `New Folder`, and name it `B`
![image](https://user-images.githubusercontent.com/15070842/31472737-0ac7dc5e-af23-11e7-8a49-14f707e7e42c.png)

4.  In the vs-code sidebar, click `New File`, and name it `Test.java`
![image](https://user-images.githubusercontent.com/15070842/31472751-1c6cd770-af23-11e7-8576-02415b7f6031.png)

5. In `Test.java`, type `package B;` and the bug appears.
![image](https://user-images.githubusercontent.com/15070842/31472874-cba595f6-af23-11e7-9b17-e5062ef31198.png)

### Interesting things to note: 
If I create the top folder and name it `src` in **Step 1**, then the linting message is right. I've tried some other folder names and folder structures but they all fail.

**Comment by fbricon** [comment] 2017-10-12 19:39
@snjeza can you check eclipse/eclipse.jdt.ls#356 fixes this, at least one Windows/Linux?

**Comment by snjeza** [comment] 2017-10-12 22:27
It does. I have rebased the PR.

**Comment by snjeza** [comment] 2017-10-16 16:04
A duplicate of #274

**Closed by snjeza** 2017-10-16 16:04 UTC
