### ISSUE TITLE
lombok @Singular cause Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failure

### ISSUE THREAD

**Issue by lamplification** [redhat-developer/vscode-java#3561] opened 2024-04-03 21:38 UTC
Lombok @Singular cause Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failed

##### Environment
- Operating System: Ubuntu x86_64 x86_64 x86_64 GNU/Linux
- JDK version: 17
- Visual Studio Code version: 1.87.2
- Java extension version: Language Support  for Java(TM) RedHat 1.29.0

##### Steps To Reproduce
1. create a demo java project
2. create a simple POJO with use of @Singular and @Builder
3. see Problem tab - Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failed - See error log.
![image](https://github.com/redhat-developer/vscode-java/assets/4444408/65158d30-2d7c-4717-b9a9-5154088208f4)

[demo.zip](https://github.com/redhat-developer/vscode-java/files/14858792/demo.zip)

##### Current Result
Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failed - See error log.

##### Expected Result
No issue

##### Additional Informations
Comment @Singular in the Domain.java, everything work as expected.  It is working in Intellij.

**Comment by snjeza** [comment] 2024-04-04 00:54
This is an upstream lombok issue caused by https://github.com/eclipse-jdt/eclipse.jdt.core/commit/cb6774f3ba36fb8dafc3a4834eb22799072db6ef

**Comment by lamplification** [comment] 2024-04-04 19:58
Thank you @snjeza , I rolled back to v1.27.0 for Language Support for Java(TM) by Red Hat. That version is working.

**Comment by sashirestela** [comment] 2024-04-04 21:35
> Thank you @snjeza , I rolled back to v1.27.0 for Language Support for Java(TM) by Red Hat. That version is working.

Rolling back to v1.28.1 is working too.

**Comment by sashirestela** [comment] 2024-04-09 16:09
@snjeza Please, could you tell us if you have any estimated time for a fixing here?

**Comment by snjeza** [comment] 2024-04-09 16:15
@sashirestela This is a lombok issue. You could ask at https://github.com/projectlombok/lombok/issues/3648

**Comment by ekeric13** [comment] 2024-04-25 20:06
how do you rollback a vscode extension version?

**Comment by azriel-healthpoint** [comment] 2024-04-25 20:10
@ekeric13 Click on the drop down next to Uninstall:

<img width="623" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/138735539/9d23c198-b685-49e0-b90a-153e591f27d0">

Then this list appears:

<img width="507" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/138735539/fab158e2-c6c3-41db-af42-678095ef86e6">

Pick the version you want.

I think you have to restart VS code + Clean Java Language Workspace after.

enjoy :v:

**Comment by sashirestela** [comment] 2024-04-25 21:14
Does anyone know if the last version (1.30.0) is fixing the bug?

**Comment by takashi-nakakido** [comment] 2024-04-26 01:09
@sashirestela 
I could not see the bug fix on my PC which has been upgraded (1.30.0).

**Comment by skozitzki** [comment] 2024-05-03 06:15
The same on my machine. No bug fix, neither with version 1.30.0 nor with 1.31.2024050208.

**Comment by matt-locker** [comment] 2024-05-27 06:19
This should be fixed with the current edge release 1.18.33 https://projectlombok.org/download-edge

@fbricon 
Is it possible to upgrade to 1.18.33 until 1.8.34 is released or alternatively downgrade to 1.18.30 again? At least for a snapshot?
https://github.com/projectlombok/lombok/issues/3648#issuecomment-2109050816 

Downgrading is no option for me. If I do so I can't run/debug unit tests with covereage in VS Code anymore...
Only fix I have is to remove @Singular usages in my projects temporarily.

**Comment by ll01** [comment] 2024-05-27 14:37
> @ekeric13 Click on the drop down next to Uninstall:
> <img alt="image" width="623" src="https://private-user-images.githubusercontent.com/138735539/325756197-9d23c198-b685-49e0-b90a-153e591f27d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjA4OTAsIm5iZiI6MTcxNjgyMDU5MCwicGF0aCI6Ii8xMzg3MzU1MzkvMzI1NzU2MTk3LTlkMjNjMTk4LWI2ODUtNDllMC1iOTBhLTE1M2U1OTFmMjdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjNhZDc2NzMyY2YzMzMxYzk1YTdiZDY2NzcxMThmNDYwMzhkODVjOGZiZjg2NTY5YTJlODk0ZTQ3OTg2MDYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DMvigZs-se5Qh2oPtwyk48olt6bTEYm5TzRwYlUZyeM">
> 
> Then this list appears:
> <img alt="image" width="507" src="https://private-user-images.githubusercontent.com/138735539/325756328-fab158e2-c6c3-41db-af42-678095ef86e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjA4OTAsIm5iZiI6MTcxNjgyMDU5MCwicGF0aCI6Ii8xMzg3MzU1MzkvMzI1NzU2MzI4LWZhYjE1OGUyLWM2YzMtNDFkYi1hZjQyLTY3ODA5NWVmODZlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzMwNjRiNTk2MGM4ZjQyMzdlNzFkNzU0NTc4MGEyNDAxZTVkZGM5ZDRlYmQ4OGE0OTM5ZjNhOTEyYzUyYWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q9lYeOnZTx-UKMvL-4ywSgW_xZadB_xgGOU2uXI7YAI">
> 
> Pick the version you want.
> 
> I think you have to restart VS code + Clean Java Language Workspace after.
> 
> enjoy ✌️

when I roll back to that version, none of my tests can be discovered

**Comment by azriel-healthpoint** [comment] 2024-05-27 20:16
If anyone wants to "just get things working", these commands should get you there:

```bash
git clone git@github.com:redhat-developer/vscode-java.git
cd vscode-java
mkdir -p lombok
curl https://projectlombok.org/lombok-edge.jar -o lombok/lombok-1.18.32.jar
npm install -g @vscode/vsce
npm install
npm run build
vsce package
code --install-extension java-1.31.0.vsix # I don't think the version number matters
```

You might have to close vscode first, and/or uninstall the existing redhat vscode-java extension. Note that that will disable some other Java extensions, which you can re-enable by going Cmd Shift X, search for `@disabled`, and re-enable them.

**Comment by daniel-belonio** [comment] 2024-05-29 06:41
> If anyone wants to "just get things working", these commands should get you there:
> 
> ```shell
> git clone git@github.com:redhat-developer/vscode-java.git
> cd vscode-java
> mkdir -p lombok
> curl https://projectlombok.org/lombok-edge.jar -o lombok/lombok-1.18.32.jar
> npm install -g @vscode/vsce
> npm install
> npm run build
> vsce package
> code --install-extension java-1.31.0.vsix # I don't think the version number matters
> ```
> 
> You might have to close vscode first, and/or uninstall the existing redhat vscode-java extension. Note that that will disable some other Java extensions, which you can re-enable by going Cmd Shift X, search for `@disabled`, and re-enable them.
> 
> > when I roll back to that version, none of my tests can be discovered
> 
> Rolling back worked at the time, something changed since then (JDT LSP?). Anyway, using edge lombok and `HEAD` vscode-java plugin is what works currently.

Nice this works, could you use the following curl command, because there is a redirect:
```shell
curl -L https://projectlombok.org/lombok-edge.jar -o lombok/lombok-1.18.32.jar
```
Thanks

**Comment by marco-belonio** [comment] 2024-06-04 06:40
Can it be, that the master is not the branch for releasing? Using the manual steps from @azriel-healthpoint and @daniel-belonio 's improvement works, but the v1.31 doesnt.

> If anyone wants to "just get things working", these commands should get you there:
> 
> ```shell
> git clone git@github.com:redhat-developer/vscode-java.git
> cd vscode-java
> mkdir -p lombok
> curl -L https://projectlombok.org/lombok-edge.jar -o lombok/lombok-1.18.32.jar
> npm install -g @vscode/vsce
> npm install
> npm run build
> vsce package
> code --install-extension java-1.31.0.vsix # I don't think the version number matters
> ```
> 
> You might have to close vscode first, and/or uninstall the existing redhat vscode-java extension. Note that that will disable some other Java extensions, which you can re-enable by going Cmd Shift X, search for `@disabled`, and re-enable them.
> 
> > when I roll back to that version, none of my tests can be discovered
> 
> Rolling back worked at the time, something changed since then (JDT LSP?). Anyway, using edge lombok and `HEAD` vscode-java plugin is what works currently.
> 
> _edit: added `-L` to curl command_

**Comment by marco-belonio** [comment] 2024-06-11 12:00
Missed @daniel-belonio's comment. He already pointed out what the problem indeed is - It's an older lombok version delivered with the extension.

**Comment by marco-belonio** [comment] 2024-06-11 12:11
See https://github.com/redhat-developer/vscode-java/pull/3674 :)

If you agree, please merge it :)

**Comment by rgrunber** [comment] 2024-06-25 19:59
Pre-releases since `v1.32.2024061408` should have included the 1.18.33 edge release which fixed this. It will make our upcoming 1.32 release.

**Closed by rgrunber** 2024-06-25 19:59 UTC
Labels: upstream

**Comment by Kogs** [comment] 2024-06-27 14:14
Can confirm new version 1.32.0 seems to fix the issue. 🚀

**Comment by Kogs** [comment] 2024-08-14 09:27
It seems the problem reappeared in the new 1.33.0 release.

**Comment by rgrunber** [comment] 2024-08-14 15:55
This is being tracked at https://github.com/redhat-developer/vscode-java/issues/3733 .

The upstream issue is https://github.com/projectlombok/lombok/issues/3706 .

**Comment by luccahuguet** [comment] 2024-10-28 16:11
- with `v1.35.1` I had this same bug 
- but downgrading to `v1.32.0` worked for me
- And better yet, downgrading to `v1.34.0` also worked for me
- I am currently using this version of java
```
java --version
openjdk 11.0.25 2024-10-15
OpenJDK Runtime Environment Temurin-11.0.25+9 (build 11.0.25+9)
OpenJDK 64-Bit Server VM Temurin-11.0.25+9 (build 11.0.25+9, mixed mode)
```

**Comment by rgrunber** [comment] 2024-10-28 18:51
Could you try the latest vscode-java from the pre-release stream and see if that resolves the issue ? As far as I can tell, we've been pulling from the latest lombok builds for some time, so if the issue was solved upstream, then it should be there.

**Comment by luccahuguet** [comment] 2024-10-28 19:05
> Could you try the latest vscode-java from the pre-release stream and see if that resolves the issue ? As far as I can tell, we've been pulling from the latest lombok builds for some time, so if the issue was solved upstream, then it should be there.

Ok, I tried it and it didn't work, back to 1.34.0 then

**Comment by rgrunber** [comment] 2024-10-29 17:08
@luccahuguet what's the error that you're seeing ? i just tried the sample project in #3733, and it works just fine. No errors.

**Comment by foxpluto** [comment] 2024-12-04 15:35
Just tested with v1.38.2024120308 and still not working, reverted back to 1.34.0 worked again.

**Comment by rgrunber** [comment] 2024-12-04 16:14
Seems to be working with `v1.38.2024120308` for me. Does language server status bar say you're using the extension's version of Lombok, or the project's version ?

![Image](https://github.com/user-attachments/assets/dd158721-ff80-4692-8a62-3eb25fadbe66)

**Comment by foxpluto** [comment] 2024-12-04 16:28
For me that menu is:

![Image](https://github.com/user-attachments/assets/288a3b8e-c7af-4596-9f3c-09930285634b)

![Image](https://github.com/user-attachments/assets/8edbb918-55f5-47b0-bbd8-bff1f63259d1)

![Image](https://github.com/user-attachments/assets/82f05621-72d3-4ba0-a397-8872f9a4b164)

Unfortunately it doesn't work.
