### ISSUE TITLE
Inconsistent color scheme scopes exported for enum types

### ISSUE THREAD

**Issue by safield** [redhat-developer/vscode-java#1629] opened 2020-09-20 16:22 UTC
Java Extension v0.67
VSCode v1.49.1

I have a enum defined _MyClass.MyEnum_.

Observe the following code examples...

```
MyClass.MyEnum result = MyClass.MyEnum.VAL1;
```
The first instance of the symbol _MyEnum_ on line 1 is exported as scope _storage.type.java_.
The second instance of symbol _MyEnum_ on line 1 is exported as scope _variable.other.object.property.java_.

The expected behaviour would be that both instances would have the same scope of _storage.type.java_.

**Comment by 0dinD** [comment] 2020-09-21 13:11
Yes, the TextMate scopes for Java can be very inconsistent sometimes. They are [provided by VS Code itself](https://github.com/Microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json), which in turn pulls the grammars [from here](https://github.com/atom/language-java). 

I would recommend using semantic highlighting if you want more consistent syntax highlighting. It's enabled by default since version 0.66.0 of this extension, [see this page for more info](https://github.com/redhat-developer/vscode-java/wiki/Semantic-Highlighting). Enums always get the token type `enum`, and their members (constants) get the token type `enumMember`. There are many other token types (and modifiers) provided by this extension, which you can see using the `Developer: Inspect Editor Tokens and Scopes` command.

![enum-token](https://user-images.githubusercontent.com/52179873/93770551-9ce8ae80-fc1c-11ea-90cc-9a56a3cd7684.png)

**Comment by safield** [comment] 2020-09-21 17:08
Hi. Thanks for the informative reply! Semantic highlighting was disabled on my java extension. I might have just toggled it myself in the past during some other long forgotten troubleshooting.

Enabling it provided the proper expected coloring.

**Comment by fbricon** [comment] 2021-09-08 10:49
Closing as this is caused by the upstream textmate grammar and it works properly with semantic highlighting enabled (which is now the default)

**Closed by fbricon** 2021-09-08 10:49 UTC
Labels: upstream, highlighting, out-of-scope
