### ISSUE TITLE
JavaFX not imported

### ISSUE THREAD

**Issue by nihiluis** [redhat-developer/vscode-java#276] opened 2017-08-10 17:36 UTC
I'm using gradle. Gradle build works fine. JavaFX classes are not recognized though. My java.home is correctly set and the same as in IntelliJ IDEA. Do I have to add some external JFX library somehow?

##### Environment
- Operating System: arch linux
- JDK version: Oracle
- Visual Studio Code version: newest
- Java extension version: newest

```
buildscript {
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '8.8.2'
    }
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenLocal()
    mavenCentral()
}

sourceSets {
    main.java.srcDirs = ['src']
    main.resources.srcDirs = ['resources']
}

apply plugin: 'javafx-gradle-plugin'

jfx {
    mainClass = 'x.Main'
    vendor = 'HI'
}

task fatJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'X',
                'Implementation-Version': version,
                'Main-Class': 'x.Main'
    }
    baseName = project.name + '-all'
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
```

**Comment by fbricon** [comment] 2017-08-10 17:47
Have you tried with Eclipse/Buildship?

**Comment by fbricon** [comment] 2017-08-10 17:55
Do you have a sample project to reproduce this issue?

**Comment by nihiluis** [comment] 2017-08-12 16:28
I didn't try Eclipse/Buildship. This is my project: https://github.com/nihiluis/jfx-test-boilerplate

**Comment by fbricon** [comment] 2017-08-24 19:38
So, Java FX is [not guaranteed to be present in all JDK distributions](https://github.com/redhat-developer/vscode-java/issues/120#issuecomment-271395007), that means your project might not build/work against other JDKs.

For now, your best bet is to tell vscode-java/eclipse.jdt.ls to ignore the error, if you're confident it won't be an issue. In order to do that, you can add a `.settings/org.eclipse.jdt.core.prefs` file at the root of your project, containing the line: 
```
org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore
```

**Comment by fbricon** [comment] 2017-08-24 19:38
Closing as duplicate of #120.

**Closed by fbricon** 2017-08-24 19:38 UTC
Labels: duplicate

**Comment by nihiluis** [comment] 2017-08-25 10:37
I got the JDK defined as Oracle in both IntelliJ IDEA and VSCode. I think Oracle distributes JFX. I'll check again eventually.

These warnings don't appear for me. IIRC errors appear, because JFX classes cannot be found. I don't know if both issues are related.

**Comment by tomsontom** [comment] 2018-08-19 14:44
In future (with jdk 11) JavaFX will be shipped as library available from maven central! No JDK will bring by default
