### ISSUE TITLE
Provide support for Java 21

### ISSUE THREAD

**Issue by snjeza** [redhat-developer/vscode-java#3292] opened 2023-09-13 16:17 UTC
The related Eclipse PR - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1325
[Java 21 support](https://www.eclipse.org/lists/jdt-dev/msg02289.html)
[Java 21 Marketplace entry](https://marketplace.eclipse.org/content/java-21-support-eclipse-2023-09-429)

**Comment by brunoborges** [comment] 2023-09-13 21:18
Everything works "fine", but I get this error:

<img width="453" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/129743/f89ee112-16e0-4fc8-a919-128c4196edd4">

**Comment by fbricon** [comment] 2023-09-13 21:37
@brunoborges indeed, that's the point of this ticket, to provide Java-SE 21 support.

**Comment by brunoborges** [comment] 2023-09-13 21:40
I guess my point is that it works (aka it is already "supported"). It just has this annoying alert

**Comment by fbricon** [comment] 2023-09-13 21:43
no it doesn't, you can't compile against Java 21 in vscode-java yet. JavaSE-21 is unknown to JDT

**Comment by robaho** [comment] 2023-10-18 03:16
Why not allow it to use the JDK-21 without preview features? All software has limitations - just don't claim vscode Java plugin has full JDK-21 support. As it is, it doesn't work at all. It says JAVASE-21 is an invalid type.

**Comment by robaho** [comment] 2023-10-18 03:21
I am also not sure how anyone is getting it to work - at least with Gradle builds. Gradle builds fine, but in vscode it either can't find the JDK libraries, or it can't find the gradle referenced libraries. So nothing works.

**Comment by cypher256** [comment] 2023-10-19 04:40
For reference, the following already seem to support Java 21.

Oracle's Java Platform extension for Visual Studio Code
> This allows us to offer VS Code IDE support for new JDK features as soon as they are introduced, even during Early Access of the JDK. To this effect, our VS Code Extension will support the current JDK releases as well as the next upcoming JDK version.
https://inside.java/2023/10/18/announcing-vscode-extension/

**Comment by rgrunber** [comment] 2023-10-19 20:45
@robaho other than Java 21 support, what features do you find work better all around ?

**Comment by robaho** [comment] 2023-10-20 00:40
First, the eclipse compiler fails on many generic constructs that javac deals with fine. 

The creation of pref files, buildship files, project files, classpath files - all which have nothing to do with compiling the project with gradle/maven 

The oracle extension requires a gradle or maven setup - but you can create a trivial gradle file as a replacement of the “unmanaged project” using the redhat extension. 

Tbh though I haven’t tried simply opening an arbitrary Java file for editing/viewing. I expect this wouldn’t work well with the Oracle extension.

**Comment by rgrunber** [comment] 2023-10-20 04:24
> First, the eclipse compiler fails on many generic constructs that javac deals with fine.

I've seen a few of these issues. There are definitely cases where the ECJ compiler may get it wrong, but there's also cases where [javac](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/366#issuecomment-1255337389) [may](https://bugs.eclipse.org/bugs/show_bug.cgi?id=158870#c14) [be](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448793#c25) [wrong](https://bugs.eclipse.org/bugs/show_bug.cgi?id=506016#c0). 

> 
> The creation of pref files, buildship files, project files, classpath files - all which have nothing to do with compiling the project with gradle/maven

Since 1.1.0 (End Nov 2021), project metadata files should not be generated in a project's root folder. See https://github.com/redhat-developer/vscode-java/blob/master/document/_java.metadataFilesGeneration.md .

**Comment by cypher256** [comment] 2023-10-20 07:55
@rgrunber Thank you for all your wonderful contributions.
JEP 12 is marked as "encourage", but is it possible to release it without the preview feature like the official release "Java 21 Support for Eclipse 2023-09"?

> JEP 12: Preview Features
Previewing a feature in the JDK will encourage tool vendors to build good support for the feature before the bulk of Java developers use it in production.

**Comment by robaho** [comment] 2023-10-20 12:41
> @rgrunber Thank you for all your wonderful contributions. JEP 12 is marked as "encourage", but is it possible to release it without the preview feature like the official release "Java 21 Support for Eclipse 2023-09"? It would be helpful if you could release them in stages, not after everything is completed.
> 
> > JEP 12: Preview Features
> > Previewing a feature in the JDK will encourage tool vendors to build good support for the feature before the bulk of Java developers use it in production.

Yes - thank you !

**Comment by mickaelistria** [comment] 2023-10-20 14:24
> a top level gradle file to use actually works better and is easier to understand what is going on.

and what about people who never use gradle, but instead always use Maven?
Any opinionated choice is a risk of disappointing users who have a different opinion.

The fact that vscode-java supports folder without build management file is IMO a great features for most people. They can start coding without bothering about build (which is exactly the trend java is taking with direct launch of Java files, support for unnamed class, JEP proposal to resolve other .java files directly...). Then, as the project scales, build can be added progressively just as user likes it (Maven vs Gradle vs Bazel vs...) and vscode-java would just react to that change.

**Comment by robaho** [comment] 2023-10-20 22:14
If they are using maven then the maven support is already there. 

The unmanaged support is basically doing this with eclipse project structures behind the scenes - no reason the gradle file can’t be hidden as well.

**Comment by mickaelistria** [comment] 2023-10-21 07:48
OK, but then if the gradle file is hidden, what does it change to user whether it exists or not? The Eclipse project structure is sufficient to edit code, what would a hidden Gradle file add?
In any case, I think we're diverging too far from the initial topic (Java 21 support, even if only partial). Please open a separate issue with a user story expliciting the problem; and describing how a hidden gradle file would help in fixing it.

**Comment by anthonyvdotbe** [comment] 2023-10-21 09:16
> > First, the eclipse compiler fails on many generic constructs that javac deals with fine.
> 
> I've seen a few of these issues. There are definitely cases where the ECJ compiler may get it wrong, but there's also cases where [javac](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/366#issuecomment-1255337389) [may](https://bugs.eclipse.org/bugs/show_bug.cgi?id=158870#c14) [be](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448793#c25) [wrong](https://bugs.eclipse.org/bugs/show_bug.cgi?id=506016#c0).

@rgrunber I'd say it's not about whether one or the other edge case compiles or is spec-compliant. It's about the fact that NetBeans' language server is much, much more resilient to errors in the code. 99% of the time, my code has at least 1 error, but that's ok, because 98% of the time, NetBeans is still able to give me code completion, meaningful errors, etc. On the other hand, this language server is very sensitive to errors: even a simple syntax error in method A, like a missing semi-colon, could cause code completion etc. to break down in method B.

And of course there's the fact that NetBeans' language server supports the latest JDKs, even early-access ones. I understand it's incredibly hard to develop an independent compiler implementation like ECJ, especially since the new JDK release cadence, but as a developer I want something that "just works" with the latest & greatest.

@brunoborges Microsoft should really switch the Java language server in its [extension pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) from Red Hat's to [Oracle's](https://marketplace.visualstudio.com/items?itemName=Oracle.oracle-java) (which has existed as [NetBeans'](https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java) for 3 years already). In my experience it has a way, way better editor experience and as mentioned it always supports the latest & greatest JDKs

**Comment by mickaelistria** [comment] 2023-10-21 10:31
> On the other hand, this language server is very sensitive to errors: even a simple syntax error in method A, like a missing semi-colon, could cause code completion etc. to break down in method B.

That's is a surprising statement as JDT parser has always been fault-tolerant (before Javac and NetBeans started to consider it) and thus capable of providing further assistance to such cases.
So that's worth digging deeper: please create a specific issue ticket with steps to reproduce such error. This will then be investigated and potentially fixed.

**Comment by anthonyvdotbe** [comment] 2023-10-21 12:35
> > On the other hand, this language server is very sensitive to errors: even a simple syntax error in method A, like a missing semi-colon, could cause code completion etc. to break down in method B.
> 
> That's is a surprising statement as JDT parser has always been fault-tolerant (before Javac and NetBeans started to consider it) and thus capable of providing further assistance to such cases. So that's worth digging deeper: please create a specific issue ticket with steps to reproduce such error. This will then be investigated and potentially fixed.

Some open issues are #1123 and #1400

**Comment by abceleung** [comment] 2023-10-24 08:06
> Why not allow it to use the JDK-21 without preview features? All software has limitations - just don't claim vscode Java plugin has full JDK-21 support. As it is, it doesn't work at all. It says JAVASE-21 is an invalid type.

Agreed.

Also, it would be nice if the pre-release version in the VSCode extension market is updated to [1.25.1](https://github.com/redhat-developer/vscode-java/pull/3314#issuecomment-1757646782).

**Comment by mickaelistria** [comment] 2023-10-24 08:11
There are some legal concerns that need to be cleared before releasing a subpart of Java 21 support. vscode-java uses Eclipse JDT which implements the Java compilation specification (JLS) and it's not legally clear whether one can release only a subpart of the Java language and still say it's "Java". The term "Java" is a trademark and comes with constraints on its usage, compliance to spec is one of those constraints; we'll soon be discussing with Eclipse Foundation whether supporting only a subset of the spec is fine (so we can just ship whatever we have) or whether it violates the trademark (so we'll have to wait more).

**Comment by aghasemi** [comment] 2023-10-27 07:16
> There are some legal concerns that need to be cleared before releasing a subpart of Java 21 support. vscode-java uses Eclipse JDT which implements the Java compilation specification (JLS) and it's not legally clear whether one can release only a subpart of the Java language and still say it's "Java". The term "Java" is a trademark and comes with constraints on its usage, compliance to spec is one of those constraints; we'll soon be discussing with Eclipse Foundation whether supporting only a subset of the spec is fine (so we can just ship whatever we have) or whether it violates the trademark (so we'll have to wait more).

Thank you for the information. Is there some recent development that has caused this legal concern?

**Comment by mickaelistria** [comment] 2023-10-27 07:52
> Is there some recent development that has caused this legal concern?

The particular case here compared to former Java releases is that until now, Eclipse JDT always managed to release full support for the newer Java version (ie all JEPs supported) at once, so it was Java XY compliant. Here it's not the case, the support for Java 21 in JDT is only partial, so it's not fully Java 21 compliant, and this is per se a legal concern of how to communicate "partial support" without breaking some rules of the Java™.

**Comment by robaho** [comment] 2023-10-30 13:32
Can't you call it a beta and move forward ? :)

**Comment by rgrunber** [comment] 2023-10-31 14:35
@snjeza , we have approval to integrate the existing Java 21 support contributions. Please rebase the PRs, and we can hopefully merge today.

**Comment by snjeza** [comment] 2023-10-31 21:44
@rgrunber I have rebased them.

**Closed** 2023-11-01 00:54 UTC

**Comment by robaho** [comment] 2023-11-05 21:50
Thank you Roland for moving this forward.

**Comment by goyalyashpal** [comment] 2023-11-23 18:12
> Value is not accepted. Valid values: "J2SE-1.5", "JavaSE-1.6", "JavaSE-1.7", "JavaSE-1.8", "JavaSE-9", "JavaSE-10", "JavaSE-11", "JavaSE-12", "JavaSE-13", "JavaSE-14", "JavaSE-15", "JavaSE-16", "JavaSE-17", "JavaSE-18", "JavaSE-19", "JavaSE-20".

```json
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-21",
      "path": "D:/ProgramFiles/Eclipse Adoptium/jdk-21.0.1.12-hotspot/",
      "default": true,
    },
  ],
```

* VSCodium: Version: 1.84.0 (system setup)
Release: 23306
Commit: 695a9146b1347633e608f9f166c81b5b2843b492
* OS: Windows_NT x64 10.0.19045
* `redhat.java`: v1.24.0

**Comment by fbricon** [comment] 2023-11-23 18:16
@goyalyashpal you need to install the pre-release version of vscode-java

**Comment by goyalyashpal** [comment] 2023-11-23 18:27
> pre-release version of vscode-jav

does that contain additional telemetry or data collection etc?

asking as many other tools did that without any special intimation. and the author responded with "you agreed to use beta - it's obvious that it collects data to collect bug reports, ..."

**Comment by fbricon** [comment] 2023-11-23 18:49
There's no special telemetry for pre-releases. 
We're collecting more performance data since last release, but if you disabled telemetry collection (`telemetry.telemetryLevel`:`off` or `redhat.telemetry.enabled`:`false`), we're still abiding by those settings.

**Comment by goyalyashpal** [comment] 2023-11-23 18:55
awesome, thanks a lot. :)

Fred Bricon wrote:
>
> There's no special telemetry for pre-releases.
> We're collecting more performance data since last release, but if you 
> disabled telemetry collection (|telemetry.telemetryLevel|:|off| or 
> |redhat.telemetry.enabled|:|false|), we're still abiding by those 
> settings.Message ID: 
> ***@***.***>
>

**Comment by mickaelistria** [comment] 2023-11-24 15:09
@milic-marko All those pieces of software involved in the development of vscode-java are open-source project. Those have failed to meet the deadline because of not enough contributors were actively developing new Java version support in Eclipse JDT  (because it's actually a lot of not trivial work for a handful of maintainers). So if you want to help making Java support provided faster, please consider contributing to Eclipse JDT in a way or another to help spreading the workload across more maintainers.

**Comment by rubensa** [comment] 2023-11-27 11:36
Any ETA for **v1.25.0**?

Is there any place where we can see the road-map of the project?

**Comment by fbricon** [comment] 2023-11-27 12:12
Thursday, Nov 30th. 
There's about 1 release, at the end of the month, in general

https://github.com/redhat-developer/vscode-java/milestones

**Comment by fbricon** [comment] 2023-11-27 12:21
I want to emphasize this release **will not include Java 21 preview features**, as those have not been added in upstream JDT yet. So, no unnamed classes, nor unnamed variables nor string templates support yet.
The ETA for those is: "when it's done".

**Comment by rubensa** [comment] 2023-11-27 12:36
Thank for the info @fbricon
