### ISSUE TITLE
[high intermittent] Java Build Status does not stop spinning. Java project does not finish loading.

### ISSUE THREAD

**Issue by tigerinus** [redhat-developer/vscode-java#2050] opened 2021-08-01 17:24 UTC
[provide a description of the issue]

##### Environment
- Operating System: Windows 10 - WSL2 - Debian
- JDK version: JDK8 for my project, JDK11 for Language Server.
- Java extension version: v0.80.0

VSCode About:
```
Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

##### Steps To Reproduce
1. Initialize a new Spring Boot project.
2. Load the project in VSCode

##### Current Result
Java project does not finish loading. Java Build Status does not stop spinning:

The output stops at:

```
f3d91492 Configuring java project flight-order-service: 68% Refreshing '/flight-order-service/src/main/java'. [684/1000]
607fa49d Synchronizing projects [Done]
1b378296 Register Watchers [Done]
```

##### Expected Result
It just loads.

**Comment by fbricon** [comment] 2021-08-01 19:00
Closing as duplicate of #2020

**Closed by fbricon** 2021-08-01 19:00 UTC
Labels: duplicate
