### ISSUE TITLE
why this plugin auto change my runtime jdk version 

### ISSUE THREAD

**Issue by lilixom** [redhat-developer/vscode-java#78] opened 2016-10-22 07:57 UTC
I alter jdk to 1.7  
path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7">
but i reopen vscode this plugin auto change my runtime jdk version  like followed
`	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/J2SE-1.5">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>`

**Comment by fbricon** [comment] 2016-10-22 13:40
You're obviously using a maven project, meaning the compilation settings for the project are directed by the pom.xml. By default the pom.xml compilation plugin targets [Java 1.5](https://maven.apache.org/plugins/maven-compiler-plugin/). pom.xml is the truth so the same level is set to the eclipse settings. If you import the same project in Eclipse or perform Maven > Update Project..., you'll see the same results. 

Given that the Java extension for VS Code uses Eclipse under the hood, it follows the same rules (and limitations!). So you need to change the pom.xml [configuration](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html) so that the Eclipse compiler gets the same settings:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.5.1</version>
  <configuration>
    <source>1.7</source>
    <target>1.7</target>
  </configuration>
</plugin>
```

At the moment, you need to close and reopen the folder in VS Code for the settings to be updated.

**Comment by fbricon** [comment] 2016-10-25 12:06
Closing as not a bug

**Closed by fbricon** 2016-10-25 12:06 UTC
Labels: not-a-bug, question
