### ISSUE TITLE
"JavaSE-17" is not accepted.

### ISSUE THREAD

**Issue by NewProgrammer1234** [redhat-developer/vscode-java#2152] opened 2021-10-06 12:01 UTC
##### Environment
- Operating System: Windows 10
- JDK version: 17
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0

##### Steps To Reproduce
1. Install JDK 17
2. open settings.json, and add:
```
"java.configuration.runtimes": [
        {
            "name": "JavaSE-17",
            "path": "path-to-jdk",
        }
    ]
```

##### Current Result
>Value is not accepted. Valid values: "J2SE-1.5", "JavaSE-1.6", "JavaSE-1.7", "JavaSE-1.8", "JavaSE-9", "JavaSE-10", "JavaSE-11", "JavaSE-12", "JavaSE-13", "JavaSE-14", "JavaSE-15", "JavaSE-16".

##### Additional Informations
README.md says that the extension supports code from Java 1.5 to **Java17**

**Comment by fbricon** [comment] 2021-10-06 12:23
Closing as duplicate of https://github.com/redhat-developer/vscode-java/pull/2102 

JavaSE-17 support has been merged in master (hence what you see in the latest readme.md file), but it has not been released to the VS Code marketplace. It'll be officially released in a couple weeks. 
Until then, you can try a CI build from http://download.jboss.org/jbosstools/jdt.ls/staging/. Download the most recent java-<version>.vsix file and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix).

**Closed by fbricon** 2021-10-06 12:23 UTC
