### ISSUE TITLE
Java - Improper warning - Potential null pointer access

### ISSUE THREAD

**Issue by ravindragullapalli** [redhat-developer/vscode-java#3124] opened 2023-05-31 12:36 UTC
In Java, Visual Studio Code is not recognizing "Objects.isNull" check statement while giving warning of Potential null pointer access (Java 536871364).

##### Environment
- Operating System: Kubuntu 22.04 (Linux x64 5.15.0-32-generic)
- JDK version: 1.8
- Visual Studio Code version: 1.78.2
- Java extension version: Language Support for java v1.18.0

##### Steps To Reproduce
For example, if the code is like

```
if (Objects.isNull(obj)){
System.out.println("obj is null");
return null;
}
return obj.toString();// Code is giving warning at this statment.
```
However, if I do this the warning disappears

```
if (obj == null){
System.out.println("obj is null");
return null;
}
return obj.toString();// No warning at this statement.
```
##### Current Result
"Potential null pointer access: The variable obj may be null at this locationJava(536871364)" warning is displayed
##### Expected Result
No warning should be there as null check is already done using `Objects.isNull`

**Comment by snjeza** [comment] 2023-05-31 15:15
@ravindragullapalli I can't reproduce the issue.
Could you attach a project example reproducing the error?

**Comment by ravindragullapalli** [comment] 2023-05-31 18:56
@snjeza Please find the attached file. 

[JavaNullTest.zip](https://github.com/redhat-developer/vscode-java/files/11617908/JavaNullTest.zip)

**Comment by liuhaoXD** [comment] 2023-07-14 02:17
Null check will also get misleading result in Assert.notNull scenary, here is an another example code snippet:

```java
import javax.annotation.Nullable;

@Data
public class Request<T> {
    @Nullable
    private T data;
}

public class PageMonitorConfigController {
    @GetMapping("/xxx")
    public Object doSth (@RequestBody  Request<Sth> req) {
        Assert.notNull(pageableRequest.getData(), "data is null");
        // got 'Potential null pointer access' here ⬇️
        java.lang.System.out.println(pageableRequest.getData().getContent()); 
        return "done";
    }
}
```

AFAK, Intellj idea provides an annotation `@Contract("null -> fail")` for developer to tell static code analyzer annotated method will throw exception when given parameter is null

**Comment by iggycoder** [comment] 2023-09-08 01:51
also with AssertJ:

```java
ResponseEntity<Response> castedResult = (ResponseEntity<Response>)result.getResult();
assertThat(castedResult).isNotNull();
assertThat(castedResult.getStatusCode()).isEqualTo(HttpStatus.OK);
```

`castedResult` in second `assertThat` has warning `Potential null pointer access: The variable castedResult may be null at this location`

**Comment by mcavigelli** [comment] 2024-02-26 08:49
This issue is marked with "upstream".

It seems @snjeza has fixed this issue in the eclipse.jdt.core project in the middle of December 2023, see mentioned issue.

What needs to be done to have this fix in the vscode-java extension?
It would be very useful to have it in our daily work.

**Comment by fbricon** [comment] 2024-02-26 10:47
AFAICT it's already fixed in vscode-java, but the issue was not closed. I can't reproduce the issue with @ravindragullapalli's test project.
@mcavigelli are you still experiencing the problem? In which case you should definitely had a new sample project.

Else I'll close this issue.

**Closed** 2024-02-29 12:10 UTC
Labels: upstream

**Comment by ravindragullapalli** [comment] 2024-03-30 04:57
I can confirm that I am not getting this warning now. Thank you for fixing it.
