### ISSUE TITLE
Add more build tool support!

### ISSUE THREAD

**Issue by leaxoy** [redhat-developer/vscode-java#106] opened 2016-11-26 06:34 UTC
This a great tool, it's so light but powerful. And a lot time it can replace `eclipse` and `intellij idea`.
But now it's only support `maven` and `basic` java project.
Is there any possible add other build tool support, like `gradle`, `ant`, `ivy` and so on. 
In fact, a lot of project use `maven` build. But some are not.(zookeeper for example).

In the mean while, `gradle` became more and more popular among people.`New project`, `android project`, `spring framework` all use `gradle` as build tool.

So add other build tool support maybe great, and earn more users.

**Comment by fbricon** [comment] 2016-11-26 21:24
Closing as duplicate of #10

**Closed** 2016-11-26 21:25 UTC
Labels: duplicate
