### ISSUE TITLE
Some methods can not  be found in auto completion list

### ISSUE THREAD

**Issue by bitray** [redhat-developer/vscode-java#1316] opened 2020-03-05 05:41 UTC
[provide a description of the issue]

##### Environment
- Operating System:10.14.6 (18G3020)
- JDK version:1.8.0_161
- Visual Studio Code version: 1.42.1
- Java extension version:0.57.0

##### Steps To Reproduce
1. [step 1] enter Arrays.sort
2. [step 2] The issue is there

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
The method can not be found in completion list
##### Expected Result
The method should be in the suggestion list
##### Additional Informations
![image](https://user-images.githubusercontent.com/4013037/75951389-e246c800-5ee6-11ea-8a91-af316a4b01d4.png)

**Comment by fbricon** [comment] 2020-03-05 08:56
Closing as duplicate of #1257

**Closed by fbricon** 2020-03-05 08:56 UTC
Labels: duplicate
