### ISSUE TITLE
Hide build files

### ISSUE THREAD

**Issue by agolomoodysaada** [redhat-developer/vscode-java#1076] opened 2019-09-23 15:54 UTC
Every time I open a java project, I end up with the following file changes. Am I expected to update the gitignore of every new project with the below paths?

```sh
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.classpath
	.project
	.settings/
	bin/
```

##### Environment
- Operating System: macOS
- JDK version: 11
- Visual Studio Code version: 1.38.1
- Java extension version: 0.49.0

##### Steps To Reproduce
1. Install extension
2. Open java project
3. Run `git status`

##### Current Result

```sh
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.classpath
	.project
	.settings/
	bin/
```

##### Expected Result

```sh
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by fbricon** [comment] 2019-09-27 13:12
> Every time I open a java project, I end up with the following file changes. Am I expected to update the gitignore of every new project with the below paths?

for now, yes. In the future, we might automatically add those settings to .gitignore, if we detect this is a git project.

**Comment by agolomoodysaada** [comment] 2019-09-27 15:29
Is there anyway this metadata can be moved out to say a `/tmp` directory?

**Comment by fbricon** [comment] 2019-10-02 09:28
no it's not possible. Those files are created by an headless eclipse process, we can't change its behavior.

**Comment by fbricon** [comment] 2019-12-10 13:31
closing as duplicate of #618

**Closed by fbricon** 2019-12-10 13:31 UTC
Labels: duplicate
