### ISSUE TITLE
Hi. Can someone tell me how to import a library in VScode?

### ISSUE THREAD

**Issue by vincent1147** [redhat-developer/vscode-java#384] opened 2017-12-05 13:38 UTC
I just switched to VS Code from IntelliJ. 

But I couldn't figure out how to import a jar in VSCode? I'm using it as a library.  

I have some libraries, for example, Junit.

Operating System: Mac Sierra
JDK version: 1.8.0_131

Thank you.

**Comment by gorkem** [comment] 2017-12-05 22:03
Duplicate of  #346

**Closed by gorkem** 2017-12-05 22:03 UTC
Labels: duplicate, question

**Comment by fbricon** [comment] 2017-12-05 22:06
See https://github.com/redhat-developer/vscode-java/issues/346#issuecomment-346698654

**Comment by vincent1147** [comment] 2017-12-06 00:18
Hi. I'm confused.  So what I need is a .classpath. But it's not an Eclipse project.

Is there a way to generate .classpath file? or I have to manually create one?

**Comment by fbricon** [comment] 2017-12-06 00:23
Try https://www.jetbrains.com/help/idea/exporting-an-intellij-idea-project-to-eclipse.html

**Comment by vincent1147** [comment] 2017-12-06 00:52
Hi fbricon,

Thanks for the quick reply. 
I just tried to manually create .classpath file. It didn't work. 
The link isn't answering my question.

So for example, I've just created a .java file in VSCode. 
Now I want to import an external library. So I can have this line of code working: **import org.junit.Test;**

I kind of feel this is a silly question. But I just can't figure out how to make it work. 

Thank you for your help. :)

**Comment by vincent1147** [comment] 2017-12-06 01:33
So if I understand this right, I need .project and .classpath to make it work.

**Comment by fbricon** [comment] 2017-12-06 02:33
yes, both are required. Please check https://github.com/redhat-developer/vscode-java/files/1500211/test_vs_code2.zip  see how the jar needs to be referenced in .classpath.

Using a Maven or Gradle project can be very simple to get started, instead of aiming for the Eclipse route. And it'll make your project IDE agnostic.

**Comment by vincent1147** [comment] 2017-12-07 01:33
Cool!! Thanks for the example code. It works. Basically, all I need is to start a project in Eclipse. I will try Maven tomorrow. It is so weird that VS Code supports Eclipse, Maven, and Gradle, but IntelliJ is not included. 

I have one more question. The Junit still doesn't work in VS Code. Other libraries are fine.
I have Java Test Runner installed. But when I click Run Test, it shows this (below in the photo). But the same project works fine in Eclipse. 

Do you have any idea how to fix it?

![screen shot 2017-12-07 at 1 59 11 am](https://user-images.githubusercontent.com/26737365/33694086-71ff5baa-daf6-11e7-8b6f-f6d6f8416b7f.png)

**Comment by FabianoTerdenge** [comment] 2018-11-29 10:12
and do you use the .jar in visual studio code ?

**Comment by lispercat** [comment] 2021-02-03 16:00
Is it still the same manual process now (to update .classpath file)?
