### ISSUE TITLE
Add extract inteface from class

### ISSUE THREAD

**Issue by itaygoz** [redhat-developer/vscode-java#2382] opened 2022-03-27 11:13 UTC
Hi, can you please make an auto-generated interface from an existing class like "Extract interface" in Eclipse?

##### Current Result
No such button

##### Expected Result
![image](https://user-images.githubusercontent.com/48314049/160278797-fba0293a-076c-4e91-8883-1f3ae16a8e7f.png)

**Comment by rgrunber** [comment] 2022-03-28 14:08
This is definitely a very requested feature so hopefully we get around to it (See https://github.com/redhat-developer/vscode-java/issues/761). It has come up as something to investigate and at least certain parts should be able to rely on the same utilities/classes that Eclipse JDT uses.

I'll close this for now as a duplicate of that one. I would add thumbs up on the main comment of the bug mentioned so we can keep track of demand.

**Closed by rgrunber** 2022-03-28 14:08 UTC
Labels: duplicate
