### ISSUE TITLE
Go to Definition (F12) opens the .class file, not .java from sources

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#786] opened 2019-02-07 13:33 UTC
[demo.zip](https://github.com/redhat-developer/vscode-java/files/2841017/demo.zip)
Why Go to Definition (F12) opens the .class file, not .java from sources

##### Environment
- Operating System: mac os
- JDK version: 1.8
- Visual Studio Code version: 1.32.0-insider
- Java extension version: 0.38.0
- Gradle + any dependencies

##### Steps To Reproduce
1. download any project template http://start.spring.io
2. try to Go to Definition (F12) into any class or method, decompilled .class you see

I saw tips like adding special plugin for eclipse, then 
eclipse {
    classpath {
        downloadJavadoc = true
        downloadSources = true
    }
}

to download sources, but 1) it is still no effect 2) I'm comparing with intellij idea, that doing it in background without any strange modifications. 

Can vscode plugin do something like that?

**Comment by fbricon** [comment] 2019-02-07 14:39
Works for me, once the server finished starting. Have you tried reopening vscode? Do you see anything in the [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs)? Try cleaning the Java server's [workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)

**Comment by jnesspro** [comment] 2019-02-07 15:26
Hi, thanks for a logs and clean ws dir tips. I did it and and see this
<img width="566" alt="screenshot 2019-02-07 at 17 50 40" src="https://user-images.githubusercontent.com/5245360/52421557-56a51100-2b05-11e9-82eb-57ecccd40975.png">

This is a source with docs, good. But tab's name still .class. I don't really know if workspace cleaning up did something or I have been confused this tab's name from the beginning. I used to see .class tabs when source code is not available.

false alarm, huh. 
Thanks for your work and help

**Comment by fbricon** [comment] 2019-02-08 16:10
The *.class indicates this comes from a binary. We automatically map the source contents to that class file, when possible, else a default source stub is generated (or you could use a [decompiler](https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler) instead).

Closing this issue, as it works as designed.

**Closed by fbricon** 2019-02-08 16:10 UTC
Labels: Gradle, bug
