### ISSUE TITLE
Cannot see the full method signature on the code complete dropdown box

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#375] opened 2017-11-23 08:13 UTC
When editing code, the extension will show the possible methods in dropdown box. But for long method, there is no way to see the full method signature.

![image](https://user-images.githubusercontent.com/14052197/33163235-7357965e-d068-11e7-86de-b850ff91fb9d.png)

See the screenshot, the left part doesn't have scroll bar and any tooltip [on hover] to show the full information.

**Comment by fbricon** [comment] 2017-11-23 13:48
Duplicate of #249. See upstream's issue: https://github.com/Microsoft/vscode/issues/29757

**Closed by fbricon** 2017-11-23 13:48 UTC
