### ISSUE TITLE
It keeps loading while first time to open dubbo/maven projects with VSCode in standard mode

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2023] opened 2021-07-14 07:13 UTC
First time to open dubbo and maven projects with VS Code in standard mode, it keeps loading.

##### Environment
- Operating System: Mac 10.14 / Windows 10
- JDK version: 11.0.7
- Visual Studio Code version: 1.57.1
- Java extension version:
![image](https://user-images.githubusercontent.com/31497677/125576987-6d5ab788-acc8-438c-9828-8129cb2759bc.png)

##### Steps To Reproduce
1. Clone the projects below and open it with VSCode in standard mode

 - Dubbo - https://github.com/apache/dubbo/tree/dubbo-2.7.7
 - Sprint Boot (maven) - https://github.com/spring-projects/spring-boot/tree/v2.2.8.RELEASE

##### Current Result
Maven project: the status keeps loading at %66
![image](https://user-images.githubusercontent.com/31497677/125579020-f8846b5e-7dd3-4b2f-b1c3-c84f66c57154.png)

Dubbo project: the status keeps loading at %44
![image](https://user-images.githubusercontent.com/31497677/125577815-71cc711f-4cce-4563-94dd-04645294601c.png)

##### Additional Informations

**Comment by snjeza** [comment] 2021-07-14 20:34
A duplicate of #2020

**Closed by snjeza** 2021-07-14 20:34 UTC

**Comment by snjeza** [comment] 2021-07-15 00:53
@v-yuyul You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712
