### ISSUE TITLE
class with a number in its class name seems to make a bug when referenced

### ISSUE THREAD

**Issue by ColinTree** [redhat-developer/vscode-java#325] opened 2017-10-11 17:37 UTC
class with a number in its class name seems to make a bug when referenced

##### Environment
- Operating System: Windows 10
- JDK version: 1.7.0_79
- Visual Studio Code version: 1.17.1
- Java extension version: 0.11.0

##### Steps To Reproduce
1. create a class named with number like "My3DView", close the file.
2. create a class in another file and reference it.
3. set up .classpath
4. the error noticed in the second class if the first class is not opened.

![image](https://user-images.githubusercontent.com/22613139/31456574-c741ea5a-aeec-11e7-92c8-8cb2f1daed38.png)
![image](https://user-images.githubusercontent.com/22613139/31456601-dcd17db8-aeec-11e7-87ce-bed6bb2d2b51.png)

**Comment by fbricon** [comment] 2017-10-12 01:47
You don't seem to be using Maven or Gradle to build your project. What/How did you configure your classpath?
Do you have a sample project to reproduce this issue?

**Comment by snjeza** [comment] 2017-12-06 22:31
A duplicate of #380

**Closed by snjeza** 2017-12-06 22:31 UTC
Labels: need info
