### ISSUE TITLE
Gradle using Java 8 - Any gradle build script error returns as a StreamCorruptedException with no useful content instead of the actual gradle exception

### ISSUE THREAD

**Issue by jakegt1** [redhat-developer/vscode-java#1594] opened 2020-08-26 13:52 UTC
When using Gradle with java.configuration.runtimes set to a JavaSE-1.8 JVM, any problems in a build.gradle script will come up with a java.io.StreamCorruptedException instead of the actual exception.

This can be very painful to debug, because it might happen that when executing gradle manually via command line, you might find that the build itself will go through with one of the default targets, but if one of the sub projects is executed it will throw an error.

##### Environment
- Operating System: Centos 7
- JDK version: 1.8.0b252
- Visual Studio Code version: 1.48.1
- Java extension version: 0.65.0

##### Steps To Reproduce
1. Write a gradle script with any sort of gradle parsing error
2. See problems menu that only describes the error as
```Could not run build action using Gradle distribution '(gradle distro)'.
java.io.StreamCorruptedException: invalid type code: 00
invalid type code: 00
```

Example script:
```gradle
this is just random text in a build.gradle
```

##### Current Result
Returns blank exception

##### Expected Result
* What went wrong:
Could not compile build file 'build.gradle'.
> startup failed:
  build file 'build.gradle': 1: unexpected token: in @ line 1, column 26.
     this is just random text in a build.gradle

**Comment by fbricon** [comment] 2020-08-26 14:07
which version of gradle are you using? can you attach a sample project?

**Comment by snjeza** [comment] 2020-08-26 14:18
@jakegt1 See https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-673747392

**Comment by fbricon** [comment] 2020-08-26 14:28
See https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#my-gradle-version-does-not-support-java-11

**Comment by fbricon** [comment] 2020-08-26 14:31
The JavaSE-8 runtime is used for compiling your Java code, but, by default the Gradle Daemon uses the jdt.ls JVM to run (so 11+). `java.import.gradle.java.home` allows you to run the daemon with a different JVM, but it requires Gradle 4.7 minimum.

**Comment by jakegt1** [comment] 2020-08-27 09:20
I am using Gradle 5.1.
There is no need for a sample project, it reproduces with a build.gradle with any syntax error.

My settings:

```
{
    "java.configuration.runtimes": [
        {
          "name": "JavaSE-1.8",
          "path": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64",
          "default": true
        },
        {
          "name": "JavaSE-11",
          "path": "/scratch/jtorranc/jdk11-0.4",
        }
    ],
    "java.home": "/scratch/jtorranc/jdk11-0.4",
}
}
```
To note, if there is no syntax error things work as expected - i can debug, i get import suggestions etc. It's just that if i do have a syntax error,

My `java.home` property is JDK 11, whereas the JDK chosen in `java.configuration.runtimes` is JDK 8 by default.

**Comment by fbricon** [comment] 2020-08-27 10:08
Ok I see now. Invalid build.gradle errors don't bubble up as diagnostics. Buildship reports it properly, so we must be something wrong:

<img width="721" alt="Screen Shot 2020-08-27 at 12 07 25 PM" src="https://user-images.githubusercontent.com/148698/91427268-f1874c80-e85d-11ea-8352-8fd13867d1bd.png">

**Comment by snjeza** [comment] 2020-10-12 17:41
> Ok I see now. Invalid build.gradle errors don't bubble up as diagnostics. Buildship reports it properly, so we must be something wrong:

I can't reproduce the issue. 
@fbricon @jakegt1 Could you attach a project example?

![gradle](https://user-images.githubusercontent.com/388609/95775187-3c500d00-0cc2-11eb-8b83-682ebe036773.png)

**Comment by jakegt1** [comment] 2020-11-17 10:41
@fbricon 

There was an example build.gradle, just simply have a build.gradle with no content.

but i'm a bit confused? Your picture there seems like you have reproduced it. That is the bug.

**Comment by jakegt1** [comment] 2021-01-22 15:28
@snjeza Still having this issue. I am still very confused by you saying that you couldn't reproduce the issue despite your screenshot being an exact reproduction of the issue?

Just really frustrating as i have no idea what the actual error is, so i cannot fix it.

**Comment by snjeza** [comment] 2021-01-22 19:51
@jakegt1 
> Still having this issue. I am still very confused by you saying that you couldn't reproduce the issue despite your screenshot being an exact reproduction of the issue?

I can't reproduce this issue:
> Ok I see now. Invalid build.gradle errors don't bubble up as diagnostics. Buildship reports it properly, so we must be something wrong:

Java LS reports the gradle errors properly.
What you expect?

**Comment by jakegt1** [comment] 2021-02-01 11:13
Your screenshot reproduces the error i was talking about. `Java.io.StreamCorruptedException: invalid type code 00` is not a gradle error.

This is the error in Java 11:
![image](https://user-images.githubusercontent.com/6144562/106451214-24251900-647e-11eb-9b20-13ad60994e46.png)

In comparison to Java 8:
![image](https://user-images.githubusercontent.com/6144562/106451460-854cec80-647e-11eb-9598-834d69fae32e.png)

Hope that makes sense now @snjeza.

**Comment by jakegt1** [comment] 2021-02-17 15:29
This is still making development in java 8 a pain, does the above example make sense now?

**Comment by snjeza** [comment] 2021-02-17 18:43
@jakegt1 The errors have been generated by the [buildship](https://github.com/eclipse/buildship) project. The issue can be reproduced in Eclipse.

**Comment by jakegt1** [comment] 2021-02-24 14:06
@snjeza so, you're suggesting it is a downstream problem and i should make an issue there? Your comments seem to be directly opposite to what @fbricon said, so i am very confused.

**Comment by CsCherrYY** [comment] 2022-04-20 02:10
@jakegt1 It's a Gradle issue, which has been addressed in https://github.com/gradle/gradle/pull/17397, and the milestone is 7.2RC, so you can upgrade your wrapper version to greater than 7.2 and this issue will disappear. 

I just tried in Gradle 7.3 and the error message can show properly, regardless of the JVM version (8 or 11 or later). Could you try it again?

**Closed** 2022-05-25 08:22 UTC
Labels: bug, Gradle, diagnostics
