### ISSUE TITLE
Completion list is too narrow for package name

### ISSUE THREAD

**Issue by Yanpas** [redhat-developer/vscode-java#922] opened 2019-05-14 14:26 UTC
##### Environment
- Operating System: linux
- JDK version: 11
- Visual Studio Code version: 1.33.1
- Java extension version: 0.44

Preamble:
Hadoop has 2 sets of APIs - old and deprecated org.apache.hadoop.mapred and new org.apache.hadoop.mapreduce. When you type some class name java suggests you classes from both packages and you can only see first symbols of both packages. So you can't know which is which.

Steps to Reproduce:

1. Enter some java class
2. Full package name isn't placed

with "More" on:
![image](https://user-images.githubusercontent.com/7345761/57705209-1907d500-766c-11e9-8bd7-913606a3c323.png)
with "More" off:
![image](https://user-images.githubusercontent.com/7345761/57705636-ead6c500-766c-11e9-9cb3-d57d354b4c4d.png)

Way to **fix**: always show full class name in "More" section.

**Comment by fbricon** [comment] 2019-05-14 14:27
Closing as duplicate of #249.

**Closed by fbricon** 2019-05-14 14:27 UTC
Labels: duplicate
