### ISSUE TITLE
The same name class exist in the same package, but "type is already defined" error will auto disappear

### ISSUE THREAD

**Issue by hhkrob1** [redhat-developer/vscode-java#2327] opened 2022-02-22 01:24 UTC
[provide a description of the issue]

##### Environment
- Operating System: Windows 11
- JDK version: OpenJDK 17 and JDK1.8
- Visual Studio Code version: 1.64.2
- Java extension version: 1.3.0

##### Steps To Reproduce
1. When the same name class exist in the same package, click run in codelen, compile will not pass, problem pannel will display "type is already defined" error,  click this navigation to related code line, the error(Red wavy line) auto disappear and never show again. but it is a error,  it will be always warnning.
2. Related gif:
![javabug1](https://user-images.githubusercontent.com/68175970/155046277-426f5189-6cff-4b6b-ae36-2c7b9302f276.gif)

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
 When the same name class exist in the same package, it is a error,  it will be always warnning, navigation to relative code line, the error auto disappear and never show again until reopen VScode next time.
##### Expected Result
 When the same name class exist in the same package, it is a error,  it will be always warnning.

**Comment by cworld1** [comment] 2023-07-09 14:24
Same problem.

**Comment by rgrunber** [comment] 2024-04-12 17:53
I just noticed this is a duplicate of https://github.com/redhat-developer/vscode-java/issues/1111. I explain what's happening at https://github.com/redhat-developer/vscode-java/issues/1111#issuecomment-1900674260  (and the previous comment). The way we collect diagnostics has a risk of hiding diagnostics at the file-level that can only be reported through a full compilation.

There may be a few ways to avoid this happening.

**Closed by rgrunber** 2024-04-12 17:53 UTC
Labels: duplicate, diagnostics
