### ISSUE TITLE
Unable to find JDK 8, it exists, eclipse has no issue, path is correct

### ISSUE THREAD

**Issue by Coderah** [redhat-developer/vscode-java#157] opened 2017-02-24 11:08 UTC
I've explicitly set `"java.home": "/usr/lib/jvm/java-8-openjdk-amd64"` however the JAVA_HOME env variable is also set to exactly that (the result is the same regardless), eclipse has no issue with this, however the extension reports "The java.home variable defined in VS Code settings does not point to a JDK."

##### Environment
- Operating System: Ubuntu 15.04
- JDK version: OpenJDK 8
- Visual Studio Code version: 1.9.1
- Java extension version: 0.0.10

##### Current Result
JDK 8 is not found

##### Expected Result
JDK 8 is found

**Comment by gorkem** [comment] 2017-02-27 15:20
I can confirm that setting `java.home` on the vscode settings is breaking the server.

**Comment by gorkem** [comment] 2017-02-27 16:05
Spoke too soon. I had a typo on the `java.home` setting. It seems to be working fine for me on ubuntu 16.04.

**Comment by AriHrannar** [comment] 2017-03-07 08:01
I have exactly the same issue on 

- OS: Ubuntu 16.04
- JDK version: OpenJDK 8
-  VSC version: 1.10.1
- Java extension version: 0.0.11

**Comment by fbricon** [comment] 2017-03-31 15:25
@Coderah @AriHrannar please give 0.1.0 a try, and if the problem still persists, open the [VS Code Developer Tools](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-vscode-java-logs) to see why the extension fails to start.

**Comment by fbricon** [comment] 2017-04-18 15:17
ping @Coderah @AriHrannar ^^

**Comment by AriHrannar** [comment] 2017-04-19 07:44
@fbricon its fixed for me in the newest version of the extension (0.1.0) :) thank you!

**Comment by attiand** [comment] 2018-03-22 20:06
I created a super simple vscode extension and imported `path-exists` and added the following 
```javascript
let javaHome = process.env['JAVA_HOME'];
console.log(`JAVA_HOME: ${javaHome}`);
console.log('pathExists: ' + pathExists.sync(javaHome));
```
When activate the extension I get 
```
JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64
extension.js:19
pathExists: false
```
Even  though the path exist
```
ls -1 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64
bin
include
jre
lib
tapset
```
- Fedora release 27
- VS Code 1.21.1

**Comment by fbricon** [comment] 2018-03-22 20:25
@attiand can you put a breakpoint in node_modules/path-exists/index.jsL15 and see why it fails?

**Comment by snjeza** [comment] 2018-03-22 21:00
@attiand can you try the following:

```
"java.home": "/usr/lib/jvm/java-1.8.0-openjdk/"
```

or
```
"java.home": "/usr/lib/jvm/java-1.8.0/"
```

**Comment by attiand** [comment] 2018-03-23 05:55
@fbricon the exception is:
```
Error: ENOENT: no such file or directory, access '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64'
code: "ENOENT"
errno: -2
message: "ENOENT: no such file or directory, access '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64'"
path: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64"
```

I added the following
```javascript
        let javaHome = process.env['JAVA_HOME'];
        console.log(`JAVA_HOME: ${javaHome}`);
        console.log('pathExists: ' + pathExists.sync(javaHome));
        console.log('pathExists - 2: ' + pathExists.sync('/usr/lib/jvm/java-1.8.0-openjdk/'));
        console.log('pathExists - 3: ' + pathExists.sync('/usr/lib/jvm/'));
        console.log('pathExists - 4: ' + pathExists.sync('/home/mattias/'));      
```
which prints (note the last line which I have drwx------ access to): 
```
JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64
pathExists: false
pathExists - 2: false
pathExists - 3: false
pathExists - 4: true
```
The following ordinary javascript:
```javascript
'use strict';
var pathExists = require("path-exists");
var javaHome = process.env['JAVA_HOME'];
console.log("JAVA_HOME: " + javaHome);
console.log('pathExists: ' + pathExists.sync(javaHome));
console.log('pathExists - 2: ' + pathExists.sync('/usr/lib/jvm/java-1.8.0-openjdk/'));
console.log('pathExists - 3: ' + pathExists.sync('/usr/lib/jvm/'));
console.log('pathExists - 4: ' + pathExists.sync('/home/mattias/'));        
```
prints:
```
;node test.js 
JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.fc27.x86_64
pathExists: true
pathExists - 2: true
pathExists - 3: true
pathExists - 4: true
```

**Comment by fbricon** [comment] 2018-04-06 18:39
@attiand could you try to make your small vscode extension use `const fs = require('fs');` and then check `fs.accessSync(javaHome);`? If that fails then it's probably a bug in vscode/electron and we need to report it upstream.

**Comment by attiand** [comment] 2018-04-07 07:33
Yes, that throws Error: ENOENT: no such file or directory, access '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-5.b14.fc27.x86_64'

Here is the extension: https://gist.github.com/attiand/16e24564dac93f5fa93bc3035e28596d

**Comment by fbricon** [comment] 2018-07-16 16:37
@akurtakov does it look like your issue?

**Comment by akurtakov** [comment] 2018-07-16 17:02
Yes, looks exactly the same.

**Comment by SiqingYu** [comment] 2018-08-27 12:44
I've also got the problem.

Operating System: Ubuntu 18.04 LTS
JDK version: OpenJDK 11
Visual Studio Code version: 1.26.1
Java extension version: 0.29.0
JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

`The JAVA_HOME environment variable does not point to a JDK.
`

**Comment by SiqingYu** [comment] 2018-08-27 13:36
I removed Oracle JDK 8 and update-alternatives uses `/usr/lib/jvm/java-11-openjdk-amd64`, then it works.
:confused:

**Comment by liuxk99** [comment] 2019-07-22 08:58
Edit the User Settings
~/.config/Code/User/settings.jason
`{
    "git.ignoreLegacyWarning": true,
    "workbench.colorTheme": "GitHub Plus",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.home": "/usr/lib/jvm/java-8-openjdk-amd64/"
}`

**Comment by rgrunber** [comment] 2022-05-13 15:27
Closing this issue for now as there have been a lot of updates/improvements to JDK detection. For example we've moved away from find-java-home to jdk-utils ( https://github.com/redhat-developer/vscode-java/pull/2246 ). If this issue persists today, feel free to re-open and we can have a closer look.

**Closed by rgrunber** 2022-05-13 15:27 UTC
Labels: bug, need info
