### ISSUE TITLE
Unable to locate secure storage module

### ISSUE THREAD

**Issue by thiagolocatelli** [redhat-developer/vscode-java#212] opened 2017-05-15 16:22 UTC
When I open any maven project folder, I get a "Unable to locate secure storage module" exception (stacktrace below)

##### Environment
- Operating System: MacOs El Capitan 10.11.6 (15G1421)
- JDK version: Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
- Visual Studio Code version: Version 1.12.1 (1.12.1)
- Java extension version: 0.3.0

##### Steps To Reproduce
1. Open VS Code
2. Open Project folder

Sample application: https://github.com/SpartaTech/sparta-test-utils
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

`[Error - 11:59:28 AM] May 15, 2017 11:59:26 AM Unable to locate secure storage module (org.eclipse.equinox.security.osxkeystoreintegration).
Unable to locate secure storage module (org.eclipse.equinox.security.osxkeystoreintegration).
org.eclipse.equinox.security.storage.StorageException: Unable to locate secure storage module (org.eclipse.equinox.security.osxkeystoreintegration).
	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findStorageModule(PasswordProviderSelector.java:190)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getModulePassword(SecurePreferencesRoot.java:233)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getPassword(SecurePreferencesRoot.java:226)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.get(SecurePreferences.java:264)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.get(SecurePreferencesWrapper.java:106)
	at org.eclipse.core.internal.net.ProxyType.loadProxyAuth(ProxyType.java:537)
	at org.eclipse.core.internal.net.ProxyType.createProxyData(ProxyType.java:138)
	at org.eclipse.core.internal.net.ProxyType.getProxyData(ProxyType.java:127)
	at org.eclipse.core.internal.net.PreferenceManager.migrateInstanceScopePreferences(PreferenceManager.java:292)
	at org.eclipse.core.internal.net.PreferenceManager.migrate(PreferenceManager.java:260)
	at org.eclipse.core.internal.net.ProxyManager.checkMigrated(ProxyManager.java:399)
	at org.eclipse.core.internal.net.ProxyManager.initialize(ProxyManager.java:269)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:175)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:103)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:359)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:437)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:386)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:378)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.addModifyListener(PreferenceServiceRegistryHelper.java:91)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.getModifyListeners(PreferenceServiceRegistryHelper.java:205)
	at org.eclipse.core.internal.preferences.PreferencesService.firePreApplyEvent(PreferencesService.java:440)
	at org.eclipse.core.internal.preferences.PreferencesService.internalApply(PreferencesService.java:692)
	at org.eclipse.core.internal.preferences.PreferencesService.applyPreferences(PreferencesService.java:93)
	at org.eclipse.m2e.core.internal.preferences.MavenConfigurationImpl.setNotCoveredMojoExecutionSeverity(MavenConfigurationImpl.java:296)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:87)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:108)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
`

##### Expected Result
The project should not trigger any error.

##### Additional Informations
No aditional information

**Comment by snjeza** [comment] 2017-05-15 21:36
Related to https://github.com/redhat-developer/vscode-java/issues/211

**Comment by thiagolocatelli** [comment] 2017-05-15 22:22
I am not seeing why this issue is related to #211.

**Comment by snjeza** [comment] 2017-05-16 13:18
@thiagolocatelli both of the issues are caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=513809.
If you don't use a proxy that requires authentication, you will get an exception in the log, but vscode-java will work properly. 
The issue has been fixed in Oxygen M7.

**Comment by snjeza** [comment] 2017-05-22 18:12
See See https://github.com/eclipse/eclipse.jdt.ls/pull/233

**Closed** 2017-05-25 17:05 UTC
Labels: bug, in progress

**Comment by fbricon** [comment] 2017-05-25 19:27
@thiagolocatelli please download and [install](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) the latest *.vsix from http://download.jboss.org/jbosstools/jdt.ls/staging/ and let us know if it fixes your issue
