### ISSUE TITLE
File Save Handler is trying to map UTF-8 characters to GBK, causing messy code

### ISSUE THREAD

**Issue by NathanIceSea** [redhat-developer/vscode-java#410] opened 2018-01-12 11:09 UTC
When saving seperated java file in UTF-8 encoding, Chinese characters are reformatted to messy code, log shows that the support service was trying to map characters to GBK, which violates my willing, hopefully there should be a way to determine the default charset other than decided by system language.

##### Environment
- Operating System: win10 pro, default lang: Chinese
- JDK version: 1.8u151
- Visual Studio Code version: latest, 1.19.2
- Java extension version: language support for java 0.16.0

##### Steps To Reproduce
1. Create a single Java temp file, write a comment in Chinese, ctrl + s, and the Charaters are mapped to messy code
2. Type Chinese in String, ctrl + s, log shows and error has occured during handling file saving procedure:

[Error - 18:53:36] 2018-1-12 18:25:59 Error while handling document save
Some characters cannot be mapped using "GBK" character encoding.
Either change the encoding or remove the characters which are not supported by the "GBK" character encoding.
Java Model Exception: Core Exception [code 3] Some characters cannot be mapped using "GBK" character encoding.
Either change the encoding or remove the characters which are not supported by the "GBK" character encoding.
	at org.eclipse.jdt.ls.core.internal.DocumentAdapter.save(DocumentAdapter.java:254)
	at org.eclipse.jdt.internal.core.CommitWorkingCopyOperation.executeOperation(CommitWorkingCopyOperation.java:123)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:795)
	at org.eclipse.jdt.internal.core.CompilationUnit.commitWorkingCopy(CompilationUnit.java:392)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.handleSaved(DocumentLifeCycleHandler.java:334)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$5.run(DocumentLifeCycleHandler.java:192)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.didSave(DocumentLifeCycleHandler.java:189)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didSave(JDTLanguageServer.java:548)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:172)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:143)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:83)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:816)
	at org.eclipse.core.internal.filebuffers.ResourceTextFileBuffer.commitFileBufferContent(ResourceTextFileBuffer.java:335)
	at org.eclipse.core.internal.filebuffers.ResourceFileBuffer.commit(ResourceFileBuffer.java:314)
	at org.eclipse.jdt.ls.core.internal.DocumentAdapter.save(DocumentAdapter.java:251)
	... 29 more
Caused by: org.eclipse.core.runtime.CoreException: Some characters cannot be mapped using "GBK" character encoding.
Either change the encoding or remove the characters which are not supported by the "GBK" character encoding.
	at org.eclipse.core.internal.filebuffers.ResourceTextFileBuffer.commitFileBufferContent(ResourceTextFileBuffer.java:347)
	at org.eclipse.core.internal.filebuffers.ResourceFileBuffer.commit(ResourceFileBuffer.java:314)
	at org.eclipse.jdt.ls.core.internal.DocumentAdapter.save(DocumentAdapter.java:251)
	at org.eclipse.jdt.internal.core.CommitWorkingCopyOperation.executeOperation(CommitWorkingCopyOperation.java:123)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:795)
	at org.eclipse.jdt.internal.core.CompilationUnit.commitWorkingCopy(CompilationUnit.java:392)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.handleSaved(DocumentLifeCycleHandler.java:334)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$5.run(DocumentLifeCycleHandler.java:192)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.didSave(DocumentLifeCycleHandler.java:189)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didSave(JDTLanguageServer.java:548)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:172)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:143)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:83)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:816)
	at org.eclipse.core.internal.filebuffers.ResourceTextFileBuffer.commitFileBufferContent(ResourceTextFileBuffer.java:335)
	... 31 more

**Comment by NathanIceSea** [comment] 2018-01-12 11:14
by the way , my vscode setting of file saving goes as followed:
"files.encoding": "utf8",
which is default

**Comment by fbricon** [comment] 2018-01-12 13:02
@snjeza please check if this was fixed by the recent fix for utf8

**Comment by snjeza** [comment] 2018-01-12 18:09
A duplicate of https://github.com/redhat-developer/vscode-java/issues/394
@NathanIceSea You can try http://download.jboss.org/jbosstools/jdt.ls/staging/java-0.17.0-799.vsix

**Closed by snjeza** 2018-01-12 18:09 UTC
