### ISSUE TITLE
MapStruct mapper generation error after upgrading to 1.36

### ISSUE THREAD

**Issue by nicolasriousset** [redhat-developer/vscode-java#3843] opened 2024-11-05 10:55 UTC
Hi,

After upgrading Language Support for Java(TM) to version 1.36, visual studio code started failing to generate MapStruct Mappers with the following error :

```
Error occured while building workspace. Details: 
 message: No implementation was created for xxxMapper due to having a problem in the erroneous element java.util.ArrayList. Hint: this often means that some other annotation processor was supposed to process the erroneous element. You can also enable MapStruct verbose mode by setting -Amapstruct.verbose=true as a compilation argument.

```

I'm using Maven with Lombok 1.18.30 and MapStruct 1.5.5.Final. Command line compilation works just fine, the issue arises only when building using the VS Code IDE.

Rolling back Language Support for Java(TM)  plugin in VS Code to version 1.35.1 solves the issue.

Below is my maven annotationProcessorPaths configuration. I can try and provide a basic application to reproduce the issue, if it helps.

```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>${lombok.mapstruct.binding.version}</version>
                            </path>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
```

Best regards,

Nicolas

**Comment by nicolasriousset** [comment] 2024-11-05 10:57
I wonder if the issue could have been introduced by this fix : [](https://github.com/redhat-developer/vscode-java/pull/3833)

**Comment by rgrunber** [comment] 2024-11-05 15:04
This is a duplicate of https://github.com/redhat-developer/vscode-java/issues/3836 . https://github.com/redhat-developer/vscode-java/pull/3833 just updated the name of the file to better reflect what it is. We've been running off the latest Lombok for some time now.

**Closed by rgrunber** 2024-11-05 15:04 UTC
Labels: duplicate

**Comment by vijb20** [comment] 2024-11-28 14:23
el problema esta en que las librerias de lombok del editor con respecto al proyecto son diferentes
para el caso de vscode se debe cambiar la version del lombok por la de tu proyecto en la siguiente ruta

C:\Users\jvjara\.vscode\extensions\redhat.java-1.36.0-win32-x64\lombok
