### ISSUE TITLE
SDKman with jdk 17 for vs code support.

### ISSUE THREAD

**Issue by nazordz** [redhat-developer/vscode-java#2129] opened 2021-09-25 15:39 UTC
<img width="1280" alt="Screen Shot 2021-09-25 at 10 14 52 PM" src="https://user-images.githubusercontent.com/17057410/134776613-fe6b5956-fc6b-47df-9bc3-1e11f0386e1c.png">

##### Environment
- Operating System: macOS Big Sur 11.6
- JDK version: 17
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0

##### Steps To Reproduce
1. I Want to add configuration java 17 from sdkman to settings.json in vscode.
2. I try to check vs code market place and this plugin not updated i think.
https://marketplace.visualstudio.com/items?itemName=redhat.java

[Please attach a sample project reproducing the error]
https://github.com/nazordz/spring-uploadcsv

**Comment by snjeza** [comment] 2021-09-25 16:16
@nazordz Could you try https://download.jboss.org/jbosstools/jdt.ls/staging/java-0.83.0-384.vsix ?

**Comment by intact** [comment] 2021-09-26 16:20
java-0.83.0-384.vsix  works for me in VSCodium with OpenJDK 17+35

**Comment by fbricon** [comment] 2021-09-27 15:15
Closing as duplicate of https://github.com/redhat-developer/vscode-java/pull/2102

**Closed by fbricon** 2021-09-27 15:15 UTC
Labels: duplicate
