### ISSUE TITLE
java.format.settings.url broke again

### ISSUE THREAD

**Issue by ericbaobao** [redhat-developer/vscode-java#1919] opened 2021-05-01 16:06 UTC
After vscode update, in windows my vscode do not follow the profile anymore
in the **settings.json**, I used to set it like this:
"java.format.settings.url": "C:\\Users\\PCNAME\\AppData\\Local\\Programs\\Microsoft VS Code\\TheXmlFile.xml",
"java.format.settings.profile": "test",

I moved to this location with shorter path and tried this, it didn't work as well
    "java.format.settings.url": "file:///c%3A/Users/PCNAME/.vscode/TheXmlFile.xml",
    "java.format.settings.profile": "test",

The xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="13">
    <profile kind="CodeFormatterProfile" name="test" version="13">
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_anonymous_type_declaration" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_method_declaration" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_block" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_constructor_declaration" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_lambda_body" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_enum_declaration" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_block_in_case" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_annotation_type_declaration" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_switch" value="next_line"/>
        <setting id="org.eclipse.jdt.core.formatter.brace_position_for_enum_constant" value="next_line"/>
		<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_catch_in_try_statement" value="insert"/>
		<setting id="org.eclipse.jdt.core.formatter.indent_switchstatements_compare_to_switch" value="true"/>
		<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_else_in_if_statement" value="insert"/>
		<setting id="org.eclipse.jdt.core.formatter.insert_new_line_before_finally_in_try_statement" value="insert"/>

    </profile>
</profiles>
```

**Comment by snjeza** [comment] 2021-05-01 16:34
@ericbaobao See https://github.com/redhat-developer/vscode-java/issues/1917#issuecomment-830652380

**Comment by snjeza** [comment] 2021-05-01 16:34
A duplicate of #1917

**Closed by snjeza** 2021-05-01 16:34 UTC
