### ISSUE TITLE
The language support always unavailable after change the method type

### ISSUE THREAD

**Issue by bobjiang1988** [redhat-developer/vscode-java#627] opened 2018-09-05 01:24 UTC
##### Environment
- Operating System: Ubuntu 18.04
- JDK version: 1.8
- Visual Studio Code version: 1.26.1
- Java extension version: 0.30.0

##### Steps To Reproduce
1. I have a method like that
```
public void test() {
}
```

2. Change the method type to Integer
```
public Integer test() {
}
```

3. Then I got a syntax error, and here is the log
```
null
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
	at org.eclipse.jface.text.TreeLineTracker.lineByOffset(TreeLineTracker.java:268)
	at org.eclipse.jface.text.TreeLineTracker.getLineNumberOfOffset(TreeLineTracker.java:1122)
	at org.eclipse.jface.text.AbstractLineTracker.getLineNumberOfOffset(AbstractLineTracker.java:154)
	at org.eclipse.jface.text.AbstractDocument.getLineOfOffset(AbstractDocument.java:871)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOfOffset(SynchronizableDocument.java:334)
	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toLine(JsonRpcHelpers.java:60)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.toRange(JDTUtils.java:468)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.toLocation(JDTUtils.java:382)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.toLocation(JDTUtils.java:344)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentSymbolHandler.collectChildren(DocumentSymbolHandler.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentSymbolHandler.collectChildren(DocumentSymbolHandler.java:68)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentSymbolHandler.getOutline(DocumentSymbolHandler.java:52)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentSymbolHandler.documentSymbol(DocumentSymbolHandler.java:44)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$13(JDTLanguageServer.java:545)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$25(JDTLanguageServer.java:751)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by bobjiang1988** [comment] 2018-09-05 01:28
More information here.
I imported lombok.Getter/Setter and added the vscode-lombok extension.

**Comment by yaohaizh** [comment] 2018-09-12 03:18
@bobjiang1988 Do you have also install vscode java test extension?

**Comment by bobjiang1988** [comment] 2018-09-12 06:10
@yaohaizh Yes, I have installed.

**Comment by fbricon** [comment] 2018-09-17 21:10
The BadLocationException issue is caused by the outline view. This should be fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/795

**Comment by yaohaizh** [comment] 2018-11-04 09:14
This should have been fixed. @bobjiang1988 Please help verify.

**Closed** 2018-11-08 01:38 UTC
Labels: need verify
