### ISSUE TITLE
... cannot be resolved as a type

### ISSUE THREAD

**Issue by Aragami1408** [redhat-developer/vscode-java#1299] opened 2020-02-25 15:33 UTC
Hi! I don't know why it gives me this kind of error like image below although I compiled and it has no error returned. And I'm making sure that I write my code correctly
![image](https://user-images.githubusercontent.com/25903678/75261899-506ff880-581e-11ea-86bd-76344814f879.png)

##### Environment
- Operating System: Windows 10 Pro
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.22.2
- Java extension version: 0.30.0

##### Current Result

```
... Cannot be resolved as a type
```

##### Expected Result

Returns no error

**Comment by fbricon** [comment] 2020-02-25 15:58
Please start by updating to the latest version of vscode-java

**Comment by IComplainInComments** [comment] 2020-02-27 04:45
> Please start by updating to the latest version of vscode-java

I'm having the same issue as well, and I'm using the latest version. My program compiles fine, even though VSCode is saying otherwise.

For me its happening on any of my Classes being used as Objects or A Class being inherited by another.

**Comment by IComplainInComments** [comment] 2020-02-27 04:50
Looks like my issue was resolved by disabling the Java Linter extension.

**Comment by jdharvey-ibm** [comment] 2020-02-27 05:14
I am seeing a very similar problem. VSCode will go through it's usual process for building our Java code, but then upon completion, thousands of errors appear in the Problems viewer, all for things that say either:
> The import ... cannot be resolved

or

> ... cannot be resolved to a variable

or

> The method ... from the type ... refers to the missing type ...

etc...

Interestingly, as soon as I open one of the affected source files, the errors for that file disappear until the next time I do a full rebuild, clean the Java language server workspace, or restart vscode. This is something I can confirm was **not** happening about 3 days ago.


```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```

**Comment by IComplainInComments** [comment] 2020-02-27 23:37
> I am seeing a very similar problem. VSCode will go through its usual process for building our Java code, but then upon completion, thousands of errors appear in the Problems viewer, all for things that say either:
> 
> > The import ... cannot be resolved
> 
> or
> 
> > ... cannot be resolved to a variable
> 
> or
> 
> > The method ... from the type ... refers to the missing type ...
> 
> etc...
> 
> Interestingly, as soon as I open one of the affected source files, the errors for that file disappear until the next time I do a full rebuild, clean the Java language server workspace, or restart vscode. This is something I can confirm was **not** happening about 3 days ago.
> 
> ```
> Version: 1.42.1
> Commit: c47d83b293181d9be64f27ff093689e8e7aed054
> Date: 2020-02-11T14:44:27.652Z
> Electron: 6.1.6
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Darwin x64 19.3.0
> ```
> 
> ```
> vscjava.vscode-java-pack: 0.8.1
> redhat.java: 0.57.0
> ```

This is exactly what was happening for me. Mine randomly got fixed after deleting the Java Linter, but it was happening even BEFORE I HAD IT INSTALLED. I honestly cannot think of why its behaving as such.

**Comment by jdharvey-ibm** [comment] 2020-02-28 14:37
I don't have that extension installed to try and remove it 😭 haha. I did try completely uninstalling VSCode and reinstalling it, removing all extensions and workspace files in the process, but I'm getting the exact same results still.

**Comment by jdharvey-ibm** [comment] 2020-03-11 22:18
@fbricon Any update on this issue? It is **100% blocking** my ability to use VSCode Java for our projects at work since nothing will compile properly. I can provide whatever details you need about my environment to help debug this issue.

**Comment by snjeza** [comment] 2020-03-11 22:24
@jdharvey-ibm could you send your project and server log - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

**Comment by jdharvey-ibm** [comment] 2020-03-12 21:51
[java-language-server.log](https://github.com/redhat-developer/vscode-java/files/4326725/java-language-server.log)

Here's my java language server log. I enabled Java tracing as well, but I can't attach that info for two reasons: 1) it's enormous because our codebase has many millions of lines of code in it; and 2) it is littered with confidential information. If there are specific things you want me to look for in the trace, just let me know.

However... the exceptions in that log file seem extremely similar to this issue: https://github.com/groovy/groovy-eclipse/issues/550
Except a potential difference being that all of our projects seem to have output directories of `bin`

**Comment by snjeza** [comment] 2020-03-12 22:41
Could you send your .project and .classpath files?

**Comment by snjeza** [comment] 2020-03-12 22:50
Could you also set the following property:

```
"java.trace.server": "verbose",
```

and send your server log?

**Comment by jdharvey-ibm** [comment] 2020-03-17 19:23
The language server log was attached in my previous comment. I cannot provide the classpath or project files directly because of the reasons I mentioned above, but I can answer questions related to it if you have specific questions.

**Comment by snjeza** [comment] 2020-03-17 20:30
> The language server log was attached in my previous comment.

you have used the following settings:
```
"java.trace.server": "messages",
```
Could you change it to the following:

``` 
"java.trace.server": "verbose",
```

Could you also try to call  Java: Clean the Java language server workspace? - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory

**Comment by jdharvey-ibm** [comment] 2020-03-20 15:21
I promise that I had and continue to have my java.trace.server setting set to verbose. If it is not outputting expected information, then that is likely a separate issue that needs investigation. Here's a copy/paste from my vscode settings file:
```
...
    "spellright.notificationClass": "hint",
    "spellright.spellContext": "body comments",
    "java.trace.server": "verbose",
}
```

Clearing the language server has no effect other than triggering a rebuild which always looks like it's *about* to succeed, but then it bombs out with all of the errors I mentioned in my first comment until I open each file, at which point the errors for that particular file get resolved.

I just found out from someone on my team that they are seeing what looks to be an identical set of symptoms in the 2020-03 version of Eclipse that was released, for example:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=561287

There are other bugs similar to that one as well.

**Comment by jdharvey-ibm** [comment] 2020-06-12 19:23
Based on guidance from the eclipse issue I mentioned above, I added this to my vscode settings file, which resolved the issue for me. I haven't really followed the rest of the discussion in that eclipse bug, but it does appear to have been fixed on 6/2.

```
"java.jdt.ls.vmargs": "-DmaxCompiledUnitsAtOnce=0"
```

**Comment by akaroml** [comment] 2020-06-14 05:00
@testforstephen `maxCompiledUnitsAtOnce` do we understand how this affects the behavior of JDT?

**Comment by testforstephen** [comment] 2020-06-14 09:33
`maxCompiledUnitsAtOnce` is a vmArgs used to control the max number of files that the JDT builder can handle in one batch compilation. Defaults to 2000. `0` means compiling all files in one batch. FYI: // @akaroml 

Have a look at the upstream discussion at https://bugs.eclipse.org/bugs/show_bug.cgi?id=561287, this issue only happens if a class references a class that is compiled in a later batch and is in a package that has a non-package subdirectory (meaning it contains only non-java files). That's why setting `0` works.

The upstream fix is already merged at March 31. Since the java extension is using the nightly build, our latest version **0.62.0** should have included the fix.

@jdharvey-ibm Could you remove the vmArgs and use the latest vscode-java@0.62.0 to try again?

**Comment by jdharvey-ibm** [comment] 2020-06-15 14:40
Just re-ran with the following extension versions, and *without* the `maxCompiledUnitsAtOnce` vmarg, and I still see the same compile failures... Numerous (7000+) "... refers to missing type" or "... cannot be resolved" errors until I open each file individually.

```
Name: Java Extension Pack
Id: vscjava.vscode-java-pack
Description: Popular extensions for Java development and more.
Version: 0.9.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack
```

```
Name: Language Support for Java(TM) by Red Hat
Id: redhat.java
Description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
Version: 0.62.0
Publisher: Red Hat
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.java
```

jvm
```
java version "1.8.0_221"
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_221-b11 06_Aug_2019_07_06 Mac OS X x64(SR5 FP40))
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
IBM Java ORB build orb80-20190708.00
XML build XL TXE Java 1.0.61
XML build IBM JAXP 1.6.1
XML build XML4J 4.5.31
```
also tried with the following jvm and got similar results
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200428_567 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)
```

**Comment by testforstephen** [comment] 2020-06-16 12:28
@jdharvey-ibm thank you for the verification. Sorry, i just checked 0.62.0 is still using an old jdt bits. The next release 0.63.0 should have the upstream fix.

**Comment by rgrunber** [comment] 2024-01-19 22:07
Closing under the assmption that this was fixed, but feel free to re-open if still an issue.

**Closed by rgrunber** 2024-01-19 22:07 UTC
Labels: need info, ls-error/crash
