### ISSUE TITLE
Provide Rename Symbol option

### ISSUE THREAD

**Issue by ajitid** [redhat-developer/vscode-java#261] opened 2017-07-25 12:53 UTC
##### Environment
- Operating System: Win 10
- JDK version: 1.8
- Visual Studio Code version: 1.14.2
- Java extension version: 0.7.0

![screenshot 233](https://user-images.githubusercontent.com/26769888/28572613-5f5d62e4-7165-11e7-950a-52d6e483d0c3.png)

This Java extension is able to identify variables and methods. I think support for Rename Symbol option (invoked by F2 in VS Code)  should be added.

**Comment by fbricon** [comment] 2017-07-25 13:21
Duplicate of #71

**Closed by fbricon** 2017-07-25 13:21 UTC
Labels: duplicate
