### ISSUE TITLE
Adjust heap space for server if it fails to start due to OOM

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#192] opened 2017-04-25 00:18 UTC
My server fails to initialize a workspace due to OOM. In this case VS Code restarts the server, we should add logic to the extension so that the heap space is adjusted.

```[Error - 5:35:23 PM] 24-Apr-2017 5:29:14 PM An internal error occurred during: "Initialize Workspace".
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at org.apache.maven.model.Plugin.getExecutions(Plugin.java:181)
	at org.apache.maven.model.merge.MavenModelMerger.mergePlugin_Executions(MavenModelMerger.java:537)
	at org.apache.maven.model.inheritance.DefaultInheritanceAssembler$InheritanceModelMerger.mergePlugin(DefaultInheritanceAssembler.java:272)
	at org.apache.maven.model.inheritance.DefaultInheritanceAssembler$InheritanceModelMerger.mergePluginContainer_Plugins(DefaultInheritanceAssembler.java:212)
	at org.apache.maven.model.merge.ModelMerger.mergePluginContainer(ModelMerger.java:2471)
	at org.apache.maven.model.merge.ModelMerger.mergePluginManagement(ModelMerger.java:2505)
	at org.apache.maven.model.merge.ModelMerger.mergePluginConfiguration_PluginManagement(ModelMerger.java:2464)
	at org.apache.maven.model.merge.ModelMerger.mergePluginConfiguration(ModelMerger.java:2449)
	at org.apache.maven.model.merge.ModelMerger.mergeBuildBase(ModelMerger.java:2324)
	at org.apache.maven.model.merge.ModelMerger.mergeBuild(ModelMerger.java:2164)
	at org.apache.maven.model.merge.ModelMerger.mergeModel_Build(ModelMerger.java:495)
	at org.apache.maven.model.merge.ModelMerger.mergeModel(ModelMerger.java:147)
	at org.apache.maven.model.merge.MavenModelMerger.mergeModel(MavenModelMerger.java:75)
	at org.apache.maven.model.merge.ModelMerger.merge(ModelMerger.java:121)
	at org.apache.maven.model.inheritance.DefaultInheritanceAssembler.assembleModelInheritance(DefaultInheritanceAssembler.java:58)
	at org.apache.maven.model.building.DefaultModelBuilder.assembleInheritance(DefaultModelBuilder.java:721)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:377)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:161)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:679)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:176)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$4.call(ProjectRegistryManager.java:704)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$4.call(ProjectRegistryManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.execute(ProjectRegistryManager.java:967)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readMavenProjectFacade(ProjectRegistryManager.java:699)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:398)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351)

[Error - 5:35:23 PM] 24-Apr-2017 5:29:14 PM Application error
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.entrySet(HashMap.java:1006)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:856)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.setProperties(ServiceRegistrationImpl.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.setAppStatus(EclipseAppHandle.java:159)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.setInternalResult(EclipseAppHandle.java:229)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:202)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by fbricon** [comment] 2017-04-25 00:45
Heap space can be set from user/workspace setting. Would you override its value somehow? Would need to warn users?

**Comment by gorkem** [comment] 2017-04-25 01:13
If user explicitly sets the value user is taking the responsibility so we do not need to override that. I do not think we need to warn for about changing it.

**Comment by fbricon** [comment] 2017-05-03 19:46
You should see if you still run into OOME after String deduplication is enabled (see #195)

**Comment by fbricon** [comment] 2019-12-10 10:23
ping @akaroml, if you guys want to look into it

**Comment by akaroml** [comment] 2019-12-13 10:24
> ping @akaroml, if you guys want to look into it

The vmargs is already exposed as a user setting, so they are free to set whatever they want. But we do think we could provide easier solution by providing presets to allow users to easily choose whether they want less memory consumption or better responsiveness. We'll follow up and form those presets.

@Eskibear

**Comment by akaroml** [comment] 2019-12-16 04:41
@fbricon  could you help assign this to @Eskibear for easier tracking?

**Comment by fbricon** [comment] 2019-12-16 09:45
@akaroml I don't have the rights to do that but @gorkem can certainly add him to the list of contributors for this repo

**Comment by rgrunber** [comment] 2021-07-07 14:46
Looks like we'llbe getting around to enhancing this, so marking this as a duplicate of #1959 . We'll definitely attempt to catch the OOM on the client side, and either report to user if it exceeds a certain threshold or increase the max heap size for the user.

**Closed by rgrunber** 2021-07-07 14:46 UTC
Labels: duplicate, enhancement
