### ISSUE TITLE
feature autoimport

### ISSUE THREAD

**Issue by scgm11** [redhat-developer/vscode-java#95] opened 2016-11-15 18:52 UTC
[provide a description of the issue]

##### Environment
- Operating System: Mac OSX Sierra
- JDK version: 1.8
- Visual Studio Code version: 1.7.1
- Java extension version: 0.0.6

##### Steps To Reproduce

Add autoimport for known types that I have on my classpath or from the jdk

**Comment by fbricon** [comment] 2016-11-15 19:08
Closing as duplicate of #56

**Closed by fbricon** 2016-11-15 19:08 UTC
Labels: duplicate
