### ISSUE TITLE
provide setting for java source zip files

### ISSUE THREAD

**Issue by Oscar-21** [redhat-developer/vscode-java#616] opened 2018-08-24 20:34 UTC
For various reasons I can not add the src.zip file to the jdk directory. Eclipse lets me "attach a source" from another directory. This would be a nice setting to have for debugging and it's more accurate than the disassembler.

**Comment by yaohaizh** [comment] 2018-08-25 02:27
@testforstephen Would you consider this issue?

**Comment by testforstephen** [comment] 2018-08-28 09:33
The disassembler only generates the method declare info, they cannot be used for debugging. Supporting `attach external source` is ideal solution for this problem. Have a look at eclipse ux, there it provides two entries about attaching source.

The first entry is exposing a button at the File editor.
![image](https://user-images.githubusercontent.com/14052197/44713929-b8893580-aae6-11e8-86e6-52cfb2d5406b.png)

The second entry is providing context menu at the dependency view.

@yaohaizh Considering the VSCode ux, feel like it is appropriate to integrate this feature with java dependency view.

**Comment by fbricon** [comment] 2018-09-12 20:42
Closing as duplicate of #233

**Closed by fbricon** 2018-09-12 20:42 UTC
Labels: duplicate
