### ISSUE TITLE
Wrong constructor generated using class code snippet

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#683] opened 2018-10-22 02:20 UTC
![class code snippet not working](https://user-images.githubusercontent.com/16755094/47275679-f46ee180-d5e3-11e8-83c2-85d18862de7e.gif)

Please see the attached recording. LS is now generating wrong constructor when using `class` code snippet.

**Comment by snjeza** [comment] 2018-10-31 17:09
I can't reproduce the issue.

**Comment by fbricon** [comment] 2019-01-30 00:40
I've never been able to reproduce this issue either. closing. @akaroml please reopen if you find a way to reproduce it.

**Closed by fbricon** 2019-01-30 00:40 UTC
Labels: non_reproducible
