### ISSUE TITLE
Extension breaks "clipboardPasteAction" in Java files

### ISSUE THREAD

**Issue by bevzzz** [redhat-developer/vscode-java#3638] opened 2024-05-02 11:02 UTC
When enabled, the VSCode extension prevents text from being pasted.   

##### Environment
- Operating System: macOS Sonoma 14.3.1 
- JDK version: 17
- Visual Studio Code version:

```
Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z (9 mos ago)
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 23.3.0
```

- Java extension version: `1.30.0`

##### Steps to reproduce

1. Install "Language Support for Java(TM) by RedHat"
2. Open a **.java** file (other files, e.g. `yaml` are fine)
3. Copy and paste any amount of text (doesn't matter if with a shortcut or with mouse actions)

Once the extension is disabled, copy-paste works as usual.
Here's a relevant excerpt from Keyboard Shortcuts Troubleshooting log:

```shell
2024-05-02 11:59:15.724 [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyV, keyCode: 86, key: v
2024-05-02 11:59:15.724 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyV, keyCode: 52 ('V')
2024-05-02 11:59:15.725 [info] [KeybindingService]: | Resolving meta+[KeyV]
2024-05-02 11:59:15.725 [info] [KeybindingService]: \ From 5 keybinding entries, matched editor.action.clipboardPasteAction, when: no when condition, source: built-in.
2024-05-02 11:59:15.725 [info] [KeybindingService]: + Invoking command editor.action.clipboardPasteAction.
2024-05-02 11:59:15.730 [error] Cannot read properties of undefined (reading 'isCancellationRequested'): TypeError: Cannot read properties of undefined (reading 'isCancellationRequested')
	at d.<anonymous> (/Users/d.solovei/.vscode/extensions/redhat.java-1.30.0-darwin-x64/dist/extension.js:2:967366)
	at Generator.next (<anonymous>)
	at o (/Users/d.solovei/.vscode/extensions/redhat.java-1.30.0-darwin-x64/dist/extension.js:2:966443)
```

##### Current Result

Text not pasted.

##### Expected Result

Text pasted.

**Comment by fbricon** [comment] 2024-05-02 11:50
Closing as duplicate of #3631

**Closed by fbricon** 2024-05-02 11:50 UTC
