### ISSUE TITLE
Unable to configure classpath/java runtime

### ISSUE THREAD

**Issue by schophil** [redhat-developer/vscode-java#2778] opened 2022-11-03 07:52 UTC
Since upgrading VSCode the "Configure Java Runtime" and "Configure Classpath" windows are empty.

<img width="1731" alt="Screenshot 2022-11-03 at 08 51 02" src="https://user-images.githubusercontent.com/11485058/199670154-698dde16-5a8e-4e3f-bccf-09b6eef3b6bd.png">

##### Environment
- Operating System: MacOS (Darwin x64 21.6.0)
- JDK version: 17.0.5 (Eclipse Adoptium)
- Visual Studio Code version: 1.73.0 (Universal)
- Java extension version: v1.12.0

##### Steps To Reproduce
1. Open Java project
2. Open "Configure Java Runtime"

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by schophil** [comment] 2022-11-03 08:07
Found the following errors in the console:

ccess to script at 'vscode-resource:/Users/XXXXX/.vscode/extensions/vscjava.vscode-java-pack-0.25.4/out/assets/java-runtime/index.js' from origin 'vscode-webview://0gk03bfobvbvmvhfgrnsogul6f42sbago1moo74ormb2u3kul8k3' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, https, vscode-webview, chrome-untrusted, data, vscode-file, chrome, chrome-extension.

index.html?id=2694d7…2F%2Fvscode-app:969 
 GET vscode-resource:/Users/XXXXXX/.vscode/extensions/vscjava.vscode-java-pack-0.25.4/out/assets/java-runtime/index.js net::ERR_FAILED

**Comment by MarcSerret51** [comment] 2022-11-03 11:22
I'm getting the same error on console.

**Comment by rgrunber** [comment] 2022-11-03 14:16
I think this is an issue in https://github.com/microsoft/vscode-java-pack/ . Specifically https://github.com/microsoft/vscode-java-pack/blob/main/src/java-runtime/index.ts#L164 .

https://github.com/microsoft/vscode/issues/102959#issuecomment-663340395

CC @Eskibear as I see he has dealt a lot with vscode-java-pack.

**Comment by Eskibear** [comment] 2022-11-03 14:28
The issue occurs on VS Code 1.73, and it works well on 1.72.2 and previous versions. 

In fact, all webviews implemented in vscode-java-pack are broken. Investigating now. Tracked in https://github.com/microsoft/vscode-java-pack/issues/1102

**Comment by Eskibear** [comment] 2022-11-03 16:02
The fix has been shipped with vscode-java-pack v0.25.6. 

Root cause is, in vscode1.73, corresponding Uri changes from `vscode-resource:/path-to-script` to something like `https://file+.vscode-resource.vscode-cdn.net/path-to-script`. And we were constructing the Uris by our own based on wrong assumption, as commented in https://github.com/redhat-developer/vscode-java/issues/2778#issuecomment-1302181400

**Comment by rgrunber** [comment] 2022-11-03 16:14
Closing for now as this should be fixed when vscode-java-pack is updated by users. Feel free to re-open if the problem still exists after trying to update to v0.25.6.

**Closed by rgrunber** 2022-11-03 16:14 UTC
