### ISSUE TITLE
[Bug] - Can not search for Java JRE classes

### ISSUE THREAD

**Issue by mamilic** [redhat-developer/vscode-java#3814] opened 2024-10-14 09:50 UTC
When I open search with CTRL + T, and search for Arrays claas or List, or some other Java internal claas it can not be found. I was wondering if I am using this correctly, is there other search that will only search internal JDK classes?

##### Environment
- Operating System: Windows 11
- JDK version: 21
- Visual Studio Code version: 1.94.2
- Java extension version: 1.35.1

##### Steps To Reproduce
1. Open any Java Project
2. Open search CTRL + T
3. Search for any of, List, Array, Long, Instant

##### Current Result
The internal JDK classes are not searchable

##### Expected Result
Internal JDK classes should be searchable

**Comment by snjeza** [comment] 2024-10-14 10:00
@mamilic Could you try https://github.com/snjeza/vscode-test/raw/refs/heads/master/java-1.37.0.vsix? See https://github.com/redhat-developer/vscode-java/issues/3797#issuecomment-2395493585

**Comment by mamilic** [comment] 2024-10-14 10:05
Hi @snjeza , actually running the "Clean Java Language Server Workspace" did the tirck. Thanks, I think we can then close this issue.

**Comment by snjeza** [comment] 2024-10-14 10:32
A duplicate of https://github.com/redhat-developer/vscode-java/issues/3797

**Closed by snjeza** 2024-10-14 10:32 UTC
