### ISSUE TITLE
"packages" autocomplete

### ISSUE THREAD

**Issue by wzdnzd** [redhat-developer/vscode-java#101] opened 2016-11-24 03:28 UTC
[provide a description of the issue]

##### Environment
- Operating System: win10
- JDK version: 1.8
- Visual Studio Code version: 1.7.2
- Java extension version: 0.07

if i type "package com.mor",it show
![package](https://cloud.githubusercontent.com/assets/8565764/20585748/6b224cf8-b238-11e6-9b5c-cf9385a9c842.png)
but when i type enter,then:
![pac](https://cloud.githubusercontent.com/assets/8565764/20585750/6e5da052-b238-11e6-80dc-c1e7a067d677.png)

when i select an item it should replaece my input before.

In addition，it will better if it can autocomplete package when i create a .java file.

Thx.

**Comment by gorkem** [comment] 2016-11-24 03:39
Duplicate of #68 closing, although this has a better explanation of the bug :)

**Closed by gorkem** 2016-11-24 03:39 UTC
Labels: bug, content-assist, duplicate

**Comment by go1done** [comment] 2019-12-19 23:30
was the issue really sorted? still occurring with vs code 1.41.1
