### ISSUE TITLE
Generate toString() limitation

### ISSUE THREAD

**Issue by BlackCherryCat** [redhat-developer/vscode-java#3480] opened 2024-01-28 18:11 UTC
Generate toString() action will only generate a toString method with the class fields instead of with the super class fields too

##### Environment
- Operating System: Windows 11 23H2
- JDK version: 17.0.10
- Visual Studio Code version: 1.85.2
- Java extension version: 1.26.0

##### Steps To Reproduce
1. Right click and choose Source code action
2. Click on Generate toString()...

##### Current Result

Only generates a toString method with the class fields

##### Expected Result

Generate a toString method with the class fields super's class fields

##### Additional Informations

**Super class:**
![Captura de pantalla 2024-01-28 190417](https://github.com/redhat-developer/vscode-java/assets/68470515/43efe149-4d11-4cfc-b733-451b0aaffb00)

**Child class with the toString method generated:**
![Captura de pantalla 2024-01-28 190430](https://github.com/redhat-developer/vscode-java/assets/68470515/c3ac8581-9912-4096-90b9-35f12008da3a)

**Comment by rgrunber** [comment] 2024-01-29 19:03
I can confirm this is an issue. The Eclipse UI definitely permits it though, so I think it should be possible to do it as well.

![image](https://github.com/redhat-developer/vscode-java/assets/1417342/416d7a09-a2ed-4ade-a4ee-9ee25e9b85bb)

I think this is just a matter of correctly configuring the APIs to allow this.
Similar to https://github.com/redhat-developer/vscode-java/issues/2639#issuecomment-1222868543 .

I'm inclined to close this as a duplicate of that, and we can address both aspects (inheriting method, inheriting fields) in a single improvement.

**Comment by BlackCherryCat** [comment] 2024-01-30 22:10
For me it's fine if we merge this issue with the other that you have mencioned, but that issue is almost two years old, altough is the same topic.
We can include this issue in the mencioned issue under the same name, but with a more generic name, like this issue

**Comment by rgrunber** [comment] 2024-02-29 14:20
This should be fixed in pre-release and will be out in the 1.29.0 release. I think we still identified some issues worth fixing in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3055#pullrequestreview-1907401353 but it should be possible to use inherited members in forming to `toString` declaration now.

**Closed by rgrunber** 2024-02-29 14:20 UTC
Labels: code action
