### ISSUE TITLE
doesnt work outside of methods

### ISSUE THREAD

**Issue by ewof** [redhat-developer/vscode-java#3422] opened 2023-12-08 10:08 UTC
there is 0 intellisense outside of methods

##### Environment
- Operating System: mac
- JDK version: 17
- Visual Studio Code version: 1.85.0
- Java extension version: v1.25.1

##### Steps To Reproduce
1. open a java file
2. make a blank class
3. type `ma` or `so` `Coll` trying to outcomplete main method or println or some class like Collection and it wont work, all the autocompletion is just dictionary stuff (it says abc)

it was fine like a month ago
the extension not auto importing classes and stuff makes writing java actually horrible
works fine if u make a method and start typing inside of the method

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by ewof** [comment] 2023-12-08 10:20
```
Cannot read the array length because the return value of "org.eclipse.jdt.core.CompletionContext.getToken()" is null
java.lang.NullPointerException: Cannot read the array length because the return value of "org.eclipse.jdt.core.CompletionContext.getToken()" is null
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.matchCase(CompletionProposalRequestor.java:698)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.accept(CompletionProposalRequestor.java:237)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.createTypeProposal(CompletionEngine.java:5534)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.proposeType(CompletionEngine.java:14568)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.acceptTypes(CompletionEngine.java:1677)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findTypesAndPackages(CompletionEngine.java:11936)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnFieldType(CompletionEngine.java:2740)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2015)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2352)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:136)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:367)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:357)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:287)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.completion(JDTLanguageServer.java:633)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rgrunber** [comment] 2023-12-08 15:48
`"java.completion.matchCase": "off"` will definitely work around the issue, but I'm not sure why this would start happening now. If a user types `mo|`, `so|` or `Coll|` then the context should be one of those, and no `null`. Even if I type and immediately delete the tokens, the context is still an empty list.

The only thing I can think of is maybe JDT Core changed how it handles the token context. Fixing it would be an easy check at https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/cd8467833e3c988cdeca69badf60c169698f8902/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java#L698

@snjeza can you reproduce this at all ?

**Comment by snjeza** [comment] 2023-12-08 16:21
> @snjeza can you reproduce this at all ?

@rgrunber No, I can't.

**Comment by robstryker** [comment] 2023-12-11 16:55
This is the kind of bug that should be fixed even if people cannot replicate it. See https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2997/files

**Closed** 2023-12-11 17:47 UTC
Labels: bug

**Comment by rgrunber** [comment] 2023-12-13 15:27
This should be fixed in the latest pre-release and will be in the next release.

**Comment by ewof** [comment] 2023-12-13 15:30
yea it seams to work on the latest prerelease but one really nice thing that was possible before but isn't now is that if you typed ma or main you could auto complete the entire main method. i don't see any snippets outside of methods in autocomplete, just classes and such

**Comment by rgrunber** [comment] 2023-12-13 16:21
![class-snippet-context](https://github.com/redhat-developer/vscode-java/assets/1417342/0fa80b87-880e-4ea6-a92c-0eb3a9c02290)

In recent versions, we made snippets a bit more context aware (see above). So if you typed `method` or `main` snippets at the top of the file, they wouldn't display because  unless you were within a type declaration, they were not valid (in the example I show a nested class, but not required). I think we might need to update this to account for the new ways main methods can be declared with the Java 21 preview feature, https://openjdk.org/jeps/445 .

Do you have a case where you wanted the `main` (or `method`) snippet within a type declaration where it wasn't showing up ?
