### ISSUE TITLE
"The content on disk is newer" when renaming class

### ISSUE THREAD

**Issue by GabrielBB** [redhat-developer/vscode-java#903] opened 2019-04-26 19:35 UTC
##### Environment
- Operating System: Windows 8.1
- JDK version: JDK 11
- Visual Studio Code version: 1.33.1
- Java extension version: 0.43.0

##### Steps To Reproduce
1. Press F2 on a class name to rename it
2. Check that filename is also renamed with the new class name
3. Press CTRL + S to save the file with the change

##### Current Result

File name and class name are renamed as expected but once you try to save the file it throws an error (check picture in Additional Information) and it does not save. When you close the file and open it again the class has the old name. You proceed to change the name again and then it works and saves as expected. So, to change the class name you have to do it twice. I believe it has something to do with the file name change, VSCode says the file i'm using is old. Maybe you guys can close the file after the rename and open it again automatically or something.

##### Expected Result

Being able to save my file with the new class name with no problems.

##### Additional Informations

![image](https://user-images.githubusercontent.com/8752823/56831823-32b9b780-6838-11e9-8c7f-05c1a6cc5cc5.png)

**Comment by fbricon** [comment] 2019-04-26 20:01
Closing as duplicate of #871. Please use VS Code Insiders for now

**Closed by fbricon** 2019-04-26 20:01 UTC
Labels: duplicate
