### ISSUE TITLE
Request textDocument/completion failed.   Message: Internal error, please look at the server's logs.   Code: -32603 

### ISSUE THREAD

**Issue by sciarrk** [redhat-developer/vscode-java#163] opened 2017-03-11 22:46 UTC
Completion stops working

##### Environment
- Operating System: Windows 10 Home 14393
- JDK version: jdk1.8.0_112 x86
- Visual Studio Code version: 1.10.2
- Java extension version: 0.0.11

This message appears everytime i use completion.
Code completion also stops working after about 20 messages like this

[Error - 23:28:54] Request textDocument/completion failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 23:28:55] Request textDocument/completion failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 23:30:37] Request textDocument/completion failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 23:31:17] Request textDocument/completion failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 23:33:21] Request textDocument/completion failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603

**Comment by gorkem** [comment] 2017-03-13 01:19
Can you find the log? It should be under `%APPDATA%\Code\User\workspaceStorage\${hash}\redhat.java\jdt_ws\.metadata\.log`.

**Comment by fbricon** [comment] 2017-03-14 16:42
that looks like some errors we had in the past where malformed protocol messages (eg. missing nodes because of null return values) would cause lsp4j to return crap to the client.

**Comment by fbricon** [comment] 2017-03-31 15:30
Can you please check if the problem still occurs in 0.1.0? If it does, please attach updated [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) and possible, a sample project reproducing the issue.

**Comment by sciarrk** [comment] 2017-03-31 15:36
problem solved. Thank you!

**Comment by fbricon** [comment] 2017-03-31 15:39
Good. Closing ticket then.

**Closed by fbricon** 2017-03-31 15:39 UTC
