### ISSUE TITLE
0.54.0: Lombok is broken with maven

### ISSUE THREAD

**Issue by ricmzn** [redhat-developer/vscode-java#1174] opened 2019-12-04 14:55 UTC
After updating the extension to version 0.54.0, lombok seems to not work during build time anymore, causing lots of errors to be flagged. This is a regression, as the extension worked without issues before.

##### Environment
- Operating System: Linux Mint 19.2 x86_64
- JDK version: OpenJDK 11.0.4
- Visual Studio Code version: 1.40.2
- Java extension version: 0.54.0

##### Steps To Reproduce
1. Ensure both the Java Language Support and [Lombok](https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok) extensions are installed
2. Create a maven project with Lombok configured [as per the Lombok docs](https://projectlombok.org/setup/maven)
3. Try to use any generated methods (getters, setters, constructors, etc)
4. Observe "method is undefined" build errors in VSCode problems tab

Sample project and logs: working on it

##### Current Result

The extension build fails to find lombok-generated methods, causing autocomplete to break and hiding actual errors in large projects. Building via maven still works, so the rest of the environment is unaffected.

##### Expected Result

Lombok generated methods are available during build time, not causing errors.

##### Additional Informations

* My locally installed version of maven is a bit outdated, at 3.6.0. I'm not sure if this has an effect, because building on the command-line still works. I'm also not even sure it's a maven issue specifically, as I only have maven-based projects to test this with.

* The `java.jdt.ls.vmargs` setting is configured exactly as in https://github.com/redhat-developer/vscode-java/wiki/Lombok-support. I noticed the Lombok extension didn't add the `-Xboothclasspath/a` parameter, but adding it manually made no difference.

**Comment by bernardmo** [comment] 2019-12-04 15:02
Same problem here. No setting defined within `java.jdt.ls.vmargs` is applied to VM (seen in process list)

**Comment by fbricon** [comment] 2019-12-04 15:04
Closing as duplicate of #1175

**Comment by chucknelson** [comment] 2019-12-04 15:05
Ah - also see the issue I just created - added some additional detail.

**Version 0.54 Not Using Global "java.jdt.ls.vmargs" Setting** (#1175)

As a workaround, you can still get Lombok to work if you apply that `vmargs` setting in your workspace settings, but it's not working globally for some reason in `0.54`...

**Closed by fbricon** 2019-12-04 15:04 UTC
Labels: duplicate
