### ISSUE TITLE
Superscripts and subscripts are not displayed correctly in Javadoc comments (on hover)

### ISSUE THREAD

**Issue by rlundy** [redhat-developer/vscode-java#563] opened 2018-06-13 11:42 UTC
When hovering over a method whose Javadoc includes a &lt;sup&gt; element in its text, the &lt;sup&gt; isn't rendered, which can lead to some startling results in the incorrectly-rendered text.

##### Environment
- Operating System: Windows 10 x64
- JDK version: 10.0.1
- Visual Studio Code version: 1.24.0
- Java extension version: 0.26.0

##### Steps To Reproduce
1. In a Java project, in a class, add this line:  `java.util.Random r = new java.util.Random();`
2. Create a new `void` method with any name.
3. In that method, enter this line:  `int n = r.nextInt();`
4. Hover over the `nextInt`.

##### Expected Result
The Javadoc text includes this line: "All 2<sup>32</sup> possible int values are produced with (approximately) equal probability."  The line should contain a superscript, as rendered correctly in this markup.

##### Current Result
The Javadoc text says "All 232 possible int values are produced with (approximately) equal probability."  The programmer scratches his head.  232?  255 or 256 I could understand, but 232?

##### Additional Information
I don't know whether the Red Hat extension or Visual Studio Code itself is causing this.  When I disable the Red Hat extension, the behavior stops...because the Javadoc-on-hover stops altogether.  But I would think that Visual Studio Code is responsible for the Javadoc rendering.  I apologize if I've put this issue in the wrong place.

**Comment by fbricon** [comment] 2018-06-13 14:58
Closing as duplicate of #155

**Closed by fbricon** 2018-06-13 14:58 UTC
Labels: duplicate

**Comment by rlundy** [comment] 2018-06-14 06:20
Ah, I searched for superscript but I didn't search for "exponent" or "sup".
