### ISSUE TITLE
No way to force a recreation of classpath from gradle file

### ISSUE THREAD

**Issue by ThadHouse** [redhat-developer/vscode-java#132] opened 2016-12-30 04:12 UTC
My source control accidentally deleted the .classpath and .project files generated from my gradle build files, and I cannot find a way to recreate them. I've tried uninstalling and reinstalling the extension, deleting the .settings files, updating my classpaths in the gradle file, and the Ctrl+Alt+U shortcut, and nothing seems to be working. Is there another file I need to delete in order to force this recreation?

##### Environment
- Operating System: Windows 10
- JDK version: Version 8
- Visual Studio Code version: 1.8.1
- Java extension version: 0.0.8

##### Steps To Reproduce
1. Have .classpath and .project files be generated from gradle
2. Manually delete the files created
3. There is no way to have these files be recreated.

**Comment by gorkem** [comment] 2016-12-30 16:13
Does restarting the VS Code regenerate them?

**Comment by ThadHouse** [comment] 2016-12-30 16:14
Nope, nor does restarting my computer.

**Comment by gorkem** [comment] 2017-01-04 23:17
@fbricon I guess buildship is doing some caching ?

**Comment by dixonwille** [comment] 2017-01-05 06:44
Was able to reproduce by accident. Really hope this gets fixed soon or a solution. FRC competition coming up and really would enjoy not using Eclipse.

**Comment by ThadHouse** [comment] 2017-01-05 06:57
@dixonwille I was able to as a workaround reclone my repo to an unrelated directory, and then opened vscode. This generated the files for that repo, and I was able to just copy them over to my existing repo. 

The FRC comment is actually really funny. The repo I'm actually working on is the actual WPILib repo, as I'm one of the developers there. And yeah I totally agree with you. Eclipse sucks. VsCode works much nicer, especially now with this working with gradle, and the cpp extension.

**Comment by dixonwille** [comment] 2017-01-05 07:06
https://github.com/technomancers/GradleRIO little shameless plug but I am a mentor for team 1758 and wanted to make the build simple for me and them. There was another plugin I based this off of but this one allows way more configuration (hopefully) have not tested the full deploy process yet!

**Comment by dixonwille** [comment] 2017-01-05 07:22
Cloned project worked as mentioned above but I think I messed up the one I was working on. Was changing package name and the such...

**Comment by fbricon** [comment] 2017-01-05 07:22
Can you try closing vscode, deleting vscode's workspace storage directory at  `%APPDATA%\Code\User\workspaceStorage\` and then reopen your gradle-based project?

**Comment by dixonwille** [comment] 2017-01-05 07:26
Did everything except ask if I want it automatic, manual, or disabled. Thanks! I did delete all the copied files from that directory before trying if that mattered.

**Comment by fbricon** [comment] 2017-01-05 07:28
@dixonwille  I'm confused, are you saying deleting workspaceStorage worked?

**Comment by dixonwille** [comment] 2017-01-05 07:33
Yes it worked. Sorry for confusion.

**Comment by fbricon** [comment] 2017-01-12 19:34
So I: 
- opened a [gradle project ](https://github.com/spring-guides/gs-caching/tree/master/complete) in vscode, got the .classpath, .project, .settings created
- deleted  .classpath, .project, .settings 
- restarted vscode =>  .classpath, .project, .settings  were recreated

Can you maybe attach a sample project, see if we can reproduce the issue?

**Comment by dixonwille** [comment] 2017-01-12 19:41
https://github.com/technomancers/2016Spike this was the exact project this was happening in. I assume you are using Windows since you used `%APPDATA%`. I am running Windows 10 Pro if it means anything. I am currently on an Insider build but this was happening on the Latest release as well (OS Build 14393.576). I do have developer mode enabled and Bash on Windows enabled. Don't see why they would affect it because VSCode and Java are installed on the Windows side. Hope this helps. Let me know if there is anything else I can do?

**Comment by Personinblack** [comment] 2017-07-12 09:38
I can confirm this. Yesterday, I copied my sample project for an application plugin and changed some package/class names and modified gradle files. After I deleted the ".classpath", ".project" files and "bin", ".settings" and ".gradle" folders they were not auto generated and I wasn't able to use intellisense or other thing on my java files in that project (I was getting "Can't read root project location for project located at" error, I managed to get rid of it but the plugin was still not functioning). So I had to recreate another project with exact same structure in VS Code from scratch.

**Comment by jcgarciam** [comment] 2017-07-14 13:54
It looks like is not only related to gradle, i can confirmed this problem is also happening for regular maven projects:

Visual Studio Code: Version 1.14.1

- Just create a simple maven project
- Make sure vscode-java kicks in and is recognizing the java project. 
- Close the folder and editor
- Delete  the .project, .classpath, ./settings
- Reopen code

The following output is shown:

> [Error - 3:46:40 PM] Jul 14, 2017 3:46:38 PM Problem importing to workspace
> The project description file (.project) for 'demo' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
> org.eclipse.core.internal.resources.ResourceException: The project description file (.project) for 'challenge-realtime-statistis' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
> 	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:901)
> 	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:904)
> 	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:774)
> 	at org.eclipse.core.internal.resources.Project.open(Project.java:1056)
> 	at org.eclipse.core.internal.resources.Project.open(Project.java:1102)
> 	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.updateProjects(MavenProjectImporter.java:109)
> 	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:92)
> 	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
> 	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:108)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Closed** 2017-07-26 23:14 UTC
Labels: bug, in progress
