### ISSUE TITLE
Illegal Argument & TypeError 

### ISSUE THREAD

**Issue by santhoshr** [redhat-developer/vscode-java#73] opened 2016-10-19 03:37 UTC
VSCode: v1.6.1
Plugin: v0.0.5
Project Type: Maven Project or Maven + Eclipse Project
Workstation: Home (I have also raised another issue for corporate installation)

Mostly on mouse hover with control key,

shell.ts:441 Illegal argument: Error: Illegal argument
    at new e (z:\Developer\vscode\resources\app\out\vs\workbench\node\extensionHostProcess.js:9:28858)
    at asHover (C:\Users\Santhosh.vscode\extensions\redhat.java-0.0.5\node_modules\vscode-languageclient\lib\protocolConverter.js:71:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Cannot read property 'start' of undefined: TypeError: Cannot read property 'start' of undefined
    at Object.f [as fromRange](z:DevelopervscoderesourcesappoutvsworkbenchnodeextensionHostProcess.js:10:21596)
    at Function.e._convertLocation (z:\Developer\vscode\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:22335)
    at z:\Developer\vscode\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:22244
    at Object.m [as _notify](z:DevelopervscoderesourcesappoutvsworkbenchnodeextensionHostProcess.js:6:5002)
    at Object.enter (z:\Developer\vscode\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:8580)
    at _run (z:\Developer\vscode\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:10408)
    at _completed (z:\Developer\vscode\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:9849)
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:441(anonymous function) @ shell.ts:354e.onUnexpectedError @ errors.ts:68o @ errors.ts:83(anonymous function) @ goToDeclaration.ts:28v @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041v @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041(anonymous function) @ async.ts:358done @ winjs.base.raw.js:1378v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041e.resolveErr @ ipcRemoteCom.ts:110f @ ipcRemoteCom.ts:198_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

output:
[Error - 9:04:31 AM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (C:\Users\Santhosh.vscode\extensions\redhat.java-0.0.5\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:294:40)
    at StreamMessageReader.callback (C:\Users\Santhosh.vscode\extensions\redhat.java-0.0.5\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:366:13)
    at StreamMessageReader.onData (C:\Users\Santhosh.vscode\extensions\redhat.java-0.0.5\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:197:18)
    at Socket.<anonymous> (C:\Users\Santhosh.vscode\extensions\redhat.java-0.0.5\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\messageReader.js:164:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by jauco** [comment] 2016-10-25 07:43
I can reproduce it every time when hovering over the `char` type (lowercase, the unboxed version)

**Comment by fbricon** [comment] 2016-10-25 11:57
I can't reproduce in master. This is most likely a duplicate of #67.

**Comment by fbricon** [comment] 2016-11-01 20:20
Please check if you can reproduce this error with the new 0.0.6 release

**Comment by jauco** [comment] 2016-11-02 19:46
I've tried. However, now the java server will not start with the log

```
[Error - 8:46:53 PM] Nov 2, 2016 8:46:50 PM Problem importing to workspace
The project description file (.project) for 'security-client-agnostic' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
org.eclipse.core.internal.resources.ResourceException: The project description file (.project) for 'security-client-agnostic' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:907)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:904)
	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:774)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1041)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1087)
	at org.jboss.tools.vscode.java.internal.managers.MavenProjectImporter.collectProjects(MavenProjectImporter.java:105)
	at org.jboss.tools.vscode.java.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:87)
	at org.jboss.tools.vscode.java.internal.managers.ProjectsManager.createProject(ProjectsManager.java:51)
	at org.jboss.tools.vscode.java.internal.handlers.InitHandler$1.run(InitHandler.java:89)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```
(A different problem of course. do you want me to create a separate issue?)

**Comment by jauco** [comment] 2016-11-14 15:21
I tried it in another repo (so not a full recheck) and the error was no longer present.

Feel free to close this issue.

**Comment by fbricon** [comment] 2016-11-17 15:34
Please open a new issue if you see a different error

**Closed by fbricon** 2016-11-17 15:34 UTC
Labels: duplicate
