### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yuchuga** [redhat-developer/vscode-java#2428] opened 2022-04-23 13:58 UTC
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `1.5.0`
- OS Version: `Darwin arm64 20.4.0`
- VS Code version: `1.67.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

Project 'Java_de230e2c' has no explicit encoding set

**Comment by snjeza** [comment] 2022-04-23 20:15
A duplicate of https://github.com/redhat-developer/vscode-java/issues/2416

**Closed** 2022-04-23 20:15 UTC
