### ISSUE TITLE
Cannot even run basic Java (with Gradle) autogenerated project

### ISSUE THREAD

**Issue by AgainPsychoX** [redhat-developer/vscode-java#2392] opened 2022-04-06 08:53 UTC
Cannot even run basic Java (with Gradle) autogenerated project.

##### Environment

- Operating System: Windows 10 
- JDK version: OpenJDK 
```
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```
- Visual Studio Code version: `1.66.0`
- Java extension version: `v0.22.2`

##### Steps To Reproduce

1. Install `Extension Pack for Java`.
2. Click `Create Java Project`.
3. Select Gradle (will ask to install `Gradle for Java`).
4. Select project location.
5. Wait for initialization to finish.
6. Try to run autogenerated basic project.

##### Current Result

Cannot use Java with Gradle in VS Code.

![image](https://user-images.githubusercontent.com/23557839/161935242-bd3a299c-c768-443e-a32f-6b411e275ad7.png)

Logs: https://gist.github.com/AgainPsychoX/c78f9c43df3f65f339e4c89aa48098ea

Terminal:
```
PS C:\Users\PsychoX\Desktop\Środa\Grafika\Renderer>  c:; cd 'c:\Users\PsychoX\Desktop\Środa\Grafika\Renderer'; & 'C:\Users\PsychoX\.vscode\extensions\redhat.java-1.4.0-win32-x64\jre\17.0.2-win32-x86_64\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:1165' '-XX:+ShowCodeDetailsInExceptionMessages' '@C:\Users\PsychoX\AppData\Local\Temp\cp_a5r05w7gbm9zfjlzvure95lfx.argfile' 'Renderer.App'
Error: Could not find or load main class Renderer.App
Caused by: java.lang.ClassNotFoundException: Renderer.App
```

##### Expected Result

I hate Java, so ngl "not working" is expected result for me. Some could argue, it should "just" work - but not in Java world.

**Comment by AgainPsychoX** [comment] 2022-04-06 09:04
* I have realized https://github.com/microsoft/vscode-java-debug/blob/main/Configuration.md#auto-generate-the-launchjson is all lies...

**Comment by AgainPsychoX** [comment] 2022-04-06 09:17
Also fails when running from "Java Projects" thingy (but different reason, malformed shell command)
![image](https://user-images.githubusercontent.com/23557839/161941393-b67f6e8c-b910-4cf0-9526-2e4bab2a718f.png)

```
PS C:\Users\PsychoX\Desktop\Środa\Grafika\Renderer> gradle  c:; cd 'c:\Users\PsychoX\Desktop\Środa\Grafika\Renderer'; & 'C:\Users\PsychoX\.vscode\extensions\redhat.java-1.4.0-win32-x64\jre\17.0.2-win32-x86_64\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:3100' '-XX:+ShowCodeDetailsInExceptionMessages' '@C:\Users\PsychoX\AppData\Local\Temp\cp_a5r05w7gbm9zfjlzvure95lfx.argfile' 'Renderer.App'
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Project 'c' not found in root project 'Renderer'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Error: could not open `C:\Users\PsychoX\AppData\Local\Temp\cp_a5r05w7gbm9zfjlzvure95lfx.argfile'
``

**Comment by AgainPsychoX** [comment] 2022-04-06 09:33
I can't understand, why isn't it working... The file is compiled into `.class`. If I decompile it, it had the proper main class. Class paths are set properly (inside file included to args `@...`; contains `-cp "C:\\Users\\PsychoX\\Desktop\\Środa\\Grafika\\Renderer\\app\\bin\\main; ...`).

**Comment by testforstephen** [comment] 2022-04-06 09:39
The issue is that your path contains some unicode character `Środa`, and Java debug extension doesn't handle it well.

Could you move the issue to https://github.com/microsoft/vscode-java-debug/issues?

**Comment by AgainPsychoX** [comment] 2022-04-06 09:52
I _"love"_ how Java brands itself as multiplatform and portable, when it can't handle Unicode characters left and right... And not even giving clear error/warning message - even working with GCC warnings is easier to read at this point...

Also, why does the issue still occur when there were similar issues in the past? https://github.com/microsoft/vscode-java-debug/issues?q=Unicode

Anyway, thanks for help.

**Comment by fbricon** [comment] 2022-04-06 10:08
@testforstephen you're a contributor to both vscode-java and vscode-java-debug, so please transfer that issue over there. Else just close it here.

**Comment by testforstephen** [comment] 2022-04-06 10:19
Tracked this issue at https://github.com/microsoft/vscode-java-debug/issues/1149

**Closed by testforstephen** 2022-04-06 10:19 UTC
