### ISSUE TITLE
Blocked in "Configuring" and "Refreshing" by the dependency "log4j-core" in pom.xml

### ISSUE THREAD

**Issue by wzh90** [redhat-developer/vscode-java#2029] opened 2021-07-15 09:37 UTC
##### Environment
- Operating System: MacOS 11.4
- JDK version: Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
- Visual Studio Code version:1.58.1
- Java extension version: v0.80.0

##### Steps To Reproduce
1. Create a simple maven project.
2. pom.xml add dependency 
`<dependency> <groupId>org.apache.logging.log4j</groupId> <artifactId>log4j-core</artifactId> <version>2.14.1</version> </dependency>`
3.  execute `JAVA: Clean Java Language Server Workspace`
4.  It's will be blocking. Why?

##### Current Result
blocking:
<img width="649" alt="WX20210715-172036@2x" src="https://user-images.githubusercontent.com/15761455/125764079-141b41e3-21c9-4812-a162-b963f6a2687f.png">

**Comment by fbricon** [comment] 2021-07-15 09:48
Probably a duplicate of #2020. 
See if @snjeza 's custom build fixes it: https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712

**Comment by wzh90** [comment] 2021-07-16 02:05
> Probably a duplicate of #2020.
> See if @snjeza 's custom build fixes it: [#2020 (comment)](https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712)

@fbricon  It's worked. Thx.

**Comment by fbricon** [comment] 2021-07-16 07:48
Closing as duplicate of #2020

**Closed by fbricon** 2021-07-16 07:48 UTC
Labels: duplicate
