### ISSUE TITLE
Gradle import fails behind corporate proxy with auth

### ISSUE THREAD

**Issue by vviskari** [redhat-developer/vscode-java#211] opened 2017-05-13 06:29 UTC
I'm ​behind a corporate proxy that requires authentication.

When opening a Gradle project, the plugin fails to download Gradle binaries. I get code completion only for JDK classes and a notification that "classpath is incomplete". The error in logs is about connection timeout.

JRE system properties are set in vscode settings as per instructions here: https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy

Tested with Windows and Linux.

**Comment by fbricon** [comment] 2017-05-13 14:08
@vviskari Can I assume it works from CLI? Do you know what kind of proxy it is? Does it works from Eclipse with Buildship installed?

My proxy tests didn't involve authentication, but I checked my local proxy was hit as expected. So I'm assuming the authentication part is at fault.

@snjeza do you have something set up to check proxy auth? My guess is we need to call the Eclipse's proxy API from jdt.ls

**Comment by vviskari** [comment] 2017-05-13 16:21
@fbricon yes CLI works fine. I will test eclipse with buildship from the office. That is, if I'm allowed to download anything (very strict policy).

**Comment by snjeza** [comment] 2017-05-16 13:16
I can't enter a proxy password in Eclipse Oxygen M6. I think that the issue is related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=513809 that has been fixed in Oxygen M7.
It is possible to configure a proxy that requires authentication in Oxygen M7 without using the Eclipse UI:

- create the <ECLIPSE_HOME>/configuration/.settings/org.eclipse.core.net.prefs file with the following contents:

eclipse.preferences.version=1
org.eclipse.core.net.hasMigrated=true
proxyData/HTTP/hasAuth=true
proxyData/HTTP/host=<HTTP_IP>
proxyData/HTTP/port=<HTTP_PORT>
proxyData/HTTPS/hasAuth=true
proxyData/HTTPS/host=<HTTPS_IP>
proxyData/HTTPS/port=<HTTPS_PORT>
systemProxiesEnabled=false

- set the Java VM arguments as described in https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy
- start Eclipse

When starting the language server from vscode-java, we need to configure the org.eclipse.core.net.prefs file based on the java.jdt.ls.vmargs VS Code preference. 
In order to test, we have to upgrade the target platform to Oxygen M7. @fbricon would you like me to do it?

@vviskari Could you test Oxygen M6 and M7?

**Comment by fbricon** [comment] 2017-05-16 13:19
@snjeza go ahead

**Comment by vviskari** [comment] 2017-05-16 19:57
Cant test Oxygen M7. I'm not allowed to download much anything in the corporate network. I have access to only Neon.

I copied the proxy settings from eclipse to the settings file in .vscode\extensions\redhat.java-0.4.0\server\config_win\.setting
Now I get the same error as in #212 :

> [Error - 22.50.43] 16.5.2017 22:50:41 Unable to locate secure storage module (org.eclipse.equinox.security.windowspasswordprovider64bit).
> Unable to locate secure storage module (org.eclipse.equinox.security.windowspasswordprovider64bit).
> org.eclipse.equinox.security.storage.StorageException: Unable to locate secure storage module (org.eclipse.equinox.security.windowspasswordprovider64bit).
> 	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findStorageModule(PasswordProviderSelector.java:190)

**Comment by snjeza** [comment] 2017-05-22 18:12
See https://github.com/eclipse/eclipse.jdt.ls/pull/233

**Closed** 2017-05-25 17:05 UTC
Labels: bug, in progress

**Comment by fbricon** [comment] 2017-05-25 19:28
@vviskari please download and [install](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) the latest *.vsix from http://download.jboss.org/jbosstools/jdt.ls/staging/ and let us know if it fixes your issue

**Comment by vviskari** [comment] 2017-06-02 06:17
Updated the plugin to version 0.5.0 and it works perfectly now. Thanks!
