### ISSUE TITLE
Unable to install the extension

### ISSUE THREAD

**Issue by eddard1** [redhat-developer/vscode-java#246] opened 2017-06-25 18:36 UTC
Whenever I try to install the extension, an error message pops up: "end of central directory record signature not found"

##### Environment
- Operating System: Ubuntu 16.04 64-bit
- JDK version: 1.8.0_131
- Visual Studio Code version:1.13.1
- Java extension version: 0.6.0
![screenshot from 2017-06-26 00-05-23](https://user-images.githubusercontent.com/29197200/27518688-3b793c78-5a03-11e7-9bd5-89339aadf657.png)

**Comment by fbricon** [comment] 2017-06-25 21:11
are you behind a proxy? This sounds like a duplicate of https://github.com/Microsoft/vscode/issues/2384

**Comment by fbricon** [comment] 2017-06-25 21:13
can you install other extensions or is the problem limited to vscode-java?

**Comment by eddard1** [comment] 2017-06-27 05:45
The problem is limited to 2 extensions-- this one and Angular v4
Typescript snippets by johnpapa.

**Comment by eddard1** [comment] 2017-06-27 05:51
And no proxy connection, only wi-fi and personal hotspot connection from my phone.

**Comment by fbricon** [comment] 2017-06-30 19:40
So this is not vscode-java specific. The extension installation mechanism is out of our hands, you should raise a bug to https://github.com/Microsoft/vscode.

In the mean time, you can install the vscode-java extension by downloading the latest java-*.vsix file from http://download.jboss.org/jbosstools/jdt.ls/staging/ and follow the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Closed by fbricon** 2017-06-30 19:40 UTC
Labels: need info
