### ISSUE TITLE
Organize imports with compilation syntax error causes incorrect deletion of imports

### ISSUE THREAD

**Issue by jihu** [redhat-developer/vscode-java#1606] opened 2020-09-02 16:31 UTC
If one triggers Organize Imports with compilation errors in the code, this can result in incorrect deletion of imports. At least for syntax errors.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0
- Visual Studio Code version: 1.48.2
- Java extension version: 0.10.0

##### Steps To Reproduce
1. Add this code: https://www.cs.utexas.edu/~scottm/cs307/javacode/codeSamples/SimpleWordCounter.java
2. Trigger Organize Import to make sure that the imports are good
3. Delete the start curly bracket for the try, ie change "try {" into just "try", causing a syntax error
4. Save the file and trigger Organize Imports

##### Current Result
A bunch of the imports are deleted. Imports that are required to run the code (after the syntax error has been fixed).

##### Expected Result
Imports that are needed should not be deleted. And if some errors in the code makes it difficult or impossible to know for sure if an import is needed or not, then it should not be deleted.

**Comment by fbricon** [comment] 2020-09-02 16:36
Closing as duplicate of https://github.com/redhat-developer/vscode-java/issues/1383

**Closed by fbricon** 2020-09-02 16:36 UTC
Labels: duplicate

**Comment by jihu** [comment] 2020-09-02 16:40
> Closing as duplicate of #1383

ok. Well, yeah, I didn't find that when searching for similar bugs already registered. But least this provides a different example of when this is triggered (as the error in the other ticket is caused by a missing semicolon, and this one by a missing bracket, and you wrote in the other ticket that it is difficult to reproduce with other types of errors than the example). Also, in my case not all imports are deleted. For some reason, the import for the IOException remains.

**Comment by fbricon** [comment] 2020-09-02 16:43
In your case, this can be reproduced in Eclipse. I assume the AST must be pretty sensible to certain errors, causing those removed imports

**Comment by jihu** [comment] 2020-09-02 16:48
Interesting. I had no idea this part was so tightly coupled with Eclipse. Do you happen to know what project is responsible for that? Then I can file a bug report there (unless one already exists).

**Comment by fbricon** [comment] 2020-09-02 17:53
I skimmed through the [JDT bugs](https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&classification=Eclipse%20Project&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f6=status_whiteboard&f7=content&f8=CP&f9=CP&j1=OR&list_id=19905300&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&product=JDT&query_format=advanced&v2=organize&v3=organize&v4=organize&v5=organize&v6=organize&v7=%22organize%22) quickly but didn't find anything relevant.
You can open a bug via https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT
