### ISSUE TITLE
Bad syntax highlighting for quote characters inside multiline strings

### ISSUE THREAD

**Issue by sbj42** [redhat-developer/vscode-java#3219] opened 2023-07-21 19:22 UTC
Here is an example Java class with a multiline string containing a quote character:
```java
class Test {
    static String TEST = """
        x " y
        """;
}
```

In VSCode, this appears as:

![image](https://github.com/redhat-developer/vscode-java/assets/99791/01d6c284-1ebe-4fb4-9a8c-f91b6e7f6501)

It seems to think the string stops at the quote character on line 3.  `y`, `;` and `}` all have the wrong color, and `{` is red indicating it couldn't find the matching brace.

##### Environment
- Operating System: Windows
- JDK version: 17
- Visual Studio Code version: 1.80.1
- Java extension version: v1.20.0

##### Steps To Reproduce
1. Create a new Java file, paste in the contents from above.

##### Current Result

The syntax highlighter thinks that quote characters terminate multiline strings.

##### Expected Result

Triple-quotes terminate multiline strings.  It should consider quote characters as part of the string.

**Comment by fbricon** [comment] 2023-07-21 22:08
Closing as duplicate of #3200

You can try a pre-release build to check the fix.

<img width="361" alt="Screenshot 2023-07-22 at 00 00 00" src="https://github.com/redhat-developer/vscode-java/assets/148698/7f91305b-9685-4538-b61a-8618494046cb">

**Closed by fbricon** 2023-07-21 22:08 UTC
