### ISSUE TITLE
Output steals focus from Terminal

### ISSUE THREAD

**Issue by aboe026** [redhat-developer/vscode-java#278] opened 2017-08-16 13:20 UTC
When there is an error with the extension, the bottom panel (that has Problems, Output, Debug Console, and Terminal tabs) automatically switches focus to the Output tab. This is extremely annoying because I only really use the Terminal tab on the bottom, so I end up having to wait for all the errors to print out before I can go back to the Terminal tab without switching focus back to the Output tab again. Would be nice if there was a setting to specify whether or not the Output tab automatically gains focus on errors.

**Comment by bawachhe** [comment] 2017-08-17 14:32
This happens for me as well, whenever I start up VSCode, and also in two more situations, which makes it even more annoying than @aboe026 described.
1. Whenever I remove a line or more from any file I'm looking at, which is very interruptive, as it actually sometimes covers the lines I was typing on.
2. When I'm using Terminal to adjust git history or update from upstream, in the process of rebasing, it also removes lines of code temporarily, and so the Output console interrupts me again in this case.

**Comment by aeschli** [comment] 2017-08-21 15:48
This is a duplicate of https://github.com/Microsoft/vscode/issues/32872

**Closed by aeschli** 2017-08-21 15:48 UTC
Labels: enhancement
