### ISSUE TITLE
Java generates many folder in workspace 

### ISSUE THREAD

**Issue by DachuanZhao** [redhat-developer/vscode-java#2114] opened 2021-09-16 11:04 UTC
Java generates many folder in workspace. How to set the output path ?

![1631790255(1)](https://user-images.githubusercontent.com/23434805/133601179-51df758a-6bd3-43df-baf5-0167e79ee7e4.png)

##### Environment
- Operating System: win10
- JDK version: openjdk11
- Visual Studio Code version: 1.60.1
- Java extension version: v0.18.4

**Comment by rgrunber** [comment] 2021-09-16 15:52
On first glance, that looks like a Maven project that has somehow set the local repository to be the project folder itself, and so when the project builds, it generates the groupId/artifactId/version folder structure of locally cached artifacts.

If you open the Settings page, does `java.configuration.maven.userSettings` or `java.configuration.maven.globalSettings` have any value for user/workspace settings ? Is the project available anywhere public to have a look ?

**Comment by DachuanZhao** [comment] 2021-09-17 04:00
> On first glance, that looks like a Maven project that has somehow set the local repository to be the project folder itself, and so when the project builds, it generates the groupId/artifactId/version folder structure of locally cached artifacts.
> 
> If you open the Settings page, does `java.configuration.maven.userSettings` or `java.configuration.maven.globalSettings` have any value for user/workspace settings ? Is the project available anywhere public to have a look ?

Here is the setting file : 
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository/>
    <interactiveMode/>
    <usePluginRegistry/>
    <offline/>
    <pluginGroups/>
    <servers/>
    <mirrors>
        <mirror>
            <id>aliyunmaven</id>
            <mirrorOf>central</mirrorOf>
            <name>阿里云公共仓库</name>
            <url>https://maven.aliyun.com/repository/central</url>
        </mirror>
        <mirror>
            <id>repo1</id>
            <mirrorOf>central</mirrorOf>
            <name>central repo</name>
            <url>http://repo1.maven.org/maven2/</url>
        </mirror>
        <mirror>
            <id>aliyunmaven</id>
            <mirrorOf>apache snapshots</mirrorOf>
            <name>阿里云阿帕奇仓库</name>
            <url>https://maven.aliyun.com/repository/apache-snapshots</url>
        </mirror>
    </mirrors>
    <proxies/>
    <activeProfiles/>
    <profiles>
        <profile>
            <repositories>
                <repository>
                    <id>aliyunmaven</id>
                    <name>aliyunmaven</name>
                    <url>https://maven.aliyun.com/repository/public</url>
                    <layout>default</layout>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
                <repository>
                    <id>MavenCentral</id>
                    <url>http://repo1.maven.org/maven2/</url>
                </repository>
                <repository>
                    <id>aliyunmavenApache</id>
                    <url>https://maven.aliyun.com/repository/apache-snapshots</url>
                </repository>
            </repositories>
        </profile>
    </profiles>
</settings>
```
And I create a github repo [https://github.com/DachuanZhao/test_for_java](https://github.com/DachuanZhao/test_for_java)

**Comment by rgrunber** [comment] 2021-09-17 16:33
I've tried with the same same settings file + project, and am no able to reproduce this behaviour. Can you try setting `java.configuration.maven.userSettings` to the location of the settings.xml file from above, and see if that resolves the issue ?

**Comment by DachuanZhao** [comment] 2021-09-26 07:22
> I've tried with the same same settings file + project, and am no able to reproduce this behaviour. Can you try setting `java.configuration.maven.userSettings` to the location of the settings.xml file from above, and see if that resolves the issue ?

I have set both ```java.configuration.maven.userSettings``` and ```java.configuration.maven.globalSettings``` , it doesn't work ...

**Comment by rgrunber** [comment] 2021-11-22 17:28
Could you try the following and let me know of the result :

Add `-Djdt.ls.debug=true` to the `java.jdt.ls.vmargs` property under Settings. You can do this for user or workspace settings. Import the project as usual ensuring the problem still happens.

From the command palette run : `Java : Open Language Server Log File`. I don't think there should be any errors here that are related, but it's worth checking. Now right click the log file and go to `Open Containing Folder`. This should take you to a path like `/home/rgrunber/.config/Code/User/workspaceStorage/ac67664cf4e430427c02c81df7cf9691/redhat.java/jdt_ws/.metadata`. There should be files like `.out-jdt.ls-${timestamp}`. There should also be error files but the contents may not be related to the issue. Take the most recent "out" file and it should have content like :

```
org.eclipse.m2e.logback.configuration: logback.configurationFile=/home/rgrunber/.config/Code/User/workspaceStorage/ac67664cf4e430427c02c81df7cf9691/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.jdt.ls.core/logback.xml
10:07:20.261 [Worker-0: Loading available Gradle versions] INFO org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions - Gradle version information cache is out-of-date. Trying to update.
10:07:28.870 [Worker-4: Clean workspace...] DEBUG org.eclipse.m2e.core.internal.builder.MavenBuilder - Cleaning project lemminx-parent
10:07:29.384 [Worker-4: Clean workspace...] DEBUG org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider - Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/rgrunber/.m2/repository
10:07:29.428 [Worker-4: Clean workspace...] DEBUG org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider - Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/rgrunber/.m2/repository
10:07:29.447 [Worker-4: Clean workspace...] DEBUG org.eclipse.m2e.core.internal.embedder.MavenImpl - Reading 1 Maven project(s): [/home/rgrunber/git/lemminx/pom.xml]
10:07:29.700 [Worker-4: Clean workspace...] DEBUG org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector - Dependency collection stats {ConflictMarker.analyzeTime=85903, ConflictMarker.markTime=306877, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=42854, ConflictIdSorter.topsortTime=650247, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1326678, ConflictResolver.conflictItemCount=0, DefaultDependencyCollector.collectTime=171703, DefaultDependencyCollector.transformTime=4799159}
```
Does the local repository used reflect what you set in user/global settings ? Is it the project folder itself ? If you could post the logs it would help.

**Comment by rgrunber** [comment] 2024-01-22 21:25
Closing based on the fact that a very similar issue was fixed in m2e a little while after I requested the info ( https://github.com/eclipse-m2e/m2e-core/issues/383#issuecomment-985613291 ). I think it would have likely fixed it but no way to know for sure unless someone is able to mention whether the issue still occurs.

**Closed by rgrunber** 2024-01-22 21:25 UTC
Labels: question, need info, Maven
