### ISSUE TITLE
Syntax Mode (aka Lightweight mode) ignores java.trace.server setting

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1483] opened 2020-06-05 22:43 UTC
In Syntax Mode (aka Lightweight mode)  java.trace.server always behaves as if it was in verbose mode, ignores other settings.

**Comment by testforstephen** [comment] 2020-06-06 08:46
Do you mean the output channel for syntax server always print verbose log? Cannot reproduce it.
![syntaxmode](https://user-images.githubusercontent.com/14052197/83940164-295d9580-a815-11ea-86fa-f49c8abb6c6a.gif)

**Comment by testforstephen** [comment] 2020-06-28 05:58
[[langId].trace.server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#logging-support-for-language-server) setting is provided by vscode.

Since i cannot reproduce it, i will close this issue first. If you can reproduce it, feel free to reopen it.

**Closed by testforstephen** 2020-06-28 05:58 UTC
Labels: bug
