### ISSUE TITLE
Auto Complete broken since 1.20.0

### ISSUE THREAD

**Issue by benzman81** [redhat-developer/vscode-java#3214] opened 2023-07-20 10:39 UTC
There Are two problem that we noticed:

1. Usually, when typing `pub` in a java call vscode provides an auto complete for a public method body. Same with private and protected. 
2. There is no auto complete any more for methods in parent classes. So if you want to override it, you have to manually write everthing in the child class.

##### Environment
- Operating System: Windows 10 22H2
- JDK version: 11
- Visual Studio Code version: 1.80.1
- Java extension version: 1.20.0

##### Steps To Reproduce
1. Type `pub` in a java class and no auto completen for public method is available
2. Type the starting letters of a public method in a parent classe to override it, and no auto completion is available

##### Current Result
no auto completion

##### Expected Result
auto completion work 

##### Additional Informations
Reverting back to 1.19.0 fixes the issues.

**Comment by snjeza** [comment] 2023-07-20 18:51
@benzman81 You may want to take a look at https://github.com/redhat-developer/vscode-java/pull/3140

**Comment by beckermarc** [comment] 2023-08-25 13:52
I am facing similar issues in VS Code 1.81.1 since Java extension version: 1.20.0.

1. Auto Completion for method overrides actually only work if you open the auto-complete window before typing the first letter.
2. In JavaDoc auto-completed class names are no longer automatically turned into a JavaDoc link.
3. The auto-complete window no longer opens automatically

Here are some simple steps to reproduce this. The following works on Java extension version 1.19.0

1. Type `eq` inside the class, the auto-complete window opens and suggest to override `equals`. Accept the suggestion.
2. Add a JavaDoc comment to the newly added method
3. Inside the JavaDoc comment start typing the first characters of the class name, open the auto-complete window and accept the suggestion `{@link <ClassName>}`

The following happens on Java extension version 1.20.0:

1. Type `eq` inside the class, the auto-complete window **doesn't open anymore**. Opening it manually **doesn't give any meaningful suggestions**. Instead delete `eq`, enforce opening of the auto-complete window, start typing `eq` and accept the suggestion to override `equals`.
2. Add a JavaDoc comment to the newly added method
3. Inside the JavaDoc comment start typing the first characters of the class name, open the auto-complete window and realize that there is **no suggestion with `{@link ...}`**, you can only auto-complete the raw class name.

I think this makes writing sub classes and JavaDoc much more cumbersome now.
Was this an intentional change? Can I use some configuration parameter to revert to the old behaviour?
I think this issue goes far beyond the UX change for method snippets.

**Comment by beckermarc** [comment] 2023-08-25 13:58
Addon: Just noticed that setting `java.completion.matchCase` to `off` solves the issues with overrides. However the removal of the very useful JavaDoc `{@link ...}` suggestion remain. Nevertheless I also still think that `java.completion.matchCase` shouldn't matter here, as the case of the first letter is correct, e.g. `e` in my example above.

**Comment by testforstephen** [comment] 2023-10-12 01:41
fixed by https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2902

**Closed by testforstephen** 2023-10-12 01:41 UTC
Labels: content-assist
