### ISSUE TITLE
Convert class to record

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2053] opened 2021-08-09 06:20 UTC
Add code action to convert class to Java 16 record.

**Comment by fbricon** [comment] 2021-08-16 08:43
AFAIK, there's no such refactoring available in JDT. So it'd have to be contributed upstream first, ideally.

**Comment by GavinRay97** [comment] 2021-08-16 16:20
Coincidentally, had just filed this here:
https://github.com/eclipse/eclipse.jdt.ls/issues/1841

Please thumbs-up if you also would like this! 🙂

**Comment by rgrunber** [comment] 2022-11-22 16:25
Closing as a duplicate of https://github.com/eclipse/eclipse.jdt.ls/issues/1841 . We can track the progress there.

**Closed by rgrunber** 2022-11-22 16:25 UTC
Labels: code action
