### ISSUE TITLE
Java Class Hierarchy Navigation

### ISSUE THREAD

**Issue by zuopx** [redhat-developer/vscode-java#1055] opened 2019-09-09 04:22 UTC
Issue Type: <b>Feature Request</b>

Java Class Hierarchy Navigation

Extension version: 0.48.0
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-957.27.2.el7.x86_64

**Comment by fbricon** [comment] 2019-09-09 14:15
Closing as a duplicate of #649

**Closed by fbricon** 2019-09-09 14:15 UTC
Labels: duplicate
