### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by bonaluo** [redhat-developer/vscode-java#1286] opened 2020-02-19 10:09 UTC
Issue Type: <b>Bug</b>

The Project is from https://github.com/spring-guides/gs-gateway.git.
The folder is gs-gateway/initial.
I've already Deleted gradle related files.

The problem is:
Could not fetch model of type 'BuildEnvironment' using Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip'.
The specified Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip' does not exist.
https://downloads.gradle-dn.com/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip

Extension version: 0.56.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fbricon** [comment] 2020-02-19 10:11
Closing as duplicate of #1285

**Closed by fbricon** 2020-02-19 10:11 UTC
Labels: duplicate
