### ISSUE TITLE
Intellisense broken with 0.55

### ISSUE THREAD

**Issue by Gameghostify** [redhat-developer/vscode-java#1214] opened 2019-12-23 14:23 UTC
Intellisense completely stops working with the recently pushed 0.55 release of vscode-java.

As soon as I downgrade to 0.54, intellisense starts working again.

##### Environment
- Operating System: Windows 10 build 18362
- JDK version: 13 (Azul Zulu)
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55
- Using Maven project (configured to use Java 13)

##### Steps To Reproduce
1. Install 0.55
2. intellisense doesn't work anymore

**Comment by Gameghostify** [comment] 2019-12-23 14:24
I can't post the LS logs right now but can do that soon, if needed

**Comment by fbricon** [comment] 2019-12-23 14:25
Closing as duplicate of #1213. TL;DR: your version of Intellicode is not compatible with vscode-java 0.55.0. Try disabling it.

**Closed by fbricon** 2019-12-23 14:25 UTC

**Comment by Gameghostify** [comment] 2019-12-23 14:27
Sorry for opening up a separate issue! Tested it and sure enough, intellicode breaks the extension.

Thanks!
