### ISSUE TITLE
Compiler issues with try with resources

### ISSUE THREAD

**Issue by giraudsa** [redhat-developer/vscode-java#3144] opened 2023-06-09 09:00 UTC
The Try With Resources result in throwing bad exception type.

##### Environment
- Operating System: Mac OS 13.4
- JDK version: Temurin 17.0.7 (but tested on several others)
- Visual Studio Code version: 1.79.0
- Java extension version: 1.19.0 (commercial version)

##### Steps To Reproduce
1. [step 1]
Create a Main.java file
```
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

public class Main {
    public static void main(final String[] args) throws Exception {
        try(final InputStream in = Files.newInputStream(Path.of("Main.java"))) {
            System.out.println("Hello, World!");
            throw new Exception("test");
        }
    }
}
```
2. [step 2]
execute in vscode

##### Current Result
```
Hello, World!
Exception in thread "main" java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at Main.main(Main.java:10)
Caused by: java.lang.Exception: test
        at Main.main(Main.java:9)
```

##### Expected Result
```
Hello, World!
Exception in thread "main" java.lang.Exception: test
	at Main.main(Main.java:9)

```

**Comment by snjeza** [comment] 2023-06-09 13:43
A duplicate of https://github.com/redhat-developer/vscode-java/issues/3138
@giraudsa Could you check the issue in VS Code `Pre-Release` ?

**Comment by giraudsa** [comment] 2023-06-09 15:45
thanks, and sorry for the duplication.

**Closed** 2023-06-09 17:07 UTC
